import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 1,
    coreTheme: "Creative force",
    coreMeaning: "Creative force describes a situation with strong capacity to initiate, shape, and sustain movement. The central question is not whether energy exists, but whether it is mature enough for the level of action being considered. Qian rewards disciplined development: potential first remains protected, then enters a shared field, withstands pressure, tests a threshold, becomes publicly effective, and finally risks excess when strength forgets proportion. This reading therefore distinguishes capacity from permission. Use initiative where timing, responsibility, and reality can carry it; hold it back where display would outrun readiness. The strongest expression of Qian is not constant acceleration. It is force that can wait, learn, accept worthy guidance, take responsibility when visible, and stop before confidence becomes overreach.",
    strength: "disciplined initiative",
    challenge: "overextension or mistaking force for correctness",
    orientation: "act with purpose while testing timing and proportion",
    structureInterpretation: "Heaven below and Heaven above create an unbroken field of yang initiative. With no receptive line inside the primary figure, the structure emphasizes continuity of force, direction, and self-propelled movement. Quick I Ching therefore reads Qian as a problem of governing strength: the same creative power that begins something can become excessive if timing, counsel, and limits are ignored.",
    reflectionQuestions: [
      "What capacity is genuinely ready to become visible now, and what part still needs protection or practice?",
      "Whose capable guidance would make your initiative more accurate rather than merely more confident?",
      "Where would stopping, waiting, or sharing authority preserve the quality of the creative force you already have?",
    ],
    watchFor: [
      "A private capability beginning to receive useful recognition or serious external testing.",
      "Sustained effort turning into strain, defensiveness, or a need to prove strength for its own sake.",
      "Moments when wider responsibility calls for counsel, coordination, or restraint rather than another increase in force.",
    ],
    transitionTheme: "turning raw creative force into form that others and circumstances can sustain",
    stabilityTheme: "consistent direction without needing constant acceleration",
    lowerTrigram: "qian",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Potential kept below the surface",
        "The first line treats creative strength as real but not yet ready for display. Something may be forming beneath the surface: skill, resolve, an idea, or a position that would lose quality if exposed too early. The useful work is private preparation and accurate observation. Hidden does not mean weak; it means the surrounding conditions have not yet earned the full use of the force available.",
        "A change here moves the reading from protected potential toward contact with the outer world. The important transition is not simply ‘act now,’ but decide what evidence would justify moving from preparation into participation. If the line changes, latent capacity is beginning to seek a form, relationship, or setting that can receive it without wasting it.",
        "Premature display can turn potential into obligation before the foundation is ready. Avoid announcing, committing, or escalating merely to prove that the energy exists; once others organize around an early move, it becomes harder to return quietly to preparation.",
        "What strength is better protected for now, and what concrete sign would tell you that concealment has served its purpose?",
        "Line 1 asks creative force to remain protected until timing and preparation justify visible use.",
      ),
      authoredLine(
        "Emerging into the field",
        "Creative ability has entered the field where other people can see, test, and respond to it. This is no longer purely private potential, yet it is not the highest position of authority either. The line favors becoming useful among others and recognizing capable guidance: a mentor, peer, standard, or experienced collaborator can sharpen what raw confidence cannot. Visibility here is relational; growth comes from contact with a wider field rather than self-enclosure.",
        "The change is from hidden capacity to recognized participation. As the line moves, private force begins to acquire social consequence, and feedback matters more. The emerging pattern asks whether talent can become reliable in a real environment—through cooperation, learning, and the willingness to be corrected—before larger responsibility is claimed.",
        "Being noticed can be mistaken for being fully established. Do not convert early recognition into entitlement, nor reject capable guidance because independence feels more powerful. The field is useful precisely because it exposes what private confidence could not test.",
        "Which capable guidance, peer, or demanding real-world setting would help this emerging strength become more trustworthy?",
        "Line 2 moves creative force into a shared field where recognition, capable guidance, and useful participation shape its next stage.",
      ),
      authoredLine(
        "Sustained effort under scrutiny",
        "The third line places creative force in a demanding phase of continued work. Momentum is present, but the task is to remain alert through effort rather than assume that energy guarantees correctness. This is the point where ambition can be tested by fatigue, repeated decisions, and the consequences of carrying responsibility across a full cycle of activity. Discipline now means reviewing conduct while continuing the work, not relaxing because the direction once felt right.",
        "Change at this point intensifies the transition from promising capability to dependable character. Pressure reveals whether the initiative can survive repetition without becoming careless or compulsive. The line asks for active self-correction: keep moving where the work is sound, but use strain and friction as evidence about method, pacing, and motive.",
        "Continuous effort can become a badge of virtue that hides deterioration. Watch for exhaustion, irritability, or a refusal to reconsider because so much energy has already been invested. Persistence loses value when vigilance disappears.",
        "During sustained effort, what recurring signal would tell you to adjust the method even if the larger purpose still remains sound?",
        "Line 3 tests whether creative force can remain vigilant and self-correcting while effort is sustained under pressure.",
      ),
      authoredLine(
        "Testing the leap",
        "The fourth line stands at a threshold: capacity developed inside the situation is considering a larger move, but the move is not automatic. The image is one of testing whether to leap rather than being compelled to do so. This makes discretion central. There may be a legitimate opening to advance, change role, or enter a more exposed arena, yet holding back can also be correct if the new level lacks support.",
        "The moving line turns internal readiness into an explicit decision about entry. Its change highlights freedom of judgment: the next structure depends on how accurately the threshold is read. A measured trial, reversible step, or deliberate pause can reveal whether the larger field will support the creative force or distort it.",
        "Do not confuse a threshold with a command to cross it. Excitement about expansion can obscure missing support, while fear can make a real opening look unsafe. The danger lies in making the decision to protect an identity—bold or cautious—instead of responding to conditions.",
        "What small test could distinguish a genuine opening from a leap driven mainly by impatience or fear of missing out?",
        "Line 4 makes the threshold itself the issue: test whether creative strength should advance, pause, or remain reversible before committing to the leap.",
      ),
      authoredLine(
        "Visible creative leadership",
        "Creative capacity is now operating in full visibility, where its effects extend beyond the self. This is a position of mature influence rather than private promise. The line favors leadership that attracts capable people and remains open to worthy counsel; strong direction is most credible when it can recognize excellence outside itself. Public effectiveness therefore includes coordination, judgment, and the ability to make room for other strong contributors.",
        "Change here shifts the question from ‘Can this force succeed?’ to ‘How should visible power be used?’ The emerging pattern tests whether authority can become stewardship. Decisions now shape the field for others, so counsel, delegation, and responsibility become part of creative action rather than constraints on it.",
        "Full visibility can feed self-sufficiency. Avoid assuming that success removes the need for worthy counsel or that authority proves every judgment correct. A leader who stops receiving information can turn a strong position into a fragile one very quickly.",
        "Which worthy counsel or capable collaborator should have real influence on a decision that your visible position allows you to make alone?",
        "Line 5 brings creative force into full visibility and asks leadership to remain strengthened by worthy counsel, shared capability, and responsible influence.",
      ),
      authoredLine(
        "Strength carried beyond its proper height",
        "At the top line, creative force risks continuing after it has reached the point where more height no longer adds value. Achievement, confidence, or authority may have become self-reinforcing, making retreat or moderation feel like loss. The distinctive issue is excess: power that was constructive at earlier stages can become isolated when it insists on remaining above correction, relationship, or changing conditions.",
        "The change releases a fully extended yang line and therefore emphasizes descent, receptivity, or redistribution after maximal assertion. The useful transition is to convert accumulated strength into a form that can rejoin reality—through restraint, succession, listening, or a deliberate reduction in pressure—before circumstances impose the correction more harshly.",
        "Do not keep escalating because past escalation worked. Pride can make limits look like enemies and feedback look like disrespect. When the position is already high, another push may create regret precisely because there is little room left to absorb error.",
        "Where has success made it harder to hear limits, and what voluntary reduction would restore proportion before the situation forces one?",
        "Line 6 warns that creative force loses quality when it exceeds proportion; mature strength must know how to descend, share, or stop.",
      ),
    ],
  },
  {
    number: 2,
    coreTheme: "Receptive support",
    coreMeaning: "Receptive support is not passive surrender. Kun describes the strength of making room, carrying weight, responding to what is actually present, and allowing viable development to take form without forcing it into a preferred shape. The challenge is to remain open without becoming shapeless. Good receptivity has boundaries, standards, and an ability to distinguish what deserves support from what merely demands it. In a reading, this hexagram often shifts attention away from initiating and toward conditions: What is asking to be received? What can be sustained? What develops when pressure is reduced? The productive stance is steady rather than dramatic. Support what proves real, coordinate with the terrain, and let responsiveness create capacity while preserving the limits that keep care from becoming over-accommodation.",
    strength: "capacity to receive, support, and carry what is viable",
    challenge: "passivity, over-accommodation, or losing your own boundaries",
    orientation: "make room, observe what is actually developing, and support it without forcing",
    structureInterpretation: "Earth below and Earth above create six receptive yin lines, so the structure contains no internal demand to initiate by force. Quick I Ching reads this as maximal capacity to receive and carry conditions. The risk is not lack of power but lack of definition: support is useful when it gives viable development room while maintaining enough boundary to avoid becoming directionless.",
    reflectionQuestions: [
      "What is already trying to develop that would benefit more from support than from another intervention?",
      "Which boundary must remain intact so responsiveness does not turn into self-erasure or passive drift?",
      "What evidence would show that your support is increasing real capacity rather than creating dependence?",
    ],
    watchFor: [
      "A situation becoming more workable after pressure is reduced and practical support increases.",
      "Requests for accommodation that repeatedly consume boundaries without producing mutual capacity.",
      "Quiet evidence that a viable direction is emerging on its own and needs room rather than control.",
    ],
    transitionTheme: "receptivity becoming active stewardship rather than passive waiting",
    stabilityTheme: "steady support that preserves both openness and boundaries",
    lowerTrigram: "kun",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Early signs of a colder direction",
        "The first line asks you to notice a small sign before it becomes an established condition. Receptivity is especially powerful at beginnings because it can register what forceful action overlooks. A subtle shift in tone, habit, demand, or environment may be telling you where the larger pattern is headed. The task is not alarm; it is to take weak signals seriously enough to prepare.",
        "As this line changes, passive observation becomes an early adjustment. The reading moves from simply receiving conditions toward shaping the boundary of what will be carried. A small response now can prevent later support from being consumed by a pattern that was visible at the beginning.",
        "Ignoring an uncomfortable early sign because it seems too small can make later correction much harder. The opposite error is dramatizing a minor signal before there is enough evidence. Receptivity needs both sensitivity and proportion.",
        "What small recurring sign deserves to be tracked now because it may reveal the direction of the larger pattern?",
        "Line 1 turns receptivity into early discernment: notice the weak signal, verify it, and prepare before it hardens into the environment.",
      ),
      authoredLine(
        "Broad, direct, and dependable support",
        "The second line represents receptive capacity working cleanly in ordinary life. Support does not need elaborate control when the underlying role is clear: make space, carry what is yours to carry, and respond directly to real needs. The value of this line is its lack of distortion. It favors practical reliability over clever positioning and shows how steadiness can become a source of order without needing to dominate.",
        "Change here turns simple receptivity into a more active relationship with the situation. The question becomes how dependable support can help something viable take its own shape. Good movement grows from consistency: repeated care, accurate follow-through, and enough openness for reality to correct your assumptions.",
        "Overhelping can make straightforward support complicated. Avoid adding conditions, emotional debt, or hidden control to what should be a clear act of carrying. Reliability loses trust when the receiver has to manage the giver.",
        "Where would simple, direct support be more useful than advice, persuasion, or an attempt to manage the outcome?",
        "Line 2 shows receptive strength at its cleanest: dependable support creates room for development without trying to own the result.",
      ),
      authoredLine(
        "Capability kept in service of the work",
        "The third line concerns useful ability that does not need to become the center of attention. You may have competence, insight, or effort to contribute while another person, role, or process carries formal authority. Receptivity here means letting the work benefit from your capacity without requiring immediate recognition. What matters is whether the contribution helps the larger task reach completion.",
        "When this line changes, quiet support begins to acquire more visible consequence. The transition tests motive: can capability remain aligned with the work as circumstances make it more noticeable? If recognition comes, it should follow substance rather than become the reason the contribution is made.",
        "Suppressed resentment can hide beneath apparent humility. Serving the work does not mean accepting exploitation, nor does it require pretending that contribution has no value. Watch whether lack of recognition is tolerable because the arrangement is sound or corrosive because the terms are unfair.",
        "What contribution can you make without needing to control the credit, and what boundary would keep that service from becoming exploitation?",
        "Line 3 asks receptive capability to serve completion without making recognition the condition for useful contribution.",
      ),
      authoredLine(
        "Containment and discretion",
        "The fourth line narrows receptivity into careful containment. Not every situation benefits from disclosure, intervention, or taking sides. When the environment is uncertain, preserving information, resources, or emotional energy can be the most responsible form of support. The line favors a closed container: enough reserve to avoid becoming entangled before the terms are clear.",
        "Change here tests whether discretion can protect capacity without becoming permanent withdrawal. Conditions may soon require a more defined response, but first the boundary itself has to hold. The emerging pattern asks what should remain uncommitted until the wider field proves safe and intelligible.",
        "Secrecy and avoidance can imitate discretion. Do not use containment to escape a responsibility that is already clear. The line is strongest when reserve is purposeful and temporary, not when it becomes a way to avoid every difficult conversation.",
        "What should remain contained until the surrounding conditions become clearer, and what event would make continued silence irresponsible?",
        "Line 4 uses restraint to protect receptive capacity from premature entanglement while the outer conditions are still uncertain.",
      ),
      authoredLine(
        "Quiet central influence",
        "The fifth line gives receptive support a central, dignified role. Influence is present, but it works through steadiness, simplicity, and trustworthy conduct rather than display. The position suggests that people or processes can organize around a reliable center that does not demand attention for itself. Support becomes leadership here precisely because it creates confidence and room for others to function.",
        "A change at this line brings quiet influence toward a more explicit form. The transition asks how a trusted center can use its position without abandoning receptivity. Decisions may need to be made, but they should grow from listening, proportion, and service to the whole rather than from a desire to prove authority.",
        "Modesty can become a mask if central influence is denied while still being exercised. Be clear about the responsibility your position actually carries. Invisible power is not automatically benign; it still needs accountability.",
        "How can you use a position of trust to make others more capable without turning quiet influence into unacknowledged control?",
        "Line 5 makes receptivity a form of quiet leadership: a trustworthy center supports order without needing theatrical authority.",
      ),
      authoredLine(
        "Receptivity pushed into conflict",
        "At the top line, accommodation has reached a point where opposing forces can no longer coexist without definition. What began as willingness to receive may now be colliding with demands, identities, or boundaries that cannot all be carried together. The line marks the limit of yielding. Continuing to absorb the conflict would not preserve harmony; it would only postpone a necessary distinction.",
        "Change releases the fully receptive position and introduces firmer definition. The emerging movement is toward naming terms, separating responsibilities, or refusing what can no longer be supported. This is not a rejection of receptivity but its completion: healthy support eventually clarifies what it cannot carry.",
        "Do not wait until resentment or exhaustion makes boundary-setting punitive. The danger is allowing over-accommodation to accumulate until the only available correction feels like battle. Earlier definition would have been cheaper.",
        "Where has support reached its honest limit, and what boundary can be stated before accumulated strain turns the correction into conflict?",
        "Line 6 shows the limit of receptivity: when accommodation can no longer hold competing demands, clear definition becomes necessary.",
      ),
    ],
  },
  {
    number: 3,
    coreTheme: "Difficulty at the beginning",
    coreMeaning: "Difficulty at the beginning describes formation before order has stabilized. A new undertaking can contain real vitality while still producing confusion, competing priorities, fragile coordination, and more resistance than its eventual value would suggest. The reading does not treat early disorder as proof of failure. Instead it asks whether enough structure exists for the new thing to survive its own momentum. Clarify the immediate task, secure practical support, and resist the temptation to demand mature performance from an immature system. Early friction is diagnostic: it reveals missing roles, weak sequencing, unrealistic assumptions, or the absence of allies. Progress comes through establishment rather than speed. Build the next workable piece, verify it, and let confidence grow from a structure that can actually carry what has begun.",
    strength: "the ability to organize confusion into first workable steps",
    challenge: "rushing an immature beginning or demanding clarity before it can exist",
    orientation: "establish order, allies, and next steps before seeking speed",
    structureInterpretation: "Thunder below initiates movement while Water above introduces uncertainty and recurring hazard. The structure therefore combines a strong impulse to begin with an outer field that does not yet offer a clear route. Quick I Ching reads this tension as the normal difficulty of formation: movement is real, but it needs sequencing, support, and repeated orientation before it becomes dependable progress.",
    reflectionQuestions: [
      "Which part of this beginning is genuinely confused, and which part simply has not had enough time to form?",
      "What support, role, or sequence is missing before greater speed would become useful rather than destabilizing?",
      "Which early friction should be treated as design information instead of as a reason to abandon the undertaking?",
    ],
    watchFor: [
      "A small piece of order beginning to repeat reliably inside an otherwise messy start.",
      "Pressure to scale, announce, or accelerate before responsibilities and dependencies are clear.",
      "An ally, resource, or simple sequence that turns confusion into a workable next step.",
    ],
    transitionTheme: "initial disorder becoming a structure that can carry growth",
    stabilityTheme: "patience with formation while protecting the essentials",
    lowerTrigram: "zhen",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Pause to establish the first foothold",
        "The beginning has energy, but the route is not yet stable enough for a direct rush forward. The first line favors stopping long enough to mark a foothold: define what is actually being attempted, identify the first dependency, and find help that can remain involved when novelty fades. Hesitation can be intelligent when it creates order instead of merely delaying commitment.",
        "As this line changes, raw beginning energy starts to become organized action. The transition depends on converting uncertainty into one reliable point of coordination. A role, rule, ally, or first deliverable can give the movement a place to return to when later complexity increases.",
        "Do not mistake early enthusiasm for infrastructure. Acting before the first support is secured can turn ordinary startup friction into a crisis of confidence. But endless planning is another danger; the foothold exists to enable movement, not replace it.",
        "What single piece of structure would make the next step repeatable instead of improvised?",
        "Line 1 asks the new undertaking to establish a dependable foothold and support before accelerating.",
      ),
      authoredLine(
        "Separate delay from refusal",
        "The second line deals with a beginning that encounters delay, ambiguity, or a relationship whose timing is not yet settled. Something may look like rejection when it is actually unfinished coordination. The useful response is patience with discernment: clarify intentions, avoid binding commitments made under confusion, and allow the real shape of the partnership or opportunity to become visible.",
        "Change here moves the beginning toward clearer relationship. The transition is less about forcing an answer than about allowing uncertainty to differentiate itself. What is viable will begin to show consistency; what is not will remain dependent on pressure, fantasy, or repeated rescue.",
        "Impatience can create a premature agreement simply to escape uncertainty. Conversely, romanticizing delay can keep an unavailable option alive long after the evidence has changed. Let behavior, not hope alone, resolve the ambiguity.",
        "Which delayed relationship or decision needs more evidence before you call it either a commitment or a dead end?",
        "Line 2 asks the beginning to let timing and behavior clarify an uncertain connection before making it binding.",
      ),
      authoredLine(
        "Do not chase without a guide",
        "The third line warns against pursuing a difficult path without enough knowledge of the terrain. Early projects often create urgency to prove progress, and that urgency can send attention after whatever seems to move. Here the better move is to admit where guidance is missing. A map, experienced person, tested method, or clearer criterion can prevent effort from becoming wandering.",
        "When this line changes, confusion is capable of becoming informed direction, but only if the pursuit is interrupted long enough to learn. The transition is from reactive searching to a route chosen with evidence. Stopping the chase may feel like lost momentum while actually preserving the undertaking.",
        "Do not equate activity with navigation. Repeatedly pursuing weak signals can consume the resources needed for a sound route later. The risk grows when embarrassment makes it hard to admit that the current approach lacks guidance.",
        "Where are you moving mainly because stopping would expose that you do not yet know the terrain?",
        "Line 3 redirects restless pursuit toward guidance, criteria, and a route that can be understood before it is chased.",
      ),
      authoredLine(
        "Seek the alliance the situation requires",
        "By the fourth line, the beginning has reached a point where solitary effort is no longer enough. Progress depends on approaching the person, team, resource, or relationship that can carry what the inner effort cannot. This is not weakness; formation often requires joining complementary capacities. The useful alliance is specific to the obstacle, not simply the most available source of encouragement.",
        "Change here turns a partly formed initiative outward. The transition asks whether support can become reciprocal and task-relevant. An honest request, clear division of work, or explicit invitation can transform a stalled beginning into coordinated movement.",
        "Pride can delay asking until the need becomes urgent, while dependency can hand too much control to the first helper who appears. Define what support is needed and what remains your responsibility before entering the alliance.",
        "Who has the complementary capacity this beginning now requires, and what precise request would make cooperation possible?",
        "Line 4 moves the emerging structure forward by seeking a specific, reciprocal alliance rather than forcing solitary progress.",
      ),
      authoredLine(
        "Nourish the center before expanding",
        "The fifth line gives the new undertaking a center, but that center is still vulnerable. There may be enough legitimacy, resources, or traction to continue, yet large expansion could dilute what has only recently become coherent. The line favors feeding the core: protect quality, strengthen the central relationship, and make the first success repeatable before extending promises outward.",
        "As this line changes, the beginning approaches a more established structure. The key transition is from fragile coherence to capacity that can support others. Growth is appropriate only to the extent that the center can nourish the new load without losing what made it viable.",
        "Early success can produce pressure to scale before the system knows how to reproduce it. Do not let visibility, demand, or praise outrun the routines that sustain the center. A larger promise built on a fragile core magnifies the eventual correction.",
        "What part of the new structure must become reliably nourishing before you ask it to carry more people, scope, or expectation?",
        "Line 5 protects the center of a difficult beginning so early success becomes repeatable before it is expanded.",
      ),
      authoredLine(
        "Recognize when the beginning needs redesign",
        "The top line shows difficulty that has persisted long enough to call the original approach into question. Continuing to label every setback ‘normal early friction’ can become denial. Grief, frustration, or exhaustion may be signaling that the undertaking needs a different structure, route, or definition rather than another attempt to push the same beginning through.",
        "Change at the top releases attachment to the original formation. The emerging possibility is not necessarily abandonment; it may be a redesign that preserves the purpose while changing the vehicle. The transition becomes constructive when lessons from the failed pattern are carried forward explicitly.",
        "Do not make suffering proof of commitment. Sunk cost can turn persistence into repetition and prevent the project from using what difficulty has taught. The opposite risk is discarding the purpose before separating it from the flawed method.",
        "What has this difficult beginning taught you that now requires redesign rather than another round of the same effort?",
        "Line 6 asks whether persistent startup difficulty has become evidence for redesign, not merely a test of endurance.",
      ),
    ],
  },
  {
    number: 4,
    coreTheme: "Learning through uncertainty",
    coreMeaning: "Learning through uncertainty begins with an uncomfortable fact: the situation cannot be understood by pretending to know more than the evidence allows. Meng treats not-knowing as a developmental condition rather than an embarrassment. Good learning requires a real question, a trustworthy source of correction, and enough discipline to stop asking the same question after an answer has already been ignored. The reading favors curiosity joined to responsibility. Investigate before guessing, test what you learn, and let consequences refine your view. Guidance can help, but it cannot substitute for attention or repeated practice. The danger is either false certainty or endless dependence on answers. Mature learning eventually changes conduct. If new information never alters a decision, habit, or standard, inquiry has become performance rather than development.",
    strength: "curiosity that can turn confusion into real learning",
    challenge: "pretending to know, asking without listening, or repeating the same mistake",
    orientation: "treat uncertainty as a reason to investigate rather than to guess",
    structureInterpretation: "Water below places uncertainty, depth, and risk inside the situation; Mountain above creates a boundary that stops undirected movement. Together they describe learning by containing confusion long enough to examine it. Quick I Ching reads the structure as disciplined inquiry: uncertainty is not solved by more motion, but by questions, limits, instruction, and evidence that can reshape behavior.",
    reflectionQuestions: [
      "What do you genuinely not know here, and which assumption have you been treating as if it were evidence?",
      "What source of instruction or feedback has earned enough trust to correct you when its answer is inconvenient?",
      "Which behavior should change if you have actually learned the lesson you keep saying you understand?",
    ],
    watchFor: [
      "A question becoming more precise after contact with evidence rather than multiplying into more speculation.",
      "Repeated requests for advice that do not change the decision, habit, or standard under examination.",
      "A moment when uncertainty becomes manageable because a boundary, teacher, or test makes the next experiment clear.",
    ],
    transitionTheme: "uncertainty becoming informed judgment through disciplined learning",
    stabilityTheme: "continued openness to evidence without surrendering discernment",
    lowerTrigram: "kan",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Create discipline around the first lesson",
        "The first line addresses confusion by introducing a boundary. When uncertainty is completely unstructured, attention scatters and every impulse can look like a possible answer. A rule, practice, or consequence helps the learner distinguish exploration from disorder. The aim is not punishment; it is to create enough containment that experience can teach something repeatable.",
        "Change here turns raw confusion into the beginning of method. Once a boundary exists, feedback becomes interpretable: you can see what happens when the practice is followed, ignored, or adjusted. The transition is from unbounded guessing to learning that has a frame.",
        "Excessive discipline can make the learner afraid to experiment or ask honest questions. Use structure to make consequences visible, not to demand obedience for its own sake. A rule that cannot be explained teaches submission rather than judgment.",
        "What simple boundary would make this uncertainty easier to learn from without closing down legitimate experimentation?",
        "Line 1 gives uncertainty a workable frame so consequences can become information rather than noise.",
      ),
      authoredLine(
        "Teach without needing the learner to be identical to you",
        "The second line concerns the capacity to hold another person’s inexperience without contempt. Good guidance makes room for uneven development while still maintaining standards. The teacher, manager, parent, or experienced peer succeeds here by being reliable enough to answer confusion and flexible enough not to demand that learning follow one personality or pace.",
        "As this line changes, instruction becomes a relationship with real consequences. The transition asks whether guidance can produce independent judgment rather than dependence on the guide. Teaching is working when the learner gradually carries more of the discrimination themselves.",
        "Patience can slide into rescuing, and authority can slide into self-importance. Do not answer every uncertainty for the learner, and do not use their inexperience as proof of your superiority. Both errors prevent development.",
        "Where could you offer steadier guidance while leaving the other person enough responsibility to develop their own judgment?",
        "Line 2 frames good instruction as patient, bounded support that helps another person become more capable of judging for themselves.",
      ),
      authoredLine(
        "Do not let fascination replace learning",
        "The third line warns that attraction to status, certainty, expertise, or a desired answer can corrupt inquiry. A learner may become more interested in possessing the teacher, conclusion, or symbol of knowledge than in doing the work of understanding. In practical terms, this can appear as chasing impressive authorities, flattering a gatekeeper, or choosing evidence because it confirms the outcome already wanted.",
        "Change here exposes the difference between inquiry and attachment. The transition requires returning attention to the question itself: what is true, what can be tested, and what behavior follows? When fascination loosens, learning can become less dependent on image and more accountable to reality.",
        "Beware of outsourcing judgment to someone simply because they appear certain. Admiration can make contradictions invisible. The same caution applies to a preferred theory or tool: elegance is not evidence.",
        "What person, theory, or desired answer are you tempted to trust because of its appeal rather than because it survives careful testing?",
        "Line 3 asks learning to separate genuine evidence from fascination with authority, status, or a preferred conclusion.",
      ),
      authoredLine(
        "Isolation inside confusion",
        "The fourth line describes uncertainty that has become enclosed. The learner may lack access to good guidance, may be repeating the same internal story, or may feel too embarrassed to expose confusion to outside correction. The problem is no longer simply not knowing; it is being trapped in a narrow information environment where the same assumptions circulate without challenge.",
        "A change at this point can open the learning system. The transition comes through contact: ask a better-informed person, seek direct evidence, compare another perspective, or enter a setting where your current explanation can be tested. New information matters because it interrupts the loop.",
        "Do not confuse private rumination with research. More time spent inside the same assumptions can increase confidence without increasing accuracy. Isolation is especially risky when shame makes correction feel threatening.",
        "What outside source of evidence or perspective would most directly challenge the explanation you have been repeating to yourself?",
        "Line 4 identifies isolation as part of the ignorance and points toward outside contact that can break the closed loop.",
      ),
      authoredLine(
        "Beginner’s openness with real discernment",
        "The fifth line represents a strong form of not-knowing: openness without defensiveness. Here the learner can admit uncertainty, receive instruction, and still remain responsible for understanding it. There is no need to perform sophistication. Simplicity becomes an advantage because attention is available for what the evidence actually says rather than for protecting an image of competence.",
        "Change here turns receptivity into informed judgment. The transition should preserve humility while adding discrimination: what has been learned must now be tested, integrated, and used. The goal is not to remain a beginner, but to keep the beginner’s ability to receive correction after competence grows.",
        "Naivety is not the same as openness. Do not accept every confident answer simply because you are willing to learn. A receptive mind still asks whether the source, reasoning, and consequences are sound.",
        "How can you admit what you do not know while still testing the guidance you receive instead of surrendering judgment?",
        "Line 5 values teachable openness that receives guidance without abandoning the responsibility to understand and test it.",
      ),
      authoredLine(
        "Correct persistent folly without becoming punitive",
        "At the top line, ignorance is no longer innocent if the same avoidable error keeps returning after clear feedback. A firmer intervention may be necessary: remove an enabling condition, enforce a consequence, or stop protecting someone—including yourself—from the result of repeated refusal to learn. The purpose remains correction, not retaliation.",
        "Change here ends an educational phase and introduces accountability. The emerging pattern asks whether consequences can interrupt repetition strongly enough for learning to restart. Once the boundary has worked, the relationship should not remain organized around punishment.",
        "Humiliation teaches defensiveness more readily than wisdom. Do not use another person’s mistake as permission for cruelty, nor make a permanent identity out of a correctable failure. Firmness is justified only by the learning function it serves.",
        "What consequence would interrupt this repeated mistake while still leaving a credible path back to responsible learning?",
        "Line 6 uses proportionate accountability to stop repeated folly, with the aim of reopening learning rather than extending punishment.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
