import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 1,
    coreTheme: "Creative force",
    legacySummary: "Strong initiating energy favors purposeful action, but lasting progress depends on discipline, timing, and the ability to keep strength aligned with principle.",
    strength: "disciplined initiative",
    challenge: "overextension or mistaking force for correctness",
    orientation: "act with purpose while testing timing and proportion",
    transitionTheme: "turning raw creative force into form that others and circumstances can sustain",
    stabilityTheme: "consistent direction without needing constant acceleration",
    lowerTrigram: "qian",
    upperTrigram: "qian",
    lineEmphases: [
      "test the first impulse before turning initiative into commitment",
      "make creative energy repeatable through disciplined practice",
      "keep strength from becoming strain when the first real resistance appears",
      "translate a strong inner direction into conduct that can meet outside constraints",
      "use visible capability as stewardship rather than as proof of superiority",
      "recognize when continued exertion would turn useful force into excess",
    ],
  },
  {
    number: 2,
    coreTheme: "Receptive support",
    legacySummary: "The situation calls for responsiveness, patience, and steady support. Progress comes less from forcing events than from making room for what can genuinely develop.",
    strength: "capacity to receive, support, and carry what is viable",
    challenge: "passivity, over-accommodation, or losing your own boundaries",
    orientation: "make room, observe what is actually developing, and support it without forcing",
    transitionTheme: "receptivity becoming active stewardship rather than passive waiting",
    stabilityTheme: "steady support that preserves both openness and boundaries",
    lowerTrigram: "kun",
    upperTrigram: "kun",
    lineEmphases: [
      "make room for what is emerging without giving away necessary boundaries",
      "support what proves viable through steady and practical responsiveness",
      "distinguish patient receptivity from passive drift when pressure increases",
      "receive outside demands without becoming shapeless or losing your own measure",
      "make support dependable enough to hold others without controlling them",
      "recognize when accommodation has reached its useful limit and needs definition",
    ],
  },
  {
    number: 3,
    coreTheme: "Difficulty at the beginning",
    legacySummary: "Early disorder is part of formation. Clarify priorities, gather support, and build structure before expecting a new undertaking to move smoothly.",
    strength: "the ability to organize confusion into first workable steps",
    challenge: "rushing an immature beginning or demanding clarity before it can exist",
    orientation: "establish order, allies, and next steps before seeking speed",
    transitionTheme: "initial disorder becoming a structure that can carry growth",
    stabilityTheme: "patience with formation while protecting the essentials",
    lowerTrigram: "zhen",
    upperTrigram: "kan",
    lineEmphases: [
      "identify the first workable order inside a confused beginning",
      "build local support before expecting the new structure to carry much weight",
      "treat early friction as information about what the beginning still lacks",
      "bring a partly formed plan into contact with reality without pretending it is mature",
      "coordinate the new effort around a clear center before expanding it further",
      "stop calling the situation a beginning once its unresolved disorder requires redesign",
    ],
  },
  {
    number: 4,
    coreTheme: "Learning through uncertainty",
    legacySummary: "Not knowing is the central condition. Ask carefully, learn from consequences, and replace impulsive certainty with disciplined inquiry.",
    strength: "curiosity that can turn confusion into real learning",
    challenge: "pretending to know, asking without listening, or repeating the same mistake",
    orientation: "treat uncertainty as a reason to investigate rather than to guess",
    transitionTheme: "uncertainty becoming informed judgment through disciplined learning",
    stabilityTheme: "continued openness to evidence without surrendering discernment",
    lowerTrigram: "kan",
    upperTrigram: "gen",
    lineEmphases: [
      "name what you do not know before seeking an answer",
      "turn curiosity into a disciplined learning relationship rather than scattered questions",
      "notice when uncertainty is provoking guesses, defensiveness, or repeated mistakes",
      "test what you have learned when it meets a wider and less forgiving context",
      "let informed judgment guide others without pretending uncertainty has disappeared",
      "release the identity of the learner when a lesson now requires accountable action",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
