import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 5,
    coreTheme: "Waiting with purpose",
    legacySummary: "Conditions are not fully ready. Prepare, conserve confidence, and use the interval well rather than treating delay as failure.",
    strength: "prepared patience that keeps resources and attention intact",
    challenge: "forcing timing, drifting into passivity, or treating delay as rejection",
    orientation: "prepare deliberately and act when conditions actually support movement",
    transitionTheme: "waiting becoming readiness so action is less improvised when the opening arrives",
    stabilityTheme: "confidence maintained by useful preparation rather than constant motion",
    lowerTrigram: "qian",
    upperTrigram: "kan",
    lineEmphases: [
      "use the first delay to prepare rather than to rehearse frustration",
      "make waiting active through readiness, reserves, and attention to conditions",
      "avoid forcing a passage simply because patience has become uncomfortable",
      "recognize the first real opening without confusing motion around you with readiness",
      "act from prepared confidence when timing and conditions finally align",
      "leave the waiting posture once delay has served its purpose and action is due",
    ],
  },
  {
    number: 6,
    coreTheme: "Conflict",
    legacySummary: "Competing positions are hardening. Define the real issue, limit unnecessary escalation, and consider where principled compromise or outside perspective can help.",
    strength: "clarity about the actual point of disagreement",
    challenge: "escalation, self-righteousness, or fighting over a distorted version of the issue",
    orientation: "separate principle from pride and limit the conflict to what must be resolved",
    transitionTheme: "contention becoming a clearer boundary, settlement, or decision about where engagement should stop",
    stabilityTheme: "integrity that does not depend on winning every contested point",
    lowerTrigram: "kan",
    upperTrigram: "qian",
    lineEmphases: [
      "define the actual point of disagreement before taking a side",
      "test whether a limited settlement is possible without abandoning principle",
      "notice when pressure is turning a solvable dispute into a contest of pride",
      "carry your position outward with enough restraint to hear the other side accurately",
      "use authority or mediation to narrow conflict rather than to humiliate an opponent",
      "know when continued contention produces no further clarity and should be ended",
    ],
  },
  {
    number: 7,
    coreTheme: "Organization and discipline",
    legacySummary: "Collective effort needs clear roles, legitimate leadership, and restraint. Order matters more than enthusiasm when many forces must act together.",
    strength: "coordinated effort under clear responsibilities",
    challenge: "confused authority, coercive control, or mobilizing people without a workable structure",
    orientation: "clarify roles, standards, and command before expanding collective action",
    transitionTheme: "scattered effort becoming coordinated capacity through legitimate structure",
    stabilityTheme: "discipline that serves the mission rather than becoming an end in itself",
    lowerTrigram: "kan",
    upperTrigram: "kun",
    lineEmphases: [
      "establish a legitimate purpose before mobilizing people or resources",
      "make roles and discipline workable in the ordinary center of the group",
      "correct confusion in command before pressure magnifies it",
      "coordinate the group as it meets external demands and real consequences",
      "use central authority to protect standards, responsibility, and proportion",
      "demobilize or redistribute power when the organized effort has reached its end",
    ],
  },
  {
    number: 8,
    coreTheme: "Holding together",
    legacySummary: "Connection is possible when commitments are sincere and timely. Examine what truly creates trust before joining, leading, or asking others to align.",
    strength: "trustworthy alignment around a real center",
    challenge: "joining from fear, demanding loyalty without reciprocity, or arriving after commitment has already formed",
    orientation: "test the basis of belonging and commit where trust can be mutual",
    transitionTheme: "loose connection becoming durable cohesion when commitments are clear",
    stabilityTheme: "belonging sustained by mutual reliability rather than pressure",
    lowerTrigram: "kun",
    upperTrigram: "kan",
    lineEmphases: [
      "test whether the first bond is based on real trust rather than fear of being outside",
      "make belonging reciprocal through reliable commitments in ordinary practice",
      "notice when loyalty is being demanded faster than trust can honestly form",
      "enter a wider alliance without abandoning the terms that make connection trustworthy",
      "become a center others can join voluntarily because reliability is visible",
      "release a bond that survives only through pressure, habit, or fear of separation",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
