import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 5,
    coreTheme: "Waiting with purpose",
    coreMeaning: "Waiting with purpose describes a delay that should be used rather than merely endured. Conditions are not yet ready for clean movement, but the interval is not empty: it can strengthen reserves, clarify dependencies, reduce improvisation, and distinguish a real opening from nervous motion. Xu asks for confidence without premature action. The further the situation moves toward danger, the more important it becomes to preserve judgment rather than let discomfort set the timetable. Preparation should become concrete—resources, information, relationships, and fallback capacity—not a ritual of endless planning. When the opening actually arrives, waiting has completed its function and must give way to action. The reading therefore treats patience as a temporary operating mode whose quality can be tested by whether it leaves you more ready, not simply older.",
    strength: "prepared patience that keeps resources and attention intact",
    challenge: "forcing timing, drifting into passivity, or treating delay as rejection",
    orientation: "prepare deliberately and act when conditions actually support movement",
    structureInterpretation: "Heaven below provides strong forward intention while Water above represents an uncertain or hazardous outer passage. The structure places capacity beneath conditions that cannot yet be forced. Quick I Ching reads the combination as purposeful waiting: preserve initiative internally, but let external readiness—not impatience—determine when the stored force should move.",
    reflectionQuestions: [
      "What can be made materially more ready during this delay instead of merely being worried about?",
      "Which sign would indicate a genuine opening, and which kinds of activity would only imitate progress?",
      "At what point would continued waiting stop protecting timing and start becoming avoidance?",
    ],
    watchFor: [
      "Reserves, information, or relationships becoming strong enough that the eventual move requires less improvisation.",
      "Anxiety creating artificial deadlines or repeated attempts to force a passage that remains structurally unready.",
      "A concrete external condition changing in a way that makes action safer, simpler, or more proportionate.",
    ],
    transitionTheme: "waiting becoming readiness so action is less improvised when the opening arrives",
    stabilityTheme: "confidence maintained by useful preparation rather than constant motion",
    lowerTrigram: "qian",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Wait at a safe distance",
        "The first line keeps the delay away from the main hazard. You may know a difficult passage lies ahead, but you are not yet entangled in it. Use that distance to establish ordinary routines, preserve energy, and prepare without dramatizing the obstacle. This is the least expensive moment to improve readiness because the situation has not yet begun consuming resources through direct friction.",
        "If this line changes, waiting is beginning to move closer to engagement. The useful shift is from general preparation to specific readiness: clarify what you will need once the hazard is no longer distant and identify the point at which remaining outside would cease to be prudent.",
        "Do not enter the difficulty early just to feel that something is happening. Equally, do not treat safe distance as permanent exemption from the task. Preparation has value only if it eventually supports contact with reality.",
        "What can you prepare now, while the main difficulty is still far enough away that mistakes remain cheap?",
        "Line 1 uses safe distance to build readiness before the difficult passage begins consuming attention and resources.",
      ),
      authoredLine(
        "Delay begins to create friction",
        "The second line brings waiting closer to the contested ground. Minor criticism, uncertainty, or irritating signals may appear even though the central danger has not arrived. The key is not to let peripheral noise set the strategy. Keep preparing, answer what genuinely needs an answer, and distinguish reputational discomfort from evidence that the underlying timing has changed.",
        "Change here shifts the reading from calm distance toward a more exposed interval. The transition asks whether patience can survive social or emotional friction without becoming reactive. A measured response preserves options while the real conditions continue to develop.",
        "Small provocations can lure you into a premature fight. Do not spend the reserves meant for the main passage on every comment, rumor, or delay-related frustration. Noise becomes expensive when it changes your timetable without changing the facts.",
        "Which current irritation is actually relevant to readiness, and which one can be allowed to pass without altering the plan?",
        "Line 2 tests whether prepared patience can remain intact when delay starts producing visible but still secondary friction.",
      ),
      authoredLine(
        "Waiting in the mud",
        "The third line shows delay becoming entanglement. The position is close enough to danger that passive waiting now carries costs: indecision, mixed commitments, or poorly chosen ground can make the obstacle harder than it needed to be. The work is to recognize how your current placement contributes to the problem and to reduce exposure before pressure dictates the next move.",
        "As this line changes, the reading turns from simple waiting toward correcting position. The transition may involve withdrawing from a bad setup, strengthening a weak boundary, or changing the route so that the eventual crossing begins from firmer ground.",
        "Do not romanticize patience when the current position is actively worsening. Remaining still in unstable ground is not the same as preserving resources. The danger is letting delay become a condition that others, habits, or risks can exploit.",
        "Where has waiting itself become a source of entanglement, and what repositioning would make the eventual action less exposed?",
        "Line 3 warns that delay on unstable ground requires repositioning, not simply more patience.",
      ),
      authoredLine(
        "Inside the danger, preserve an exit",
        "The fourth line is no longer waiting outside risk; the situation has entered a genuinely exposed phase. Pressure may feel immediate, emotional, or costly. The priority is survival of judgment: reduce unnecessary commitments, identify the exit, and avoid making a permanent decision simply because the present discomfort is intense. Waiting here means not adding another layer of danger while a path out is being found.",
        "Change at this line can open a release from direct exposure. The emerging movement depends on recognizing the route that leads out rather than trying to dominate the hazard from inside it. Simpler commitments and clearer boundaries help restore room to choose.",
        "Panic can turn a difficult moment into a deeper trap by provoking rash promises, confrontations, or doubling down. Do not confuse immediate intensity with evidence that the largest possible response is required.",
        "What is the cleanest way to reduce exposure now without creating a larger obligation that will survive the present danger?",
        "Line 4 makes preservation and exit the task: inside real danger, do not add commitments that make the hazard harder to leave.",
      ),
      authoredLine(
        "Use the interval to restore capacity",
        "The fifth line gives waiting a centered and sustaining quality. Basic needs can be met; there is enough stability to eat, rest, plan, and maintain confidence while timing finishes its work. This is not indulgence. Restored capacity is part of readiness, especially after a period of tension. The line favors normalizing the body and mind so the eventual decision is not made from depletion.",
        "If this line moves, preparation is nearing completion. The transition is from maintained readiness toward action that can be taken without desperation. A well-rested, well-supplied center is more capable of recognizing the opening without either grasping at it or missing it through fatigue.",
        "Comfort can quietly become attachment to the waiting state. Do not make preparation so pleasant or elaborate that movement itself starts to feel threatening. Nourishment should support the crossing, not replace it.",
        "What form of rest, replenishment, or ordinary maintenance would make you more capable of acting well when the opening appears?",
        "Line 5 treats nourishment and normal routine as part of readiness, while keeping the eventual move clearly in view.",
      ),
      authoredLine(
        "An unexpected arrival changes the wait",
        "The top line shows waiting reaching a place where control over timing is minimal. An unexpected person, demand, event, or piece of information can enter and alter the situation. The useful response is respectful attention rather than immediate resistance. What arrives may contain a way through that planning alone could not produce, especially if the delay has already exhausted the obvious options.",
        "Change here ends the old waiting configuration. The emerging pattern comes from receiving new information and revising the map rather than insisting that the opening resemble what was expected. Courtesy, listening, and quick reorientation can turn surprise into usable direction.",
        "Do not accept every unexpected arrival as a rescue. Surprise deserves examination, not surrender. The risk is either rejecting help because it was not planned or granting it authority merely because it appeared at a dramatic moment.",
        "What unexpected development deserves a fair hearing because it may change the structure of the delay rather than merely interrupt it?",
        "Line 6 closes the waiting cycle by asking you to receive an unexpected development carefully enough to recognize a genuine new route.",
      ),
    ],
  },
  {
    number: 6,
    coreTheme: "Conflict",
    coreMeaning: "Conflict describes a situation in which positions are hardening and the cost of misunderstanding is rising. Song does not assume that one side is morally pure or that every disagreement should be compromised away. It asks for accurate definition: what is actually disputed, what principle matters, what is negotiable, and where engagement should stop. The more conflict becomes a contest of identity or pride, the less information either side can use. Evidence, boundaries, proportionate procedure, and credible mediation are therefore strengths. A partial resolution can be wiser than total victory if the latter requires escalation that damages the larger system. This reading favors firmness without vindictiveness. Clarify the claim, narrow the battlefield, and preserve enough integrity that a settlement or disengagement remains possible.",
    strength: "clarity about the actual point of disagreement",
    challenge: "escalation, self-righteousness, or fighting over a distorted version of the issue",
    orientation: "separate principle from pride and limit the conflict to what must be resolved",
    structureInterpretation: "Water below holds risk and suspicion inside the situation while Heaven above pushes strongly in its own direction. The two tendencies do not naturally meet, producing a structure of opposed movement. Quick I Ching reads this as conflict that requires definition and procedure: strong conviction must be constrained by accurate facts, limits, and a clear decision about how far contention should go.",
    reflectionQuestions: [
      "What is the narrowest accurate statement of the disagreement, stripped of accumulated accusations?",
      "Which part of your position is principle, and which part is now being defended mainly because backing down feels costly?",
      "What settlement, mediation, or boundary would resolve enough of the conflict without requiring total victory?",
    ],
    watchFor: [
      "The dispute becoming easier to describe in one concrete sentence instead of a history of grievances.",
      "Escalation driven by humiliation, audience effects, or the need to win a symbolic point unrelated to the original issue.",
      "A credible procedure, mediator, or boundary that allows the conflict to narrow without denying the real difference.",
    ],
    transitionTheme: "contention becoming a clearer boundary, settlement, or decision about where engagement should stop",
    stabilityTheme: "integrity that does not depend on winning every contested point",
    lowerTrigram: "kan",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Do not enlarge the first dispute",
        "The first line advises against turning an early disagreement into a campaign. The issue may be real, but repeating it, recruiting an audience, or adding old grievances can make a limited problem much harder to settle. State what matters, document the necessary facts, and resist the impulse to give the conflict a larger identity than it deserves.",
        "When this line changes, contention can move toward a bounded resolution. The shift occurs by limiting duration and scope: enough is said to protect the principle, but not so much that every relationship becomes organized around the dispute.",
        "Silence is not always the answer; an unspoken problem can still grow. The caution is against amplification, not clarity. Say what must be said once with enough precision that repetition is not needed to prove seriousness.",
        "What would a complete but deliberately limited statement of this disagreement sound like?",
        "Line 1 contains conflict early by making the claim clear without expanding the quarrel around it.",
      ),
      authoredLine(
        "Know when the contest is unwinnable",
        "The second line recognizes a mismatch of position or power. Continuing the contest may not protect principle; it may simply expose more people and resources to a fight that cannot be carried effectively. Strategic withdrawal, local protection, or returning attention to responsibilities under your control can preserve dignity without pretending the difference disappeared.",
        "Change here redirects energy away from direct contention. The emerging pattern depends on distinguishing surrender of principle from refusal to pursue a losing form of engagement. A boundary can remain firm even when the contest itself is ended.",
        "Pride can make withdrawal feel like moral failure, while fear can make necessary advocacy look impossible. Evaluate the actual leverage and consequences. Retreat is useful only if it protects what matters better than continued fighting would.",
        "If winning this form of the conflict is unrealistic, what can you still protect without prolonging the contest?",
        "Line 2 redirects an unwinnable contest toward protection, boundary, and responsibilities that remain within reach.",
      ),
      authoredLine(
        "Hold to earned substance, not status",
        "The third line favors standing on what has already been earned through work, responsibility, or established commitment rather than trying to gain new status through the dispute. Conflict can tempt people to inflate claims in order to avoid appearing weak. Here the safer ground is modest: keep what is legitimate, fulfill the obligations attached to it, and do not make ambition part of the argument.",
        "As this line changes, conflict becomes a test of whether established substance can remain intact without expansion. The transition may leave you with less symbolic victory but more real stability because the position no longer depends on proving superiority.",
        "Do not use the language of principle to disguise a new claim for advantage. A defensible position becomes harder to defend when extra demands are attached to it. Protect the core by refusing unnecessary additions.",
        "What part of your position is already legitimate and sufficient without asking this conflict to grant you anything more?",
        "Line 3 protects earned substance by refusing to turn conflict into a vehicle for status, expansion, or extra claims.",
      ),
      authoredLine(
        "Turn back from a conflict that cannot be justified",
        "The fourth line allows for an important correction: you may discover that the current form of contention is not the right one to pursue. New facts, a better perspective, or recognition of your own contribution can make continued resistance less defensible. Returning to a sounder course is not humiliation; it is evidence that principle matters more than consistency of ego.",
        "Change here transforms confrontation into self-correction. The emerging movement is toward a more stable rule, agreement, or inner standard that can be followed without keeping an opponent in view. Peace becomes possible because the conflict no longer supplies identity.",
        "The danger is either stubbornness or performative capitulation. Do not reverse position merely to escape discomfort; reverse because the evidence or principle has genuinely changed how the issue should be handled.",
        "What new fact or perspective would justify changing your own position even if the other side never admitted fault?",
        "Line 4 makes principled self-correction a legitimate way out of conflict when the current contention no longer deserves pursuit.",
      ),
      authoredLine(
        "Submit the dispute to a fair standard",
        "The fifth line is the strongest place for adjudication, mediation, or a clear decision because the conflict can be brought under a legitimate standard. The goal is not to reward the louder side but to separate evidence from emotion and apply rules that both parties can understand. A fair center can end ambiguity that private argument could not resolve.",
        "When this line changes, contention becomes decision. The transition works only if the standard is credible and the process does not become another weapon. Once judgment is made, the next task is implementation rather than endless relitigation.",
        "Authority can settle a dispute badly if it humiliates one side or bends rules to produce a convenient answer. A decision gains durability from transparent reasoning and proportionate consequences, not merely from power to enforce it.",
        "What neutral standard, evidence, or credible mediator could decide this issue more cleanly than continued private argument?",
        "Line 5 moves conflict toward fair adjudication, using a legitimate standard to replace escalating private contention.",
      ),
      authoredLine(
        "Victory that cannot be worn securely",
        "At the top line, conflict may produce a visible prize, title, concession, or symbolic victory, but the gain is unstable because it was obtained through contention that remains active underneath. Winning can become another burden if it requires constant defense or repeated demonstrations of dominance. The line asks whether the trophy is worth the ongoing conflict needed to keep it.",
        "Change here releases attachment to victory as proof of rightness. The emerging pattern favors a more durable settlement in which status is less important than stable terms. Letting go of the symbolic prize may reduce the incentives for the dispute to restart.",
        "Do not confuse a favorable ruling or public win with actual resolution. If resentment, ambiguity, or retaliation remains, celebrating too aggressively can recreate the very conflict that seemed finished.",
        "What part of ‘winning’ this dispute would still need constant defense, and would a less visible settlement be more durable?",
        "Line 6 warns that a contentious victory can become unstable property; durable resolution matters more than a trophy that keeps the fight alive.",
      ),
    ],
  },
  {
    number: 7,
    coreTheme: "Organization and discipline",
    coreMeaning: "Organization and discipline become necessary when many people, resources, or risks must act together. Shi is not a celebration of command for its own sake. It asks whether collective force has a legitimate purpose, clear roles, dependable routines, and leadership capable of using power without confusing discipline with domination. Enthusiasm cannot substitute for structure when consequences are shared. The reading therefore emphasizes preparation before mobilization, competence in the center, and careful distribution of responsibility. A group becomes strong when people know what they are responsible for, why the effort matters, and how decisions will be made under pressure. It becomes dangerous when authority is vague, power is personal, or the campaign continues after the task has ended. Order should serve the mission and then release what no longer needs mobilization.",
    strength: "coordinated effort under clear responsibilities",
    challenge: "confused authority, coercive control, or mobilizing people without a workable structure",
    orientation: "clarify roles, standards, and command before expanding collective action",
    structureInterpretation: "Water below contains risk, effort, and potentially dangerous force; Earth above provides the field that must carry and organize it. Quick I Ching reads this as collective capacity held inside a broader structure. The issue is not generating more force but making it disciplined, legitimate, and accountable enough that many participants can act without the group becoming chaotic or coercive.",
    reflectionQuestions: [
      "Is the collective effort organized around a purpose clear enough to justify the discipline being asked of people?",
      "Which responsibility or decision right is currently ambiguous enough to create avoidable friction under pressure?",
      "What will tell you that the mobilized structure has completed its task and should release or redistribute authority?",
    ],
    watchFor: [
      "People beginning to coordinate reliably because roles and standards are clearer, not because supervision has intensified.",
      "Authority becoming personalized, punitive, or detached from the purpose that originally justified it.",
      "A completed phase continuing to consume resources because nobody has defined how demobilization should occur.",
    ],
    transitionTheme: "scattered effort becoming coordinated capacity through legitimate structure",
    stabilityTheme: "discipline that serves the mission rather than becoming an end in itself",
    lowerTrigram: "kan",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Mobilize only under clear rules",
        "The first line makes order a prerequisite for collective action. Before people or resources move, the purpose, basic rules, and responsibilities need enough clarity that the group can recognize both correct conduct and unacceptable deviation. Starting with vague authority may feel faster, but ambiguity becomes expensive as soon as pressure arrives.",
        "Change here turns scattered capacity into formal mobilization. The transition should be visible in roles and standards, not merely in stronger rhetoric. A group is becoming an organized force when participants can predict how decisions are made and what they owe one another.",
        "Do not use urgency to justify unclear rules. Once people act under ambiguous authority, later correction can look arbitrary or political. Discipline introduced after confusion has already spread is harder to make legitimate.",
        "What rule or responsibility must be explicit before asking others to commit effort under a shared command?",
        "Line 1 establishes legitimacy and rules before mobilization so collective force begins as order rather than improvisation.",
      ),
      authoredLine(
        "Competence at the center of command",
        "The second line places leadership close to the actual work. Authority is useful because it understands operations, maintains confidence, and can coordinate people without needing constant symbolic display. The leader’s central task is practical: translate purpose into executable decisions, keep standards stable, and remain connected enough to reality that information can travel upward.",
        "As this line changes, organized effort gains a dependable center. The emerging pattern tests whether authority can remain both effective and accountable as responsibility grows. Recognition or formal support strengthens command only when operational competence is already present.",
        "A central leader can become a bottleneck if every decision must pass through one person. Do not confuse being essential with making the organization dependent. Good command builds other people’s capacity to act within clear limits.",
        "Which decisions genuinely require central authority, and which could be delegated without weakening the shared standard?",
        "Line 2 centers command in practical competence while asking leadership to coordinate without making the whole group dependent on one person.",
      ),
      authoredLine(
        "Do not carry dead weight into pressure",
        "The third line warns that a collective effort can be weakened by roles, plans, or commitments that no longer serve but continue to consume capacity. Under pressure, unresolved mistakes become heavy: people may defend failed assumptions, preserve unsuitable assignments, or keep inactive obligations alive because admitting loss feels demoralizing. The group needs an honest inventory of what should be removed.",
        "Change here allows the organization to recover by separating usable capacity from accumulated burden. The transition may involve ending a plan, reassigning a role, or acknowledging a loss so that the living effort is no longer forced to carry it.",
        "Do not hide failure inside the group in the name of morale. Buried mistakes continue to shape decisions and often demand more resources later. The opposite error is scapegoating individuals instead of correcting the structure that produced the failure.",
        "What burden, failed assumption, or obsolete role is the group still carrying because acknowledging it would be uncomfortable?",
        "Line 3 protects collective capacity by removing dead weight and learning from failure before pressure magnifies it.",
      ),
      authoredLine(
        "Withdraw to preserve the force",
        "The fourth line permits an organized retreat when the current position cannot be held productively. Discipline includes the ability to move back without collapse, panic, or shame. Preserving people, trust, and capability can be more faithful to the mission than remaining in a bad position simply to appear resolute.",
        "When this line changes, collective effort is reorganizing around a safer or more viable position. The transition should retain command, communication, and purpose while releasing terrain or commitments that are no longer worth the cost.",
        "A retreat can become disorder if nobody understands the reason or sequence. It can also become avoidance if leaders use preservation as an excuse never to re-engage. Make the withdrawal explicit and connected to the larger purpose.",
        "What would an orderly retreat preserve that a continued stand would unnecessarily consume?",
        "Line 4 treats disciplined withdrawal as a legitimate organizational move when preserving capacity serves the mission better than holding position.",
      ),
      authoredLine(
        "Assign responsibility to the capable",
        "The fifth line addresses command when a real threat or task is present. The central issue is choosing capable responsibility rather than allowing status, enthusiasm, or family-like preference to determine who leads critical work. Experienced judgment should direct the response while less prepared participants are given roles they can actually carry.",
        "Change here makes the organization’s hierarchy visible through assignment. The emerging pattern depends on matching authority to competence. When responsibility is allocated accurately, collective force becomes more precise and less likely to create damage through inexperience.",
        "Do not reward loyalty with command that exceeds capability. A weak appointment can endanger both the mission and the person placed in the role. Conversely, overcontrol by senior people can prevent the next layer from ever developing competence.",
        "Which critical responsibility should be held by demonstrated capability rather than by status, closeness, or enthusiasm?",
        "Line 5 asks the organized force to match authority with proven competence so real responsibility is carried by those prepared for it.",
      ),
      authoredLine(
        "Demobilize without distributing power carelessly",
        "At the top line, the campaign or mobilized phase is ending. The organization now has to convert temporary force into ordinary order. Rewards, roles, and authority should be assigned carefully because power that was useful during crisis can become destabilizing when carried into a different phase without review.",
        "Change here moves from mobilization toward governance and maintenance. The transition succeeds when temporary command structures are dissolved or translated deliberately, preserving legitimate contribution while preventing exceptional powers from becoming permanent by inertia.",
        "Do not let victory or completion become an excuse to hand lasting authority to people whose value depended on the crisis context. Gratitude, recognition, and governance are different decisions and should not be confused.",
        "Which temporary powers or roles should end now, and which contributions deserve a durable place in the ordinary structure?",
        "Line 6 completes collective mobilization by converting temporary force into a stable order without letting crisis authority persist automatically.",
      ),
    ],
  },
  {
    number: 8,
    coreTheme: "Holding together",
    coreMeaning: "Holding together concerns the basis on which people, commitments, or resources genuinely belong together. Bi does not treat connection as automatically good. Cohesion becomes durable when there is a trustworthy center, clear commitment, and enough reciprocity that people join because the relationship is viable rather than because exclusion is frightening. Timing matters: some alliances require an early decision, and repeated hesitation can leave a person outside after the terms have already formed. Leadership is tested by whether others can approach freely and understand what they are joining. The reading asks you to examine the actual glue—shared purpose, reliability, mutual need, habit, fear, or dependency. Strengthen bonds whose center can carry them, and do not demand loyalty where trust has not been earned.",
    strength: "trustworthy alignment around a real center",
    challenge: "joining from fear, demanding loyalty without reciprocity, or arriving after commitment has already formed",
    orientation: "test the basis of belonging and commit where trust can be mutual",
    structureInterpretation: "Earth below creates a receptive field of many yin lines while Water above contains a single central yang line around which cohesion can organize. Quick I Ching reads the structure as a question of trustworthy center and voluntary alignment. The many parts can hold together only if the center is reliable enough to receive commitment without turning belonging into pressure.",
    reflectionQuestions: [
      "What actually holds this group or relationship together when social pressure and habit are removed?",
      "Has the center of the alliance earned trust through consistent conduct, or is loyalty being requested in advance of evidence?",
      "Is there a commitment whose timing now requires a clear yes or no rather than further indefinite testing?",
    ],
    watchFor: [
      "People choosing to coordinate voluntarily because the center proves reliable in ordinary practice.",
      "Belonging being enforced through fear of exclusion, status, guilt, or unclear consequences for dissent.",
      "A decision window closing as the terms of an alliance become established without the hesitant participant.",
    ],
    transitionTheme: "loose connection becoming durable cohesion when commitments are clear",
    stabilityTheme: "belonging sustained by mutual reliability rather than pressure",
    lowerTrigram: "kun",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Begin with sincerity in the bond",
        "The first line makes the quality of the initial commitment more important than its scale. A small bond can become strong if it begins with sincerity, clear intention, and behavior that gives others a reason to trust. The container may still be modest, but what fills it should be genuine rather than strategic performance.",
        "Change here turns an initial connection into something others can begin to rely on. The emerging pattern grows through consistency: promises kept, motives made legible, and small acts that demonstrate the bond can hold weight without being constantly negotiated.",
        "Do not rush to display closeness before the relationship has evidence underneath it. Symbolic unity, public affiliation, or emotional intensity can create expectations that the early bond is not yet able to carry.",
        "What small act of reliability would make this new connection more trustworthy than another statement of loyalty?",
        "Line 1 builds cohesion from sincere, observable reliability rather than from the appearance of immediate closeness.",
      ),
      authoredLine(
        "Belong from the inside out",
        "The second line favors a connection that grows from genuine inner alignment rather than pressure from the outside. You may already know why the relationship, team, or commitment matters to you. Acting from that internal clarity makes participation steadier because belonging does not depend on constant approval or fear of being left out.",
        "When this line changes, private alignment becomes more explicit participation. The transition asks you to translate inward commitment into ordinary contribution while preserving the ability to think independently inside the group.",
        "Do not confuse internal loyalty with unquestioning compliance. A strong bond can tolerate accurate disagreement. If belonging requires suppressing every independent judgment, the center may be asking for dependency rather than commitment.",
        "What would participation look like if it came from your own clear commitment rather than from a need to be accepted?",
        "Line 2 grounds belonging in inward conviction, making participation steadier and less dependent on social pressure.",
      ),
      authoredLine(
        "Do not bind yourself to the wrong company",
        "The third line asks whether the available alliance is actually trustworthy. Proximity, friendliness, or common circumstance can make a group look like the obvious place to belong, yet its values or incentives may pull you away from what you know is sound. Holding together becomes harmful when cohesion is purchased by joining the wrong center.",
        "Change here can break an unsuitable alignment before it becomes entrenched. The emerging movement may involve distance, a different circle, or a refusal to let convenience decide affiliation. Separation can preserve integrity when the bond itself is the problem.",
        "Fear of isolation can make weak company feel safer than no company. Do not accept corrosive norms merely because the alternative is temporary loneliness. Belonging has a cost when it repeatedly requires you to act against your own standard.",
        "Which relationship or group feels available but would require you to normalize conduct you do not actually respect?",
        "Line 3 protects cohesion by refusing an alliance whose center would make belonging incompatible with integrity.",
      ),
      authoredLine(
        "Make the outer alliance explicit",
        "The fourth line brings connection into a wider or more public field. The relationship may now need clear terms visible to people beyond the original inner circle. Open commitment reduces ambiguity: others can see what the alliance is for, what it does not imply, and how responsibilities are shared.",
        "As this line changes, private trust becomes external coordination. The transition succeeds when the bond can withstand visibility without relying on hidden exceptions or special understandings that outsiders cannot verify.",
        "Public affiliation can create pressure to defend the group even when it acts poorly. Do not let visibility turn loyalty into reputation management. The alliance remains trustworthy only if its standards still apply when the group is challenged.",
        "What term of this alliance should be made explicit before wider participation or public identification increases?",
        "Line 4 moves cohesion into the public field by making commitment, purpose, and boundaries understandable beyond the inner circle.",
      ),
      authoredLine(
        "A center people can approach freely",
        "The fifth line describes leadership that creates cohesion without trapping participants. A trustworthy center sets direction and protects standards while leaving people enough freedom to approach, contribute, or decline without being hunted for loyalty. This makes the alliance stronger because commitment is evidence of fit rather than evidence of fear.",
        "Change here tests whether central influence can remain attractive without becoming possessive. The emerging pattern may broaden the group, but only if the leader trusts voluntary alignment and does not treat every departure or disagreement as betrayal.",
        "A strong center can become controlling if it starts measuring success by how completely others orbit it. Do not use charisma, access, or authority to make leaving artificially costly. Voluntary cohesion requires a real exit.",
        "How could the center of this group make commitment clearer while also making dissent or departure less punitive?",
        "Line 5 defines strong cohesion as voluntary alignment around a reliable center, not the elimination of people’s freedom to differ or leave.",
      ),
      authoredLine(
        "A bond without a clear beginning cannot hold",
        "At the top line, belonging lacks a stable head or initiating center. The group may have accumulated by habit, reaction, or late participation without a shared origin that explains who is responsible and why the bond exists. When nobody can name the center, cohesion becomes difficult to sustain because every member is waiting for structure to come from somewhere else.",
        "Change here exposes the need either to establish a real center or to stop pretending the loose association is already a durable alliance. The emerging direction depends on a fresh act of definition: purpose, leadership, terms, or an honest decision not to bind.",
        "Do not manufacture a leader or purpose simply to preserve a group that has no real basis. Late attempts to force coherence can produce obedience without trust. Sometimes the correct conclusion is that the bond never truly formed.",
        "What essential center—purpose, responsibility, or initiating commitment—is missing from this alliance, and can it still be established honestly?",
        "Line 6 shows that cohesion without a clear center or beginning cannot be repaired by loyalty slogans alone; the basis of the bond must be defined or released.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
