import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 9,
    coreTheme: "Small restraints",
    legacySummary: "Minor limits can shape a larger outcome. Attend to details, relationships, and incremental preparation instead of trying to overpower the situation.",
    strength: "fine-grained influence through small corrections",
    challenge: "impatience with modest progress or underestimating small constraints",
    orientation: "work through details and limited leverage instead of forcing a breakthrough",
    transitionTheme: "small adjustments accumulating until a larger movement becomes possible",
    stabilityTheme: "discipline in minor matters that protects the larger direction",
    lowerTrigram: "qian",
    upperTrigram: "xun",
    lineEmphases: [
      "accept the first small limit as useful information rather than an insult",
      "use minor corrections to shape behavior before a larger intervention is needed",
      "notice when impatience with small constraints is creating avoidable friction",
      "carry incremental influence into the wider situation without exaggerating its reach",
      "coordinate details so modest leverage begins to support a larger outcome",
      "stop refining minor matters when restraint has done enough and movement is ready",
    ],
  },
  {
    number: 10,
    coreTheme: "Careful conduct",
    legacySummary: "You may be moving near stronger forces or sensitive boundaries. Respect, awareness, and correct conduct reduce unnecessary risk.",
    strength: "situational awareness and respectful precision",
    challenge: "carelessness, entitlement, or treating a sensitive boundary as a test of courage",
    orientation: "move carefully, know the limits, and let conduct carry more weight than bravado",
    transitionTheme: "cautious passage becoming confidence earned through correct behavior",
    stabilityTheme: "self-command when circumstances demand tact and attention",
    lowerTrigram: "dui",
    upperTrigram: "qian",
    lineEmphases: [
      "identify the sensitive boundary before taking the first step near it",
      "make careful conduct natural enough that it does not depend on constant fear",
      "slow down when pressure makes tact feel like weakness",
      "enter the stronger field with respect, clear awareness, and no unnecessary provocation",
      "show that confidence can remain precise even when responsibility becomes visible",
      "leave the dangerous edge once the passage is complete instead of testing it again",
    ],
  },
  {
    number: 11,
    coreTheme: "Flow and exchange",
    legacySummary: "Different forces can cooperate productively. Use favorable circulation to strengthen foundations rather than assuming harmony will maintain itself.",
    strength: "productive exchange between different roles and levels",
    challenge: "complacency during favorable conditions or using flow without reinforcing its foundations",
    orientation: "use the opening to circulate resources, trust, and information while conditions are receptive",
    transitionTheme: "easy exchange becoming durable order through maintenance and inclusion",
    stabilityTheme: "reciprocity that keeps favorable circulation from becoming taken for granted",
    lowerTrigram: "qian",
    upperTrigram: "kun",
    lineEmphases: [
      "use the first opening in communication to strengthen a real channel of exchange",
      "make reciprocity practical through steady circulation of information and support",
      "notice early signs that easy flow is hiding dependency or complacency",
      "extend cooperation outward while preserving the conditions that made it possible",
      "use a favorable center to distribute benefit and reinforce foundations",
      "prepare for changing conditions before harmony is mistaken for a permanent state",
    ],
  },
  {
    number: 12,
    coreTheme: "Stagnation",
    legacySummary: "Connection is blocked and useful exchange is limited. Preserve integrity, avoid futile forcing, and watch for the conditions that could restore movement.",
    strength: "the ability to preserve a sound center when external channels are closed",
    challenge: "exhaustion from pushing blocked channels or adapting yourself to a distorted environment",
    orientation: "conserve integrity, reduce futile effort, and look for genuine signs that circulation can resume",
    transitionTheme: "stagnation loosening only when the conditions for real exchange return",
    stabilityTheme: "steadiness that does not confuse immobility with permanent defeat",
    lowerTrigram: "kun",
    upperTrigram: "qian",
    lineEmphases: [
      "recognize the first blocked channel without wasting energy on denial",
      "preserve a workable inner standard when external exchange remains poor",
      "stop escalating effort when repeated pressure only hardens the blockage",
      "test cautiously whether any outer channel has genuinely reopened",
      "hold integrity in a visible position without pretending influence is greater than it is",
      "leave a stagnant arrangement when its closure is complete and a new opening is real",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
