import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 9,
    coreTheme: "Small restraints",
    coreMeaning: "Small restraints describe influence that works through limited leverage, careful detail, and repeated correction rather than through a decisive breakthrough. Xiao Chu is easy to underestimate because the visible constraint may look minor: a dependency, a relationship, a procedural limit, or a detail that cannot simply be ignored. Yet these small factors can determine whether stronger energy becomes usable or merely frustrated. The reading favors precision. Improve the part you can actually touch, coordinate the small pieces, and let modest gains accumulate until the larger movement has support. This is not a command to remain small forever. Restraint has a purpose: it shapes force, prevents waste, and buys time for conditions to gather. Once the necessary detail work has done its job, refinement should yield to movement rather than becoming perfectionism.",
    strength: "fine-grained influence through small corrections",
    challenge: "impatience with modest progress or underestimating small constraints",
    orientation: "work through details and limited leverage instead of forcing a breakthrough",
    structureInterpretation: "Heaven below supplies strong initiative while Wind above applies subtle, repeated influence. The larger force is present, but it is held and shaped by something less dramatic. Quick I Ching reads this as a structure in which small constraints matter because they regulate how much of the underlying power can move cleanly at one time.",
    reflectionQuestions: [
      "Which small dependency or detail is currently governing a larger outcome more than its size suggests?",
      "What modest correction could be repeated often enough to change the trajectory without requiring a showdown?",
      "Where has useful refinement crossed the line into delay because you are waiting for every minor condition to be perfect?",
    ],
    watchFor: [
      "A sequence of small corrections beginning to reduce friction or make the larger move easier to support.",
      "Impatience causing the same minor constraint to be hit harder rather than understood more accurately.",
      "The moment when enough details align that continued restraint adds less value than a measured advance.",
    ],
    transitionTheme: "small adjustments accumulating until a larger movement becomes possible",
    stabilityTheme: "discipline in minor matters that protects the larger direction",
    lowerTrigram: "qian",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Return to the workable path",
        "The first line encounters restraint very close to the beginning and responds by returning to a sound route rather than fighting the limit. A small correction made early can preserve initiative without turning the situation into a contest. The emphasis is on recognizing that the obstacle is not an insult; it is information about where the path currently supports movement and where it does not.",
        "Change here redirects force before much momentum has accumulated. The emerging pattern benefits from a quick, low-cost correction: withdraw from the unworkable angle, recover the main direction, and resume from a position that does not require constant struggle against a minor constraint.",
        "Do not persist simply to prove that the obstacle should not matter. Early pride can make a tiny limit expensive. The opposite mistake is abandoning the larger purpose because one route needed correction.",
        "What small return to a known workable path would preserve the larger initiative without turning this limit into a battle?",
        "Line 1 uses an early correction to keep strong initiative aligned with the route that is actually open.",
      ),
      authoredLine(
        "Be drawn back by a reliable connection",
        "The second line shows restraint operating through relationship. A trustworthy person, precedent, or existing connection can pull you back from an unhelpful direction before the deviation becomes costly. The line values responsiveness to good influence: autonomy is preserved by recognizing who or what reliably helps you recover proportion.",
        "As this line changes, small restraint becomes cooperative correction. The transition is not submission to another person but the use of relationship as a stabilizing force. A shared standard or credible peer can keep the larger movement from fragmenting into private impulse.",
        "Dependence is the shadow of helpful influence. Do not require another person to regulate every decision, and do not follow merely because someone is familiar. The connection is useful only while it points back toward a sound direction.",
        "Who or what reliably helps you return to proportion when momentum starts pulling you away from the main direction?",
        "Line 2 treats a trustworthy connection as a small restraint that protects the larger course from unnecessary deviation.",
      ),
      authoredLine(
        "A small mechanical failure exposes misalignment",
        "The third line shows a minor component failing under strain, revealing that the larger system is not moving as one. Friction between intention and relationship, or between parts that should coordinate, becomes impossible to ignore. The useful response is diagnostic: inspect the interface that failed instead of applying more force to the whole machine.",
        "Change at this point turns irritation into structural information. The emerging direction depends on repairing coordination—roles, expectations, communication, or a practical connection—before the stronger energy underneath is asked to move again.",
        "Blame can turn a repairable misalignment into a personal conflict. Do not focus so heavily on who caused the breakdown that the failed connection itself remains unrepaired. Repeated force against a damaged interface will widen the problem.",
        "Which small connection between people, tasks, or expectations is failing in a way that reveals a larger coordination problem?",
        "Line 3 uses a small breakdown to expose misalignment and redirects effort toward the connection that must be repaired.",
      ),
      authoredLine(
        "Sincerity reduces the danger around influence",
        "The fourth line places subtle influence in a more exposed field, where mistrust or fear can make even a modest intervention look threatening. Sincerity matters because it makes motive legible. Clear reasons, transparent limits, and conduct consistent with what has been said can reduce the suspicion surrounding a small but persistent influence.",
        "When this line changes, influence gains room to work because the relationship around it becomes less defensive. The transition depends on credibility rather than pressure: others can respond to the actual proposal instead of protecting themselves from hidden leverage.",
        "Do not use the language of sincerity to demand trust that has not been earned. Transparency must be observable in behavior and consequences. Reassurance without evidence can intensify suspicion rather than remove it.",
        "What motive, limit, or consequence should be made more visible so this influence can be evaluated without unnecessary fear?",
        "Line 4 makes transparent motive the condition that allows subtle influence to operate without creating avoidable mistrust.",
      ),
      authoredLine(
        "Shared resources make small influence stronger",
        "The fifth line shows limited leverage becoming more effective through trusted connection and shared resources. No single participant needs overwhelming power if the network can coordinate what each contributes. The line favors mutual reliability: information, support, reputation, or practical capacity circulates so that modest influence becomes collectively meaningful.",
        "Change here moves small restraint toward a more coherent shared position. The emerging pattern gains strength by linking resources rather than concentrating control. What was individually insufficient can become enough when relationships are credible and contributions are aligned.",
        "Shared resources can create hidden obligations or unequal dependence. Do not call an arrangement mutual if one side controls access or if the cost of leaving is concealed. Cooperation needs terms that remain fair when circumstances tighten.",
        "Which small resources or relationships could become genuinely useful if they were coordinated transparently rather than held separately?",
        "Line 5 turns modest leverage into coordinated influence by linking trusted people and resources without requiring one dominant force.",
      ),
      authoredLine(
        "The restraint has gathered enough",
        "At the top line, small restraints have accumulated to the point where the larger situation is saturated. The preparation, influence, or correction has done enough for now. Continuing to press the same subtle method can become overmanagement, especially when the conditions that were being gathered have already reached a useful level.",
        "Change here releases the phase of containment. The emerging movement may finally use the strength that has been shaped, but it should do so with awareness that the transition is delicate. What has gathered needs integration before another round of control is applied.",
        "Do not keep tightening because restraint has been successful. A method that protected timing can become obstruction once readiness is present. Watch for perfectionism disguised as prudence.",
        "What evidence shows that the small corrections have already done enough and that further restraint would now delay useful movement?",
        "Line 6 closes the restraint phase by recognizing when enough has gathered and the larger force should be allowed to move.",
      ),
    ],
  },
  {
    number: 10,
    coreTheme: "Careful conduct",
    coreMeaning: "Careful conduct is about moving through a field where stronger forces, sensitive boundaries, or real consequences require precision. Lu does not ask for fearfulness. It asks whether behavior is appropriate to the power relationship actually present. Respect, timing, manners, and situational awareness can let a person pass close to danger without provoking what need not be provoked. Confidence becomes trustworthy when it is joined to self-command. The reading therefore favors knowing the limit before testing it, noticing how your conduct affects others, and allowing correct behavior to carry more weight than bravado. A dangerous situation is not improved by pretending the danger is imaginary, nor by treating caution as weakness. Move deliberately, observe response, and review the whole passage afterward so confidence is earned from evidence rather than from surviving one lucky step.",
    strength: "situational awareness and respectful precision",
    challenge: "carelessness, entitlement, or treating a sensitive boundary as a test of courage",
    orientation: "move carefully, know the limits, and let conduct carry more weight than bravado",
    structureInterpretation: "Lake below creates openness and responsive social energy while Heaven above represents a stronger, more authoritative field. The lower force approaches something that can overpower it if handled carelessly. Quick I Ching reads the structure as conduct under asymmetry: awareness and correctness make movement possible where raw assertion would create unnecessary danger.",
    reflectionQuestions: [
      "What power difference or sensitive boundary needs to be acknowledged before you take the next step?",
      "Which part of your conduct would still look appropriate if the stronger party disagreed with your desired outcome?",
      "What did the last successful passage actually teach you about risk, rather than merely proving that you got through it once?",
    ],
    watchFor: [
      "A tense interaction becoming safer because expectations, respect, and boundaries are more explicit.",
      "Confidence turning into unnecessary testing of a limit that was already understood.",
      "Feedback from the stronger field that distinguishes tolerated conduct from genuinely trusted conduct.",
    ],
    transitionTheme: "cautious passage becoming confidence earned through correct behavior",
    stabilityTheme: "self-command when circumstances demand tact and attention",
    lowerTrigram: "dui",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Simple conduct at the outset",
        "The first line favors an uncomplicated beginning. When entering a sensitive field, you do not need status, elaborate signaling, or a performance of confidence. Straightforward conduct reduces the number of things that can be misread. Attend to the task, respect the boundary, and let the first step be modest enough that correction remains easy.",
        "If this line changes, the passage becomes more engaged. The transition works best when it carries forward the simplicity of the beginning: more involvement should add responsibility, not extra display or claims that the situation has not yet granted.",
        "Trying to look important can create risk before any practical need exists. Avoid borrowing authority, exaggerating familiarity, or making a small entry more conspicuous than necessary. The cleanest path may be the least theatrical one.",
        "How could you make the first step simpler so that the situation has less to react against or misunderstand?",
        "Line 1 enters the sensitive field with plain, modest conduct that keeps risk low and correction easy.",
      ),
      authoredLine(
        "Walk a level path without seeking attention",
        "The second line describes careful conduct becoming natural. The path is workable when you do not add unnecessary complexity to it. Someone who can remain internally steady does not need constant recognition or reassurance from the stronger field. Quiet consistency allows the passage to continue without turning every step into a negotiation about status.",
        "Change here turns caution into earned ease. The emerging pattern is less dependent on vigilance because good conduct has become habitual. Confidence grows from repeatability: you know how to move because the method has already survived ordinary testing.",
        "Do not confuse quiet with invisibility or passivity. If the boundary changes, speak and adjust. The danger is using a familiar routine after the conditions that made it safe have shifted.",
        "What behavior could become so consistently appropriate that you no longer need external reassurance at every step?",
        "Line 2 shows careful conduct becoming a steady path, where confidence comes from repeatable appropriateness rather than attention.",
      ),
      authoredLine(
        "Limited perception can make confidence dangerous",
        "The third line warns about acting boldly with incomplete capacity. A person may be able to see part of the situation or perform part of the task and then assume the missing pieces do not matter. Near a stronger force, partial competence is especially dangerous because the consequence arrives before self-image has time to adjust. The line calls for humility about what is not yet seen or mastered.",
        "As this line changes, overconfidence can become teachable caution. The transition depends on accepting limitation early enough to change the route, seek help, or reduce exposure. Acknowledging partial competence protects future development better than testing the boundary until it bites back.",
        "Bravery cannot compensate for missing information, skill, or leverage. Do not interpret willingness to take risk as proof that the risk is well understood. The strongest correction may be to step out of a role you are not yet equipped to carry.",
        "Which part of this situation are you treating as understood mainly because acknowledging the gap would reduce your freedom to act?",
        "Line 3 exposes the danger of bold conduct built on partial perception and redirects confidence toward humility, support, and reduced exposure.",
      ),
      authoredLine(
        "Cautious contact with the dangerous force",
        "The fourth line is close to real power and feels the danger directly, but it can still proceed through alertness. Fear itself is not a failure if it sharpens attention rather than freezes action. Respect the consequence, keep the purpose narrow, and let each response from the stronger field inform the next step.",
        "Change here can convert nervous caution into a successful passage. The emerging movement is based on feedback: correct conduct is confirmed gradually as the situation allows continued progress without requiring a challenge to the stronger force.",
        "Suppressing fear can lead to careless testing, while feeding fear can make every signal look hostile. Use apprehension as data about where precision matters, not as a story about inevitable disaster.",
        "What specific behavior would let you proceed while respecting the danger instead of either provoking it or retreating automatically?",
        "Line 4 keeps close contact with danger workable by turning apprehension into precise, responsive conduct.",
      ),
      authoredLine(
        "Decisive conduct still needs awareness",
        "The fifth line carries enough position and confidence to act decisively, but the danger has not disappeared. Stronger authority or clearer purpose can tempt a person to stop monitoring the field. The line favors firm action with an active sense of consequence: know what you are committing, who is affected, and which boundary remains capable of pushing back.",
        "When this line changes, caution and decisiveness are being integrated. The transition can produce trustworthy authority if the decision remains informed by risk rather than protected from it. Confidence is mature when it can act without pretending to be invulnerable.",
        "Do not let formal authority cancel situational awareness. A decision can be legitimate and still be badly timed or unnecessarily provocative. The higher the confidence, the more important it is to preserve channels for warning and correction.",
        "What risk deserves to remain visible even after you have decided that firm action is justified?",
        "Line 5 combines decisive conduct with continuing risk awareness so authority does not become careless simply because it can act.",
      ),
      authoredLine(
        "Review the whole path before judging the outcome",
        "The top line looks back over the completed passage. Success should be evaluated by the quality of conduct across the route, not only by the fact that the immediate danger was survived. Review where caution helped, where luck helped, and where a boundary was respected or nearly crossed. This turns experience into a standard rather than a story of personal invulnerability.",
        "Change here converts completed conduct into learning that can guide the next situation. The emerging pattern becomes more stable when the passage is interpreted accurately: repeat what was sound, correct what was merely fortunate, and carry the lesson forward without needing to recreate the danger.",
        "Survival bias can turn a risky method into a proud tradition. Do not conclude that every step was correct because the result was favorable. A good review distinguishes skill from luck and restraint from fear.",
        "Looking back over the entire passage, which part deserves to become a repeatable standard and which part succeeded mainly through good fortune?",
        "Line 6 completes careful conduct by reviewing the whole passage so future confidence is based on evidence rather than survival alone.",
      ),
    ],
  },
  {
    number: 11,
    coreTheme: "Flow and exchange",
    coreMeaning: "Flow and exchange describe a period when different levels, roles, or interests can circulate productively instead of remaining sealed off. Tai is favorable because movement between above and below creates cooperation, but favorable conditions contain their own risk: ease can be mistaken for permanence. The reading asks you to use circulation while it is available. Move information, resources, trust, and benefit across boundaries that had previously separated them. At the same time, reinforce the practices that make exchange trustworthy so the opening does not depend on mood alone. Harmony should produce stronger foundations, not merely pleasant experience. Watch for complacency, hidden dependency, or the assumption that a good phase will maintain itself without care. The best use of flow is to build capacity that remains useful when the cycle eventually changes.",
    strength: "productive exchange between different roles and levels",
    challenge: "complacency during favorable conditions or using flow without reinforcing its foundations",
    orientation: "use the opening to circulate resources, trust, and information while conditions are receptive",
    structureInterpretation: "Heaven below rises while Earth above descends, bringing the two trigrams into exchange rather than separation. Quick I Ching reads this as reciprocal movement across levels: initiative and receptivity can meet, allowing resources and information to circulate. The favorable structure is dynamic, so maintaining it requires active reciprocity rather than assuming harmony is self-sustaining.",
    reflectionQuestions: [
      "What can circulate more freely now because roles or levels that were separated have become receptive to one another?",
      "Which foundation should be strengthened while conditions are favorable so the benefit survives a less easy phase?",
      "Where has smooth cooperation made a hidden dependency or maintenance need easy to overlook?",
    ],
    watchFor: [
      "Information, resources, or trust moving across boundaries that previously required friction or permission.",
      "Favorable exchange becoming one-sided because the cost of reciprocity is being carried by only one part of the system.",
      "Early signs that the cycle is shifting and the practices built during harmony are being tested without the same tailwind.",
    ],
    transitionTheme: "easy exchange becoming durable order through maintenance and inclusion",
    stabilityTheme: "reciprocity that keeps favorable circulation from becoming taken for granted",
    lowerTrigram: "qian",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Pull connected roots together",
        "The first line shows that favorable movement rarely involves one isolated element. When one part begins to move, connected people, tasks, or resources may be ready to move with it. This is a good time to identify the cluster rather than advancing alone. Shared roots can turn an individual opening into coordinated progress if the connections are real and responsibilities are clear.",
        "Change here expands a first opening into collective motion. The emerging pattern gains strength by carrying related elements together instead of forcing them to catch up later. Early coordination reduces the cost of alignment once momentum increases.",
        "Do not recruit every nearby person simply because the conditions are favorable. Connection should be functional, not social decoration. Pulling unsuitable dependencies into the movement can burden the very opening that made progress possible.",
        "Which connected people or tasks should move together now because separating them would create more friction later?",
        "Line 1 uses a favorable opening to move genuinely connected elements together while the ground supports coordinated progress.",
      ),
      authoredLine(
        "Make room for the rough edges of exchange",
        "The second line broadens flow by tolerating difference and imperfection. Productive exchange often requires working with people, information, or conditions that do not arrive in polished form. The task is to stay inclusive enough to receive value without losing standards. Big circulation depends on the ability to carry some unevenness while keeping the center clear.",
        "As this line changes, harmony becomes more resilient because it can include what is less familiar or less refined. The transition moves from easy cooperation among similar parts toward exchange that can cross meaningful differences without breaking.",
        "Openness can become indiscriminate acceptance. Do not call every disruption ‘diversity’ or every weak contribution ‘inclusion.’ The line favors broad capacity, not the abandonment of discernment about what the system can actually use.",
        "What useful contribution are you tempted to reject mainly because it arrives in an unfamiliar or imperfect form?",
        "Line 2 strengthens flow by widening what can be carried, while keeping enough discernment that inclusion remains useful rather than shapeless.",
      ),
      authoredLine(
        "Remember that smooth ground will change",
        "The third line introduces the cycle inside favorable conditions. Flat ground eventually meets a slope; ease eventually encounters effort. The value of this line is perspective. Use the good phase fully, but do not build plans that require harmony to continue without interruption. Prepare for ordinary reversal without poisoning the present with fear.",
        "Change here makes favorable circulation more mature by adding resilience. The emerging pattern asks whether relationships, reserves, and routines can survive when exchange becomes harder. What is built now should be capable of carrying some friction later.",
        "Complacency and pessimism are opposite distortions. One assumes ease is permanent; the other refuses to enjoy or use it because it will end. Both waste the current conditions. Steward the opening while preparing quietly for change.",
        "What could you strengthen now so this favorable exchange remains useful when conditions become less easy?",
        "Line 3 brings cycle-awareness into harmony, using the favorable phase to build resilience before the terrain changes.",
      ),
      authoredLine(
        "Trust crosses the gap without display",
        "The fourth line shows people or roles crossing boundaries readily because the relationship itself can carry them. Status display, formal proof, or heavy transaction costs become less necessary when trust is active. This is a chance to simplify coordination and let direct contact replace unnecessary ceremony.",
        "When this line changes, exchange becomes more relational and less dependent on hierarchy. The transition can deepen cooperation if openness remains sincere and reciprocal. Information should move because the channel is trusted, not because one side has become careless about safeguards.",
        "Ease of access can weaken needed boundaries. Do not treat trust as permission to bypass every control or assume closeness makes conflicts of interest disappear. Good circulation still needs proportionate safeguards.",
        "Which unnecessary barrier could be lowered because trust is now strong enough to carry direct exchange responsibly?",
        "Line 4 lets trust simplify exchange across levels while preserving the safeguards that keep openness from becoming carelessness.",
      ),
      authoredLine(
        "Use central connection to bind different sides",
        "The fifth line places favorable exchange at a central relationship capable of linking different groups or levels. A visible commitment can make cooperation more durable by turning goodwill into a clear bond. The important point is reciprocity: central connection should distribute benefit and confidence across the system rather than becoming a private alliance above everyone else.",
        "Change here formalizes part of the harmony. The emerging pattern can carry more weight because an important relationship is publicly trustworthy. The transition works when the bond supports circulation beyond itself and does not monopolize access.",
        "A central alliance can create resentment if it looks like favoritism or becomes the only route through which benefit flows. Make the purpose and terms legible enough that wider cooperation is strengthened rather than narrowed.",
        "How could an important relationship or commitment be used to improve circulation for the wider system instead of becoming a privileged channel?",
        "Line 5 makes a central bond serve the whole by using visible trust to connect levels, distribute benefit, and stabilize exchange.",
      ),
      authoredLine(
        "When the wall falls inward",
        "At the top line, the favorable order has reached its limit and the structure that once protected it may begin to collapse or reverse. Trying to force the old arrangement back into place can intensify disorder. The line favors recognition that the phase has changed: simplify commitments, protect what still works, and stop demanding yesterday’s harmony from today’s conditions.",
        "Change here ends a cycle of easy circulation. The emerging pattern requires rebuilding from nearer ground rather than projecting strength outward. Attention shifts from expansion and exchange to internal repair, boundary, and the preservation of essentials.",
        "Denial can waste the remaining trust and resources by treating structural change as temporary bad mood. Do not mobilize a large campaign merely to recreate appearances. First determine what part of the old order is actually recoverable.",
        "Which sign shows that the favorable phase has structurally changed, and what should be protected before attempting any rebuild?",
        "Line 6 recognizes the end of easy flow and redirects effort from preserving appearances toward protecting essentials and rebuilding from the inside.",
      ),
    ],
  },
  {
    number: 12,
    coreTheme: "Stagnation",
    coreMeaning: "Stagnation describes a period when useful exchange is blocked and the parts of a system no longer reach one another easily. Pi can feel like personal failure because effort produces little movement, yet the structure asks for a different test: can integrity be preserved when external circulation is poor? Repeatedly pushing a closed channel often consumes energy without improving access. The reading therefore favors conservation, accurate boundaries, and attention to real signs of reopening. Do not adapt yourself to a distorted environment merely to appear effective inside it. Strength may need to remain inward for a time while the outer conditions sort themselves. This is not permanent defeat. Stagnation is a phase whose ending should be recognized by evidence—renewed contact, credible change in incentives, or a genuine opening—not by wishful thinking or another round of pressure.",
    strength: "the ability to preserve a sound center when external channels are closed",
    challenge: "exhaustion from pushing blocked channels or adapting yourself to a distorted environment",
    orientation: "conserve integrity, reduce futile effort, and look for genuine signs that circulation can resume",
    structureInterpretation: "Earth below descends while Heaven above rises, so the two trigrams move away from each other instead of exchanging. Quick I Ching reads this separation as blocked circulation: strong initiative and receptive conditions cannot currently meet. The useful response is to preserve the quality of the inner center and avoid wasting force on channels that are structurally closed.",
    reflectionQuestions: [
      "Which channel is genuinely blocked, and what repeated effort has failed to change that fact?",
      "What standard or resource needs to be preserved so the stagnant environment does not reshape you in its image?",
      "What observable evidence would count as a real reopening rather than another hopeful interpretation of the same closed conditions?",
    ],
    watchFor: [
      "Repeated attempts producing the same non-response because the channel itself, not the intensity of effort, is the problem.",
      "Pressure to compromise a core standard merely to gain movement inside an environment that rewards distortion.",
      "A concrete change in access, incentive, leadership, or response that makes cautious re-engagement materially different from the past.",
    ],
    transitionTheme: "stagnation loosening only when the conditions for real exchange return",
    stabilityTheme: "steadiness that does not confuse immobility with permanent defeat",
    lowerTrigram: "kun",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Withdraw connected roots from a bad field",
        "The first line recognizes stagnation early and protects a connected group of values, people, or practices from being absorbed by it. If the surrounding environment rewards conduct you do not want to normalize, moving one part away may require moving the related parts as well. Shared roots can preserve integrity when isolated resistance would be worn down.",
        "Change here converts passive blockage into deliberate separation. The emerging pattern gains coherence because connected elements stop trying to thrive in conditions that cannot currently support them. Withdrawal creates a cleaner base for later re-entry or a different direction.",
        "Do not turn selective withdrawal into contempt for everyone who remains. The goal is to preserve standards, not to create a purity contest. Stay attentive to whether conditions later change enough to justify renewed contact.",
        "Which connected commitments need to be protected together because leaving only one exposed would let the stagnant environment reshape the rest?",
        "Line 1 protects integrity by withdrawing connected roots from a field whose current incentives cannot support healthy exchange.",
      ),
      authoredLine(
        "Endure blockage without endorsing it",
        "The second line deals with the practical need to live inside a stagnant system for a time. Accommodation may be necessary in minor matters, but inner agreement is not required. The distinction is important: you can carry what the situation currently demands without allowing poor conditions to redefine what you consider sound.",
        "When this line changes, endurance becomes more deliberate. The emerging movement depends on knowing which compromises are temporary logistics and which would cross a line into endorsement. A clear internal standard keeps survival from becoming assimilation.",
        "Resentment can consume as much energy as futile resistance, while excessive accommodation can quietly become consent. Keep the temporary nature of compromises visible and review whether they are still necessary.",
        "Which accommodation is merely practical for now, and which one would begin to make the stagnant system’s values your own?",
        "Line 2 separates temporary endurance from endorsement, preserving an inner standard while external exchange remains poor.",
      ),
      authoredLine(
        "Stagnation exposes what is shameful",
        "The third line brings the discomfort of blockage into awareness. Weak arrangements, compromised motives, or conduct that was easier to ignore during movement can become visible when progress stops. This exposure is unpleasant but useful. Shame can point toward a correction if it is treated as information about behavior rather than as a permanent judgment of identity.",
        "Change here allows stagnation to become diagnostic. The emerging pattern uses the stopped condition to identify what should not be carried forward when circulation returns. Naming the compromised part is the first step toward removing its influence.",
        "Do not defend a poor practice simply because acknowledging it feels humiliating. But also avoid global self-condemnation. The task is specific correction: identify the behavior or arrangement that deserves to change and separate it from the whole person or project.",
        "What uncomfortable truth has the lack of progress made visible that would have been easier to ignore during busier times?",
        "Line 3 turns the discomfort of stagnation into specific self-correction by naming what should not survive the blocked phase.",
      ),
      authoredLine(
        "A mandate to reopen one channel",
        "The fourth line shows the first credible possibility of movement returning. The opening should not be generalized too quickly. A particular responsibility, authority, or condition may now support action where none existed before. Use the new access carefully and verify that the channel remains open under real use.",
        "As this line changes, separation begins to reconnect. The transition is cautious because the larger stagnant pattern has not necessarily disappeared. One working channel can become a bridge if it is tested and maintained rather than treated as proof that every barrier has fallen.",
        "Hope can overinterpret the first positive signal. Do not restore full commitments on the basis of one exception or symbolic gesture. Re-engagement should scale with repeated evidence that the changed condition is real.",
        "What newly opened channel can be tested at limited scale before you assume the broader stagnation has ended?",
        "Line 4 begins reopening through one credible channel, asking for measured re-engagement rather than immediate restoration of the whole system.",
      ),
      authoredLine(
        "Stabilize the first real recovery",
        "The fifth line marks a stronger reversal of stagnation, but recovery remains something to secure rather than celebrate carelessly. The central task is to reinforce whatever has restored circulation: a leadership change, new agreement, repaired channel, or return of trust. Assume that weak points still exist and make the recovery harder to reverse.",
        "Change here moves the situation from mere reopening toward sustained exchange. The emerging pattern becomes credible when the new conditions survive stress and do not depend on one favorable moment. Tie the recovery to routines, responsibilities, and feedback that can keep it alive.",
        "Relief can create complacency. Do not dismantle the safeguards that preserved integrity during stagnation before the recovery has proven durable. A reopened system can close again if its underlying causes were not actually changed.",
        "Which part of this recovery needs reinforcement now so renewed circulation does not depend on a single favorable moment?",
        "Line 5 treats recovery from stagnation as something to secure through routines and safeguards before confidence is relaxed.",
      ),
      authoredLine(
        "The blockage finally overturns",
        "At the top line, stagnation has reached the point where the blocked pattern can reverse. The important distinction is that the ending follows recognition and endurance, not denial. Old separation may finally lose its structure, allowing exchange to resume in a way that earlier pressure could not produce. The moment calls for participation, but also memory of what the stagnant period revealed.",
        "Change here closes the cycle of separation and opens a different field of movement. The emerging direction benefits from rebuilding with the lessons of closure intact: clearer boundaries, more realistic expectations, and less dependence on channels that previously failed.",
        "Do not convert the end of stagnation into a fantasy that the old problems never mattered. Rapid relief can recreate the same vulnerabilities if the system rushes back to previous habits without integrating what was learned.",
        "What lesson from the blocked period must be built into the renewed exchange so the reopening does not simply recreate the old weakness?",
        "Line 6 marks the overturning of stagnation and asks renewed movement to carry forward the structural lessons learned during closure.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
