import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 13,
    coreTheme: "Fellowship",
    legacySummary: "Shared purpose can bring people together across narrower interests. Make the common ground explicit and keep cooperation open rather than factional.",
    strength: "cooperation built around a purpose larger than private advantage",
    challenge: "cliques, hidden agendas, or confusing social warmth with shared direction",
    orientation: "state the common purpose plainly and keep participation wider than a favored circle",
    transitionTheme: "separate interests becoming coordinated through transparent common ground",
    stabilityTheme: "fellowship maintained by openness, fairness, and explicit purpose",
    lowerTrigram: "li",
    upperTrigram: "qian",
    lineEmphases: [
      "state the common purpose before inviting people to identify with the group",
      "build fellowship through ordinary cooperation rather than slogans of unity",
      "address factional tension before it turns shared purpose into competing camps",
      "open the circle to wider participation without diluting the reason for gathering",
      "use visible leadership to keep common ground broader than private alliances",
      "let a coalition change or dissolve when the shared purpose no longer honestly holds",
    ],
  },
  {
    number: 14,
    coreTheme: "Great possession",
    legacySummary: "Resources or influence are available. The question is how to use abundance responsibly, proportionately, and without letting possession become arrogance.",
    strength: "the capacity to steward substantial resources or visibility",
    challenge: "pride, hoarding, or using abundance to justify excess",
    orientation: "treat what you have as a responsibility and allocate it where it creates durable value",
    transitionTheme: "possession becoming stewardship when power is connected to proportion and service",
    stabilityTheme: "abundance preserved by restraint, transparency, and useful distribution",
    lowerTrigram: "qian",
    upperTrigram: "li",
    lineEmphases: [
      "treat the first resource or advantage as something to steward rather than display",
      "put abundance to useful work in the ordinary center before expanding possession",
      "notice when pride or overextension begins to accompany increased resources",
      "bring wealth, influence, or visibility into wider circulation with clear terms",
      "use central abundance to create durable value beyond personal accumulation",
      "release excess or status claims when possession starts to govern the possessor",
    ],
  },
  {
    number: 15,
    coreTheme: "Modesty",
    legacySummary: "Balanced self-measurement supports durable progress. Reduce excess, acknowledge limits, and let competence show through consistent action rather than display.",
    strength: "accurate self-measurement and the ability to reduce excess",
    challenge: "false humility, self-erasure, or display disguised as modesty",
    orientation: "stay proportionate: neither inflate nor diminish what is actually present",
    transitionTheme: "excess being leveled so capability can operate without distortion",
    stabilityTheme: "quiet competence that remains visible through results rather than display",
    lowerTrigram: "gen",
    upperTrigram: "kun",
    lineEmphases: [
      "correct the first exaggeration without making humility into self-denial",
      "let competence become quietly reliable in ordinary practice",
      "stay proportionate when pressure tempts either self-inflation or self-erasure",
      "carry modest conduct into public situations where comparison becomes stronger",
      "use a central role without needing extra display to prove worth",
      "avoid turning modesty itself into a performance, doctrine, or source of superiority",
    ],
  },
  {
    number: 16,
    coreTheme: "Enthusiasm",
    legacySummary: "Energy can mobilize people and plans, but excitement needs direction. Build momentum around something real enough to sustain collective effort.",
    strength: "mobilizing energy that can turn intention into coordinated movement",
    challenge: "hype, premature celebration, or momentum detached from substance",
    orientation: "channel excitement into preparation, rhythm, and concrete commitments",
    transitionTheme: "emotion becoming organized momentum rather than a temporary surge",
    stabilityTheme: "energy renewed by real progress instead of constant stimulation",
    lowerTrigram: "kun",
    upperTrigram: "zhen",
    lineEmphases: [
      "ground the first surge of excitement in something concrete enough to act on",
      "turn enthusiasm into rhythm, preparation, and dependable participation",
      "notice when excitement is outrunning substance as pressure rises",
      "bring momentum into the wider field without demanding that everyone share the same intensity",
      "use visible energy to coordinate action rather than to manufacture applause",
      "let excitement subside when the mobilizing phase is complete and maintenance must begin",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
