import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 13,
    coreTheme: "Fellowship",
    coreMeaning: "Fellowship describes cooperation built around a purpose that can be stated in the open. Tong Ren is stronger than friendliness: people with different interests become able to act together because the common ground is broader than private loyalty. The reading therefore asks what the group is actually for and whether participation remains accessible beyond a favored circle. Cooperation weakens when it becomes tribal, defensive, or organized around a shared enemy instead of a shared task. It strengthens when terms are visible, disagreement can be survived, and leadership protects the common purpose from being captured by faction. Fellowship may pass through suspicion or conflict before becoming durable. The test is whether the relationship can return to a public, principled center after private alliances and defensive instincts have been exposed.",
    strength: "cooperation built around a purpose larger than private advantage",
    challenge: "cliques, hidden agendas, or confusing social warmth with shared direction",
    orientation: "state the common purpose plainly and keep participation wider than a favored circle",
    structureInterpretation: "Fire below provides clarity and differentiation while Heaven above supplies strong shared direction. Quick I Ching reads the combination as cooperation that requires visible purpose: people do not become identical, but clarity about difference can be held inside a larger direction strong enough to coordinate them.",
    reflectionQuestions: [
      "Can the common purpose be stated in terms that remain meaningful outside the closest inner circle?",
      "Where has loyalty to a subgroup begun to matter more than the work that originally brought people together?",
      "What disagreement needs to be handled openly so fellowship does not depend on pretending everyone already agrees?",
    ],
    watchFor: [
      "People from different positions cooperating because the task and rules are public enough to trust.",
      "Private alliances, defensive language, or shared enemies replacing the stated common purpose.",
      "A conflict becoming less divisive after the parties return to a larger principle or task they still share.",
    ],
    transitionTheme: "separate interests becoming coordinated through transparent common ground",
    stabilityTheme: "fellowship maintained by openness, fairness, and explicit purpose",
    lowerTrigram: "li",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Fellowship at the gate",
        "The first line begins cooperation at an open threshold rather than inside a private room. The practical value is accessibility: the basis for joining can be understood without special intimacy, hidden history, or membership in a preferred faction. A public purpose makes early cooperation easier to trust because nobody needs privileged access to know what the group stands for.",
        "Change here moves isolated intention into visible association. The emerging pattern becomes stronger if the first agreements can survive being seen and explained by outsiders. Openness at the beginning reduces the amount of hidden loyalty the group must manage later.",
        "Do not confuse openness with lack of standards. A gate can be open while participation still has clear terms. The danger is either creating an inner club too early or accepting anyone without regard for the purpose that makes fellowship meaningful.",
        "What part of this collaboration should be made public enough that a newcomer can understand the purpose without needing insider relationships?",
        "Line 1 establishes fellowship through an open, intelligible basis for participation rather than through private allegiance.",
      ),
      authoredLine(
        "Fellowship confined to the clan",
        "The second line shows cooperation narrowing into a familiar circle. Trust may be real, but if the group only works among people who already share identity, history, or advantage, fellowship loses its wider purpose. The issue is not that close ties are bad; it is that private belonging can quietly become the criterion for access, voice, or benefit.",
        "When this line changes, the reading tests whether the inner circle can reopen to the larger field. The transition requires making decisions by common purpose and transparent standards rather than by kinship, friendship, or factional comfort.",
        "A closed circle can convince itself that loyalty equals merit. Watch for decisions that are difficult to defend without saying ‘we know them’ or ‘they are one of us.’ Favoritism damages both outsiders and the credibility of genuine close relationships.",
        "Where is familiarity being treated as evidence of fitness, trustworthiness, or entitlement that should instead be tested by a wider standard?",
        "Line 2 warns that fellowship loses legitimacy when belonging to the inner circle becomes more important than the public purpose.",
      ),
      authoredLine(
        "Defensive alliance hidden behind suspicion",
        "The third line shows fellowship corrupted by fear. People may hide their real intentions, prepare against one another, or maintain cooperation only while watching for betrayal. The group appears connected but is actually organized around defensive calculation. This atmosphere makes every ambiguity look threatening and prevents the common purpose from receiving honest attention.",
        "Change here exposes the defensive structure so it can be dismantled. The transition asks whether security can come from clearer terms, verification, and direct communication instead of concealed countermeasures. Fellowship begins to recover when participants no longer need to keep metaphorical weapons hidden from one another.",
        "Do not use ‘prudence’ to justify permanent suspicion. Some safeguards may be necessary, but secret preparation against partners can create the betrayal it claims to prevent. If trust cannot be rebuilt, the honest answer may be to reduce the alliance rather than simulate fellowship.",
        "What defensive behavior inside this collaboration reveals that people are preparing for one another rather than for the shared task?",
        "Line 3 identifies hidden defensiveness as the obstacle to fellowship and redirects security toward explicit terms, evidence, and honest limits.",
      ),
      authoredLine(
        "Strength that chooses not to attack",
        "The fourth line reaches a position from which confrontation may be possible, yet restraint becomes the mark of stronger fellowship. Seeing the other side clearly does not require defeating it. A boundary, disagreement, or rival position can be acknowledged without escalating into an attack that would make future cooperation impossible.",
        "As this line changes, conflict energy is converted into disciplined separation or negotiation. The emerging pattern gains room because the parties discover that not every defensible position must be used offensively. Restraint can preserve the larger field in which common purpose may later return.",
        "Do not call avoidance ‘restraint’ when a necessary issue is simply being postponed. The line is about having the capacity to confront and deliberately choosing proportion, not about pretending the difference does not exist.",
        "Where do you have enough leverage to attack but more to gain by setting a boundary and leaving future cooperation possible?",
        "Line 4 makes non-attack an active use of strength, preserving a larger common field even when positions remain opposed.",
      ),
      authoredLine(
        "Separation gives way to reunion",
        "The fifth line describes fellowship that has passed through real separation, grief, or conflict and can still find its way back. The value of reunion comes from what has been survived, not from pretending nothing happened. Honest recognition of the break can make the restored relationship more credible because the participants now know what their common ground can withstand.",
        "Change here turns conflict history into renewed coordination. The emerging pattern depends on reconnecting around a principle or purpose that remained meaningful even while the relationship was strained. Repair becomes durable when the causes of separation are addressed rather than merely forgiven emotionally.",
        "Relief at reunion can encourage premature closure. Do not use warmth to skip the practical repairs—changed rules, clarified expectations, or acknowledged harm—that make renewed fellowship safer than the old version.",
        "What must be repaired in practice so a reunion after conflict becomes more than a return to the same vulnerable arrangement?",
        "Line 5 shows fellowship recovering after separation by combining emotional reunion with concrete repair of the conditions that broke trust.",
      ),
      authoredLine(
        "Fellowship at the outer meadow",
        "At the top line, cooperation exists but at greater distance from the center. The relationship may be cordial, useful, and limited without becoming intimate or fully integrated. This can be appropriate. Not every alliance needs deep belonging; some common purposes are best served by respectful coordination among parties who retain substantial independence.",
        "Change here releases the expectation that fellowship must always move toward greater closeness. The emerging direction may preserve a looser network in which contact is sufficient for the task and nobody is required to surrender distinct identity or local commitments.",
        "Distance can protect honesty, but it can also become disengagement. Make sure the limited alliance still contains enough communication and responsibility to do what it claims to do. Courtesy without contribution is not cooperation.",
        "Would this relationship work better if its purpose were defined as respectful, limited cooperation rather than an expectation of deep unity?",
        "Line 6 accepts fellowship at a wider distance, allowing useful cooperation without forcing every alliance into intimacy or full integration.",
      ),
    ],
  },
  {
    number: 14,
    coreTheme: "Great possession",
    coreMeaning: "Great possession describes a situation in which resources, visibility, talent, or influence are genuinely available. Da You shifts the problem from acquisition to stewardship. Abundance increases the number of choices that can be made and therefore increases responsibility for proportion, distribution, and consequence. The reading asks whether what you possess is being put into useful circulation or turned into evidence of superiority. Strong holdings become durable when they support work larger than the possessor, attract capable contribution, and remain governed by restraint. Pride, hoarding, or unnecessary display can isolate the very abundance that created opportunity. The best use of plenty is not to prove that there is more. It is to make resources reliable, portable, and beneficial enough that their value survives changes in status or fortune.",
    strength: "the capacity to steward substantial resources or visibility",
    challenge: "pride, hoarding, or using abundance to justify excess",
    orientation: "treat what you have as a responsibility and allocate it where it creates durable value",
    structureInterpretation: "Heaven below supplies concentrated creative strength while Fire above makes that strength visible and discriminating. Quick I Ching reads this as abundance brought into the light: possession is not hidden potential but power others can see. Visibility makes stewardship, allocation, and moral proportion part of the structure itself.",
    reflectionQuestions: [
      "Which resource or advantage has become a responsibility now that its scale or visibility has increased?",
      "Where would distribution create more durable value than keeping the benefit concentrated around the possessor?",
      "What sign would show that abundance is beginning to distort judgment, identity, or relationships?",
    ],
    watchFor: [
      "Resources becoming more useful because they are assigned to a clear purpose rather than merely accumulated.",
      "Status, abundance, or visibility creating insulation from feedback and increasing the cost of admitting error.",
      "An opportunity to use surplus capacity in a way that strengthens the wider system without creating dependency.",
    ],
    transitionTheme: "possession becoming stewardship when power is connected to proportion and service",
    stabilityTheme: "abundance preserved by restraint, transparency, and useful distribution",
    lowerTrigram: "qian",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Keep the first possession free of harmful attachment",
        "The first line treats new advantage cautiously because possession can attract trouble before its use is understood. A resource, role, or opportunity may be valuable without needing immediate display or entanglement. Protect it from relationships and commitments that would turn abundance into obligation before a sound purpose has been chosen.",
        "Change here moves possession from simple availability toward active use. The transition should occur only after the conditions around the resource are understood. Clean ownership makes later stewardship easier because the advantage is not already pledged to avoidable complications.",
        "Do not let excitement about having something lead to careless association with people or uses that damage its value. The first risk of abundance is often not loss but a poor commitment made because new capacity feels limitless.",
        "What new resource or advantage needs cleaner boundaries before you decide how publicly or extensively to use it?",
        "Line 1 protects abundance from early entanglement so possession can acquire a sound purpose before it acquires obligations.",
      ),
      authoredLine(
        "A large wagon can carry the load",
        "The second line focuses on capacity, not display. Possession becomes useful when there is a vehicle capable of carrying it: systems, people, routines, liquidity, or infrastructure that make resources portable and deployable. Having plenty without a reliable way to move it can turn abundance into fragility.",
        "As this line changes, stored value becomes operational capacity. The emerging pattern asks whether resources can be allocated where needed without improvising a new structure each time. A strong carrying system converts possession into dependable action.",
        "Do not scale the load beyond what the vehicle can safely carry. Abundance can hide infrastructure limits until stress arrives. The question is not how much exists but how much can be moved without damaging the carrier.",
        "What system or capacity would let the resources you already have be used reliably rather than remaining impressive but difficult to deploy?",
        "Line 2 turns abundance into practical capacity by strengthening the vehicle that can carry resources to where they are needed.",
      ),
      authoredLine(
        "Offer abundance to a larger purpose",
        "The third line tests whether substantial resources can serve something beyond private advantage. Possession gains legitimacy when part of it is offered to a larger institution, public purpose, community, or responsibility that exceeds the owner’s immediate benefit. The emphasis is generosity joined to competence: contribution should strengthen the whole rather than merely advertise virtue.",
        "Change here shifts abundance from ownership toward public stewardship. The emerging direction asks what the resource can enable when placed in a wider system with standards and responsibilities of its own. Giving becomes structural rather than sentimental.",
        "Grand gestures can be self-serving if they ignore whether the recipient can use what is offered. Do not confuse visibility of giving with usefulness. A poorly designed gift can create dependency, distortion, or status theater.",
        "Where could part of this abundance serve a larger purpose in a way that strengthens capacity rather than merely signaling generosity?",
        "Line 3 gives abundance legitimacy by placing part of it in service of a larger purpose under conditions where it can be used well.",
      ),
      authoredLine(
        "Refuse comparison at the height of advantage",
        "The fourth line warns that abundance becomes unstable when it is measured mainly against other people’s possessions or status. A strong position can remain proportionate by refusing the need to outshine, dominate, or prove that its advantages are greater. Self-restraint protects both relationships and judgment.",
        "When this line changes, possession becomes less identity-bound. The transition allows resources to be managed according to purpose instead of competition. This makes it easier to reduce, share, or redirect abundance when circumstances call for it.",
        "Comparison can turn plenty into perceived scarcity: no amount is enough if the real goal is superiority. Watch for unnecessary expenditure, expansion, or display whose only function is to preserve rank.",
        "What decision would change if you stopped comparing this advantage with what others possess and judged it only by the purpose it should serve?",
        "Line 4 protects great possession from competitive excess by separating stewardship from the need to display superiority.",
      ),
      authoredLine(
        "Sincere authority with enough dignity",
        "The fifth line gives the possessor a central public role. Trust matters, but so does the ability to maintain boundaries and standards. Effective stewardship combines accessibility with dignity: people can approach the center honestly while still understanding that resources and responsibilities will not be distributed through flattery or favoritism.",
        "Change here deepens abundance into credible leadership. The emerging pattern depends on trust that is neither lax nor intimidating. A central steward can be generous because the rules are clear enough that generosity does not dissolve accountability.",
        "Warmth without boundary can invite opportunism, while majesty without sincerity creates fear and hidden behavior. Do not choose between being liked and being respected; design the relationship so both trust and standards can coexist.",
        "How can you make access to your resources or authority more sincere without making the terms so loose that responsibility disappears?",
        "Line 5 centers great possession in leadership that combines genuine trust with enough dignity to keep stewardship accountable.",
      ),
      authoredLine(
        "Abundance aligned with what is larger than the self",
        "At the top line, possession is strongest when it no longer needs to prove ownership. Resources, conduct, and purpose have become aligned enough that support can arrive from beyond direct control—through trust, reputation, reciprocal goodwill, or favorable conditions created by prior stewardship. The line points toward abundance that participates in a larger order rather than standing above it.",
        "Change here releases attachment to possession as a personal identity. The emerging direction may involve succession, gifting, wider distribution, or simply confidence that value can continue without constant grasping. Good stewardship makes support more likely because others can see what the resources are for.",
        "Do not turn favorable support into a doctrine that you deserve every good outcome. Alignment improves conditions; it does not guarantee immunity from loss. Remain accountable to evidence and circumstance.",
        "What would it mean to use this abundance so well that its value could continue even if your personal control over it became smaller?",
        "Line 6 completes great possession by aligning resources with a larger purpose, reducing the need to cling to ownership as proof of worth.",
      ),
    ],
  },
  {
    number: 15,
    coreTheme: "Modesty",
    coreMeaning: "Modesty is accurate self-measurement rather than self-diminishment. Qian reduces excess and allows real capability to occupy the amount of space it actually deserves. This makes modesty operational: expectations become more realistic, credit becomes easier to share, and correction becomes less threatening because identity is not invested in appearing larger than reality. The reading warns against both arrogance and false humility. Hiding competence to avoid responsibility can be as distorted as exaggerating it for status. Durable progress comes from making contribution visible through consistent work while reducing needless display. Modesty also affects power: a central or successful position should be used without requiring others to perform submission. When correction is necessary, it can be firm without becoming grandiose. The goal is proportion—neither inflation nor erasure.",
    strength: "accurate self-measurement and the ability to reduce excess",
    challenge: "false humility, self-erasure, or display disguised as modesty",
    orientation: "stay proportionate: neither inflate nor diminish what is actually present",
    structureInterpretation: "Mountain below contains substance and height within; Earth above spreads level receptivity across the outside. Quick I Ching reads the structure as capability kept from unnecessary display. The mountain is real, but it is held inside a broader field, making proportion and leveling—not denial of strength—the organizing principle.",
    reflectionQuestions: [
      "Where are you taking more space, certainty, or credit than the evidence actually supports?",
      "Where are you hiding real competence in a way that prevents you from carrying a responsibility you should accept?",
      "What would accurate proportion look like if neither praise nor embarrassment were allowed to set your self-assessment?",
    ],
    watchFor: [
      "Competence becoming easier to trust because it appears consistently without requiring extra display.",
      "Humility language being used to avoid decisions, deny influence, or invite reassurance from others.",
      "A conflict becoming easier to correct once status and face are removed from the measurement of the problem.",
    ],
    transitionTheme: "excess being leveled so capability can operate without distortion",
    stabilityTheme: "quiet competence that remains visible through results rather than display",
    lowerTrigram: "gen",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Modesty deep enough to cross difficulty",
        "The first line begins with a double reduction of self-display. When facing a substantial task, attention is better spent on the crossing than on proving identity, status, or specialness. Modesty makes difficult movement possible because energy is not diverted into defending an image. Preparation can be thorough without becoming theatrical.",
        "Change here turns quiet self-measurement into committed action. The emerging pattern shows that humility is not passivity: once excess has been reduced, the person can undertake a demanding passage with fewer distractions and clearer learning.",
        "Do not confuse modesty with minimizing the difficulty or your own capacity. A major crossing still requires resources and judgment. Understatement becomes dangerous when it prevents realistic preparation.",
        "What part of this difficult undertaking becomes easier if you stop needing the process to demonstrate something about your status or identity?",
        "Line 1 uses deep modesty to free attention for the real work of a difficult crossing rather than for self-display.",
      ),
      authoredLine(
        "Modesty that can be heard",
        "The second line shows modesty becoming visible in conduct and speech. Quiet competence does not need to hide. Others may recognize a person who is proportionate, reliable, and uninflated precisely because the behavior repeats consistently. The important distinction is that the signal arises naturally from conduct rather than from advertising humility.",
        "As this line changes, private proportion becomes social credibility. The emerging pattern allows modest behavior to influence relationships because people can see that claims, performance, and self-assessment match one another.",
        "Performing modesty can become a sophisticated form of status-seeking. Watch for self-deprecation designed to attract reassurance or moral superiority built around appearing less ambitious than others.",
        "What behavior could communicate accurate self-measurement without requiring you either to boast or to deny what you can actually do?",
        "Line 2 lets modesty become audible through consistent conduct, making proportion itself a source of credibility.",
      ),
      authoredLine(
        "Merit that remains modest after hard work",
        "The third line combines real accomplishment with continued proportion. Work has been done and competence may be obvious; modesty now means not allowing earned merit to become immunity from correction or a claim to permanent precedence. The line honors labor while keeping the person connected to the larger task.",
        "Change here turns achievement into durable trust. The emerging pattern becomes stronger when success can be completed without demanding extra privilege. Others are more willing to rely on capability that does not use past effort as leverage in every future decision.",
        "Do not erase legitimate contribution in the name of humility, but do not use contribution as a debt the group must keep repaying. Merit is strongest when it can be acknowledged cleanly and then returned to service.",
        "What achievement should be recognized accurately without allowing it to become a claim on every later decision?",
        "Line 3 shows mature modesty carrying real merit without converting hard-earned accomplishment into permanent entitlement.",
      ),
      authoredLine(
        "Modesty expressed through active adjustment",
        "The fourth line makes modesty an action rather than an attitude. There may be excess in role, procedure, visibility, or expectation that can be actively reduced. A gesture of yielding, delegating, simplifying, or correcting scale can improve the wider situation when it is done for function rather than for appearance.",
        "When this line changes, proportion begins to reshape the outer field. The emerging pattern demonstrates that stepping back in one dimension can increase usefulness elsewhere. Modesty becomes structural when it changes how responsibility and space are distributed.",
        "A dramatic gesture of self-removal can create more attention than it reduces. Do not relinquish necessary authority merely to look humble. Adjust only the excess; keep the part of the role that genuinely serves the work.",
        "What specific excess in role, visibility, or control could you reduce without abandoning a responsibility that still belongs to you?",
        "Line 4 turns modesty into a practical redistribution of space and responsibility, reducing only what is excessive.",
      ),
      authoredLine(
        "Modesty does not forbid firm correction",
        "The fifth line has enough responsibility to act firmly when disorder persists. Modesty is sometimes misread as softness, but accurate proportion may require enforcing a boundary, correcting unfairness, or using collective support against a problem that will not resolve through politeness. The key is that force serves correction, not self-glorification.",
        "Change here integrates humility with authority. The emerging pattern allows decisive action without a grand narrative of personal righteousness. A central position can correct the situation and then return to ordinary proportion once the task is complete.",
        "Do not use ‘firmness’ to smuggle pride back into the reading. Public humiliation, unnecessary punishment, or a campaign larger than the problem would contradict the modesty that gives the correction legitimacy.",
        "What firm action is actually proportionate to the problem, and what part would exist mainly to display authority?",
        "Line 5 shows that modesty can support decisive correction when force is limited to what the situation genuinely requires.",
      ),
      authoredLine(
        "Use modesty to correct the home territory",
        "At the top line, modesty is fully visible and can be used to address disorder, but the first target should be what is closest and truly under your responsibility. It is easier to preach proportion to distant others than to correct the local system, habits, or team that reflects your own influence. The line brings reform back home.",
        "Change here turns declared modesty into accountable correction of the immediate field. The emerging direction favors cleaning one’s own structure before extending judgment outward. This makes any later influence more credible because it begins with responsibility rather than accusation.",
        "Do not use moral language about humility to launch a broad campaign against other people’s excess. Correcting the local sphere is less glamorous and more revealing. If the near problem remains untouched, wider criticism becomes suspect.",
        "What excess or disorder within your own sphere of responsibility should be corrected before you direct the same standard elsewhere?",
        "Line 6 brings modesty back to local accountability, using proportion first to correct the territory for which you are actually responsible.",
      ),
    ],
  },
  {
    number: 16,
    coreTheme: "Enthusiasm",
    coreMeaning: "Enthusiasm describes energy that can mobilize people, plans, and attention when it is attached to something real enough to carry momentum. Yu is powerful because emotion coordinates action quickly, but that speed is also its risk. Excitement can amplify a weak idea, reward theatrical confidence, or make preparation feel unnecessary. The reading therefore asks what the energy is for and whether the structure underneath can convert it into repeated action. Genuine enthusiasm creates rhythm: people know what to do next, resources gather, and commitment survives after the emotional peak. Empty enthusiasm requires constant stimulation. Use the favorable energy to prepare, coordinate, and move; do not demand that everyone share the same intensity. When the mobilizing phase has served its purpose, let excitement change form rather than trying to live indefinitely at a peak.",
    strength: "mobilizing energy that can turn intention into coordinated movement",
    challenge: "hype, premature celebration, or momentum detached from substance",
    orientation: "channel excitement into preparation, rhythm, and concrete commitments",
    structureInterpretation: "Earth below offers a receptive field while Thunder above releases movement outward. Quick I Ching reads the structure as stored collective capacity awakened by a strong signal. Enthusiasm becomes useful when the field can receive and organize that activation; otherwise the same surge becomes noise, overreaction, or temporary excitement without follow-through.",
    reflectionQuestions: [
      "What concrete work is this enthusiasm making easier, and what would still need to happen after the emotional energy fades?",
      "Which part of the momentum comes from real evidence or preparation, and which part depends on everyone staying excited?",
      "How can people with lower emotional intensity still participate effectively without being treated as disloyal or uncommitted?",
    ],
    watchFor: [
      "Excitement becoming a repeatable rhythm of preparation, coordination, and completed commitments.",
      "The group needing ever-larger emotional signals because underlying progress is too weak to sustain motivation.",
      "A point where the mobilizing phase is complete and maintenance, routine, or quieter execution needs to take over.",
    ],
    transitionTheme: "emotion becoming organized momentum rather than a temporary surge",
    stabilityTheme: "energy renewed by real progress instead of constant stimulation",
    lowerTrigram: "kun",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Enthusiasm announced before it has substance",
        "The first line warns about proclaiming excitement too early. Loud confidence can create social pressure and expectations before the work underneath has earned them. The more energy is spent broadcasting the future, the harder it becomes to revise the plan when reality provides inconvenient information.",
        "Change here can redirect expressive energy into preparation. The emerging pattern becomes healthier when the first proof of enthusiasm is useful action rather than volume. Let results begin to carry the message that excitement was trying to announce.",
        "Do not mistake positive emotion for evidence. Premature celebration can make honest doubt feel disloyal and can trap a group inside promises made for motivational effect rather than operational need.",
        "What would you stop announcing and start building if the enthusiasm had to prove itself through action rather than through expression?",
        "Line 1 redirects premature excitement from proclamation toward the concrete work that can eventually justify confidence.",
      ),
      authoredLine(
        "Know the signal quickly and stay firm",
        "The second line describes discernment inside an excited environment. You can recognize what is real without needing a long emotional cycle to decide. A firm inner standard makes it possible to join good momentum quickly and refuse weak momentum just as quickly. The line values clarity that is not swept along by collective mood.",
        "As this line changes, enthusiasm becomes selective commitment. The emerging pattern gains stability because action is tied to a criterion rather than to atmosphere. Quick recognition prevents both cynical delay and impulsive participation.",
        "Being ‘hard to impress’ can become its own performance. The goal is not detachment from enthusiasm but rapid discrimination. If the evidence is sound, excessive hesitation wastes the opening just as surely as hype does.",
        "What simple criterion would let you decide quickly whether this momentum deserves commitment without waiting for the crowd to decide for you?",
        "Line 2 gives enthusiasm a firm internal criterion, allowing quick commitment to what is sound and quick refusal of what is not.",
      ),
      authoredLine(
        "Looking upward for excitement creates regret",
        "The third line shows energy becoming dependent on someone else’s approval, charisma, or promise. Instead of participating in the work itself, attention keeps looking upward for another signal that enthusiasm is justified. This delays independent action and can turn motivation into dependency on a leader or spectacle.",
        "Change here brings energy back into personal responsibility. The emerging pattern asks each participant to convert inspiration into their own next action rather than waiting for the source of excitement to keep supplying direction and confidence.",
        "Admiration can make people passive. Do not confuse being inspired by a leader with having a plan, and do not let delay accumulate because you are waiting for another speech, permission, or emotional lift.",
        "What action already belongs to you that you are postponing while waiting for someone else to renew your enthusiasm?",
        "Line 3 breaks dependency on external inspiration by returning mobilized energy to the participant’s own responsibility and action.",
      ),
      authoredLine(
        "Become a genuine source of mobilization",
        "The fourth line is the strong center of enthusiasm: energy gathers because people recognize a credible source of direction. Support can accumulate quickly when confidence is linked to real preparation and the leader does not doubt every response. The task is to use this magnetism to coordinate, not to make everyone dependent on the source.",
        "When this line changes, enthusiasm can become organized collective movement. The emerging pattern strengthens as supporters connect with one another and responsibilities distribute outward. A good center turns gathered energy into a network rather than a fan base.",
        "Charisma can become self-reinforcing. Do not interpret the number of supporters as proof that the direction is correct, and do not keep all decisions near the center simply because attention naturally gathers there.",
        "How can the energy gathering around this initiative be converted into distributed responsibility so the work does not depend on one source of motivation?",
        "Line 4 makes enthusiasm a coordinating center, then asks that gathered energy be distributed into real roles, relationships, and action.",
      ),
      authoredLine(
        "Chronic strain without collapse",
        "The fifth line describes enthusiasm constrained by a persistent problem. Energy cannot flow freely, yet the system remains alive. This can be frustrating because nothing feels fully well, but the continuing capacity matters. The practical task is maintenance: protect what is still functioning while diagnosing the condition that keeps vitality from becoming easy movement.",
        "Change here may convert chronic limitation into a more sustainable rhythm. The emerging pattern does not require a dramatic cure; it may begin with reducing repeated strain, changing expectations, or building around a limitation that has proven durable.",
        "Do not turn chronic difficulty into an identity or use survival as proof that no correction is needed. Continuing to function is valuable evidence, but it does not make ongoing strain harmless.",
        "What is still reliably alive in this strained situation, and what adjustment would reduce the cost of keeping it functioning?",
        "Line 5 protects the vitality that remains under chronic strain while seeking a more sustainable way to carry the persistent limitation.",
      ),
      authoredLine(
        "Enthusiasm becomes delusion, then changes",
        "At the top line, excitement has outrun reality. The group or individual may be intoxicated by momentum, attached to a story of inevitable success, or continuing a peak emotional state after its evidence has disappeared. The saving possibility is change: recognizing the distortion can end the problem without requiring permanent condemnation of the original enthusiasm.",
        "Change here brings the cycle back toward sobriety. The emerging direction uses disillusionment as correction rather than as an excuse for cynicism. Energy can be reorganized around what remains true after the inflated story is removed.",
        "Do not defend a failing narrative merely because many people were once inspired by it. But also do not conclude that all enthusiasm is foolish. The task is to separate the valid purpose from the exaggerated expectations that gathered around it.",
        "What part of the enthusiastic story has become impossible to defend, and what worthwhile purpose could survive after that exaggeration is dropped?",
        "Line 6 ends intoxicated enthusiasm through honest revision, preserving whatever purpose remains sound after the inflated story is released.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
