import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 17,
    coreTheme: "Following",
    legacySummary: "Adaptation is useful when it follows what is worthy rather than what is merely convenient. Notice which influence deserves commitment.",
    strength: "responsive adaptation without losing judgment",
    challenge: "following habit, popularity, or convenience instead of what is sound",
    orientation: "choose the influence or course worth following and stay able to revise when evidence changes",
    transitionTheme: "adaptation becoming alignment with what proves worthy in practice",
    stabilityTheme: "flexibility anchored by discernment rather than dependence",
    lowerTrigram: "zhen",
    upperTrigram: "dui",
    lineEmphases: [
      "choose the first influence worth following instead of drifting toward convenience",
      "make adaptation practical while keeping an independent standard of judgment",
      "reconsider allegiance when pressure reveals that the followed path is unsound",
      "adapt to wider conditions without surrendering the reason you chose the course",
      "model responsive leadership that can both follow good evidence and be followed",
      "stop following when loyalty outlives the worthiness of the direction",
    ],
  },
  {
    number: 18,
    coreTheme: "Repairing what has decayed",
    legacySummary: "Something inherited or neglected needs correction. Diagnose the source, accept responsibility for repair, and change the pattern rather than patching symptoms.",
    strength: "the willingness to inspect causes and repair neglected systems",
    challenge: "blame, cosmetic fixes, or repeating inherited habits while treating only symptoms",
    orientation: "trace the problem to its source, repair the process, and verify that the pattern actually changes",
    transitionTheme: "decay becoming renewal when responsibility reaches causes instead of appearances",
    stabilityTheme: "maintenance habits that prevent repaired weaknesses from quietly returning",
    lowerTrigram: "xun",
    upperTrigram: "gen",
    lineEmphases: [
      "trace the first visible symptom back toward the neglected cause",
      "repair an inherited weakness through ordinary maintenance and changed habits",
      "stay with root causes when pressure makes cosmetic fixes more attractive",
      "bring the repair into the wider system where old incentives may resist it",
      "take visible responsibility for correction without turning repair into blame",
      "finish the repair by preventing the old pattern from quietly rebuilding itself",
    ],
  },
  {
    number: 19,
    coreTheme: "Approach",
    legacySummary: "Access and influence are increasing. Use proximity to understand, support, and prepare, remembering that favorable openings also have limits.",
    strength: "constructive proximity and the ability to meet what is approaching",
    challenge: "overconfidence during an opening or assuming access will remain indefinitely",
    orientation: "use growing access to understand conditions and strengthen relationships before the window changes",
    transitionTheme: "distance becoming engagement, with responsibility increasing alongside influence",
    stabilityTheme: "attentive presence that uses access without taking it for granted",
    lowerTrigram: "dui",
    upperTrigram: "kun",
    lineEmphases: [
      "use the first increase in access to listen before trying to influence",
      "build trust through close, useful contact while the opening is still modest",
      "remember the limits of proximity when growing access creates confidence",
      "bring support outward as influence expands and more people are affected",
      "use a central position of approach to serve, prepare, and clarify expectations",
      "recognize when the season of easy approach is ending and distance must be respected",
    ],
  },
  {
    number: 20,
    coreTheme: "Contemplation",
    legacySummary: "Step back far enough to see the pattern and your own role in it. Observation becomes useful when it changes the quality of subsequent action.",
    strength: "perspective that reveals patterns hidden by immediate activity",
    challenge: "detached observation, self-deception, or watching without letting evidence alter conduct",
    orientation: "observe the system and your place in it before choosing the next intervention",
    transitionTheme: "observation becoming changed behavior when insight is carried back into action",
    stabilityTheme: "regular perspective-taking that prevents activity from replacing understanding",
    lowerTrigram: "kun",
    upperTrigram: "xun",
    lineEmphases: [
      "pause the first impulse to intervene long enough to observe the pattern",
      "make reflection practical by noticing your own role in what you are studying",
      "test your interpretation when pressure exposes blind spots or selective attention",
      "carry what you have seen into the wider field and compare it with others' evidence",
      "use a visible perspective to improve conduct rather than to claim superior insight",
      "end contemplation when further observation becomes avoidance of necessary action",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
