import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 17,
    coreTheme: "Following",
    coreMeaning: "Following is about responsive alignment rather than passive obedience. Sui asks what deserves to guide your movement and whether the relationship between follower and direction remains worthy in practice. Adaptation is a strength when it keeps you connected to reality; it becomes weakness when convenience, popularity, or habit replaces judgment. The reading therefore emphasizes selection. Some influences should be left behind so a more mature standard can be followed. Some opportunities offer immediate benefit but require scrutiny because attachment can distort independence. At its best, following becomes mutual: trustworthy conduct creates a direction others can recognize without coercion. Loyalty is never the final criterion. If evidence changes or the object of commitment ceases to be worthy, faithful adaptation may require a new course rather than stubborn continuity.",
    strength: "responsive adaptation without losing judgment",
    challenge: "following habit, popularity, or convenience instead of what is sound",
    orientation: "choose the influence or course worth following and stay able to revise when evidence changes",
    structureInterpretation: "Thunder below begins movement while Lake above invites responsive exchange. Quick I Ching reads the structure as movement shaped by what it encounters: following is neither inert nor unilateral. The lower impulse moves, the upper field responds, and the quality of the result depends on whether adaptation remains connected to a worthy direction.",
    reflectionQuestions: [
      "What are you following because it has proven worthy, and what are you following mainly because it is familiar or socially easy?",
      "Which influence would require you to leave a less mature attachment behind in order to follow it honestly?",
      "What evidence would justify changing course without treating revision as disloyalty or failure?",
    ],
    watchFor: [
      "A more mature standard becoming attractive enough that a weaker habit or attachment loses its hold.",
      "Loyalty being used to suppress evidence that the followed direction is no longer serving the stated purpose.",
      "Other people beginning to follow a course voluntarily because its conduct has become trustworthy and useful.",
    ],
    transitionTheme: "adaptation becoming alignment with what proves worthy in practice",
    stabilityTheme: "flexibility anchored by discernment rather than dependence",
    lowerTrigram: "zhen",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Change the standard when conditions change",
        "The first line begins Following with a shift in what governs action. A role, rule, or priority may need revision because the old standard no longer fits the present conditions. The important point is to make the change through open contact with reality rather than through private impulse. Going out, observing, and comparing evidence keeps adaptation from becoming arbitrary.",
        "Change here makes following an active decision about criteria. The emerging direction becomes cleaner when the rule itself is updated before behavior is asked to conform. Once the standard is sound, adaptation can proceed without constant improvisation.",
        "Do not change principles merely because the current situation is inconvenient. A flexible rule still needs a reason that can be explained beyond personal preference. Otherwise adaptation becomes opportunism.",
        "Which rule or priority no longer fits the conditions, and what outside evidence would justify replacing it with a better standard?",
        "Line 1 begins Following by revising the governing standard in response to reality rather than by drifting with convenience.",
      ),
      authoredLine(
        "Following the immature loses the mature",
        "The second line presents a choice of attachment. Attention captured by what is immediate, dependent, or immature can cost connection with a more developed person, standard, or opportunity. Following always has an opportunity cost: what you stay close to shapes what you cannot accompany. The line asks whether familiarity is keeping you below the level of influence you now need.",
        "As this line changes, the reading differentiates between attachments by maturity. The emerging movement requires releasing a smaller pull so there is room to follow a more capable guide or demanding standard. Growth becomes possible when selection is explicit.",
        "Do not despise the less mature merely to feel advanced. The issue is allocation of commitment, not contempt. Some responsibilities to beginners remain real even when they should not define your own direction.",
        "What familiar or dependent attachment is consuming the attention you would need to learn from a more mature influence?",
        "Line 2 makes following selective: attachment to the immature can prevent movement with the more developed direction now available.",
      ),
      authoredLine(
        "Choose the mature direction and accept the loss",
        "The third line reverses the previous choice. Following a more mature person, standard, or path may require leaving behind something easier, younger, or more immediately gratifying. The gain is not free: serious alignment narrows options. The line favors accepting that trade-off rather than trying to keep incompatible attachments equally central.",
        "Change here turns discernment into commitment. The emerging pattern becomes stronger because the chosen direction can now organize effort and produce practical benefit. Asking clearly for what is needed is appropriate when the underlying alignment is sound.",
        "Do not label every sacrifice ‘maturity.’ A demanding path deserves commitment only if it is actually more worthy, not simply more prestigious or difficult. Verify the quality of what you are choosing before romanticizing the loss.",
        "What would you need to release in order to follow the more mature direction wholeheartedly, and why is that trade-off justified?",
        "Line 3 accepts the opportunity cost of following a more mature course, allowing commitment to become practical instead of divided.",
      ),
      authoredLine(
        "Following that brings gains can still be dangerous",
        "The fourth line warns that successful following may generate benefit, influence, or followers of its own. Gains can make an alignment look self-validating even when the motive has begun to drift. This is where sincerity and a clear path matter: the direction should remain defensible apart from the rewards it now produces.",
        "When this line changes, following becomes leadership under scrutiny. The emerging pattern tests whether benefit can be accepted without allowing it to redefine the purpose. Transparent motive and consistent conduct keep success from turning adaptation into self-interest.",
        "Do not assume that profitable or popular following is therefore correct. Rewards can conceal capture. If you would abandon the direction as soon as the benefit disappeared, examine what you are actually loyal to.",
        "Would this direction still deserve your commitment if the status, access, or practical gain it currently produces became smaller?",
        "Line 4 tests successful following by separating the worth of the path from the rewards that have begun to accumulate around it.",
      ),
      authoredLine(
        "Sincere alignment with what is excellent",
        "The fifth line places following around a clearly worthy center. Commitment is not based on fear, convenience, or reward but on recognition of quality. A person, principle, or practice has shown enough excellence to deserve sincere alignment. This creates steadiness because judgment and loyalty point in the same direction.",
        "Change here turns chosen alignment into a source of wider trust. The emerging pattern may make the follower capable of guiding others because the standard is no longer borrowed superficially; it has become embodied in conduct.",
        "Admiration can still become idealization. Excellence should remain testable, and sincere commitment should not require blindness to error. A worthy standard is strong enough to survive accurate criticism.",
        "What has this person, principle, or practice repeatedly demonstrated that makes sincere commitment reasonable rather than merely emotional?",
        "Line 5 stabilizes Following around a genuinely excellent standard whose worth has been demonstrated in practice.",
      ),
      authoredLine(
        "A commitment held even after the ordinary following ends",
        "At the top line, following becomes a deep bond that is not easily released by ordinary change of circumstance. The commitment may be to a lineage, promise, institution, or principle that has become part of identity and memory. Such bonds can provide continuity beyond short-term advantage, but they need conscious renewal rather than mere inherited attachment.",
        "Change here brings the following cycle into ritual or long-term commitment. The emerging direction asks whether the bond can be honored deliberately, with gratitude for its source, while still allowing present judgment to determine how its values are carried forward.",
        "Deep loyalty can become captivity when the original reason for the bond is no longer examined. Honor does not require repeating every old form. Distinguish the enduring value from the historical expression through which it was first received.",
        "Which long-standing commitment deserves conscious renewal, and which part of its inherited form can change without betraying the value at its center?",
        "Line 6 turns Following into durable commitment, asking inherited loyalty to remain conscious, examined, and connected to the value that made it worthy.",
      ),
    ],
  },
  {
    number: 18,
    coreTheme: "Repairing what has decayed",
    coreMeaning: "Repairing what has decayed deals with damage produced over time: neglected maintenance, inherited habits, weak governance, or patterns that once worked but now reproduce failure. Gu is not satisfied with cosmetic repair. It asks where the corruption came from and what responsibility belongs to the present even when the cause began earlier. The work may involve correcting what was received from authority figures, family systems, predecessors, or one’s own past decisions. Different defects require different degrees of firmness; some can be repaired gently, while others have been tolerated too long. The reading favors diagnosis, ownership, and verification after intervention. Repair is complete only when the process that generated the weakness has changed enough that the same decay does not quietly rebuild itself.",
    strength: "the willingness to inspect causes and repair neglected systems",
    challenge: "blame, cosmetic fixes, or repeating inherited habits while treating only symptoms",
    orientation: "trace the problem to its source, repair the process, and verify that the pattern actually changes",
    structureInterpretation: "Wind below penetrates and spreads through the inner system while Mountain above stops movement and accumulates what has not been cleared. Quick I Ching reads the combination as decay that develops when patterns circulate underneath a structure that has become too fixed to correct them. Repair therefore requires both diagnosis inside and decisive boundary at the point of accumulation.",
    reflectionQuestions: [
      "Which present problem is being reproduced by an inherited process rather than by the most visible symptom?",
      "What responsibility belongs to you now even if the original cause came from a predecessor, family system, or earlier leadership?",
      "How will you know after the repair that the underlying pattern has changed rather than merely gone quiet?",
    ],
    watchFor: [
      "The same failure returning after cosmetic fixes because the original incentive, routine, or neglected responsibility remains intact.",
      "Repair conversations becoming dominated by blame for the past instead of ownership of the present process.",
      "A maintenance practice or new boundary beginning to prevent the weakness before it again becomes visible damage.",
    ],
    transitionTheme: "decay becoming renewal when responsibility reaches causes instead of appearances",
    stabilityTheme: "maintenance habits that prevent repaired weaknesses from quietly returning",
    lowerTrigram: "xun",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Repair what was inherited from the father-line",
        "The first line begins with a defect inherited from prior authority, design, or leadership. The present person did not create the whole problem, but can still interrupt its continuation. Repair should be respectful enough to learn why the old system developed and firm enough not to repeat its weakness merely out of loyalty to the predecessor.",
        "Change here converts inherited burden into present responsibility. The emerging pattern becomes healthier when the old cause is named without making ancestry or prior leadership an excuse. Correction can preserve what was valuable while changing the mechanism that decayed.",
        "Blame can feel clarifying while actually postponing repair. Do not spend more energy judging the predecessor than changing the process you now control. Equally, respect should not require maintaining a known defect.",
        "What inherited rule or habit can you change now without needing to settle the entire moral judgment about the person who created it?",
        "Line 1 starts repair by taking present responsibility for an inherited defect while separating correction from blame.",
      ),
      authoredLine(
        "Repair what came through the nurturing system gently",
        "The second line deals with decay tied to a nurturing, relational, or protective system. Problems rooted in care, family habit, or accommodation often cannot be corrected by blunt force without damaging the relationship that also contains value. The repair needs tact: distinguish the harmful pattern from the person or bond that carried it.",
        "As this line changes, repair becomes relational renegotiation. The emerging movement asks for new terms, habits, or boundaries introduced with enough gentleness that the system can adapt instead of defending itself against humiliation.",
        "Gentleness can turn into continued enabling. Do not avoid a necessary correction merely because the old pattern was associated with care or good intention. Intent does not remove consequence.",
        "How can you correct this inherited relational pattern clearly without turning the repair into an attack on the person who once carried it?",
        "Line 2 repairs decay inside a nurturing relationship through tactful boundary change rather than through either denial or attack.",
      ),
      authoredLine(
        "Correct inherited decay even if the repair is imperfect",
        "The third line favors action despite the likelihood of some roughness. The defect has enough consequence that waiting for a perfectly elegant repair would allow more damage. You may make small mistakes in the correction, but those are preferable to leaving the decayed structure untouched. The emphasis is on responsible intervention with ongoing review.",
        "Change here moves diagnosis into active repair. The emerging pattern can improve quickly if the intervention remains open to adjustment. Admitting a minor repair error is part of the process, not evidence that the original decay should have been tolerated.",
        "Urgency does not justify recklessness. The line allows imperfect repair, not careless demolition. Keep enough feedback available to distinguish acceptable roughness from a new defect created by the solution itself.",
        "What repair is important enough to begin before every detail is perfect, and what feedback will let you correct the correction as you go?",
        "Line 3 accepts some imperfection in the repair process when continued delay would preserve a more serious inherited defect.",
      ),
      authoredLine(
        "Tolerating decay makes you part of it",
        "The fourth line warns against indulgence toward a known inherited problem. Understanding why the defect exists may have become an excuse for leaving it untouched. Once the pattern is visible and responsibility is available, continued tolerance changes the moral position: the present steward begins to participate in the decay rather than merely inherit it.",
        "When this line changes, accommodation can become accountability. The emerging direction requires a firmer boundary, deadline, or repair commitment that makes continued neglect harder. Sympathy remains possible without allowing the defective process to continue indefinitely.",
        "Do not confuse compassion with permission. A system can have understandable causes and still require decisive correction. Delayed action can create deeper consequences for people who had no role in creating the original problem.",
        "What known defect are you still ‘understanding’ long after you have enough responsibility to begin correcting it?",
        "Line 4 marks the point where tolerating inherited decay becomes participation in it and firmer accountability is required.",
      ),
      authoredLine(
        "Repair the inheritance in a way that earns trust",
        "The fifth line shows successful repair becoming visible and credible. A person in central responsibility can correct an inherited weakness while preserving continuity with what deserves respect. The result is not merely technical improvement; it restores confidence because others can see that the legacy is being handled honestly rather than either worshipped or rejected wholesale.",
        "Change here turns repair into renewed legitimacy. The emerging pattern can carry forward what is useful from the past without being trapped by its defects. Recognition follows because stewardship has demonstrated both discernment and responsibility.",
        "Public praise for a repair can tempt leadership to stop verifying the underlying process. Do not let recognition substitute for maintenance. The best legacy correction is one that continues working after attention moves elsewhere.",
        "What part of the inherited system can be preserved with honor once the defective mechanism around it is genuinely corrected?",
        "Line 5 converts repair into renewed legitimacy by preserving the worthy inheritance while visibly correcting what had decayed.",
      ),
      authoredLine(
        "Step outside the inherited system to serve a larger standard",
        "At the top line, repair reaches a limit where continued service inside the old structure may no longer be the right task. A person can refuse position, status, or participation when the larger principles they serve cannot be expressed through the inherited arrangement. This is not escapism if the withdrawal follows serious understanding and responsibility.",
        "Change here releases the reformer from the assumption that every decayed system must be repaired from within. The emerging direction may involve independent work, a new institution, or service to a broader standard that does not depend on preserving the old hierarchy.",
        "Leaving can become moral vanity if it avoids responsibilities that still can be repaired. Make sure the decision is based on the limits of the structure, not on a desire to appear purer than those who remain.",
        "Has this system reached the point where serving the larger principle requires stepping outside it rather than seeking another internal repair?",
        "Line 6 recognizes that some repair cycles end with principled independence from the inherited structure rather than with another attempt to fix it from within.",
      ),
    ],
  },
  {
    number: 19,
    coreTheme: "Approach",
    coreMeaning: "Approach describes increasing access, influence, and proximity. Lin is favorable because distance is shrinking: a person can learn more directly, offer support, and shape conditions that were previously remote. But access carries responsibility and has a season. The reading asks how the opening is being used before it changes. Approach should increase understanding, not merely confidence. Listen while the channel is open, strengthen relationships through useful presence, and clarify expectations before familiarity produces assumptions. Authority expressed through approach should feel like service rather than inspection. The later lines remind you that no window stays permanently easy; wise engagement includes awareness of withdrawal, changing conditions, and the need to leave behind structures that remain helpful after direct proximity declines.",
    strength: "constructive proximity and the ability to meet what is approaching",
    challenge: "overconfidence during an opening or assuming access will remain indefinitely",
    orientation: "use growing access to understand conditions and strengthen relationships before the window changes",
    structureInterpretation: "Lake below creates openness and exchange while Earth above receives and carries what rises toward it. Quick I Ching reads the structure as constructive approach: contact expands because the field can receive it. The favorable movement should be used to build understanding and capacity, with awareness that every period of increased access eventually changes.",
    reflectionQuestions: [
      "What can you understand now through direct contact that would have been guesswork when the situation was more distant?",
      "How can increased influence be used to strengthen another person or system rather than simply to increase your own reach?",
      "What should be established before this favorable period of access naturally becomes less immediate?",
    ],
    watchFor: [
      "Direct contact replacing assumptions and revealing needs or constraints that distance had hidden.",
      "Familiarity creating entitlement, loose boundaries, or an expectation that access will remain available indefinitely.",
      "A relationship, routine, or local capability becoming strong enough to continue after direct involvement decreases.",
    ],
    transitionTheme: "distance becoming engagement, with responsibility increasing alongside influence",
    stabilityTheme: "attentive presence that uses access without taking it for granted",
    lowerTrigram: "dui",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Approach together from a shared basis",
        "The first line begins increased contact with alignment. You are not approaching alone; another person, principle, or group can move with you because the basis for engagement is shared. This creates confidence without needing dominance. Early approach works best when motives are compatible and the parties can state why the contact is useful.",
        "Change here turns potential connection into active engagement. The emerging pattern gains stability when the first approach is coordinated rather than improvised independently. Shared terms now can reduce misunderstanding as access grows.",
        "Do not assume that moving together means wanting exactly the same thing. Clarify the common basis before increased proximity exposes hidden differences. False alignment at the beginning creates more friction later.",
        "Who should approach this situation with you, and what shared purpose is strong enough to coordinate both of you without erasing your differences?",
        "Line 1 begins Approach through aligned companionship, using a shared basis to make the first increase in contact more stable.",
      ),
      authoredLine(
        "Mutual approach broadens the opening",
        "The second line describes access that is welcomed rather than merely tolerated. There is reciprocity in the movement: you approach, and the situation or other party also makes room. This makes broader engagement possible because the connection is not being sustained by one side’s persistence alone.",
        "As this line changes, the opening can support more varied activity. The emerging pattern benefits from using mutual trust across several areas rather than keeping the relationship narrowly defensive. Reciprocity allows influence to expand without feeling like intrusion.",
        "A warm response can encourage overextension. Do not convert mutual goodwill into assumptions about unlimited access or agreement. Keep noticing where reciprocity is real and where permission has not actually been given.",
        "Where is the approach genuinely mutual, and what additional cooperation is now possible because both sides are making room?",
        "Line 2 uses reciprocal welcome to broaden engagement while keeping the boundaries of real permission visible.",
      ),
      authoredLine(
        "Comfortable approach can become careless",
        "The third line warns that easy access can make engagement superficial. When proximity feels pleasant and nothing immediately resists, there is a temptation to assume the relationship needs no further care. The useful correction is concern: review whether you are still listening, still providing value, and still respecting the conditions that created the opening.",
        "Change here turns complacent closeness into renewed attentiveness. The emerging direction improves when comfort becomes a reason to deepen responsibility rather than an excuse to stop observing. Awareness of the risk itself reduces it.",
        "Do not invent problems simply because the reading mentions complacency. The issue is neglect born from ease, not a requirement to distrust a good relationship. Use the favorable conditions while maintaining the practices that made them favorable.",
        "What responsibility have you begun to neglect because this access or relationship currently feels easy and secure?",
        "Line 3 renews attentiveness inside comfortable access so favorable approach does not decay through complacency.",
      ),
      authoredLine(
        "Arrive directly where the need is",
        "The fourth line favors a complete, unpretentious approach. Instead of managing from distance or through excessive intermediaries, move close enough to understand the real conditions and respond directly. Presence itself can become useful when it removes distortion between decision and consequence.",
        "When this line changes, influence becomes grounded in first-hand contact. The emerging pattern is more accurate because outer responsibility meets the local reality without needing to guess through layers of abstraction.",
        "Direct access can become micromanagement if presence is used to override the people who already understand the local field. Approach to learn and support, not to make proximity another form of control.",
        "Where would direct contact reduce distortion, and how can you enter without displacing the people who already carry local knowledge?",
        "Line 4 brings approach close to the actual conditions, using direct presence to improve understanding without turning proximity into control.",
      ),
      authoredLine(
        "Wise approach strengthens others",
        "The fifth line places influence in a mature central role. The best use of access is not to make every decision personally but to understand enough to assign, support, and trust capable people. Wise approach increases the quality of the whole field because those closest to the work become more able to act.",
        "Change here turns proximity into distributed capacity. The emerging pattern becomes sustainable when central influence creates local judgment and does not require permanent direct involvement to keep the system functioning.",
        "Do not call delegation ‘trust’ if information is still tightly controlled or mistakes are punished so harshly that nobody can exercise judgment. Strengthening others requires real room to carry responsibility.",
        "Who should become more capable because of your current access, and what responsibility can be transferred while support is still close?",
        "Line 5 uses central approach to build other people’s judgment and capacity so the benefit of access can outlast direct involvement.",
      ),
      authoredLine(
        "Generous approach at the end of the season",
        "At the top line, approach becomes broad-hearted support rather than expansion of control. Influence may be near its seasonal limit, so the most useful act is to leave something beneficial behind: encouragement, resources, teaching, or goodwill that does not require continued proximity. The relationship can remain honorable even as access changes.",
        "Change here prepares for greater distance. The emerging direction preserves the best of the favorable period by converting presence into durable support. What was learned and strengthened during approach becomes more important than maintaining closeness for its own sake.",
        "Generosity can become a way to avoid letting go. Do not attach hidden conditions to the help you leave behind or use support to keep yourself indispensable after the season of direct approach has ended.",
        "What can you leave behind that remains genuinely useful even if your access or influence becomes smaller?",
        "Line 6 completes Approach by converting favorable proximity into generous, durable support that can continue after direct access changes.",
      ),
    ],
  },
  {
    number: 20,
    coreTheme: "Contemplation",
    coreMeaning: "Contemplation asks for enough distance to see a pattern that immediate activity has hidden. Guan includes both looking and being looked at: observation changes when you recognize that your own conduct is part of the system under examination. The reading favors perspective, careful attention, and a willingness to let what is seen alter later behavior. Different levels of observation produce different quality. A narrow view notices only the obvious; a fuller view examines one’s own role, the wider system, the effect of leadership, and finally the pattern of a whole life or structure. Insight is not an end state. If contemplation produces no changed decision, standard, or action, it can become refined avoidance. Step back, observe honestly, compare perspectives, and then return to conduct with a clearer sense of what your position contributes to the pattern.",
    strength: "perspective that reveals patterns hidden by immediate activity",
    challenge: "detached observation, self-deception, or watching without letting evidence alter conduct",
    orientation: "observe the system and your place in it before choosing the next intervention",
    structureInterpretation: "Earth below provides a broad field while Wind above moves across and penetrates it gradually. Quick I Ching reads the structure as a vantage point from which patterns can be surveyed rather than immediately acted upon. Observation becomes meaningful because subtle influence travels across the field and because the observer’s own example is also visible to others.",
    reflectionQuestions: [
      "What pattern becomes visible only when you stop intervening long enough to watch it operate on its own?",
      "How does your own behavior alter the system you are trying to observe or diagnose?",
      "What decision would need to change if you took the strongest evidence from this period of observation seriously?",
    ],
    watchFor: [
      "Repeated behavior becoming visible once attention shifts from individual incidents to the pattern across time.",
      "Observation turning into distance from responsibility, with more analysis but no willingness to alter conduct.",
      "Other people responding to your example in a way that reveals influence you were not accounting for.",
    ],
    transitionTheme: "observation becoming changed behavior when insight is carried back into action",
    stabilityTheme: "regular perspective-taking that prevents activity from replacing understanding",
    lowerTrigram: "kun",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "A childlike view sees only the immediate surface",
        "The first line describes observation with very limited perspective. Seeing only the nearest event may be understandable when responsibility is small, but it becomes inadequate when important decisions depend on a wider pattern. The task is to recognize the limits of the view before confidence grows larger than the information available.",
        "Change here opens observation beyond the immediate surface. The emerging pattern asks for more context—history, another stakeholder, longer time horizon, or direct comparison—so what looked simple can be placed inside a larger structure.",
        "Do not shame a narrow view when the observer has not yet had access to more. The problem begins when limited perspective is defended as complete knowledge. Curiosity is the appropriate correction.",
        "What important context is missing from the way you are currently viewing this situation, and how could you gain access to it?",
        "Line 1 identifies the limits of a narrow viewpoint and invites observation to widen before larger conclusions are drawn.",
      ),
      authoredLine(
        "A view through the crack",
        "The second line sees more than the first but still through a restricted opening. Partial information can be useful for modest decisions, especially when the observer knows the boundary of what can be seen. Problems arise when a narrow sample is generalized into a complete picture. The line favors conclusions proportional to the aperture.",
        "As this line changes, observation can broaden by deliberately testing what lies outside the current frame. The emerging movement asks for comparison: another data source, another role, or direct exposure to the part of the system previously inferred rather than seen.",
        "A partial view often feels especially convincing because it is concrete. Do not let vivid local evidence outweigh larger but less visible information simply because the local sample is easier to experience.",
        "Which conclusion are you drawing from a narrow sample, and what additional perspective would be most likely to change it?",
        "Line 2 keeps conclusions proportional to the limited view and points toward the perspective needed to test what the narrow aperture cannot show.",
      ),
      authoredLine(
        "Contemplate your own advance and retreat",
        "The third line turns observation inward. Instead of only studying other people or external conditions, examine the pattern of your own movement: when you advance, withdraw, commit, hesitate, or react. Your behavior is data. The line asks whether the observer can become an object of observation without collapsing into self-judgment.",
        "Change here converts self-observation into a decision about participation. The emerging pattern becomes more deliberate because action is informed by evidence about your own tendencies. You can adjust timing or role based on what repeated conduct reveals.",
        "Introspection can become a closed loop if every event is interpreted through personal psychology. Keep the external facts in view. The point is to understand your contribution to the pattern, not to make yourself the cause of everything.",
        "Looking at your own recent pattern of advance and retreat, what tendency should influence the next decision about timing or involvement?",
        "Line 3 makes the observer part of the evidence, using self-observation to improve the timing and quality of participation.",
      ),
      authoredLine(
        "Observe the light of the larger system",
        "The fourth line gains access to a broader field—an organization, community, market, institution, or leadership system—and can see how its values actually operate. This perspective is useful because the public image can be compared with lived structure. The observer is now close enough that the insight may justify participation or service.",
        "When this line changes, observation moves toward informed involvement. The emerging pattern asks whether what has been seen is worthy enough to join and whether your contribution can fit the system without losing independent judgment.",
        "Prestige can make a large system look brighter than it is. Do not confuse scale, visibility, or official values with evidence that the actual culture deserves commitment. Observe how decisions are made when interests conflict.",
        "What does this larger system consistently illuminate through its actual behavior, and does that make deeper participation more or less worthy?",
        "Line 4 uses a wider institutional view to decide whether observation should become informed participation in the larger system.",
      ),
      authoredLine(
        "Examine the effects of your own life and leadership",
        "The fifth line puts observation at the center of responsibility. A leader or influential person should examine the consequences of their own conduct in the people and systems around them. Intentions are insufficient evidence. What repeats under your influence—initiative, fear, clarity, dependency, honesty—shows what your example is actually producing.",
        "Change here turns central self-observation into leadership correction. The emerging pattern can improve when the person with influence changes behavior based on the field’s response instead of asking the field to confirm the leader’s self-image.",
        "Do not conduct ‘reflection’ that only collects flattering feedback. Power shapes what people are willing to report. Seek evidence from outcomes, dissent, turnover, workarounds, and behavior that does not depend on pleasing you.",
        "What repeated behavior in the people around you is the strongest evidence of the culture your own conduct is creating?",
        "Line 5 evaluates leadership by its observable effects, making the surrounding field part of the evidence about the observer’s own conduct.",
      ),
      authoredLine(
        "Contemplate the whole pattern beyond personal advantage",
        "At the top line, observation expands beyond immediate self-interest. The question becomes what the whole life, system, or long arc of conduct reveals when viewed with distance. This perspective can reduce the importance of short-term praise and blame because isolated episodes are placed inside a more enduring pattern of consequence and meaning.",
        "Change here completes contemplation by preparing a return to action from a wider standard. The emerging direction should carry fewer impulsive corrections because the observer has considered what deserves continuity across changing circumstances.",
        "Grand perspective can become abstraction that avoids the next concrete responsibility. Seeing the whole does not excuse neglecting the part you can actually change. Insight proves itself when it returns to proportionate conduct.",
        "From the widest perspective available, what pattern in this life or system deserves to continue, and what concrete next action would honor that conclusion?",
        "Line 6 completes Contemplation by placing immediate concerns inside the larger pattern and then returning that perspective to concrete conduct.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
