import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 21,
    coreTheme: "Biting through obstacles",
    legacySummary: "A concrete obstruction requires clear discrimination and decisive handling. Apply only the degree of firmness needed to restore order.",
    strength: "decisive clarity about a specific obstruction",
    challenge: "vague punishment, excessive force, or avoiding a necessary decision",
    orientation: "identify the obstruction precisely and remove it with proportionate firmness",
    transitionTheme: "blocked movement becoming restored order after a specific impediment is addressed",
    stabilityTheme: "clear standards that reduce the need for repeated corrective force",
    lowerTrigram: "zhen",
    upperTrigram: "li",
    lineEmphases: [
      "name the specific obstruction before applying any corrective force",
      "use clear standards to remove a manageable impediment without dramatizing it",
      "reassess proportionality when pressure makes harsher action feel automatically justified",
      "carry a necessary correction into the wider system with transparent reasons",
      "use central authority to restore order while limiting punishment to the actual problem",
      "stop corrective force once the obstruction is removed instead of continuing from momentum",
    ],
  },
  {
    number: 22,
    coreTheme: "Grace and form",
    legacySummary: "Presentation and form matter, but they should reveal rather than replace substance. Refine what is visible without confusing appearance with the core issue.",
    strength: "the ability to give substance an appropriate and intelligible form",
    challenge: "decoration replacing substance or polishing what should first be corrected",
    orientation: "use form to clarify and support what is real, not to conceal its weakness",
    transitionTheme: "rough substance becoming communicable through proportionate refinement",
    stabilityTheme: "attention to form that remains accountable to underlying quality",
    lowerTrigram: "li",
    upperTrigram: "gen",
    lineEmphases: [
      "make the first improvement in form reveal substance rather than distract from it",
      "refine presentation so ordinary communication becomes clearer and more fitting",
      "notice when pressure is pushing appearance ahead of what the underlying work can support",
      "bring a well-formed message into public view without polishing away important complexity",
      "use visible form to dignify substance rather than to substitute for it",
      "let ornament fall away when refinement has reached the point of obscuring what matters",
    ],
  },
  {
    number: 23,
    coreTheme: "Splitting apart",
    legacySummary: "Support is being stripped away. Reduce exposure, protect what is essential, and avoid pretending a weakening structure can carry the same load.",
    strength: "discernment about what must be protected as support erodes",
    challenge: "denial, overloading a failing structure, or fighting to preserve every layer",
    orientation: "reduce demands, protect the core, and let unsustainable layers fall away",
    transitionTheme: "erosion becoming the precondition for rebuilding once what cannot hold has been released",
    stabilityTheme: "minimal integrity preserved until real support can be rebuilt",
    lowerTrigram: "kun",
    upperTrigram: "gen",
    lineEmphases: [
      "reduce the first unnecessary load when support begins to weaken",
      "protect the essential core instead of defending every threatened layer",
      "stop adding pressure when erosion shows that the present structure cannot carry it",
      "withdraw exposed commitments as weakening becomes visible to the outer environment",
      "use central judgment to decide what must be preserved and what can safely fall away",
      "accept the end of a failing form so rebuilding can begin from what remains sound",
    ],
  },
  {
    number: 24,
    coreTheme: "Return",
    legacySummary: "A cycle is turning back toward its root. Small, genuine renewal matters more than dramatic correction; restore the right direction step by step.",
    strength: "the capacity to notice deviation and restore a sound direction early",
    challenge: "dramatic overcorrection, repeated drifting, or mistaking one good step for completed repair",
    orientation: "return to fundamentals through small repeatable corrections",
    transitionTheme: "deviation becoming renewal when the right direction is re-established and then maintained",
    stabilityTheme: "a simple course repeatedly renewed before error compounds",
    lowerTrigram: "zhen",
    upperTrigram: "kun",
    lineEmphases: [
      "notice the first deviation and return before correction becomes expensive",
      "accept steady support that helps a sound direction become habitual again",
      "learn from repeated drifting without turning each correction into self-reproach",
      "choose the return even when surrounding momentum continues in another direction",
      "own the correction quietly and make the restored direction credible through conduct",
      "recognize when the chance to return is being lost through delay, drama, or overcorrection",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
