import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 21,
    coreTheme: "Biting through obstacles",
    coreMeaning: "Biting through obstacles describes a blockage that will not dissolve through patience alone. Shi He asks for discrimination before force: what exactly is obstructing movement, what standard has been violated, and what degree of correction is enough to restore order? The image is not generalized aggression. It is the focused effort needed to bite through something specific that prevents the parts from meeting. The reading therefore favors evidence, proportionate consequence, and transparent reasons. Small obstructions should receive small corrections; serious or persistent violations may require firmer action. Authority becomes credible when it can stop after the problem is removed. The main danger is punishment acquiring its own momentum—becoming vague, theatrical, or larger than the obstruction. Correct the impediment, repair the standard around it, and then return the system to ordinary functioning.",
    strength: "decisive clarity about a specific obstruction",
    challenge: "vague punishment, excessive force, or avoiding a necessary decision",
    orientation: "identify the obstruction precisely and remove it with proportionate firmness",
    structureInterpretation: "Thunder below provides the impulse to act while Fire above provides illumination and discrimination. Quick I Ching reads the structure as correction guided by clarity: action is justified when the obstruction can be seen accurately enough that force is directed at the problem rather than spread across the whole situation.",
    reflectionQuestions: [
      "What is the exact obstruction, stated without turning the whole person or system into the problem?",
      "What is the smallest consequence or intervention that would actually restore the broken standard?",
      "How will you know when correction has done enough and should stop rather than becoming a new source of disorder?",
    ],
    watchFor: [
      "A disputed problem becoming easier to resolve once evidence identifies one concrete obstruction instead of a cloud of complaints.",
      "Corrective action expanding because anger or audience pressure demands more than the actual problem requires.",
      "The original standard becoming easier to follow after the obstruction is removed and expectations are clarified.",
    ],
    transitionTheme: "blocked movement becoming restored order after a specific impediment is addressed",
    stabilityTheme: "clear standards that reduce the need for repeated corrective force",
    lowerTrigram: "zhen",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "A small restraint stops the first offense",
        "The first line deals with misconduct or obstruction at a very early, limited scale. A minor consequence can be useful precisely because the pattern has not yet hardened. The purpose is immediate feedback: make the boundary unmistakable, interrupt repetition, and allow the person or process to correct course without turning a small problem into a permanent identity.",
        "Change here converts a first violation into learning. The emerging pattern improves when consequence and correction are closely linked in time, making it clear what behavior must change. Early firmness can prevent the need for harsher measures later.",
        "Do not humiliate someone for a first, contained problem or impose a punishment whose size serves authority more than learning. A small obstruction does not justify a large theater of enforcement.",
        "What immediate, limited consequence would make this boundary clear without making the first offense larger than it is?",
        "Line 1 uses a small, timely restraint to interrupt an early violation before stronger corrective force becomes necessary.",
      ),
      authoredLine(
        "Bite through the obvious soft obstruction",
        "The second line encounters an impediment that is comparatively easy to identify and remove. There is no need to turn the correction into a philosophical battle. Apply the standard, clear the obstruction, and move on. The value lies in directness: simple problems become costly when people hesitate because they want every correction to feel perfectly comfortable.",
        "As this line changes, the system moves quickly from blockage back toward function. The emerging pattern benefits from an intervention that is decisive enough to work but modest enough that no new conflict has to be managed afterward.",
        "Even easy correction can become overreach if irritation adds unnecessary force. Do not keep biting after the obstruction has yielded. The goal is restored movement, not proof that you were capable of enforcing the rule.",
        "Which current problem is straightforward enough that a clear standard and direct correction would resolve it without further drama?",
        "Line 2 removes a manageable obstruction cleanly, treating decisiveness as a way to restore function rather than display severity.",
      ),
      authoredLine(
        "A difficult bite reveals something toxic",
        "The third line reaches an obstruction whose correction exposes unpleasant material—resentment, hidden incentives, contamination, or consequences nobody wanted to see. The discovery can make the person doing the correction feel compromised or discouraged. The line still favors continuing, but with humility about the mess uncovered by intervention.",
        "Change here turns a simple enforcement problem into deeper diagnosis. The emerging pattern asks whether the newly exposed toxicity can be separated from the original obstruction and treated directly rather than allowed to poison the whole corrective process.",
        "Do not abandon a necessary correction merely because it reveals ugliness, but do not pretend the exposure is harmless. If the process itself has become contaminated by anger, conflict of interest, or bad information, adjust before applying more force.",
        "What unpleasant secondary issue has this correction exposed, and how can it be addressed without losing sight of the original obstruction?",
        "Line 3 continues necessary correction while treating the toxicity revealed by the process as new information that also needs care.",
      ),
      authoredLine(
        "Bite through the hard obstruction with evidence",
        "The fourth line confronts a genuinely tough impediment that has resisted easier measures. Firmness is justified, but so is preparation. Strong correction should rest on evidence, clear authority, and the endurance to apply a standard consistently rather than impulsively. The harder the obstruction, the more dangerous it is to rely on emotion alone.",
        "When this line changes, persistent blockage can finally give way to restored structure. The transition succeeds because force is supported by facts and a credible process. Resistance may continue, but the intervention is less vulnerable to being dismissed as arbitrary.",
        "A hard problem can seduce leaders into believing every tool should become hard. Do not let one resistant case normalize severity for the whole system. Keep the stronger measure tied to the exceptional obstruction that justified it.",
        "What evidence and authority would make a firmer intervention defensible even to someone who disagrees with the outcome?",
        "Line 4 applies sustained, evidence-based firmness to a hard obstruction while keeping exceptional force tied to the specific case.",
      ),
      authoredLine(
        "Central judgment extracts value from a hard correction",
        "The fifth line places corrective authority at the center and asks for discriminating judgment. A difficult case may contain both culpability and complexity; the task is to separate what deserves consequence from what can be repaired. The value found in the hard material is a clearer standard, not simply a heavier penalty.",
        "Change here turns central enforcement into institutional learning. The emerging pattern becomes stronger when the decision produces a rule, precedent, or repaired process that makes future violations less likely and future judgments more consistent.",
        "Authority can become overconfident after succeeding in a difficult correction. Keep listening for exculpatory facts and unintended effects. Central position should increase care because the decision now shapes more than one case.",
        "What principle should this difficult correction clarify for future cases so the system learns rather than merely punishes?",
        "Line 5 turns a hard central correction into a clearer and more durable standard for the wider system.",
      ),
      authoredLine(
        "Repeated refusal makes warning harder to hear",
        "At the top line, correction has failed to become learning. The person or system has become insulated from warning, so repeated violations produce increasingly severe consequence. The image is not an invitation to cruelty; it shows what happens when feedback is ignored until the channels for ordinary correction are almost closed.",
        "Change here ends the corrective cycle by exposing its limit. The emerging direction may require removal from a role, termination of access, or a structural separation because further warnings no longer function as information.",
        "Do not assume repeated failure always proves bad character. Check whether the warning system itself was understandable, consistent, and reachable. Severe consequence is legitimate only after ordinary correction truly had a fair chance to work.",
        "What evidence shows that repeated warnings have genuinely been heard and refused rather than merely delivered badly?",
        "Line 6 marks the limit of ordinary correction, where persistent refusal may require separation because warning no longer produces learning.",
      ),
    ],
  },
  {
    number: 22,
    coreTheme: "Grace and form",
    coreMeaning: "Grace and form concern the relationship between substance and presentation. Bi recognizes that form matters: language, design, ritual, appearance, and manners shape whether substance can be understood and received. The problem begins when refinement becomes independent of what it is supposed to reveal. The reading therefore favors proportionate form. Make the important thing clearer, more fitting, and easier to engage without polishing away its complexity or hiding defects that need repair. Some moments call for ornament; others call for simplicity. Grace can dignify a modest offering, communicate respect, or make a rough truth bearable, but it cannot manufacture real content. At the highest point, excess ornament should fall away. The strongest form is the one that becomes almost invisible because it serves the underlying reality so well.",
    strength: "the ability to give substance an appropriate and intelligible form",
    challenge: "decoration replacing substance or polishing what should first be corrected",
    orientation: "use form to clarify and support what is real, not to conceal its weakness",
    structureInterpretation: "Fire below provides clarity and visible distinction while Mountain above stops and gives form. Quick I Ching reads the structure as illumination held inside a boundary: substance becomes legible through shape, but the boundary must remain subordinate to what it contains. Form is strongest when it reveals rather than competes with content.",
    reflectionQuestions: [
      "What part of the substance currently needs better form so other people can perceive its real value?",
      "Where is polishing consuming attention that should instead be spent correcting the underlying work?",
      "What could become simpler without losing dignity, meaning, or clarity?",
    ],
    watchFor: [
      "A message, product, or relationship becoming easier to understand because form now matches the underlying substance.",
      "Presentation improving while the core defect remains untouched or becomes harder to discuss.",
      "A point where simplicity communicates more confidence and truth than another layer of ornament.",
    ],
    transitionTheme: "rough substance becoming communicable through proportionate refinement",
    stabilityTheme: "attention to form that remains accountable to underlying quality",
    lowerTrigram: "li",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Walk on your own feet before decorating the vehicle",
        "The first line chooses direct substance over unnecessary display at the beginning. A simpler method may require more personal effort, but it keeps attention on the actual task rather than on the status attached to how the task is approached. Before adding impressive form, prove that the underlying movement can stand on its own.",
        "Change here turns self-reliant simplicity into a foundation for later refinement. The emerging pattern becomes healthier because presentation is added to something that already works instead of being asked to create the appearance of capability.",
        "Simplicity can become performative asceticism just as easily as luxury can become display. Do not reject useful tools merely to prove purity. The question is whether form serves the task, not whether it looks expensive or austere.",
        "What could you do in a simpler, more direct way first so you know the substance works before investing in its presentation?",
        "Line 1 establishes substance through direct action before allowing status or ornament to define how the work is perceived.",
      ),
      authoredLine(
        "Adornment that depends on what it belongs to",
        "The second line treats form as secondary and attached. A beard has no independent purpose apart from the face it frames; likewise, presentation should derive its meaning from the substance it serves. Good refinement follows the contours of the real thing rather than forcing a borrowed style onto it.",
        "As this line changes, form becomes more integrated with content. The emerging pattern asks designers, communicators, or participants to let the underlying structure determine tone, detail, and emphasis instead of choosing ornament first and squeezing reality into it.",
        "Do not let a familiar style survive after the underlying substance has changed. A once-fitting presentation can become misleading if it continues by habit. Recheck the connection between what is shown and what is actually present.",
        "Which element of presentation makes sense only if it accurately follows the substance, and does that relationship still hold?",
        "Line 2 makes form accountable to the substance it adorns, allowing presentation to follow rather than dictate the underlying reality.",
      ),
      authoredLine(
        "Rich refinement needs lasting discipline",
        "The third line enjoys a high degree of polish, attractiveness, or favorable presentation. There is real pleasure in the refined form, but the line asks for constancy so the surface does not become a temporary peak detached from deeper quality. Refinement should be maintained by standards that remain after novelty fades.",
        "Change here tests whether beauty can become durable craft. The emerging pattern strengthens when attractive form is supported by process, maintenance, and repeated attention rather than by one successful presentation moment.",
        "Seduction by the surface can make feedback about substance harder to hear. Do not let praise for appearance become evidence that the core work is finished. Rich form increases the need for honest quality checks.",
        "What discipline would make this attractive form sustainable without allowing praise for the surface to substitute for evidence about substance?",
        "Line 3 turns rich refinement into durable quality by pairing beauty with the discipline needed to sustain what the surface promises.",
      ),
      authoredLine(
        "White simplicity can be more sincere than ornament",
        "The fourth line reaches a choice between added decoration and a cleaner, plainer presentation. What first appears austere or uncertain may actually create more trust because the situation no longer needs embellishment. Simplicity here is not lack of care; it is confidence that the substance can meet others without disguise.",
        "When this line changes, presentation becomes more transparent. The emerging pattern may remove intermediaries, simplify language, or choose a more direct relationship so that intention is easier to read and less likely to be mistaken for manipulation.",
        "Do not strip away form that carries necessary respect, accessibility, or context. Plainness can be rude or obscure when the audience needs structure. Simplicity should reveal more, not merely remove things.",
        "Where would a plainer form make your real intention easier to trust than another layer of polish?",
        "Line 4 favors lucid simplicity when ornament would make sincere intention harder rather than easier to perceive.",
      ),
      authoredLine(
        "A modest offering with genuine intent",
        "The fifth line shows refinement expressed through a limited but sincere offering. The resources available for presentation may be modest, yet care, intention, and fit can give the gesture dignity. This is especially relevant when someone fears that a simple contribution will look inadequate compared with a more lavish standard.",
        "Change here shifts value away from scale and toward appropriateness. The emerging pattern becomes more trustworthy because form communicates real regard without pretending to possess resources or certainty that are not actually present.",
        "Do not use sincerity as an excuse for careless execution. A modest offering still deserves attention to fit and respect. The distinction is between limited means and limited care.",
        "What modest but well-considered form would communicate genuine respect without pretending to a scale you do not actually have?",
        "Line 5 gives dignity to a modest offering by making care and fit more important than scale or display.",
      ),
      authoredLine(
        "Plain form at the end",
        "At the top line, ornament has completed its work and can fall away. The most refined expression may now be plain because nothing important needs to be added for the substance to be understood. Simplicity becomes the culmination of form rather than its absence: only what serves meaning remains.",
        "Change here releases attachment to presentation itself. The emerging direction lets the content stand with fewer supports, reducing maintenance and making it harder for surface concerns to distract from what the work actually is.",
        "Minimalism can become another aesthetic ideology. Do not remove useful context simply because plainness now feels sophisticated. The test is whether subtraction increases truth and clarity, not whether it looks cleaner.",
        "What can now be removed because the substance is strong enough to stand without that layer of explanation, decoration, or display?",
        "Line 6 completes Grace by letting unnecessary ornament fall away until form becomes almost transparent to the substance it serves.",
      ),
    ],
  },
  {
    number: 23,
    coreTheme: "Splitting apart",
    coreMeaning: "Splitting apart describes structural support being stripped away layer by layer. Bo is not a good setting for ambitious expansion. When foundations are weakening, the first responsibility is to reduce load, protect what remains sound, and stop pretending that the old form can carry the same demands. The reading favors discernment about levels of loss. Some outer layers can be released without destroying the core; other signs show that erosion has reached something essential. Fighting to preserve every part can accelerate collapse by spending resources on what cannot be saved. The deepest value is preservation of a viable seed from which rebuilding can later occur. Splitting apart is therefore not nihilistic. It asks for a smaller, truer structure that can survive the decline and recognize when one sound element remains capable of becoming a new beginning.",
    strength: "discernment about what must be protected as support erodes",
    challenge: "denial, overloading a failing structure, or fighting to preserve every layer",
    orientation: "reduce demands, protect the core, and let unsustainable layers fall away",
    structureInterpretation: "Earth below is almost entirely receptive and yielding while Mountain above supplies the last firm boundary at the top. Quick I Ching reads the structure as support being removed from beneath a remaining form. Stability cannot be restored by adding more load; the immediate task is to preserve the sound remnant while weak layers are allowed to fall away.",
    reflectionQuestions: [
      "Which layer of support has already weakened enough that planning as if it were intact has become dangerous?",
      "What is the smallest core that must remain viable even if outer commitments, status, or structure are released?",
      "Which threatened layer are you defending mainly because letting it go would force you to admit that the old form is ending?",
    ],
    watchFor: [
      "Repeated failures moving from peripheral inconvenience toward essential support, showing that erosion is deepening.",
      "Effort being spent on keeping appearances intact while the resources needed for the core become thinner.",
      "One remaining capability, relationship, or principle staying sound enough to become the seed of a later rebuild.",
    ],
    transitionTheme: "erosion becoming the precondition for rebuilding once what cannot hold has been released",
    stabilityTheme: "minimal integrity preserved until real support can be rebuilt",
    lowerTrigram: "kun",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Erosion reaches the lowest support",
        "The first line detects weakening at the base. The damage may still look local, but a support that carries weight has begun to fail. Reduce unnecessary load immediately and inspect what rests on the compromised foundation. Early acknowledgment is less costly than preserving normal operations until the failure becomes visible everywhere.",
        "Change here turns denial into protective reduction. The emerging pattern becomes smaller but more realistic as commitments are adjusted to the support that actually remains. What is removed now can prevent the core from being damaged later.",
        "Do not cover a foundational weakness with cosmetic repair or additional pressure. A structure can look intact while its load path is already failing. The urge to maintain appearances is especially dangerous at the beginning of erosion.",
        "What demand should be reduced now because the underlying support has weakened even if the outer structure still appears normal?",
        "Line 1 responds to early foundational erosion by reducing load before visible collapse spreads upward through the structure.",
      ),
      authoredLine(
        "The supporting frame continues to strip away",
        "The second line shows erosion moving beyond one isolated point into the frame that normally distributes support. The situation now requires a broader review. What depended on the weakening layer may need to be separated, paused, or simplified before failure becomes systemic.",
        "As this line changes, the reading moves from local repair toward structural triage. The emerging direction prioritizes what can still stand independently and stops forcing threatened parts to hold one another up through mutual weakness.",
        "Do not assume that because one part survived the first failure it can safely inherit more load. Redistribution helps only when the receiving support is genuinely stronger. Otherwise the collapse is merely moved sideways.",
        "Which connected commitment needs to be separated from the weakening frame before it begins depending on another compromised support?",
        "Line 2 broadens the response from local repair to structural triage as erosion reaches the frame that distributes support.",
      ),
      authoredLine(
        "Separate from the collapsing pattern",
        "The third line finds a position that can disengage from the wider erosion. Not every part has to fall with the structure. A person, practice, or unit may be able to break its dependency on the failing arrangement and preserve function independently. Separation can be responsible when continued attachment would only spread the damage.",
        "Change here creates a viable exception inside decline. The emerging pattern gains a protected element that may later contribute to rebuilding. Independence matters because it prevents the remaining sound capacity from being consumed by obligations to the collapsing whole.",
        "Do not abandon shared responsibilities prematurely or use the decline as cover for selfish extraction. Separation is sound when it protects real function and does not transfer avoidable harm onto those with fewer options.",
        "What can be responsibly decoupled from the weakening structure now so it remains viable instead of being pulled down by dependencies it no longer needs?",
        "Line 3 preserves a sound element through responsible separation from the larger pattern of structural decline.",
      ),
      authoredLine(
        "Erosion reaches the body of the system",
        "The fourth line marks a serious escalation: loss is no longer peripheral but touching the part that directly sustains people, identity, or essential function. The situation should not be treated as a routine efficiency problem. Exposure must be reduced and the core protected with urgency because further deterioration now has immediate human or operational consequence.",
        "When this line changes, the response shifts from selective reduction to emergency protection. The emerging pattern may require stopping normal operations, drawing a hard boundary, or abandoning a threatened outer form to preserve what cannot be replaced easily.",
        "Do not normalize essential harm because the decline happened gradually. Familiarity with deterioration can blunt judgment. Once erosion reaches the body of the system, maintaining continuity may be more dangerous than an explicit interruption.",
        "What essential function or person is now being touched by the decline, and what normal activity should stop to protect it?",
        "Line 4 treats erosion of essential support as an emergency boundary, prioritizing protection of the system’s body over continuity of appearances.",
      ),
      authoredLine(
        "Order the remaining resources around the protected core",
        "The fifth line finds a way to organize what remains. Even in decline, remaining resources, people, or capacities can be aligned rather than allowed to scatter. A coherent line of support can protect the core and reduce waste while the larger form continues to contract. Leadership here is about conservation and orderly passage.",
        "Change here turns decline into disciplined preservation. The emerging pattern gains a small but coherent structure capable of carrying essentials through the loss. What remains is not enough for the old scale, but it may be enough for continuity at a truer scale.",
        "Do not use central control to pretend the old abundance still exists. Organizing scarce resources requires transparent priorities. Hidden favoritism or denial about limits will destroy the trust needed for people to accept contraction.",
        "How should the remaining resources be ordered so the essential core is protected fairly while nonessential layers are allowed to go?",
        "Line 5 gives decline an orderly center by aligning remaining resources around the core that must survive.",
      ),
      authoredLine(
        "One sound fruit remains for the next cycle",
        "At the top line, the old structure is nearly gone, but one sound element remains capable of carrying continuity into the future. This may be a principle, person, skill, relationship, or resource that survived because it was genuinely viable rather than merely protected by the old form. The task is to recognize and preserve this seed without demanding that it instantly rebuild everything.",
        "Change here closes the splitting cycle and prepares renewal. The emerging direction begins from what remained sound after stripping away, giving later rebuilding a cleaner foundation. Loss becomes informative because it reveals what could survive without the old supports.",
        "Do not use the surviving seed as an excuse to reconstruct the failed form exactly as it was. Survival may prove the value of the core, not the wisdom of the previous structure around it.",
        "What has remained genuinely sound through the decline, and how can it be protected as a seed rather than forced to recreate the old structure immediately?",
        "Line 6 preserves the sound remnant after collapse and treats it as a seed for renewal rather than proof that the old form should be restored unchanged.",
      ),
    ],
  },
  {
    number: 24,
    coreTheme: "Return",
    coreMeaning: "Return describes renewal through reorientation rather than through dramatic reinvention. Fu begins with a small movement back toward a sound root after deviation, exhaustion, or a completed cycle. The reading values early correction because the distance from the right course is still manageable. It also recognizes that returning can happen repeatedly: people drift, notice, and return again before the new direction becomes stable. Support can help, but at some point the correction must be owned inwardly and carried even when the surrounding current points elsewhere. The deepest danger is not having deviated; it is losing the capacity to recognize or accept the return point. Renewal is therefore measured through repeatable conduct. A genuine return makes the next deviation shorter, the correction less dramatic, and the restored direction increasingly credible in ordinary life.",
    strength: "the capacity to notice deviation and restore a sound direction early",
    challenge: "dramatic overcorrection, repeated drifting, or mistaking one good step for completed repair",
    orientation: "return to fundamentals through small repeatable corrections",
    structureInterpretation: "Thunder below is the first renewed movement while Earth above provides receptive space for that movement to grow. With one yang line returning beneath five yin lines, the structure emphasizes a small but genuine renewal at the root. Quick I Ching reads Fu as restoration that begins quietly and becomes trustworthy through repetition rather than through force.",
    reflectionQuestions: [
      "What is the simplest sound direction you already know how to return to without inventing a new system?",
      "Where has repeated drifting become useful evidence about what makes the correction difficult to maintain?",
      "What behavior would make this return credible even if nobody around you changed direction at the same time?",
    ],
    watchFor: [
      "A deviation being noticed earlier, allowing correction before large consequences or elaborate repair are required.",
      "Return becoming theatrical—large promises, self-reproach, or overcorrection—while the ordinary habit remains unchanged.",
      "A restored practice holding even when the surrounding environment continues to reward the previous direction.",
    ],
    transitionTheme: "deviation becoming renewal when the right direction is re-established and then maintained",
    stabilityTheme: "a simple course repeatedly renewed before error compounds",
    lowerTrigram: "zhen",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Return before distance grows",
        "The first line catches deviation almost as soon as it occurs. The mistake, distraction, or wrong turn has not yet accumulated enough momentum to require a major repair. The strength here is quick recognition without self-dramatization: notice that the course is off, correct it, and resume the sound direction while the cost remains small.",
        "Change at this line turns an incipient deviation into immediate renewal. The emerging pattern becomes more resilient because correction is integrated into ordinary movement instead of postponed until failure becomes undeniable. Early return is a skill that reduces the need for later heroics.",
        "Do not turn a small correction into a crisis of identity. Shame can make the deviation feel larger and ironically increase the distance from the course. Equally, do not minimize the signal so much that the same drift is allowed to compound.",
        "What small deviation can you correct today before it requires apology, recovery, or structural repair later?",
        "Line 1 makes early return the ideal correction: notice the drift while it is still near and restore direction without drama.",
      ),
      authoredLine(
        "Return with steady support",
        "The second line shows renewal strengthened by good company, a reliable practice, or an environment that makes the sound direction easier to inhabit. Returning does not have to be solitary. Support is valuable when it normalizes the better course without controlling it, allowing correction to become less effortful through repeated contact with what is healthy.",
        "As this line changes, an individual correction begins to become a stable habit. The emerging pattern benefits from relationships and routines that reinforce return before willpower has to carry the whole burden. Support becomes part of the structure of renewal.",
        "Do not outsource the return to the supporter. A helpful person or environment cannot own the correction for you. If the sound direction exists only while supervision is present, the habit has not yet become internal.",
        "What person, routine, or environment reliably helps you return to the sound direction without making you dependent on being managed?",
        "Line 2 makes renewal easier to sustain by accepting steady support while keeping ownership of the return inside the person who is changing.",
      ),
      authoredLine(
        "Repeated return without self-punishment",
        "The third line describes a pattern of drifting and returning more than once. Repetition can be discouraging, but the continuing capacity to notice and correct remains valuable. The useful question is what the recurrence teaches about triggers, weak points, or conditions that have not yet changed. Each return should become more informed, not more ashamed.",
        "Change here turns repeated correction into learning about the mechanism of drift. The emerging pattern becomes stronger when recurrence produces a practical adjustment—new boundary, cue, sequence, or support—rather than another promise to ‘try harder’ in exactly the same conditions.",
        "Self-reproach can become part of the cycle by consuming attention after each lapse without changing what causes it. Avoid treating recurrence as proof that return is meaningless. The failure would be refusing to learn from the repetition.",
        "What recurring condition appears just before the drift, and what could you change there so the next return begins earlier?",
        "Line 3 treats repeated return as diagnostic evidence, replacing self-punishment with a more informed correction of the recurring weak point.",
      ),
      authoredLine(
        "Returning against the surrounding current",
        "The fourth line chooses the sound direction even while the surrounding group, habit, or environment continues another way. Renewal becomes more independent here because consensus is no longer available as support. The person must trust a clearer internal standard enough to step out of the prevailing current without turning the difference into contempt for others.",
        "When this line changes, return becomes a public act of alignment. The emerging pattern gains credibility because conduct now demonstrates the correction under social pressure. A restored direction that survives difference is more stable than one that depends on everyone moving together.",
        "Independence can become superiority. Do not make the return into a performance of being more correct than the surrounding group. The proof is in steady conduct, not in criticizing those who remain on the other path.",
        "What sound correction would you still choose if the people around you continued in the opposite direction and offered no social reward for returning?",
        "Line 4 makes return an independent commitment, maintaining the sound direction even when surrounding momentum continues elsewhere.",
      ),
      authoredLine(
        "Sincere return made credible",
        "The fifth line brings renewal to a centered and self-owned form. The person no longer needs repeated external pressure to admit the deviation. Return is sincere because responsibility is accepted plainly, and it becomes credible because conduct after the correction matches the stated intention. The emphasis is less on apology than on the integrity of follow-through.",
        "Change here turns renewal into stable character. The emerging pattern shows that the right direction has become easier to choose from within, allowing correction to be quiet, prompt, and proportionate. Trust can rebuild because others no longer have to guess whether the return is only verbal.",
        "Sincerity is not proven by intensity of feeling. Large declarations can distract from the mundane repetitions that actually restore trust. Avoid asking others to certify the return before your conduct has had time to demonstrate it.",
        "What ordinary repeated behavior would make this return believable without requiring another explanation or promise?",
        "Line 5 makes renewal credible through quiet ownership and repeated conduct that demonstrates the restored direction without theatrical proof.",
      ),
      authoredLine(
        "Missing the moment to return",
        "The top line shows return becoming difficult because the corrective signal is no longer recognized or is repeatedly ignored. Delay, confusion, pride, or dramatic overreaction can carry the person so far from the root that an easy correction is no longer available. The issue is not one mistake but losing contact with the orientation that would make return possible.",
        "Change here exposes the cost of a missed return point. The emerging direction may require a larger reset, outside help, or acceptance of consequences before the sound course can be found again. The lesson is to rebuild sensitivity to early signals rather than depend on rescue after major drift.",
        "Do not answer a missed return with another extreme swing. Overcorrection can create a second deviation and further obscure the root. Serious consequences may require serious repair, but the direction should still be simple enough to recognize.",
        "Which early warning have you repeatedly ignored, and what would make it difficult to miss the next time the course begins to drift?",
        "Line 6 warns that delayed recognition can turn a simple return into a major repair, making sensitivity to early corrective signals essential.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
