import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 25,
    coreTheme: "Uncontrived action",
    legacySummary: "Act from what is straightforward and appropriate rather than from manipulation or overplanning. Unexpected events are easier to meet when motives remain clear.",
    strength: "straightforward action grounded in clean motives and present facts",
    challenge: "scheming, overcontrol, or interpreting every surprise as a personal message",
    orientation: "act appropriately from what is known and leave room for events you cannot engineer",
    transitionTheme: "contrivance giving way to cleaner action and more direct contact with reality",
    stabilityTheme: "clarity of motive that remains steady when circumstances surprise you",
    lowerTrigram: "zhen",
    upperTrigram: "qian",
    lineEmphases: [
      "act on the first straightforward fact without inventing hidden motives around it",
      "make clean intention visible through simple and appropriate conduct",
      "stay uncontrived when pressure tempts manipulation or elaborate control",
      "meet unexpected outer conditions without treating surprise as proof of a secret design",
      "use a central role to keep motives transparent and action proportionate",
      "release rigid innocence when refusing complexity would become another form of distortion",
    ],
  },
  {
    number: 26,
    coreTheme: "Great restraint",
    legacySummary: "Substantial power is being contained and trained. Accumulate capability, knowledge, and resources so that later action is deliberate rather than premature.",
    strength: "stored capacity strengthened through training and restraint",
    challenge: "premature release, pride in unused potential, or endless preparation without purpose",
    orientation: "develop capability, retain energy, and choose the moment when stored strength has a real task",
    transitionTheme: "contained power becoming mature capacity ready for deliberate use",
    stabilityTheme: "continued training that makes restraint productive rather than merely restrictive",
    lowerTrigram: "qian",
    upperTrigram: "gen",
    lineEmphases: [
      "contain the first burst of power long enough to learn what it is for",
      "train capability through repeatable practice instead of admiring potential",
      "hold strength under pressure when premature release would waste it",
      "bring developed capacity into the wider field only after it can meet real demands",
      "use stored strength deliberately where responsibility justifies its release",
      "stop accumulating for its own sake when mature capacity now needs a concrete purpose",
    ],
  },
  {
    number: 27,
    coreTheme: "Nourishment",
    legacySummary: "Pay attention to what sustains people, systems, and attention. What you take in—and what you repeatedly provide—shapes the condition that follows.",
    strength: "discernment about inputs, support, and what truly sustains",
    challenge: "feeding appetite rather than need, careless consumption, or giving in ways that create dependence",
    orientation: "examine what is being taken in and supplied, then improve the quality of nourishment",
    transitionTheme: "poor inputs becoming sustainable support through better selection and provision",
    stabilityTheme: "habits of nourishment that reinforce vitality rather than short-term appetite",
    lowerTrigram: "zhen",
    upperTrigram: "gen",
    lineEmphases: [
      "inspect the first input before assuming it is nourishing",
      "make support reliable by matching what is provided to actual need",
      "notice when appetite, anxiety, or habit is distorting what gets consumed or supplied",
      "carry better nourishment into the wider system without creating dependence",
      "use a central role to improve both the quality and distribution of what sustains people",
      "stop feeding a pattern that has outgrown its need or begun to consume the system itself",
    ],
  },
  {
    number: 28,
    coreTheme: "Great excess",
    legacySummary: "The structure is carrying unusual pressure. Ordinary measures may be insufficient, so identify the overloaded point and respond before strain becomes collapse.",
    strength: "the courage to recognize exceptional load and adjust structure accordingly",
    challenge: "normalizing overload, heroic overcommitment, or delaying a needed structural response",
    orientation: "identify where the load exceeds capacity and make a proportionate structural change",
    transitionTheme: "dangerous strain becoming a survivable transition when support is redistributed in time",
    stabilityTheme: "ongoing load awareness that prevents exceptional pressure from becoming normal",
    lowerTrigram: "xun",
    upperTrigram: "dui",
    lineEmphases: [
      "acknowledge the first sign that ordinary capacity is being exceeded",
      "reinforce the most important support before the unusual load grows heavier",
      "change the structure when pressure proves that normal measures are no longer enough",
      "carry an emergency adjustment outward without pretending it can become permanent routine",
      "use central authority to redistribute exceptional load before failure concentrates",
      "end the extraordinary arrangement when its necessity has passed or collapse becomes imminent",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
