import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 25,
    coreTheme: "Uncontrived action",
    coreMeaning: "Uncontrived action describes conduct that stays close to reality instead of trying to engineer every outcome. Wu Wang favors clean motive, direct response, and willingness to meet events that were not part of the plan. The reading does not promise that innocence prevents difficulty; unexpected trouble can still arrive. Its point is that manipulation adds a second problem to the first by making judgment dependent on hidden agendas and imagined control. Act from what is actually known, cultivate what can be cultivated, and do not treat every surprise as a personalized message. When misfortune has no ethical or practical connection to your conduct, avoid frantic self-correction. When your own action is the cause, correct it plainly. The reliable center is appropriate action without contrivance, not a fantasy of perfect control.",
    strength: "straightforward action grounded in clean motives and present facts",
    challenge: "scheming, overcontrol, or interpreting every surprise as a personal message",
    orientation: "act appropriately from what is known and leave room for events you cannot engineer",
    structureInterpretation: "Thunder below initiates spontaneous movement while Heaven above supplies a strong, principled field. Quick I Ching reads the structure as action that begins naturally and remains answerable to something larger than private calculation. Movement stays sound when it responds directly to conditions rather than being distorted by manipulation or obsessive control.",
    reflectionQuestions: [
      "Which part of your plan depends on hidden leverage or assumptions that would not survive open examination?",
      "What event are you overinterpreting as a personal signal when it may simply be an external condition to meet appropriately?",
      "What straightforward action remains sound even if you cannot control how the situation responds afterward?",
    ],
    watchFor: [
      "A simple action producing cleaner information because nobody has to decode a hidden motive behind it.",
      "Unexpected events triggering elaborate stories about blame, fate, or secret intention instead of practical assessment.",
      "A situation becoming easier when effort shifts from controlling every outcome to doing the next appropriate thing well.",
    ],
    transitionTheme: "contrivance giving way to cleaner action and more direct contact with reality",
    stabilityTheme: "clarity of motive that remains steady when circumstances surprise you",
    lowerTrigram: "zhen",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Move from the first clean impulse",
        "The first line favors action whose motive does not need explanation to make it defensible. A straightforward opportunity may be present, and hesitation caused by strategic overthinking would add complication without adding wisdom. Begin where intention and conduct are aligned, then let real response provide the next information.",
        "Change here releases natural movement into the situation. The emerging pattern becomes trustworthy when the first step is simple enough to evaluate honestly: what happened, what changed, and what should follow can be seen without untangling a web of private tactics.",
        "Spontaneity is not permission to ignore obvious consequences. Clean motive must still meet practical reality. If the first step would predictably harm a boundary or responsibility, calling it ‘natural’ does not make it appropriate.",
        "What action would you take if you did not need it to prove anything, manipulate anyone, or guarantee the outcome in advance?",
        "Line 1 begins uncontrived action with a clean, defensible step whose consequences can be observed without hidden strategy.",
      ),
      authoredLine(
        "Cultivate without harvesting in advance",
        "The second line separates good work from premature claim on its reward. Sow, tend, and build because the work itself is appropriate, not because every effort must immediately secure a return. When attention stays with cultivation, quality improves and the future remains open instead of being forced to satisfy a calculation made too early.",
        "As this line changes, uncontrived effort becomes productive continuity. The emerging pattern grows from repeated work whose value can accumulate before outcomes are harvested. This creates resilience because motivation is not entirely hostage to short-term confirmation.",
        "Do not romanticize labor without feedback. Cultivation should still be evaluated for whether anything viable is growing. The caution is against demanding the harvest before the process matures, not against checking whether the field is alive.",
        "What work deserves to be done well now even though its eventual return cannot yet be guaranteed or claimed?",
        "Line 2 keeps attention on cultivation rather than premature reward, allowing appropriate work to mature before its harvest is demanded.",
      ),
      authoredLine(
        "An innocent party can still meet misfortune",
        "The third line makes an important distinction: trouble can arrive without proving that the person affected caused it. Loss, misunderstanding, or another person’s error may cross your path despite clean intention. The task is practical containment, not obsessive moral accounting. Determine what happened, protect what can be protected, and avoid inventing guilt simply to make the event feel controllable.",
        "Change here turns arbitrary disruption into a test of grounded response. The emerging pattern improves when the event is treated according to its actual cause and consequence rather than as evidence that every misfortune contains a personal lesson.",
        "The opposite error is refusing all responsibility because some harm is accidental. Investigate causality carefully. Innocence should be an evidence-based conclusion, not a defensive identity used to avoid anything uncomfortable.",
        "What part of this difficulty is genuinely yours to correct, and what part should be handled without turning it into a story of personal fault?",
        "Line 3 distinguishes undeserved trouble from self-caused error so response can follow evidence rather than a need to assign moral meaning to every event.",
      ),
      authoredLine(
        "Hold to what is correct without extra maneuvering",
        "The fourth line favors consistency when the basic course is already sound. Pressure may invite tactical changes, clever positioning, or attempts to secure certainty that the situation cannot offer. If conduct is appropriate and the boundary is clear, steadiness can be stronger than another layer of control.",
        "When this line changes, the reading tests whether simple correctness can survive wider conditions. The emerging pattern becomes more stable if the person does not abandon a sound standard merely because uncertainty makes contrivance emotionally attractive.",
        "Steadiness becomes stubbornness when new evidence changes the facts. Hold the principle, not a frozen tactic. A clean course remains responsive to reality even when it refuses manipulation.",
        "Which part of your current approach is already sound enough that adding another tactic would create more distortion than protection?",
        "Line 4 preserves an appropriate course under pressure, refusing unnecessary maneuvering while remaining open to genuine new evidence.",
      ),
      authoredLine(
        "Do not medicate an illness that is not yours",
        "The fifth line warns against frantic intervention when trouble arises without a clear causal link to your conduct. Not every disturbance needs a corrective act from you. Sometimes the cleanest response is to maintain ordinary health and allow an external irregularity to pass rather than introducing a remedy that creates new side effects.",
        "Change here reduces overcontrol. The emerging pattern benefits from waiting for clearer causality before acting. By refusing to treat every symptom as evidence of personal failure, attention remains available for the moment when a real intervention is justified.",
        "Non-intervention is not neglect. If evidence shows the problem is worsening or a responsibility is genuinely yours, act. The caution is specifically against treating uncertainty itself as a reason to prescribe a solution.",
        "What problem are you trying to fix mainly because doing nothing feels irresponsible, even though the evidence has not shown that your intervention is needed?",
        "Line 5 protects uncontrived action from unnecessary remedies, asking causality to become clear before intervention is added to the situation.",
      ),
      authoredLine(
        "Action taken after innocence has become rigidity",
        "At the top line, insistence on acting can itself become a form of contrivance. The person may be so attached to the identity of being straightforward or correct that they continue forward after conditions have stopped supporting movement. Innocence loses value when it refuses complexity and turns clean intention into a justification for imprudent action.",
        "Change here releases the need to act merely to preserve self-image. The emerging direction may be pause, revision, or acceptance that a previously sound approach has reached its limit. Restraint restores contact with reality.",
        "Do not treat good motives as protection from consequences. A person can be sincere and still be wrong about timing, capacity, or effect. When warning signs accumulate, humility matters more than consistency of posture.",
        "Where are you continuing mainly because admitting that conditions changed would threaten your image of having acted correctly from the start?",
        "Line 6 shows that uncontrived action must remain responsive; clean motive cannot rescue conduct that has become rigidly detached from present conditions.",
      ),
    ],
  },
  {
    number: 26,
    coreTheme: "Great restraint",
    coreMeaning: "Great restraint describes substantial force being stored, trained, and governed before release. Da Chu is not merely blockage. It is the productive containment that turns raw ability into capacity capable of carrying a serious task. The reading favors learning, discipline, reserves, and contact with standards larger than immediate impulse. Strong potential can be dangerous if released before it knows what it is for; it can also become sterile if preparation turns into a permanent identity. Each stage asks a different question: should movement stop, what mechanism needs control, what skill needs training, and when does the path finally open? The best restraint improves the quality of later action. It preserves energy without worshipping accumulation and releases strength when responsibility, timing, and competence make use preferable to further storage.",
    strength: "stored capacity strengthened through training and restraint",
    challenge: "premature release, pride in unused potential, or endless preparation without purpose",
    orientation: "develop capability, retain energy, and choose the moment when stored strength has a real task",
    structureInterpretation: "Heaven below supplies powerful creative force while Mountain above stops and contains it. Quick I Ching reads the structure as strength deliberately held beneath a boundary so it can accumulate quality rather than merely pressure. The mountain is useful only while containment produces training, reserve, and better timing.",
    reflectionQuestions: [
      "What capability is being improved by restraint rather than merely delayed by it?",
      "Which mechanism—habit, incentive, resource, or skill—must be brought under control before stronger action becomes safe?",
      "What would count as evidence that preparation has matured enough and further restraint would now become avoidance?",
    ],
    watchFor: [
      "Stored energy becoming more precise because practice, knowledge, or infrastructure improves during the delay.",
      "Potential becoming part of identity, with endless preparation replacing any willingness to test capability in reality.",
      "A previously blocked route opening after the relevant skill, control, or support has become genuinely reliable.",
    ],
    transitionTheme: "contained power becoming mature capacity ready for deliberate use",
    stabilityTheme: "continued training that makes restraint productive rather than merely restrictive",
    lowerTrigram: "qian",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Stop before danger makes the decision for you",
        "The first line meets a clear warning that forward force would be badly timed. Restraint is protective here, not developmental theater. The useful move is to stop early enough that capacity remains intact and the person still has room to learn why the path is dangerous.",
        "Change here converts an impulse to advance into preserved potential. The emerging pattern gains future options because energy is not spent proving it can push against a condition that has already signaled resistance.",
        "Fear can overgeneralize one warning into permanent avoidance. Stop because the present route is unsafe, then investigate what would need to change. The value lies in preserving capacity for a better opportunity, not in making non-action a virtue.",
        "What warning is clear enough that stopping now would preserve more strength than another attempt to push forward?",
        "Line 1 uses early restraint to preserve great capacity when the current route shows enough danger that force would be wasteful.",
      ),
      authoredLine(
        "Remove the axle before momentum runs away",
        "The second line restrains movement by disabling the mechanism that would carry it forward too easily. Willpower alone may not be enough when momentum is built into a habit, incentive, system, or access point. A structural brake can be wiser: remove the trigger, pause the process, or make rapid escalation physically harder.",
        "As this line changes, containment becomes engineered rather than merely intended. The emerging pattern is safer because restraint no longer depends on repeated heroic self-control. The system itself gives capacity time to mature.",
        "A brake can become a permanent obstruction if nobody defines how or when it will be restored. Build a review condition alongside the restraint so protection does not quietly become paralysis.",
        "What mechanism could you temporarily disable so this strong impulse cannot outrun judgment while capacity is still being trained?",
        "Line 2 makes restraint structural by removing the mechanism of premature movement rather than relying only on willpower.",
      ),
      authoredLine(
        "Train with the force instead of merely holding it",
        "The third line moves beyond simple containment into disciplined practice. Strong capacity should be exercised under controlled conditions so skill, coordination, and timing improve together. Training may include repeated drills, testing, or preparation that exposes weakness without risking the full consequence of real deployment.",
        "Change here turns stored power into practiced capability. The emerging pattern becomes ready for larger use because strength has learned how to move, stop, and respond under pressure instead of remaining impressive only in reserve.",
        "Practice can become another form of impatience if the exercises are too dangerous or designed mainly to simulate glory. Keep training scaled to learning. The purpose is feedback and mastery, not proving that full release is already deserved.",
        "What controlled practice would reveal whether this stored strength is becoming skilled enough for real conditions?",
        "Line 3 converts great restraint into disciplined training so stored power becomes practiced capability rather than untested potential.",
      ),
      authoredLine(
        "Control the dangerous point before it grows",
        "The fourth line uses an early restraint on the point where power could become harmful. A young force is easier to guide before its habits harden. The practical lesson is preventive design: shape the incentive, boundary, or behavior while correction is still small and the underlying energy can be redirected rather than suppressed.",
        "When this line changes, restraint becomes a source of safety and future freedom. The emerging pattern can carry more force because the dangerous mechanism has been managed before it matured into a recurring threat.",
        "Preventive control can become overprotection if it never relaxes as competence grows. The boundary should evolve with evidence. Otherwise a safeguard that once enabled development can later prevent it.",
        "What dangerous tendency can be shaped now while it is still small enough that correction will not require a fight?",
        "Line 4 manages the dangerous point early, allowing greater strength to develop safely because the main risk is addressed before it hardens.",
      ),
      authoredLine(
        "Transform the source of aggression, not only its expression",
        "The fifth line goes deeper than restraining visible force. Instead of repeatedly stopping the same dangerous behavior, change the source that keeps generating it. Incentives, unmet needs, access, status dynamics, or unmanaged drives may be redirected so the energy no longer needs constant external control.",
        "Change here makes restraint more mature because control is internalized or structurally transformed. The emerging pattern releases supervisory burden: strength becomes less dangerous not because guards are tighter but because the source has changed form.",
        "Do not mistake suppression for transformation. If pressure simply drives the force underground, the system may appear calm while risk accumulates. Look for observable change in the generating conditions, not only fewer visible incidents.",
        "What underlying incentive or drive keeps producing the behavior you are repeatedly trying to restrain, and how could that source be redirected?",
        "Line 5 matures restraint by transforming the source of dangerous force so safety depends less on repeated external control.",
      ),
      authoredLine(
        "The great path opens",
        "At the top line, restraint has completed its work. Capacity, timing, and structure have matured enough that the route is no longer a place to hold back. Release is appropriate because stored strength now has a real task and the means to carry it. The challenge shifts from containment to using the accumulated capability without clinging to the identity of preparation.",
        "Change here ends the training phase and opens full movement. The emerging pattern benefits from decisive use of what has been learned and stored. Delay no longer protects quality; it would begin to waste the very capacity restraint created.",
        "Preparation can become psychologically safer than deployment. Do not invent new requirements merely because action exposes capability to judgment. If the path is genuinely open, continued containment is no longer prudence.",
        "What evidence shows that the restraints have done their job and that the mature capacity now needs a real task rather than another round of preparation?",
        "Line 6 releases great restraint when training, timing, and structure have matured enough that the open path now rewards deliberate use of stored strength.",
      ),
    ],
  },
  {
    number: 27,
    coreTheme: "Nourishment",
    coreMeaning: "Nourishment asks what enters the system, what is repeatedly supplied, and whether those inputs actually sustain life, attention, capability, or relationship. Yi includes food but extends beyond it: information, conversation, money, recognition, routines, and care all become forms of nourishment when they are taken in or provided repeatedly. The reading favors discernment over appetite. A craving can be intense without being sustaining, and generous giving can still create dependence if it replaces another person’s own capacity. Look at the mouth in both directions: what are you consuming, and what are you asking others to consume from you? Improve quality before quantity. The strongest nourishment supports vitality and autonomy; the weakest merely feeds a pattern because it asks loudly, feels familiar, or rewards the provider with a sense of importance.",
    strength: "discernment about inputs, support, and what truly sustains",
    challenge: "feeding appetite rather than need, careless consumption, or giving in ways that create dependence",
    orientation: "examine what is being taken in and supplied, then improve the quality of nourishment",
    structureInterpretation: "Thunder below initiates appetite and movement while Mountain above forms the boundary of the mouth-like structure. Quick I Ching reads the combination as an active need held inside a container that must choose what enters and what leaves. Nourishment becomes a governance problem: appetite needs standards, and provision needs proportion.",
    reflectionQuestions: [
      "What are you repeatedly taking in that leaves you more agitated or dependent rather than more capable?",
      "Which form of support are you giving because it truly nourishes, and which because being needed is rewarding to you?",
      "What input or routine would improve the system’s own capacity to sustain itself instead of requiring repeated rescue?",
    ],
    watchFor: [
      "A change in inputs producing more stable energy, attention, or decision quality rather than only short-term satisfaction.",
      "Support being requested more often while the receiver becomes less able to function without it.",
      "A neglected source of real nourishment becoming visible once appetite and habit are separated from actual need.",
    ],
    transitionTheme: "poor inputs becoming sustainable support through better selection and provision",
    stabilityTheme: "habits of nourishment that reinforce vitality rather than short-term appetite",
    lowerTrigram: "zhen",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Do not abandon your own source for another person’s mouth",
        "The first line warns against neglecting an available inner resource while staring at what someone else possesses or consumes. Envy, comparison, and fascination can make a person forget the nourishment already within reach. The issue is not self-sufficiency in everything; it is failing to use your own capacity because another source looks more impressive.",
        "Change here returns attention to direct sources of nourishment. The emerging pattern becomes less dependent on comparison and more capable of asking what actually sustains you rather than what appears desirable from the outside.",
        "Do not use ‘look within’ as an excuse to refuse needed help. The warning concerns abandoning an adequate source because of fascination, not pretending every need can be met alone.",
        "What sustaining resource do you already have access to but overlook because another person’s source looks more attractive or prestigious?",
        "Line 1 restores nourishment to an available source instead of letting comparison make genuine capacity seem inadequate.",
      ),
      authoredLine(
        "Seeking nourishment in the wrong direction",
        "The second line describes dependence forming around an inappropriate source. The person may look upward or outward for support that should come from a more direct, ordinary, or reciprocal channel. This distorts both parties: one becomes dependent and the other carries a role that may not belong to them.",
        "As this line changes, nourishment can be rerouted toward a more sustainable relationship. The emerging pattern asks what source is naturally connected to the need and how support can be obtained without bypassing the structures that should normally carry it.",
        "A dramatic or powerful provider can feel safer than a modest local source, but distance and asymmetry can increase dependence. Do not choose support merely because it appears superior in status.",
        "Which need are you taking to an impressive but unsuitable source instead of strengthening the ordinary channel that should normally sustain it?",
        "Line 2 redirects nourishment away from an inappropriate dependency and toward the source naturally fitted to carry the need.",
      ),
      authoredLine(
        "A corrupted appetite cannot be fed into health",
        "The third line shows the object of nourishment itself becoming distorted. Appetite may repeatedly choose what weakens the system—information that inflames, habits that numb, relationships that reward dysfunction, or consumption that leaves capacity poorer. More of the same input will not repair the condition because the selection mechanism is part of the problem.",
        "Change here requires a break in the feeding cycle. The emerging pattern begins when the person stops treating desire as evidence of need and creates enough distance for a different appetite or source to become possible.",
        "Do not rely on moderation if the current input reliably destroys judgment about moderation. Some patterns require a clearer interruption and external structure before choice becomes trustworthy again.",
        "What are you repeatedly consuming or reinforcing even though the after-effect shows that the appetite itself is currently unreliable?",
        "Line 3 identifies corrupted appetite as the problem and interrupts the feeding cycle so selection can become trustworthy again.",
      ),
      authoredLine(
        "Look outward carefully for what can nourish the whole",
        "The fourth line permits seeking nourishment beyond the immediate source when the motive is responsible. A leader, caretaker, or system may need to look widely for resources because what is being sustained is larger than the self. Alertness matters: the search should be active without becoming predatory or indiscriminate.",
        "When this line changes, provision becomes outward-facing stewardship. The emerging pattern grows through finding and integrating resources that strengthen the wider field, not simply satisfying the provider’s appetite for acquisition.",
        "A search for resources can become extraction. Do not consume another system’s capacity in the name of feeding your own. Sustainable nourishment respects the source and the long-term relationship around it.",
        "What external resource could genuinely strengthen the whole you are responsible for, and what terms would keep the search from becoming extractive?",
        "Line 4 seeks nourishment outward for a larger responsibility while keeping acquisition alert, selective, and sustainable.",
      ),
      authoredLine(
        "Accept an unusual source while avoiding the great crossing",
        "The fifth line recognizes that ordinary self-sufficiency may not be available. Receiving nourishment from an unusual source can be correct if it preserves what matters, but this is not the time to take on an enormous independent venture. Dependence should be acknowledged plainly while capacity is rebuilt.",
        "Change here stabilizes support without pretending that full autonomy has already returned. The emerging pattern can strengthen gradually because the receiver is honest about limits and does not turn temporary assistance into evidence that every risk is now manageable.",
        "Pride may reject necessary support, while relief may encourage reckless expansion. Both ignore the actual condition. Use the nourishment for recovery and capacity, not for a dramatic proof of independence.",
        "What support should you accept without shame, and what large commitment should wait until that support has actually rebuilt your own capacity?",
        "Line 5 accepts necessary nourishment from an unusual source while postponing large risks until the receiver has genuinely regained capacity.",
      ),
      authoredLine(
        "Become a source others can draw from without exhausting it",
        "At the top line, nourishment is concentrated in a person, institution, or resource capable of sustaining many others. This position carries both value and danger. A great source should remain accessible enough to serve and protected enough not to be depleted. Stewardship now includes renewal of the source itself.",
        "Change here expands nourishment into public or systemic responsibility. The emerging pattern can support larger undertakings because a dependable source exists, but only if provision is governed by standards that keep the source viable over time.",
        "Being needed can become addictive. Do not allow the provider’s identity to depend on endless demand, and do not let recipients organize around permanent dependence when capability could be shared or developed.",
        "How can this strong source continue nourishing others while also renewing itself and increasing their capacity to stand without constant rescue?",
        "Line 6 turns nourishment into stewardship of a major source, balancing generous provision with renewal and the receiver’s growing autonomy.",
      ),
    ],
  },
  {
    number: 28,
    coreTheme: "Great excess",
    coreMeaning: "Great excess describes a structure carrying more than ordinary design can safely bear. Da Guo is not simply ‘a lot happening.’ The load is exceptional enough that normal habits may fail even when everyone works harder. The reading therefore asks where the beam is bending, which support is critical, and what must change structurally before strain becomes collapse. Extraordinary conditions can justify extraordinary measures, but those measures should remain tied to the emergency rather than becoming a permanent operating model. Sometimes an aging or depleted system can still produce surprising renewal; sometimes the load has reached a point where a difficult crossing is unavoidable. Courage matters, but heroic overcommitment is not the same as structural repair. Redistribute pressure, reinforce the essential span, and know when the exceptional arrangement must end.",
    strength: "the courage to recognize exceptional load and adjust structure accordingly",
    challenge: "normalizing overload, heroic overcommitment, or delaying a needed structural response",
    orientation: "identify where the load exceeds capacity and make a proportionate structural change",
    structureInterpretation: "Wind below penetrates the inner structure while Lake above adds openness and weight at the top; four strong yang lines are concentrated between weak outer supports. Quick I Ching reads the figure as a loaded beam whose center is powerful but whose ends are vulnerable. The problem is structural distribution, not lack of effort.",
    reflectionQuestions: [
      "Where is the current load exceeding designed capacity rather than merely requiring more effort?",
      "Which support point would create the greatest reduction in systemic risk if it were reinforced or relieved first?",
      "What emergency measure are you tempted to normalize even though it should have an explicit end condition?",
    ],
    watchFor: [
      "Repeated strain concentrating on the same support, showing that the problem is structural rather than motivational.",
      "People being praised for heroic overwork while the workload, staffing, or dependency that creates overload remains unchanged.",
      "An extraordinary adjustment reducing load enough that normal operation can eventually replace emergency mode.",
    ],
    transitionTheme: "dangerous strain becoming a survivable transition when support is redistributed in time",
    stabilityTheme: "ongoing load awareness that prevents exceptional pressure from becoming normal",
    lowerTrigram: "xun",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Prepare the ground with excessive care",
        "The first line accepts unusual caution because the load ahead is unusual. Before placing something heavy or consequential, improve the surface, redundancy, or preparation beyond what ordinary conditions would require. A small extra margin at the beginning can prevent a large failure later.",
        "Change here transforms anxiety about overload into preventive engineering. The emerging pattern gains resilience because exceptional risk is acknowledged before commitment, when adding protection is still relatively cheap.",
        "Do not let precaution become paralysis or ritual. Extra preparation should answer a specific load or failure mode. If nobody can explain what the margin protects against, caution may be substituting for decision.",
        "What extra preparation is justified by the exceptional load, and what specific failure would that margin prevent?",
        "Line 1 responds to great excess with deliberate extra preparation, adding margin before the heavy load is placed on the structure.",
      ),
      authoredLine(
        "Old capacity produces unexpected new growth",
        "The second line shows renewal appearing in a system that might have been assumed too old, depleted, or established to generate anything new. Under exceptional conditions, dormant capacity can become useful again. The opportunity is real precisely because it comes from a place others may have written off.",
        "As this line changes, overload does not only threaten collapse; it also reveals latent adaptive capacity. The emerging pattern can use unconventional pairings, revived resources, or renewed roles to carry pressure in a way the normal structure did not anticipate.",
        "Do not treat surprising renewal as proof that age, depletion, or prior limits no longer matter. New growth needs proportionate support. An exceptional recovery can be wasted by immediately loading it with the entire system’s unmet demand.",
        "What overlooked or supposedly exhausted capacity is showing signs of real renewal, and how can it be used without immediately overloading it?",
        "Line 2 finds regenerative capacity inside great excess, using unexpected renewal carefully rather than treating it as unlimited rescue.",
      ),
      authoredLine(
        "The main beam bends",
        "The third line identifies the classic danger of Great Excess: the central support itself is failing under load. This is not the moment for motivational language or cosmetic reinforcement. If the primary load-bearing element is bending, demand must be reduced, redistributed, or structurally redesigned before the failure becomes irreversible.",
        "Change here forces a shift from endurance to intervention. The emerging pattern becomes survivable only if the system stops assuming the main support can absorb more. Repair may be disruptive because the current load path is no longer trustworthy.",
        "Do not ask the strongest person or component to ‘hold a little longer’ merely because it has always carried the most. Central strength can hide approaching failure until the remaining margin is small.",
        "What load-bearing person, process, or resource is already bending, and what must move off it before another demand is added?",
        "Line 3 treats a bending primary support as a structural emergency, requiring load reduction or redesign rather than more endurance.",
      ),
      authoredLine(
        "Reinforce the beam without creating hidden dependency",
        "The fourth line finds a workable reinforcement. Additional support can stabilize the overloaded structure and allow the necessary task to continue. The key is that the reinforcement genuinely changes the load path. Help that merely makes the main support work harder does not count as reinforcement.",
        "When this line changes, emergency adaptation becomes functional structure. The emerging pattern gains time and resilience because pressure is shared more intelligently. This can create a bridge toward a more permanent redesign.",
        "Support can come with conditions that create a new vulnerability. Do not stabilize one failure point by making the whole system dependent on a helper whose incentives, capacity, or availability are uncertain.",
        "What reinforcement would actually change the distribution of load rather than simply encourage the overloaded part to keep carrying it?",
        "Line 4 stabilizes great excess by adding real structural support while checking that the new reinforcement does not become another hidden failure point.",
      ),
      authoredLine(
        "Late display without durable renewal",
        "The fifth line shows something old producing a visible flourish that may be attractive but does not necessarily restore long-term capacity. Under exceptional strain, a system can generate one impressive success, late partnership, or symbolic renewal while its deeper demographic or structural problem remains unchanged. Appreciate the bloom without mistaking it for a full reset.",
        "Change here clarifies the difference between a bright episode and durable regeneration. The emerging pattern becomes more realistic when short-term success is allowed to be valuable on its own terms rather than being burdened with a promise it cannot keep.",
        "Do not dismiss the late bloom simply because it is temporary, but do not build a long-range plan on it without evidence of repeatable support. Symbolic success can delay necessary structural decisions if it is overinterpreted.",
        "What recent success is genuinely valuable but too limited to prove that the deeper structural strain has been solved?",
        "Line 5 distinguishes a meaningful late flourish from durable renewal so exceptional success is not mistaken for structural recovery.",
      ),
      authoredLine(
        "Crossing beyond ordinary safety",
        "At the top line, the situation may require moving through danger so deep that ordinary caution cannot remove the risk. A person can choose a difficult crossing because the purpose matters, even while knowing the cost may be high. The line respects commitment but does not turn it into a guarantee of success.",
        "Change here ends the overloaded configuration through a decisive passage. The emerging direction may only become possible after accepting that the old structure cannot be made completely safe. Courage becomes the willingness to act with eyes open, not denial of danger.",
        "Heroism can become a way of avoiding the earlier structural lesson. Do not choose extreme sacrifice when load could still be redistributed. A dangerous crossing is appropriate only after the safer structural options have genuinely been exhausted.",
        "What purpose could justify accepting exceptional risk here, and what evidence shows that structural alternatives have truly been exhausted first?",
        "Line 6 accepts a dangerous crossing only when the exceptional purpose and exhausted alternatives justify moving beyond ordinary safety without pretending the risk has disappeared.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
