import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 29,
    coreTheme: "Repeated danger",
    legacySummary: "Risk or uncertainty recurs. Reliability comes from learning the terrain, keeping to sound practice, and moving without denying the danger.",
    strength: "reliable practice under recurring uncertainty",
    challenge: "panic, denial, or improvising differently every time the same risk returns",
    orientation: "respect the hazard, use proven procedures, and keep moving one sound step at a time",
    transitionTheme: "repeated exposure becoming competence when experience improves practice",
    stabilityTheme: "steadiness built through consistent methods rather than false certainty",
    lowerTrigram: "kan",
    upperTrigram: "kan",
    lineEmphases: [
      "identify the first hazard clearly instead of relying on optimism",
      "use a proven practice to move through recurring risk one step at a time",
      "avoid panic or improvisational bravado when the same danger tightens again",
      "carry disciplined risk awareness into a wider and less controllable environment",
      "use a central position to normalize reliable procedure rather than fear",
      "leave the dangerous cycle when experience shows a sound exit instead of proving endurance",
    ],
  },
  {
    number: 30,
    coreTheme: "Clarity and attachment",
    legacySummary: "Illumination depends on what it is attached to. Choose sound objects of attention and make distinctions clearly without becoming consumed by brightness or certainty.",
    strength: "clear discrimination joined to the ability to sustain attention",
    challenge: "fixation, dazzling certainty, or attaching clarity to an unworthy object",
    orientation: "clarify what deserves attention and keep insight connected to reality and responsibility",
    transitionTheme: "confusion becoming usable clarity through right attachment and careful distinction",
    stabilityTheme: "illumination sustained by repeatedly checking what your attention serves",
    lowerTrigram: "li",
    upperTrigram: "li",
    lineEmphases: [
      "choose the first object of attention carefully because clarity depends on its attachment",
      "make discrimination steady enough to illuminate ordinary decisions",
      "question dazzling certainty when pressure makes one explanation seem irresistibly bright",
      "carry insight outward while checking whether the wider context supports it",
      "use visible clarity to help others see distinctions without demanding agreement",
      "release an attachment to certainty when the light it gave has become fixation",
    ],
  },
  {
    number: 31,
    coreTheme: "Influence",
    legacySummary: "Mutual responsiveness can change the situation without coercion. Notice what genuinely moves you and others, and keep influence reciprocal rather than manipulative.",
    strength: "sensitivity to reciprocal influence and subtle response",
    challenge: "manipulation, seduction by reaction, or assuming responsiveness equals agreement",
    orientation: "notice what moves the relationship and keep influence voluntary, mutual, and proportionate",
    transitionTheme: "separate positions becoming responsive without losing their integrity",
    stabilityTheme: "influence sustained through sincerity and freedom rather than pressure",
    lowerTrigram: "gen",
    upperTrigram: "dui",
    lineEmphases: [
      "notice the first genuine response without trying to manufacture it",
      "let mutual influence develop through ordinary reciprocity and consent",
      "slow down when attraction or reaction creates pressure for premature conclusions",
      "bring responsiveness into the wider relationship without turning it into leverage",
      "use visible influence with restraint so others remain free to respond",
      "stop amplifying a connection when influence has become self-reinforcing or manipulative",
    ],
  },
  {
    number: 32,
    coreTheme: "Duration",
    legacySummary: "Continuity matters more than a burst of effort. Choose a course that can be maintained while allowing methods to adapt as circumstances change.",
    strength: "commitment that can persist through changing conditions",
    challenge: "rigidity, inconsistency, or confusing stubborn repetition with endurance",
    orientation: "choose a durable direction and let methods adapt without abandoning the underlying commitment",
    transitionTheme: "short-lived effort becoming continuity through repeatable practice and adaptive discipline",
    stabilityTheme: "a stable course renewed by flexible methods rather than fixed routines",
    lowerTrigram: "xun",
    upperTrigram: "zhen",
    lineEmphases: [
      "choose a first step that can actually be repeated over time",
      "turn commitment into a durable practice rather than a temporary burst",
      "adapt methods when pressure exposes rigidity without abandoning the underlying direction",
      "carry continuity into changing outer conditions by adjusting form rather than purpose",
      "use a central role to model persistence that remains responsive to evidence",
      "end a long-standing pattern when endurance has become mere repetition without value",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
