import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 29,
    coreTheme: "Repeated danger",
    coreMeaning: "Repeated danger describes a situation in which uncertainty or risk is not a one-time interruption but part of the terrain. Kan asks for reliability under recurrence. The goal is not to pretend the hazard has disappeared; it is to learn the contours well enough that each passage becomes less improvised. Good practice, honest risk recognition, and a stable inner standard matter more than dramatic courage. Repeated danger can create panic, numbness, or the temptation to invent a new method every time discomfort returns. The reading favors continuity: use what has proven sound, update it when evidence requires, and maintain the ability to move one step at a time. At the deepest point, escape may be temporarily unavailable; even there, accurate recognition of the constraint prevents false moves from making the trap worse.",
    strength: "reliable practice under recurring uncertainty",
    challenge: "panic, denial, or improvising differently every time the same risk returns",
    orientation: "respect the hazard, use proven procedures, and keep moving one sound step at a time",
    structureInterpretation: "Water below and Water above repeat the same trigram of depth, danger, and passage. Quick I Ching reads the doubled structure as recurrence: risk is not incidental to the situation. Reliability comes from learning how to move through a repeated condition without either denying it or letting fear redesign the method every time.",
    reflectionQuestions: [
      "Which part of this danger is recurring enough that it should now have a standard procedure rather than another improvised response?",
      "What practice has actually helped you move through this terrain before, and where does it still need refinement?",
      "Where are fear or fatigue tempting you to abandon a sound method simply because the hazard has returned again?",
    ],
    watchFor: [
      "The same hazard becoming less disorganizing because preparation and response are more consistent.",
      "Panic or boredom causing a proven safety practice to be skipped precisely because the risk feels familiar.",
      "A credible exit or shallower route appearing after enough experience reveals the terrain more accurately.",
    ],
    transitionTheme: "repeated exposure becoming competence when experience improves practice",
    stabilityTheme: "steadiness built through consistent methods rather than false certainty",
    lowerTrigram: "kan",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Falling into the pit within the pit",
        "The first line begins repeated danger badly: the person is not merely near a hazard but slipping into a deeper pattern of it. Familiarity may have reduced attention, or the first response may be adding another layer of risk. The immediate task is to stop the downward sequence rather than prove that normal movement can continue.",
        "Change here creates the possibility of arresting compounding danger. The emerging pattern improves when the person acknowledges the depth, simplifies commitments, and returns to the most basic safety practice before considering progress.",
        "Do not normalize a repeated hazard because it has happened before. Each additional layer can reduce future options. The desire to ‘get through quickly’ is especially dangerous when the route is already deteriorating.",
        "What action is currently deepening the danger rather than helping you move through it, and what is the simplest way to stop that sequence?",
        "Line 1 interrupts compounding danger by recognizing when a familiar hazard has become a deeper pit and returning to basic safety.",
      ),
      authoredLine(
        "Seek only a small gain inside danger",
        "The second line is inside real risk but still has room to make modest progress. Large ambitions would expose too much; a small objective can preserve movement without pretending the field is safe. The measure of success is not distance covered but whether the next position is more stable than the present one.",
        "As this line changes, repeated danger becomes manageable through incremental passage. The emerging pattern trusts a sequence of limited gains that can be verified before the next is attempted. Small progress accumulates practical knowledge about the terrain.",
        "Do not let frustration with modest gains provoke a leap whose downside cannot be absorbed. Inside danger, scale matters. A smaller move that preserves options can be strategically superior to a bold move that depends on everything going right.",
        "What is the smallest meaningful improvement you can secure without increasing exposure beyond what the current position can absorb?",
        "Line 2 advances through danger by securing a limited, verifiable gain rather than demanding a dramatic escape before the terrain allows it.",
      ),
      authoredLine(
        "Danger ahead and behind calls for stillness",
        "The third line finds hazard on both sides. Forward movement is risky, retreat may also be risky, and agitation can make the person bounce between two bad choices. This is a moment to stop and study the structure rather than letting urgency choose the direction. Stillness can preserve the remaining room for judgment.",
        "Change here shifts the problem from motion to orientation. The emerging pattern may reveal a third route, a timing change, or a support that was invisible while attention was trapped in the forward-versus-backward dilemma.",
        "Stopping is useful only if it gathers information. Freezing from fear can allow conditions to worsen without producing clarity. Define what you are waiting to learn and how long the current position remains viable.",
        "What information or support could create a third option when both advancing and retreating currently appear dangerous?",
        "Line 3 pauses between dangers so urgency does not force a choice before the structure has been understood well enough to reveal another route.",
      ),
      authoredLine(
        "Simple sincerity reaches through the narrow opening",
        "The fourth line shows that even inside danger, a modest and sincere exchange can create access. There may be no room for elaborate ceremony, bargaining, or display. A simple offering, clear message, or direct request can be enough to establish trust when the circumstances are constrained.",
        "When this line changes, a narrow channel becomes usable. The emerging pattern relies on transparency and proportion: small, credible contact can connect people across a difficult boundary and reduce isolation inside the hazardous situation.",
        "Do not overload a narrow opening with too many requests or promises. The channel is valuable because it is credible and manageable. Trying to make it carry the whole problem at once can close it.",
        "What simple, honest exchange could open a useful channel here without requiring either side to pretend the danger is smaller than it is?",
        "Line 4 uses modest, sincere contact to open a narrow but credible channel inside a constrained and dangerous situation.",
      ),
      authoredLine(
        "The pit is not yet full, but the level is rising",
        "The fifth line suggests danger is approaching a manageable level without being completely resolved. The situation may be stabilizing enough that ordinary passage becomes imaginable, but declaring safety too early would be a mistake. Continue the practices that have reduced the depth and watch whether improvement holds under real use.",
        "Change here moves repeated danger toward a shallower, more navigable condition. The emerging pattern gains confidence gradually as the hazard stops dominating every decision. Recovery is measured by restored options, not by emotional relief alone.",
        "A period of improvement can produce premature relaxation. Do not abandon the method that created stability before the terrain has actually changed enough to make those safeguards unnecessary.",
        "What evidence would show that the danger has become genuinely shallower rather than merely feeling less frightening because you have adapted to it?",
        "Line 5 recognizes improving conditions while keeping the proven safeguards in place until restored options demonstrate that the hazard has truly receded.",
      ),
      authoredLine(
        "Bound by a danger that no longer offers an easy exit",
        "At the top line, repeated danger has become a severe constraint. Choices made earlier, institutional limits, or accumulated consequences may have narrowed the available exits. The reading does not pretend that a clever move can instantly undo the bind. First acknowledge the confinement accurately and stop adding violations that extend it.",
        "Change here begins through acceptance of consequence and restoration of basic order. The emerging direction may be slow: serving a required period, rebuilding trust, or waiting for conditions that cannot be accelerated. Reality, not dramatic escape, becomes the path out.",
        "Desperation can invite another risky shortcut that deepens the bind. When options are already narrow, false escape routes are especially costly. Use whatever limited agency remains to prevent the confinement from becoming worse.",
        "What constraint cannot currently be escaped, and what behavior can keep you from extending or deepening it while time and responsibility do their work?",
        "Line 6 faces severe confinement without fantasy, using limited agency to stop further deterioration until a real exit can eventually become possible.",
      ),
    ],
  },
  {
    number: 30,
    coreTheme: "Clarity and attachment",
    coreMeaning: "Clarity and attachment describe illumination that depends on what attention is attached to. Li is fire: bright, useful, and unable to exist without something to burn. The reading therefore asks not only whether you can see clearly, but what your clarity serves. A sharp mind attached to a false premise can intensify error; a compelling explanation can become fixation if it stops receiving evidence. Good illumination distinguishes, compares, and remains connected to reality and responsibility. It can help others see without demanding that everyone accept the same interpretation. The six lines move from confused first impressions through stable brightness, mortality and emotional reaction, sudden flare, sorrow that restores proportion, and finally decisive removal of the source of disorder. Clarity is mature when it can illuminate a problem without becoming consumed by the brightness of its own certainty.",
    strength: "clear discrimination joined to the ability to sustain attention",
    challenge: "fixation, dazzling certainty, or attaching clarity to an unworthy object",
    orientation: "clarify what deserves attention and keep insight connected to reality and responsibility",
    structureInterpretation: "Fire below and Fire above double the trigram of illumination and attachment. Each Li trigram has a yielding center held by firm outer lines, suggesting clarity that depends on relation rather than isolated self-sufficiency. Quick I Ching reads the doubled structure as sustained illumination whose quality depends on repeatedly checking the object and purpose of attention.",
    reflectionQuestions: [
      "What assumption or object is your current clarity attached to, and what happens if that attachment is wrong?",
      "Which distinction has become clearer through evidence rather than merely through repetition of one explanation?",
      "Where is brightness becoming fixation—making contradictory evidence harder to see rather than easier?",
    ],
    watchFor: [
      "A confusing situation becoming easier to distinguish because attention is attached to observable facts and consequences.",
      "One explanation becoming emotionally dazzling enough that alternatives are dismissed before they are examined.",
      "Insight spreading usefully because it helps others make distinctions without forcing them into the same conclusion.",
    ],
    transitionTheme: "confusion becoming usable clarity through right attachment and careful distinction",
    stabilityTheme: "illumination sustained by repeatedly checking what your attention serves",
    lowerTrigram: "li",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Confused tracks at first light",
        "The first line begins with multiple traces, impressions, or possible directions before clarity has organized them. The correct response is careful attention rather than rapid synthesis. Respect the mess of early evidence enough to inspect it before deciding which pattern is real.",
        "Change here turns scattered impressions into the beginnings of discrimination. The emerging pattern improves as observations are sorted, compared, and attached to a question precise enough that irrelevant brightness no longer competes for attention.",
        "Do not force coherence merely because ambiguity is uncomfortable. Early certainty can make later evidence invisible. But endless collection is also a danger; the purpose of careful observation is eventually to distinguish, not to worship complexity.",
        "Which early signals are you prematurely combining into one story, and what would you learn by keeping them separate a little longer?",
        "Line 1 begins clarity by respecting the disorder of first impressions long enough to distinguish real tracks from an invented pattern.",
      ),
      authoredLine(
        "Yellow light holds the center",
        "The second line represents balanced illumination: clear enough to guide action, moderate enough not to dazzle. Attention is centered on what is relevant, and judgment does not need dramatic certainty to feel secure. This is clarity that can be used in ordinary decisions because it remains proportionate.",
        "As this line changes, insight becomes dependable practice. The emerging pattern benefits from a stable interpretive center that can receive new evidence without swinging between confusion and overconfidence.",
        "Moderation should not become blandness that refuses necessary distinctions. Balanced clarity can still say that one option is better supported than another. The key is confidence proportional to evidence.",
        "What would a well-centered conclusion look like if confidence matched the quality of the evidence rather than the intensity of your feeling?",
        "Line 2 establishes usable clarity in the center, keeping illumination bright enough to guide while moderate enough to remain corrigible.",
      ),
      authoredLine(
        "The setting sun tests how you meet decline",
        "The third line recognizes that brightness has a cycle. A period, role, relationship, or phase of capability is moving toward decline, and the response can become either frantic denial or bitter resignation. Clear sight includes mortality and ending. The task is to remain present enough to use what light remains without pretending the cycle can be stopped.",
        "Change here transforms fear of decline into a more mature relationship with time. The emerging pattern can preserve meaning by allowing completion, gratitude, and adjustment to replace the demand that peak conditions continue indefinitely.",
        "Do not turn awareness of ending into premature abandonment. The sun is setting, not already gone. There may still be useful work, conversation, or enjoyment available before the phase actually closes.",
        "What is clearly declining, and how could you use the remaining light well without either denying the ending or ending it too early?",
        "Line 3 brings clarity to decline itself, asking for presence and proportion as a bright phase moves toward its natural ending.",
      ),
      authoredLine(
        "A sudden flare arrives and burns out",
        "The fourth line shows intensity without continuity. An idea, person, opportunity, or emotion may appear brilliantly and demand immediate attention, yet its very speed can make it unstable. Sudden brightness is information, not proof of enduring value. Observe what remains after the flare loses heat.",
        "When this line changes, the reading separates momentary intensity from sustained illumination. The emerging pattern becomes more reliable if decisions are based on what survives repeated exposure rather than on the first dramatic impression.",
        "Do not build a durable commitment around an experience whose primary evidence is how strongly it arrived. Conversely, do not dismiss every sudden insight; test it after the emotional or social heat has passed.",
        "What in this sudden bright development still looks valuable after you remove urgency, novelty, and emotional intensity from the evaluation?",
        "Line 4 treats a sudden flare as something to test for durability before allowing its intensity to determine a lasting commitment.",
      ),
      authoredLine(
        "Grief restores proportion to clarity",
        "The fifth line places illumination inside sorrow. Tears and concern can be appropriate when clear sight reveals loss, responsibility, or the limits of control. Emotional response does not automatically cloud judgment; it can restore humanity to an analysis that had become too detached or triumphant.",
        "Change here integrates feeling and discernment. The emerging pattern becomes more trustworthy because clarity is no longer defended against the human cost of what is seen. Grief can narrow attention to what truly matters.",
        "Emotion can also become self-absorption. Let sorrow inform responsibility, not monopolize it. The goal is neither coldness nor endless mourning but a clearer sense of what the situation requires.",
        "What loss or consequence needs to be felt honestly before your understanding of this situation can become fully proportionate?",
        "Line 5 lets grief deepen illumination, bringing emotional truth into a central judgment without surrendering discernment.",
      ),
      authoredLine(
        "Use clarity to remove the source of disorder",
        "At the top line, illumination supports decisive action against the source of a larger disturbance. The emphasis is selective: identify the principal cause, remove what drives the disorder, and avoid treating every subordinate part as equally culpable. Clarity allows force to discriminate.",
        "Change here converts understanding into a final corrective act. The emerging pattern can restore order because attention is directed at the generating source rather than dispersed across symptoms or secondary participants.",
        "A strong diagnosis can still become a purge if certainty outruns evidence. Do not expand responsibility beyond what the facts support. Decisive removal should narrow disorder, not create a new cycle of indiscriminate blame.",
        "What is the primary source of the disorder, and which secondary elements should be corrected or released rather than treated as equally responsible?",
        "Line 6 completes clarity by directing decisive correction at the main source of disorder while keeping responsibility carefully differentiated.",
      ),
    ],
  },
  {
    number: 31,
    coreTheme: "Influence",
    coreMeaning: "Influence describes mutual responsiveness: something moves you, you move something else, and the quality of the relationship depends on how freely that response occurs. Xian is not coercion. Its power is subtle because real influence enters through sensitivity, attraction, example, and reciprocal adjustment. The lines progress through the body—from toes and calves toward the heart, neck, and mouth—showing different degrees of impulse, stability, and expression. A first reaction may be too slight to act on; a stronger attraction may need restraint before it becomes reliable. Mature influence stays connected to intention and does not manipulate another person’s response for proof of power. At the outermost point, words alone can simulate influence without substance. The reading asks what genuinely moves the relationship and whether both sides remain free enough that responsiveness can still count as evidence rather than compliance.",
    strength: "sensitivity to reciprocal influence and subtle response",
    challenge: "manipulation, seduction by reaction, or assuming responsiveness equals agreement",
    orientation: "notice what moves the relationship and keep influence voluntary, mutual, and proportionate",
    structureInterpretation: "Mountain below provides stillness and boundary while Lake above opens to exchange and pleasure. Quick I Ching reads the combination as responsiveness arising because firmness and openness are both present. Influence becomes trustworthy when attraction can be felt without erasing the boundary that keeps response voluntary.",
    reflectionQuestions: [
      "What response in yourself or another person is genuinely spontaneous, and what response may be produced by pressure or expectation?",
      "Where does attraction need enough stillness that you can tell whether it represents a durable alignment or only immediate reaction?",
      "What influence are you trying to produce with words that would be more credible if it were carried by conduct instead?",
    ],
    watchFor: [
      "A relationship becoming more responsive without either side needing to increase pressure or performance.",
      "Attraction, fear, or approval-seeking creating quick movement before intention and boundaries are clear.",
      "Words becoming more persuasive because they are confirming an influence already demonstrated through behavior.",
    ],
    transitionTheme: "separate positions becoming responsive without losing their integrity",
    stabilityTheme: "influence sustained through sincerity and freedom rather than pressure",
    lowerTrigram: "gen",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "A first movement in the toes",
        "The first line registers influence at its earliest and weakest point. Something has caught attention or created an impulse to move, but the response is not yet substantial enough to justify a large interpretation. Notice the reaction without forcing it to become a decision.",
        "Change here turns a faint signal into information that can be watched over time. The emerging pattern becomes clearer if the first response is allowed to repeat, deepen, or disappear before commitment is attached to it.",
        "Do not treat every spark of attraction, discomfort, or interest as a message that requires action. Early bodily or emotional response is useful data, but its meaning remains underdetermined.",
        "What has begun to move you only slightly, and what would need to repeat before that reaction deserves a larger decision?",
        "Line 1 treats the first stir of influence as a signal to observe rather than a command to act before the response has substance.",
      ),
      authoredLine(
        "The calves want to move before the whole person is ready",
        "The second line feels a stronger urge to move, but the impulse may still be ahead of integrated judgment. Attraction or pressure can create restlessness that wants immediate contact, commitment, or withdrawal. Remaining still for a time allows the response to recruit more than instinct.",
        "As this line changes, influence can become more coordinated. The emerging pattern benefits from letting intention, values, and practical conditions catch up with the initial urge before the body carries the person into consequence.",
        "Restraint should not become chronic indecision. The point is to wait long enough for the response to become whole, not to suppress it until every feeling disappears. If alignment persists after reflection, movement can be more trustworthy.",
        "What urge feels strong enough to notice but not yet integrated enough to act on, and what would help the rest of your judgment catch up?",
        "Line 2 restrains a strong early impulse until the wider self can decide whether the movement deserves to become action.",
      ),
      authoredLine(
        "Following the thighs follows another person’s movement",
        "The third line warns about influence becoming imitation. Instead of responding from a clear center, the person moves because someone else moves, desires because someone else desires, or changes direction because the relationship itself has become the guide. The result can feel intimate while weakening independent judgment.",
        "Change here separates responsiveness from mimicry. The emerging pattern becomes healthier when the person can feel another’s influence without automatically reproducing it. A pause restores the ability to choose which response genuinely belongs to you.",
        "Do not call all adaptation ‘loss of self.’ Relationships naturally shape behavior. The problem is unexamined following, especially when your action cannot be explained without referring to what the other person did first.",
        "Which current choice is primarily following someone else’s movement, and what would you choose if their behavior stopped being the reference point?",
        "Line 3 protects mutual influence from becoming imitation by restoring an independent center inside the relationship.",
      ),
      authoredLine(
        "Steady intention makes influence trustworthy",
        "The fourth line reaches a position where influence can become strong and far-reaching if intention remains stable. Repeatedly changing whom or what you are trying to move creates anxious calculation; consistency allows others to understand the direction and respond freely. Influence becomes credible because it is not constantly chasing reaction.",
        "When this line changes, subtle responsiveness develops into a durable pattern of mutual adjustment. The emerging direction benefits from staying with a sound intention long enough for the relationship to organize around it without manipulation.",
        "Persistence can become obsession if the goal shifts from expressing a stable intention to monitoring every reaction it produces. Do not turn influence into a feedback addiction. The other side’s freedom remains part of the test.",
        "What intention is worth expressing consistently without tracking every response as proof that your influence is working?",
        "Line 4 makes influence trustworthy through steady intention, reducing anxious manipulation and allowing the other side freedom to respond.",
      ),
      authoredLine(
        "Influence that reaches the back of the neck",
        "The fifth line shows a subtle influence that is real but not centered in overt desire or display. The response may be quiet, embodied, and difficult to manipulate consciously. This can be stabilizing because the relationship is less dependent on dramatic signs. What matters is whether the subtle alignment produces consistent conduct over time.",
        "Change here brings influence toward a more integrated central role. The emerging pattern trusts quiet, repeatable response rather than seeking constant emotional confirmation. Connection becomes less noisy and potentially more durable.",
        "Subtlety can invite projection. Do not assume another person feels what you feel merely because the relationship seems quietly aligned. Keep room for explicit communication where consequences depend on consent or agreement.",
        "What quiet, repeated behavior provides better evidence of genuine influence here than dramatic expressions or verbal reassurance would?",
        "Line 5 values subtle, embodied influence when it produces consistent conduct while still leaving important assumptions open to explicit confirmation.",
      ),
      authoredLine(
        "Influence reduced to jaw, cheeks, and tongue",
        "At the top line, influence risks becoming mostly verbal. Persuasion, charm, explanation, or performance may continue after the deeper responsiveness of the relationship has weakened. Words can still matter, but they cannot substitute indefinitely for conduct, trust, or genuine mutual movement.",
        "Change here strips influence back to substance. The emerging direction asks whether behavior, structure, or shared experience can carry what speech has been trying to accomplish. If not, more talking may only make the absence of deeper influence more obvious.",
        "Do not dismiss communication as superficial merely because this line warns about speech. The caution is against speech without supporting reality. Honest words can also acknowledge that influence is limited instead of pretending otherwise.",
        "What are you trying to accomplish through persuasion that would be more credible if it were demonstrated through conduct or accepted as beyond your control?",
        "Line 6 exposes the limit of verbal influence and redirects attention toward the conduct, trust, and mutual response that words cannot manufacture by themselves.",
      ),
    ],
  },
  {
    number: 32,
    coreTheme: "Duration",
    coreMeaning: "Duration is continuity that can survive changing circumstances. Heng does not mean repeating the same behavior forever. It asks for a durable direction supported by practices flexible enough to adapt when methods, roles, or environments change. A commitment that begins too rigidly may fail because it demands permanence before reality has tested it; a commitment that changes with every mood never becomes reliable enough to build on. The reading favors rhythm, review, and consistency of purpose. Duration becomes visible through ordinary repeated conduct, not through dramatic vows. It can also end: a pattern that has become empty repetition may need release precisely to preserve fidelity to the deeper purpose. Sustainable continuity therefore combines memory and adaptation—knowing what must remain, what can change, and when persistence has ceased to serve the thing it once protected.",
    strength: "commitment that can persist through changing conditions",
    challenge: "rigidity, inconsistency, or confusing stubborn repetition with endurance",
    orientation: "choose a durable direction and let methods adapt without abandoning the underlying commitment",
    structureInterpretation: "Wind below works through gradual persistence while Thunder above supplies recurring movement. Quick I Ching reads the combination as continuity created by repeated movement along a stable direction. Duration is dynamic: methods may shift, but the relation between persistence and renewed action keeps the course coherent through time.",
    reflectionQuestions: [
      "What is the durable direction beneath the routine, and which parts of the routine are only current methods?",
      "Where is inconsistency preventing trust from accumulating because others cannot predict whether the commitment will still exist tomorrow?",
      "What repeated practice has outlived the value it once served and now needs to change so the deeper purpose can continue?",
    ],
    watchFor: [
      "A commitment becoming easier to trust because it survives ordinary changes without needing renewed dramatic promises.",
      "Rigid method being defended as loyalty even after evidence shows it is undermining the original purpose.",
      "A sustainable rhythm emerging in which renewal and adjustment occur without making the whole direction unstable.",
    ],
    transitionTheme: "short-lived effort becoming continuity through repeatable practice and adaptive discipline",
    stabilityTheme: "a stable course renewed by flexible methods rather than fixed routines",
    lowerTrigram: "xun",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Do not demand permanence at the beginning",
        "The first line warns against digging too deeply for duration before a pattern has had time to establish itself. Early intensity can impose commitments, routines, or expectations that are too heavy for what is still being tested. Sustainable continuity usually starts lighter and earns depth through repetition.",
        "Change here relaxes premature rigidity. The emerging pattern becomes more durable because the beginning is allowed to learn before every detail is made permanent. Commitment grows from demonstrated fit rather than from pressure to guarantee the future immediately.",
        "Do not use gradual commitment as an excuse to avoid any real obligation. The point is proportional depth, not indefinite ambiguity. Establish enough consistency that the relationship or practice can actually be tested.",
        "What are you trying to make permanent before it has had enough ordinary experience to prove what form of commitment it can sustain?",
        "Line 1 protects duration from premature rigidity by letting depth grow from repeated fit rather than demanding permanence at the outset.",
      ),
      authoredLine(
        "Regret disappears when the course becomes proportionate",
        "The second line finds duration settling into a workable center. Previous uncertainty or overcorrection can fade because the commitment now matches capacity and circumstance. There is less need to revisit the decision constantly; ordinary consistency begins to carry it.",
        "As this line changes, continuity becomes less effortful. The emerging pattern benefits from a course that no longer requires emotional recommitment every day. Stability comes from fit between purpose, method, and available capacity.",
        "Comfort with the course should not eliminate review. A stable pattern can still drift slowly. Keep enough feedback that the commitment remains alive rather than becoming automatic in a way that hides changing conditions.",
        "What part of this commitment has finally become proportionate enough that you can stop repeatedly questioning it and simply practice it?",
        "Line 2 shows duration becoming an ordinary, workable center where continuity no longer depends on constant emotional recommitment.",
      ),
      authoredLine(
        "Inconstancy undermines dignity and trust",
        "The third line shows a person repeatedly changing conduct in a way that makes commitment hard to trust. The problem is not adaptation itself but the absence of a stable principle beneath the changes. Others cannot know what will persist, and the person’s own sense of integrity begins to erode.",
        "Change here asks for a dependable core. The emerging pattern improves when variation in method is explicitly tied to a consistent purpose, allowing flexibility without making every pressure point a reason to abandon the course.",
        "Do not respond to accusations of inconsistency by becoming rigid in the wrong thing. The correction is to clarify the enduring standard, not to promise that no method or opinion will ever change.",
        "What stable principle could make your recent changes intelligible as adaptation rather than look like a series of unrelated reversals?",
        "Line 3 restores credibility by placing changing methods under a principle stable enough that others can recognize what the commitment actually is.",
      ),
      authoredLine(
        "Persistence in an empty field produces nothing",
        "The fourth line warns that duration alone cannot make an unsuitable field productive. Repeated effort may be perfectly consistent yet still directed where the needed resource, opportunity, or response is absent. Persistence should include periodic tests of whether the environment can support the purpose.",
        "When this line changes, continuity becomes capable of relocating or changing method. The emerging pattern preserves the deeper commitment by refusing to waste it on a field that repeatedly proves barren.",
        "Sunk cost can make an empty field feel sacred because so much time has already been invested there. Do not confuse the duration of effort with evidence that the location or method deserves more.",
        "What have you pursued consistently for a long time without evidence that this particular field can ever provide what the purpose requires?",
        "Line 4 distinguishes endurance from futile repetition, allowing a durable purpose to move away from a field that has repeatedly proved empty.",
      ),
      authoredLine(
        "Duration must fit the role and responsibility",
        "The fifth line asks how constancy operates within a particular role. Endurance is not identical for every person or position: one role may require steady receptivity, another active leadership, and another periodic change. A durable commitment must be shaped by the actual responsibilities attached to the position rather than by a generic ideal of persistence.",
        "Change here aligns continuity with function. The emerging pattern becomes more sustainable because the form of endurance matches what the role genuinely asks instead of copying someone else’s model of constancy.",
        "Role language can be used to freeze unequal or outdated expectations. Test whether the responsibility is legitimate and current. Duration should serve a real function, not preserve a role merely because it is traditional.",
        "What does constancy actually require in your present role, and which inherited expectation should not be mistaken for an enduring responsibility?",
        "Line 5 makes duration role-specific, sustaining the responsibilities that remain legitimate without turning inherited form into permanent obligation.",
      ),
      authoredLine(
        "Restless persistence destroys duration",
        "At the top line, the person tries to maintain continuity through constant movement, adjustment, or agitation. Nothing is allowed to settle long enough to become durable. Activity is mistaken for commitment, so the course repeatedly renews its surface while losing the stable rhythm that duration requires.",
        "Change here releases compulsive motion. The emerging direction can become steadier by reducing interventions, allowing a tested practice to run, and distinguishing necessary adaptation from anxiety-driven change.",
        "Stillness can become complacency if conditions truly require revision. The correction is not ‘never change’ but ‘stop changing merely to manage discomfort.’ Let evidence, not restlessness, trigger the next adjustment.",
        "What are you repeatedly changing because staying with a sound routine feels emotionally too quiet, uncertain, or slow?",
        "Line 6 shows that duration cannot be manufactured through constant agitation; continuity needs enough stillness for a sound rhythm to become real.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
