import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 33,
    coreTheme: "Retreat",
    legacySummary: "Stepping back can preserve position and clarity when direct engagement is unproductive. Withdrawal is strongest when it is timely, orderly, and purposeful.",
    strength: "strategic distance that protects clarity and resources",
    challenge: "flight disguised as strategy, delayed withdrawal, or retreat that leaves obligations in chaos",
    orientation: "step back deliberately from what cannot be productively engaged and preserve what matters",
    transitionTheme: "unproductive engagement becoming protected space for a better-positioned next move",
    stabilityTheme: "clear boundaries that keep distance purposeful rather than fearful",
    lowerTrigram: "gen",
    upperTrigram: "qian",
    lineEmphases: [
      "create the first useful distance before conflict or entanglement consumes more resources",
      "make withdrawal orderly enough to preserve relationships, options, and self-respect",
      "retreat before pressure turns a strategic step back into a panicked escape",
      "carry clear boundaries into the outer field so distance is understood rather than guessed",
      "use a strong position to disengage without humiliation, revenge, or needless display",
      "stop retreating once distance has restored perspective and a constructive re-entry is possible",
    ],
  },
  {
    number: 34,
    coreTheme: "Great power",
    legacySummary: "Capacity is high, which makes restraint more important. Use strength in proportion to the situation and avoid turning capability into unnecessary pressure.",
    strength: "strong capacity under conscious restraint",
    challenge: "bullying, overreach, or acting simply because power is available",
    orientation: "use only the amount of strength the situation actually requires",
    transitionTheme: "raw power becoming legitimate influence when disciplined by proportion",
    stabilityTheme: "strength that remains credible because it does not need constant demonstration",
    lowerTrigram: "qian",
    upperTrigram: "zhen",
    lineEmphases: [
      "test the first use of power for necessity rather than for the pleasure of exerting it",
      "make strength dependable by keeping it under proportionate self-command",
      "reduce force when resistance is tempting you to prove capability instead of solve the problem",
      "bring power into the wider field with enough restraint to avoid creating new opposition",
      "use central strength to protect standards and capacity rather than dominate weaker positions",
      "recognize when further assertion would turn legitimate power into excess or isolation",
    ],
  },
  {
    number: 35,
    coreTheme: "Progress",
    legacySummary: "Visibility and forward movement are increasing. Use the opening to contribute clearly, build trust, and keep advancement connected to real value.",
    strength: "momentum, visibility, and the opportunity to contribute more",
    challenge: "chasing recognition, mistaking visibility for value, or outrunning support",
    orientation: "advance through useful contribution and make each gain strengthen the next stage",
    transitionTheme: "movement becoming durable progress when visibility is matched by substance",
    stabilityTheme: "forward motion maintained by value creation rather than status alone",
    lowerTrigram: "kun",
    upperTrigram: "li",
    lineEmphases: [
      "use the first gain in visibility to contribute something concrete",
      "turn early progress into reliable value before seeking the next advance",
      "notice when pressure for recognition is outrunning the substance beneath the progress",
      "carry momentum into a wider audience while keeping expectations tied to evidence",
      "use a central opening to advance others and the work, not only your own standing",
      "prepare for a change in pace when progress has reached a visible peak",
    ],
  },
  {
    number: 36,
    coreTheme: "Brightness concealed",
    legacySummary: "An unfavorable environment may punish open display. Protect insight, stay inwardly clear, and choose carefully how much of your position to reveal.",
    strength: "inner clarity that does not require public display",
    challenge: "needless exposure, bitterness, or hiding so completely that judgment also dims",
    orientation: "protect what is true and reveal only what the environment can safely hold",
    transitionTheme: "exposed insight becoming guarded clarity until conditions permit fuller expression",
    stabilityTheme: "inner standards preserved even when outer conditions reward something else",
    lowerTrigram: "li",
    upperTrigram: "kun",
    lineEmphases: [
      "protect the first vulnerable insight when the environment cannot receive it safely",
      "keep inner clarity alive through ordinary conduct that does not attract needless exposure",
      "avoid letting concealment become bitterness, paranoia, or loss of your own standard",
      "enter the outer field selectively, revealing only what the context can hold without distortion",
      "use a central position to preserve truth quietly when open display would provoke damage",
      "leave concealment behind when protection has become habitual after conditions have changed",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
