import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 33,
    coreTheme: "Retreat",
    coreMeaning: "Retreat is strategic distance taken before a deteriorating situation controls the terms of departure. Dun does not glorify flight. It asks whether engagement still serves the purpose and whether withdrawal can preserve people, integrity, information, or capacity for a better time. Different stages of retreat carry different costs. Delay can leave the trailing edge exposed; attachment can make separation difficult; a clear and voluntary withdrawal can become surprisingly powerful because it prevents the opponent or circumstance from dictating the next move. The reading favors explicit boundaries and orderly disengagement. Retreat should have a purpose and, where appropriate, conditions for re-entry. The strongest withdrawal does not need revenge, theatrical defeat, or a story that engagement was always a mistake. It simply recognizes when distance now protects what continued contact would consume.",
    strength: "the ability to create strategic distance before pressure consumes options",
    challenge: "flight without purpose, delayed withdrawal, or leaving obligations in chaos",
    orientation: "disengage deliberately, preserve what matters, and make the boundary understandable",
    structureInterpretation: "Mountain below stops and forms an inner boundary while Heaven above moves strongly away and upward. Quick I Ching reads the structure as disciplined disengagement: stillness at the base gives strong movement a clean direction outward rather than letting retreat become panic.",
    reflectionQuestions: [
      "What are you trying to preserve through distance, and would continued engagement actually protect it better?",
      "Which obligation must be settled before withdrawal can be orderly rather than simply transferred to someone else?",
      "What future condition would justify re-entry, and what would show that permanent separation is the wiser boundary?",
    ],
    watchFor: [
      "Options shrinking because withdrawal keeps being delayed while pressure gains control over timing.",
      "A clear boundary reducing conflict because both sides finally understand what engagement will and will not continue.",
      "Distance restoring perspective, capacity, or dignity that had been repeatedly consumed inside the original interaction.",
    ],
    transitionTheme: "engagement becoming protected distance before circumstances force a worse exit",
    stabilityTheme: "boundaries maintained for a purpose rather than from fear or bitterness",
    lowerTrigram: "gen",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "The tail is still exposed",
        "The first line catches retreat late enough that the rear of the movement remains vulnerable. Starting a new venture or provocative move while still disentangling from the old situation would increase exposure. The priority is to complete the withdrawal and reduce the number of commitments that can be caught behind.",
        "Change here turns a poorly timed retreat into safer separation. The emerging pattern improves as the trailing obligations are gathered and the person stops creating new reasons to remain connected to the danger.",
        "Do not accelerate so abruptly that people, responsibilities, or information are abandoned without handoff. Haste can convert a necessary retreat into avoidable damage that follows you into the next phase.",
        "What unfinished obligation is still exposed at the rear of this retreat, and what must be closed before you start anything new?",
        "Line 1 protects the vulnerable tail of a late retreat by finishing disengagement before adding another commitment or confrontation.",
      ),
      authoredLine(
        "Attachment binds the retreat",
        "The second line shows withdrawal complicated by a strong bond, promise, or dependency. Separation cannot be accomplished by simply declaring distance because something real still ties the parties together. The task is to identify the binding element and negotiate it directly rather than pretending the retreat is already complete.",
        "As this line changes, attachment becomes an explicit term of separation. The emerging pattern can create real distance once the bond is honored, transferred, repaid, or consciously released instead of left as an invisible tether.",
        "Do not cut a serious bond casually in the name of freedom, but do not use loyalty to justify endless exposure. A binding commitment deserves clarity about its limits and completion conditions.",
        "What specific bond is keeping this retreat incomplete, and how can it be honored or resolved without preserving the entire unwanted relationship?",
        "Line 2 makes the binding attachment explicit so retreat can respect a real obligation without remaining trapped by it indefinitely.",
      ),
      authoredLine(
        "A constrained retreat carries strain",
        "The third line is trying to withdraw while responsibilities or dependents remain close. Distance is needed, but complete separation is not immediately possible. The result can be exhausting because the person must preserve a boundary while still carrying limited duties inside the old field.",
        "Change here turns entanglement into managed distance. The emerging pattern benefits from narrowing responsibilities to what is truly necessary and refusing extra commitments that would make partial retreat permanent.",
        "Resentment can make essential care feel like captivity, while guilt can turn limited duties back into total involvement. Define the remaining responsibility precisely and do not let either emotion expand it.",
        "Which responsibilities genuinely have to travel with you during retreat, and which are being kept only through guilt, habit, or fear of judgment?",
        "Line 3 manages an imperfect retreat by carrying only essential obligations while preventing partial responsibility from recreating full entanglement.",
      ),
      authoredLine(
        "Voluntary retreat is easier for the clear-minded",
        "The fourth line shows someone who can choose distance before being compelled. Because the withdrawal is deliberate, the person can leave without hatred and preserve dignity. Others may find the same separation harder if their identity or advantage depends on continued engagement, but that does not invalidate the boundary.",
        "When this line changes, retreat becomes an expression of self-command. The emerging pattern gains freedom because the person no longer needs the other side to agree that distance is justified before taking it.",
        "Do not confuse emotional detachment with moral superiority. A clean retreat should reduce unnecessary entanglement, not become a performance of being above those who remain affected.",
        "What boundary can you choose freely now, before circumstances become severe enough to choose it for you?",
        "Line 4 makes retreat voluntary and self-directed, preserving dignity because distance is chosen before compulsion removes the remaining options.",
      ),
      authoredLine(
        "A graceful retreat preserves relationships",
        "The fifth line gives withdrawal a central, composed quality. The person can step back while remaining clear, courteous, and trustworthy. There is no need to humiliate the other side or rewrite the entire history as failure. A well-handled ending can preserve future respect even when present engagement no longer works.",
        "Change here turns retreat into a durable boundary rather than an active feud. The emerging pattern benefits from explicit terms, completed responsibilities, and a tone that makes renewed contact possible if conditions truly change.",
        "Grace should not soften the boundary into ambiguity. Kindness is compatible with a firm no. If the other party interprets courtesy as invitation to resume the old pattern, clarify again without escalating hostility.",
        "How can you make this withdrawal unmistakable while leaving behind as little humiliation, resentment, or unnecessary damage as possible?",
        "Line 5 completes a graceful retreat through firm terms and respectful conduct, preserving future dignity without weakening the boundary.",
      ),
      authoredLine(
        "Spacious retreat without inner conflict",
        "At the top line, withdrawal is complete enough that the person no longer feels divided about it. Distance creates space rather than deprivation because the old engagement has stopped defining what must happen next. This is retreat at its freest: little needs to be defended, explained, or avenged.",
        "Change here releases the retreat itself as an active project. The emerging direction can use the recovered space for new work or a different form of engagement rather than continuing to organize life around what was left behind.",
        "Freedom can turn into avoidance if every future difficulty is answered with distance. The lesson is not that retreat is always superior, but that this particular withdrawal has completed its purpose and need not remain an identity.",
        "What becomes possible once you stop spending attention on justifying, monitoring, or emotionally revisiting the retreat you have already completed?",
        "Line 6 ends retreat as a conflict and converts the recovered distance into open capacity for whatever deserves attention next.",
      ),
    ],
  },
  {
    number: 34,
    coreTheme: "Great power",
    coreMeaning: "Great power describes real capability that is already strong enough to alter the situation. Da Zhuang therefore shifts the question from whether you can act to whether force is necessary, proportionate, and governable. Power becomes most dangerous when it is used to prove that it exists. Early force can rush ahead through the ‘toes’; stubborn force can become trapped like horns in a fence; disciplined power can finally move effectively because it no longer wastes itself on resistance. The reading favors self-command, legal or ethical boundary, and selective use of strength. Great power should protect standards, create room for useful action, and then relax when pressure is no longer required. If every disagreement becomes an occasion to display strength, capacity turns into isolation. Mature power remains able not to use itself.",
    strength: "substantial capacity that can act decisively under restraint",
    challenge: "bullying, overreach, or using force merely because it is available",
    orientation: "apply power only where the situation genuinely requires it and keep force under self-command",
    structureInterpretation: "Heaven below supplies concentrated strength while Thunder above releases it into movement. Quick I Ching reads this as power already charged for action. Because momentum is easy to generate, the central discipline is restraint: force should follow judgment rather than become the judge.",
    reflectionQuestions: [
      "What action is necessary because of the situation, and what action would exist mainly to demonstrate capability or authority?",
      "Where is strong force becoming less effective because resistance, pride, or escalation is consuming it?",
      "What boundary would prove that this power remains under self-command rather than being driven by the need to win?",
    ],
    watchFor: [
      "A strong position becoming more effective after unnecessary displays of force are removed.",
      "Resistance increasing because pressure is being applied where a smaller or more legitimate intervention would work better.",
      "The moment when a previously blocked force gains a clear route and can move without attacking the boundary itself.",
    ],
    transitionTheme: "raw power becoming legitimate influence through restraint and right use",
    stabilityTheme: "strength that remains credible because it does not need constant display",
    lowerTrigram: "qian",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Power rushing through the toes",
        "The first line places strength in the impulse to move before the rest of judgment has joined it. The capacity is real, but acting from the first urge makes power crude and exposed. Hold long enough for purpose, consequence, and authority to catch up with the desire to advance.",
        "Change here keeps strong momentum from becoming premature commitment. The emerging pattern improves when force is gathered into a whole-person decision rather than released from the most impatient part of the system.",
        "Do not interpret restraint as evidence that strength is weak or unavailable. The danger lies precisely in having enough power to create consequences before the decision has matured.",
        "What strong impulse should wait until your wider judgment can explain why the action is necessary and proportionate?",
        "Line 1 restrains power at its first impulse so strength does not rush ahead of the judgment needed to govern it.",
      ),
      authoredLine(
        "Steady central power avoids regret",
        "The second line holds substantial capability in a balanced position. There is no need for display because strength is available when required. Consistency, preparedness, and proportion make the power more credible than a dramatic show would. The situation benefits from knowing the capacity exists without being forced to feel it constantly.",
        "As this line changes, power becomes dependable influence. The emerging pattern gains trust because force is connected to a stable standard rather than mood. Others can anticipate how authority will respond under pressure.",
        "Quiet power can still become complacent. Keep capability maintained and standards explicit. Restraint is credible only if the system can actually act when the boundary is crossed.",
        "How can you make strong capability reliably available without using repeated displays to remind everyone that it exists?",
        "Line 2 centers great power in preparedness and proportion, making restraint credible because action remains available when genuinely needed.",
      ),
      authoredLine(
        "The inferior person uses force; the mature person governs it",
        "The third line contrasts brute use of power with disciplined restraint. Under pressure, the temptation is to solve the problem by applying more strength directly. This can make strong capability behave like stubborn horns: force goes forward because stopping would feel like weakness, not because forward movement is wise.",
        "Change here separates courage from aggression. The emerging pattern becomes stronger when the person can tolerate not using maximum force and can search for the point where leverage, timing, or a different angle makes strength useful rather than trapped.",
        "Do not moralize restraint into passivity. There are times when force is necessary. The test is whether it solves the problem or merely satisfies the emotional need to push back against resistance.",
        "Where are you using strength mainly because resistance offends you, and what alternative would make the same capacity more effective?",
        "Line 3 distinguishes governed power from brute assertion, refusing to let resistance itself determine how much force is used.",
      ),
      authoredLine(
        "The fence opens when power stops fighting it",
        "The fourth line finds release after restraint. A barrier that previously caught or opposed strong force can open once timing, structure, or approach changes. Power becomes useful because it has a route rather than an enemy. This is the moment to move through the opening without wasting energy on the fact that resistance existed before.",
        "When this line changes, stored strength converts into effective progress. The emerging pattern may carry heavy responsibility because the force is finally aligned with a path that can support it. Movement becomes productive instead of oppositional.",
        "Do not celebrate the opening by accelerating beyond what the new route can carry. Freedom from one barrier does not remove every limit. Continue to govern scale as momentum returns.",
        "What obstacle has become passable because the approach or timing changed, and how can you use the opening without turning release into another excess?",
        "Line 4 lets great power move effectively once the fence opens, redirecting strength from opposition into a route that can actually carry it.",
      ),
      authoredLine(
        "Let go of the ram without regret",
        "The fifth line suggests that strength no longer needs to be held in a combative posture. A source of aggressive pressure can be released without loss. The central position is secure enough that identity does not depend on keeping every symbol of power close or maintaining readiness for a fight that is ending.",
        "Change here turns power into easier stewardship. The emerging pattern reduces defensive burden by letting a no-longer-needed force, role, or posture leave. Capacity remains, but it is less organized around confrontation.",
        "Do not disarm a necessary protection merely because conflict fatigue makes peace attractive. Release is wise when the threat or requirement has truly changed, not when you simply want relief from carrying responsibility.",
        "What defensive force or combative posture can you release now because your position no longer depends on maintaining it?",
        "Line 5 shows mature power letting go of an unnecessary combative resource without treating release as loss of strength.",
      ),
      authoredLine(
        "Horns caught where neither advance nor retreat works",
        "At the top line, force has become entangled with resistance. Pushing harder deepens the trap, yet retreat also feels humiliating or mechanically difficult. The solution is not another surge but recognition that the mode of engagement itself must change. Accepting the impasse creates room for a different route.",
        "Change here breaks the identification between power and forward motion. The emerging direction may involve waiting, negotiation, disassembly of the obstacle, or a lateral move. Strength regains usefulness when it stops trying to solve the trap by repeating the action that created it.",
        "Frustration can provoke reckless escalation just to end the feeling of being stuck. Do not convert an impasse into a catastrophe for the sake of decisive appearance. A temporary inability to move is less damaging than force applied blindly.",
        "What would you try if neither pushing harder nor retreating in shame were allowed to define the options?",
        "Line 6 releases great power from an impasse by changing the mode of engagement rather than repeating force against the same trap.",
      ),
    ],
  },
  {
    number: 35,
    coreTheme: "Progress",
    coreMeaning: "Progress describes increasing visibility and forward movement when useful contribution meets receptive conditions. Jin is not only advancement in rank. Its healthier measure is whether what becomes more visible also becomes more valuable, accountable, and capable of carrying wider expectations. Early progress may be uneven or misunderstood; recognition can arrive later after repeated contribution proves itself. A central opening can allow rapid advancement, but visibility also exposes unresolved weaknesses and attracts new demands. The reading favors using momentum without becoming dependent on status. Let progress bring more of the work into the light, help capable people advance, and prepare for the fact that every bright phase changes. At the outer limit, pushing progress through force can produce regret because movement has stopped being supported by the same receptive field that made advancement possible.",
    strength: "forward momentum that increases visibility and contribution",
    challenge: "chasing recognition, confusing status with progress, or advancing faster than support allows",
    orientation: "use the opening to contribute visibly and let advancement follow demonstrated value",
    structureInterpretation: "Earth below provides a receptive field while Fire above rises in visibility like the sun over the ground. Quick I Ching reads the structure as illumination advancing across a field ready to receive it. Progress is therefore relational: visibility grows because contribution meets conditions that can recognize and carry it.",
    reflectionQuestions: [
      "What has become more valuable or useful as visibility increases, apart from the fact that more people now notice it?",
      "Which expectation is growing faster than the support, process, or capability needed to fulfill it?",
      "How could your progress create advancement for others rather than becoming a private contest for recognition?",
    ],
    watchFor: [
      "Useful contribution receiving wider recognition after it has demonstrated repeatable value.",
      "Status markers advancing while the underlying process, capability, or quality begins to lag behind.",
      "A period of high visibility starting to attract demands that require a different operating structure than the earlier phase.",
    ],
    transitionTheme: "visibility increasing when useful contribution finds conditions ready to receive it",
    stabilityTheme: "progress anchored in value and preparation rather than status alone",
    lowerTrigram: "kun",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Progress checked at the beginning",
        "The first line tries to advance but does not yet receive full trust or recognition. This is not necessarily a verdict on the value of the work. Early progress often lacks enough evidence for others to commit. Maintain integrity, continue producing what can be verified, and do not let the absence of immediate recognition distort the offering.",
        "Change here converts frustrated advancement into credibility-building. The emerging pattern becomes stronger as the work accumulates evidence independent of approval. Trust can then arrive without having been pressured into existence.",
        "Do not retaliate against skepticism or become performatively indifferent. Early doubt may be useful information about what has not yet been demonstrated. But avoid redesigning the whole purpose simply to win immediate acceptance.",
        "What evidence can you continue building even if recognition remains slower than the quality of the work feels it deserves?",
        "Line 1 keeps early progress grounded in integrity and evidence when recognition has not yet caught up with the contribution.",
      ),
      authoredLine(
        "Progress with sorrow finds support",
        "The second line advances while carrying disappointment, isolation, or emotional weight. Progress does not always feel triumphant. A supportive connection may appear from a more senior, distant, or unexpected source, reminding the person that recognition and care can arrive even when the immediate environment feels cold.",
        "As this line changes, advancement becomes less solitary. The emerging pattern can integrate support without making emotional relief the sole proof that progress is real. The work and the relationship strengthen each other.",
        "Do not let one supportive person become the entire foundation for progress. Receive encouragement, but continue building practical capacity and wider evidence. Emotional rescue is not a substitute for structure.",
        "What support could help you continue through the emotionally difficult part of progress without making the work dependent on one person’s reassurance?",
        "Line 2 allows support to accompany difficult progress while keeping advancement grounded in the work rather than in emotional rescue alone.",
      ),
      authoredLine(
        "Trust from the group removes regret",
        "The third line shows progress becoming socially credible. Others begin to support, endorse, or coordinate with the direction, reducing the friction of proving every step alone. Collective trust matters because advancement can now carry more than one person’s ambition.",
        "Change here converts individual progress into shared movement. The emerging pattern gains resilience as responsibility and confidence distribute across the group instead of remaining concentrated in the original advocate.",
        "Group approval can become echo-chamber validation. Make sure support reflects observed value and not merely social conformity. A larger coalition increases the importance of dissent that can still reach the center.",
        "What has the group now seen repeatedly enough that its support represents evidence rather than simply enthusiasm or loyalty?",
        "Line 3 turns progress into shared credibility when collective support grows from demonstrated value rather than social pressure.",
      ),
      authoredLine(
        "Advancement by furtive accumulation is unstable",
        "The fourth line warns about progress gained through hoarding, opportunism, hidden maneuvering, or behavior that thrives in the gaps of oversight. Advancement may occur, but it lacks legitimacy and therefore creates fear about exposure. Visibility becomes dangerous because the method cannot survive inspection.",
        "When this line changes, progress is forced toward transparency. The emerging pattern can become stable only if gains are converted into defensible contribution and hidden tactics are stopped. What cannot be explained cleanly should not be the basis of future advancement.",
        "Do not assume every private strategy is unethical; discretion has legitimate uses. The warning is about progress whose advantage depends on others not seeing how it was obtained or whose gains are extracted from the system without reciprocal value.",
        "Which part of this advancement would become difficult to defend if the method were fully visible to the people affected by it?",
        "Line 4 exposes unstable progress built through hidden accumulation and redirects advancement toward methods that can survive visibility.",
      ),
      authoredLine(
        "Central progress does not need to count every gain and loss",
        "The fifth line stands in a strong advancing position and can stop overreacting to each small fluctuation. When the larger direction is sound, temporary gains and losses need not control confidence. Attention can remain on the responsibilities of the central role and the value being created through continued progress.",
        "Change here makes advancement less emotionally volatile. The emerging pattern can support broader influence because decisions are no longer being made from every short-term signal. Perspective allows consistent investment in what matters.",
        "Ignoring small losses is wise only when they do not reveal a structural problem. Do not use ‘long-term perspective’ to dismiss recurring evidence that the model is weakening. Track trends even while refusing to panic over noise.",
        "Which short-term gain or loss are you giving too much influence over a direction that should be judged on a broader horizon?",
        "Line 5 stabilizes central progress by keeping short-term fluctuations in proportion while remaining alert to evidence of real structural change.",
      ),
      authoredLine(
        "Using horns to force progress at the limit",
        "At the top line, advancement has reached a point where force is being used to obtain more progress after receptive conditions have weakened. Strong action may still be justified inside a limited sphere—for example, correcting one’s own territory—but pushing outward simply because expansion has been successful can create regret.",
        "Change here ends the assumption that progress must continue in the same direction. The emerging pattern may consolidate gains, correct local weaknesses, or accept a plateau rather than turning advancement into conquest.",
        "Momentum can make stopping feel like decline. Do not launch another expansion merely to preserve the identity of being in progress. At the limit, consolidation can be the more advanced decision.",
        "Where should progress turn inward toward consolidation or correction instead of using force to extend the advance one step further?",
        "Line 6 recognizes the limit of outward progress and redirects strong effort toward consolidation or local correction before expansion becomes coercive.",
      ),
    ],
  },
  {
    number: 36,
    coreTheme: "Brightness concealed",
    coreMeaning: "Brightness concealed describes preserving clarity when displaying it openly would invite unnecessary harm. Ming Yi is not a celebration of secrecy. It asks how truth, judgment, or integrity can survive inside a field that currently punishes direct illumination. Sometimes the wise response is to lower visibility, simplify expression, and keep the inner standard intact until conditions change. The lines distinguish different kinds of concealment: quick protection after injury, accepting practical rescue, correcting the source of harm when possible, leaving a dangerous center after understanding it, preserving principle under oppressive authority, and finally watching false brightness collapse under its own excess. The challenge is to hide the light without extinguishing it. Bitterness, paranoia, or permanent withdrawal would let the hostile environment reshape the very clarity being protected.",
    strength: "the ability to protect inner clarity when display would create unnecessary danger",
    challenge: "reckless exposure, bitterness, or hiding so completely that judgment itself dims",
    orientation: "keep the inner standard clear and reveal only what conditions can safely receive",
    structureInterpretation: "Fire below places illumination inside while Earth above covers and absorbs it. Quick I Ching reads the structure as brightness under concealment: the light remains real but cannot currently govern the outer field openly. Wisdom lies in preserving the source of clarity until expression becomes safer or strategically necessary.",
    reflectionQuestions: [
      "What truth or capability needs protection because open display would create more harm than useful change right now?",
      "How can you preserve access to honest feedback so concealment does not turn into isolation, bitterness, or self-deception?",
      "What specific change in conditions would make a more open expression of the inner standard worth the risk?",
    ],
    watchFor: [
      "A person preserving clear internal standards while becoming more selective about where and how they are expressed.",
      "Protective concealment hardening into cynicism, withdrawal, or a refusal to test whether conditions have changed.",
      "A credible opportunity to expose or correct the source of harm without sacrificing the protected core unnecessarily.",
    ],
    transitionTheme: "exposed insight becoming guarded clarity until conditions can receive it safely",
    stabilityTheme: "inner standards preserved without requiring public recognition or display",
    lowerTrigram: "li",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Lower the wings at the first sign of injury",
        "The first line senses danger early and reduces visibility quickly. A person may need to leave, decline attention, or accept temporary hardship rather than remain exposed where the light has become a target. The retreat can look like lost status while actually preserving freedom and judgment.",
        "Change here converts public brightness into protected movement. The emerging pattern gains survival capacity because the person stops asking the hostile field to validate what is already known inwardly.",
        "Do not dramatize every criticism as persecution. Concealment is justified by credible risk, not discomfort with disagreement. Maintain enough contact with reality to distinguish danger from ordinary correction.",
        "What exposure could you reduce now to protect the work or principle without abandoning it?",
        "Line 1 lowers visibility early so clarity can survive a hostile field without confusing temporary concealment with surrender of the underlying purpose.",
      ),
      authoredLine(
        "Injury is real; accept the horse that can carry you out",
        "The second line has already been hurt, but a practical means of rescue remains available. Speed and support matter more than pride. Accept transportation, assistance, cover, or a straightforward resource that can remove you from the dangerous position before the injury deepens.",
        "As this line changes, concealment becomes recovery. The emerging pattern uses concrete support to restore mobility and reduce exposure. The rescue need not solve the whole hostile environment; it only needs to carry the injured part to safety.",
        "Do not reject help because dependence feels inconsistent with strength. At the same time, verify that the rescuer does not create a new controlling obligation. Emergency support should increase freedom after the immediate danger passes.",
        "What practical help could move you out of the harmful position faster than trying to prove you can recover there alone?",
        "Line 2 accepts practical rescue after injury, using available support to restore mobility before exposure creates deeper damage.",
      ),
      authoredLine(
        "Correct the source of darkness without expecting instant reform",
        "The third line creates an opportunity to confront a major source of the harmful conditions. A decisive correction may be possible, but removing one leader, rule, or mechanism does not instantly heal the whole environment. The surrounding habits and dependencies need time to reorganize.",
        "Change here turns protected clarity into targeted intervention. The emerging pattern can reduce harm significantly if action remains focused on the source rather than becoming a campaign against everyone associated with the old order.",
        "Do not mistake a successful intervention for completed transformation. Power vacuums, inherited habits, and fear can reproduce the same darkness in a new form. Plan for the slower work after the decisive correction.",
        "If the main source of harm can be corrected, what slower cultural or structural work will still be necessary afterward?",
        "Line 3 permits targeted correction of a major source of harm while refusing the fantasy that one decisive act instantly transforms the whole environment.",
      ),
      authoredLine(
        "Understand the dark center, then leave it",
        "The fourth line gets close enough to the center of the problem to understand how it actually works. This knowledge can be disturbing but clarifying. Once the mechanism is seen, continued presence may no longer be necessary or safe. Leave with the insight rather than remaining inside merely because access has finally been gained.",
        "When this line changes, concealed understanding becomes strategic exit. The emerging direction preserves knowledge that can guide future boundaries, warnings, or repair without requiring ongoing immersion in the harmful center.",
        "Curiosity and influence can make dangerous systems seductive. Do not stay simply because understanding grants a sense of special access. Knowledge becomes less valuable if the environment gradually normalizes what you originally recognized as harmful.",
        "What have you learned by getting close to the center of this problem that now makes departure more useful than continued observation?",
        "Line 4 turns intimate knowledge of the harmful center into a reason for informed exit rather than prolonged exposure.",
      ),
      authoredLine(
        "Preserve the inner standard under hostile authority",
        "The fifth line concerns clarity maintained inside an oppressive or distorted power structure. Open confrontation may be impossible or strategically foolish, but inward agreement is not required. The person protects principle through careful conduct, selective speech, memory, and refusal to let the outer regime redefine what is known to be true.",
        "Change here makes concealment an ethical discipline rather than simple fear. The emerging pattern preserves continuity of values until conditions allow them to be expressed more openly or carried into a safer context.",
        "Long concealment can damage the person if no truthful relationship or private record remains. Find some protected channel through which reality can still be named. Otherwise survival may gradually become assimilation.",
        "What protected practice, relationship, or record would help you preserve the inner standard without exposing it to a power that cannot currently receive it safely?",
        "Line 5 makes concealment a disciplined preservation of principle under hostile authority, keeping truth alive without demanding suicidal display.",
      ),
      authoredLine(
        "False brightness rises high and then falls into darkness",
        "At the top line, a power that once appeared brilliant or dominant has carried its distortion to an extreme. The same force that covered other people’s light may eventually lose its own legitimacy and fall. This line provides perspective: oppressive visibility is not permanent simply because it currently occupies the highest position.",
        "Change here closes the cycle of concealment as the outer darkness exposes itself. The emerging direction may create space for protected clarity to re-enter public life, but rebuilding should not imitate the same concentration of brilliance that created the problem.",
        "Do not celebrate collapse so quickly that the lessons of the dark period are lost. A fallen authority can be replaced by another if the incentives and habits that supported it remain untouched.",
        "What would need to be rebuilt differently if the power that forced concealment loses its position and public space opens again?",
        "Line 6 watches distorted brightness collapse under its own excess and asks the returning light to rebuild without recreating the structure that once suppressed it.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
