import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 37,
    coreTheme: "Family and roles",
    coreMeaning: "Family and roles describe order created through repeated conduct inside the closest system. Jia Ren is less about formal hierarchy than about the credibility of expectations: rules work when the people who set them also embody them, responsibilities are knowable, and care does not become an excuse for inconsistency. The reading asks what the household, team, or intimate system learns from ordinary behavior rather than from stated values alone. Different roles may carry different duties, but authority must remain answerable to example. Excessive harshness damages trust; excessive indulgence dissolves standards. Strong inner order then extends outward through influence rather than through forcing every external relationship to copy the same domestic rules. The best family structure creates people who can act responsibly without constant supervision because boundaries and care have become predictable.",
    strength: "clear roles, dependable boundaries, and leadership by example",
    challenge: "hypocrisy, unclear expectations, or control without modeling the required conduct",
    orientation: "clarify responsibilities and make ordinary conduct match the standards you expect from others",
    structureInterpretation: "Fire below provides inner clarity and differentiation while Wind above spreads influence gradually through the outer field. Quick I Ching reads the structure as an intimate system whose internal conduct becomes its external influence. Order begins with what is practiced close to home, not with rules imposed at a distance.",
    reflectionQuestions: [
      "Which expectation in this close system is unclear enough that people are learning the rule mainly through conflict?",
      "Where are leaders or senior members asking for conduct they do not reliably model themselves?",
      "What repeated household or team practice would make responsibility easier to carry without increasing supervision?",
    ],
    watchFor: [
      "A role becoming easier to trust because responsibilities and boundaries are repeated consistently in ordinary moments.",
      "Harshness or indulgence increasing when leaders rely on mood instead of a standard that applies to themselves too.",
      "Good internal conduct influencing outsiders naturally without needing to impose the same intimate rules on every relationship.",
    ],
    transitionTheme: "unclear close relationships becoming trustworthy through repeated roles, boundaries, and example",
    stabilityTheme: "ordinary conduct that makes the inner system predictable enough to sustain trust",
    lowerTrigram: "li",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Set the household boundary before habits harden",
        "The first line deals with the beginning of a close system, when expectations are easiest to establish and cheapest to correct. A clear boundary around responsibilities, privacy, money, communication, or conduct can prevent later disputes from becoming personal because the standard existed before the conflict.",
        "Change here turns informal closeness into a workable container. The emerging pattern gains trust because participants can learn the rules while relationships are still flexible enough to adapt without feeling that every limit is a punishment.",
        "Do not use early boundary-setting to control every detail. A household or team needs enough room for individual judgment. Define what protects the relationship and shared responsibility, not a complete script for everyone’s behavior.",
        "Which expectation should be made explicit now because waiting until it is violated would make the same conversation more emotionally expensive?",
        "Line 1 builds trustworthy family order by setting necessary boundaries before unclear habits harden into recurring conflict.",
      ),
      authoredLine(
        "Sustain the center through ordinary provision",
        "The second line values the work that keeps the inner system functioning: meals, scheduling, maintenance, emotional steadiness, follow-through, and other forms of provision that rarely look dramatic. Influence here comes from reliability rather than from pursuing authority outside the assigned sphere.",
        "As this line changes, ordinary care becomes structural strength. The emerging pattern can support wider activity because the center is nourished consistently. What looks domestic or routine becomes the platform from which other roles can operate.",
        "Provision can become invisible labor that others take for granted. Reliability should not mean one person absorbs every unmet need. Make the work visible enough that responsibility can be shared and appreciation can remain real.",
        "Which ordinary form of provision is holding the system together, and how can it be made sustainable rather than silently dependent on one person?",
        "Line 2 strengthens the family center through reliable provision while making sure the work of care does not become invisible or permanently one-sided.",
      ),
      authoredLine(
        "Firm correction is better than indulgent disorder",
        "The third line shows a close system under enough strain that correction must be felt. Excessive severity creates regret, but habitual indulgence can be worse because it teaches that standards are optional until someone finally explodes. The useful middle is firm, timely consequence followed by return to ordinary relationship.",
        "Change here turns accumulated irritation into a clearer standard. The emerging pattern improves if correction is tied to specific conduct and is not used to rewrite the whole person’s identity. After the boundary is restored, warmth can return without negating it.",
        "Do not justify humiliation or intimidation as necessary discipline. Fear may produce short-term compliance while damaging truthfulness. The line favors seriousness, not domination.",
        "What behavior needs a firm consequence now, and how can the correction remain specific enough that the relationship can return to warmth afterward?",
        "Line 3 chooses timely, proportionate firmness over permissive disorder while refusing to make correction into humiliation or permanent hostility.",
      ),
      authoredLine(
        "A well-managed home creates real abundance",
        "The fourth line shows value arising from competent stewardship of the inner system. Resources are organized, people know what they can rely on, and care is translated into practical abundance rather than display. Prosperity here can mean money, time, trust, health of routines, or simply lower friction.",
        "When this line changes, strong internal management begins to support a wider field. The emerging pattern can share capacity outward because the household or team is no longer consuming all of its energy managing avoidable internal confusion.",
        "Do not reduce family or team life to efficiency metrics. A system can be organized and emotionally barren. Abundance should increase people’s capacity and security, not merely produce a polished appearance of order.",
        "What practical stewardship would make this close system genuinely richer in capacity, time, trust, or resilience rather than merely more controlled?",
        "Line 4 turns competent inner stewardship into real abundance, creating capacity that can eventually support responsibilities beyond the household itself.",
      ),
      authoredLine(
        "Leadership enters the household without fear",
        "The fifth line places a central authority inside the close system and asks whether leadership can be both respected and approachable. Strong order does not require people to fear the leader’s presence. When the standard is fair and the example is credible, authority can enter ordinary life without producing hidden behavior.",
        "Change here turns formal leadership into relational trust. The emerging pattern becomes more durable because people can tell the truth near authority and still understand that boundaries matter. Respect and psychological safety reinforce one another instead of competing.",
        "A leader can mistake relaxed atmosphere for proof that everyone feels safe. Power changes what people reveal. Create explicit channels for disagreement and correction rather than relying on your own impression that nobody seems afraid.",
        "What would make people inside your closest system able to tell you an uncomfortable truth without doubting that the relationship or role can survive it?",
        "Line 5 makes central authority credible by combining fair standards with enough relational safety that truth can still travel toward the leader.",
      ),
      authoredLine(
        "Character becomes the final source of family authority",
        "At the top line, rules and roles reach their limit; the leader’s own character becomes the strongest organizing force. Others learn from what is consistently embodied—how promises are kept, conflict is handled, resources are used, and mistakes are admitted. Authority that depends only on enforcement weakens when supervision disappears.",
        "Change here releases excessive dependence on formal control. The emerging direction allows the system’s values to persist because they have become visible in conduct and internalized by other members rather than remaining attached to one person’s commands.",
        "Do not turn ‘leading by example’ into a reason to leave expectations unspoken. Example is powerful, but ambiguity still causes conflict. Character should support clear rules, not replace necessary communication.",
        "What repeated behavior of yours is teaching this close system more strongly than any rule or value statement you have given it?",
        "Line 6 completes family order by making embodied character—not constant enforcement—the deepest source of credible authority.",
      ),
    ],
  },
  {
    number: 38,
    coreTheme: "Opposition",
    coreMeaning: "Opposition describes real difference that does not need to become total rupture. Kui appears when perspectives, interests, identities, or methods point in different directions, yet some limited relationship may still be possible. The reading favors precise distinction. False unity produces resentment, while dramatic polarization can make every disagreement look like betrayal. Small cooperation, clear boundaries, and accurate interpretation matter more than forcing consensus. Opposition often contains perceptual distortion: suspicion can make ordinary events look hostile until direct evidence corrects the story. At its strongest, the hexagram asks people to remain themselves while identifying the specific common ground that still exists. Difference can sharpen judgment when it is not weaponized. The goal is not to erase disagreement, but to prevent it from colonizing every part of the relationship.",
    strength: "clarity about real differences without needing to erase them",
    challenge: "false unity, escalation, or treating every disagreement as betrayal",
    orientation: "name the difference precisely, protect distinct positions, and cooperate where common ground is real",
    structureInterpretation: "Lake below opens outward while Fire above rises and differentiates; the two trigrams move in different ways. Quick I Ching reads the structure as separation of viewpoint and direction. Because difference is structural, progress comes through clear distinction and limited common ground rather than by pretending the parties naturally want the same thing.",
    reflectionQuestions: [
      "What exactly is different here, and what parts of the relationship are being unnecessarily included in that disagreement?",
      "Where could limited cooperation continue without requiring either side to pretend the deeper difference has disappeared?",
      "What suspicion should be tested directly before it becomes evidence in your mind simply because the relationship already feels opposed?",
    ],
    watchFor: [
      "A disagreement becoming easier to manage after it is narrowed to one specific issue instead of a judgment about the whole relationship.",
      "Ordinary ambiguity being interpreted as hostility because the parties now expect opposition before examining evidence.",
      "A small shared task proving that coexistence remains possible even though larger perspectives remain different.",
    ],
    transitionTheme: "friction becoming workable coexistence when difference is named and bounded",
    stabilityTheme: "respectful distinction that prevents disagreement from spreading into every domain",
    lowerTrigram: "dui",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Do not chase what leaves; let what belongs return",
        "The first line begins opposition by discouraging anxious pursuit. A person, resource, or point of agreement may move away, but forcing its return can intensify the separation. Maintain a clear position and attend to what remains within your responsibility. Some connection may restore itself once pressure is removed.",
        "Change here transforms opposition from pursuit into stable boundary. The emerging pattern gains dignity because the person stops treating every departure as something that must be controlled. Contact that returns voluntarily provides better information about the relationship.",
        "Non-pursuit can become passive avoidance of a repair you actually owe. Distinguish what simply needs space from what requires apology, clarification, or a practical act to make return possible.",
        "What are you chasing mainly because its departure feels like rejection, and what would happen if you maintained your position without trying to force a return?",
        "Line 1 reduces opposition by ending anxious pursuit and allowing voluntary return to reveal which connections still have a natural basis.",
      ),
      authoredLine(
        "Meet the other person in a narrow lane",
        "The second line finds contact through an informal, limited channel rather than through the main public structure of disagreement. A brief private conversation, side meeting, or practical encounter can restore humanity when formal positions have become rigid. The goal is not secret alliance but a place where the person can be seen apart from the faction.",
        "As this line changes, opposition gains a usable communication path. The emerging pattern may not settle the larger issue, but it reduces distortion and can identify one point of cooperation or accurate understanding that formal channels could not reach.",
        "Private contact becomes dangerous if it undermines legitimate public process or creates hidden commitments. Use the narrow lane to understand and clarify, not to make promises that cannot survive daylight.",
        "What limited, direct conversation could reduce caricature here without pretending the public disagreement has already been resolved?",
        "Line 2 opens a narrow direct channel through opposition, restoring person-to-person understanding without bypassing legitimate public responsibilities.",
      ),
      authoredLine(
        "A frightening appearance may be misread",
        "The third line sees a hostile-looking situation: movement appears blocked, motives look threatening, and the other side may seem almost monstrous. Yet perception under opposition is unreliable. Before escalating, separate what has actually happened from the story your alarm has built around it.",
        "Change here turns fearful interpretation into evidence-testing. The emerging pattern can reveal that some apparent threat was distortion, while any real aggression becomes easier to address because it has been distinguished from projection.",
        "Do not use the possibility of misperception to deny genuine danger. Verify. The point is that opposition magnifies hostile interpretation, not that every hostile signal is imaginary.",
        "Which part of your picture of the other side is directly observed, and which part has been inferred from the fact that you already expect opposition?",
        "Line 3 interrupts escalation by testing frightening interpretations against direct evidence before treating suspicion as established fact.",
      ),
      authoredLine(
        "Isolation inside opposition finds one sincere ally",
        "The fourth line experiences separation strongly enough that the person may feel alone in their position. A sincere connection with one trustworthy person can prevent difference from hardening into total isolation. The value is not numerical support but contact with someone who can engage honestly across the divide.",
        "When this line changes, opposition becomes less total because one credible relationship creates a bridge. The emerging pattern can use that bridge to test assumptions, share information, or simply preserve psychological proportion while larger disagreements continue.",
        "Do not make one ally into proof that your entire position is correct. A bridge is valuable because it preserves contact, not because it creates a new faction. Keep the relationship open enough to carry disagreement too.",
        "Who can engage your position sincerely without needing to join your side completely, and how can that relationship keep the wider opposition from becoming absolute?",
        "Line 4 reduces isolation by preserving one sincere bridge across opposition without turning that connection into another factional weapon.",
      ),
      authoredLine(
        "A trusted connection bites through the covering",
        "The fifth line finds a central relationship capable of cutting through misunderstanding and reaching the real issue underneath. Someone close enough to challenge the surface story can help reveal what has been obscured by opposition. Trust allows directness that would feel threatening from a stranger.",
        "Change here transforms central opposition into workable contact. The emerging pattern gains precision as hidden assumptions are exposed and the real difference can finally be handled rather than defended against through proxies.",
        "Trust should not make one person the sole interpreter of the other side. Use the relationship to reach evidence and direct communication, not to replace them. A mediator becomes harmful if every truth must pass through them forever.",
        "Which trusted relationship could help you cut through the surface story and identify the actual issue that has been covered by opposition?",
        "Line 5 uses trusted directness to break through misunderstanding and bring the real disputed issue into a form that can finally be handled.",
      ),
      authoredLine(
        "Suspicion dissolves when the supposed enemy is recognized differently",
        "At the top line, opposition has reached an extreme of projection. What first looked like an attacker or threat may prove to be an ally, partner, or simply a less hostile figure than imagined once contact becomes clear. The dramatic reversal shows how much perception can be shaped by expectation under prolonged separation.",
        "Change here releases the most distorted layer of opposition. The emerging pattern can move toward reunion or at least de-escalation because the other party is no longer required to carry the entire image of an enemy.",
        "Do not swing from suspicion into naive trust merely because one interpretation was wrong. Update proportionately. The lesson is to revise the picture with evidence, not to replace one absolute story with its opposite.",
        "What new evidence would require you to redraw your image of the other side without pretending the real differences never existed?",
        "Line 6 dissolves extreme projection by revising the image of the supposed enemy according to evidence, opening room for de-escalation without false unity.",
      ),
    ],
  },
  {
    number: 39,
    coreTheme: "Obstruction",
    coreMeaning: "Obstruction describes a route that cannot be taken directly under present conditions. Jian asks for redirection rather than repeated collision. The blockage may reveal missing support, unsuitable timing, incomplete skill, or a path whose cost has become disproportionate to the purpose. The reading favors turning toward help, perspective, and another route before exhaustion narrows judgment. Some lines advise coming back rather than going out; others show when support and leadership make renewed movement possible. A central obstruction can become a gathering point because shared difficulty reveals who can cooperate. The highest insight is that returning from a blocked path is not always failure. If the obstacle has already taught what the route cannot carry, a revised path can serve the original purpose better than stubborn persistence ever could.",
    strength: "the ability to learn from blockage and seek support or a better route",
    challenge: "pushing the same barrier repeatedly, isolating yourself, or treating every delay as bad luck",
    orientation: "reassess the route, seek useful support, and move where the terrain actually permits progress",
    structureInterpretation: "Mountain below stops movement while Water above presents danger beyond the stop. Quick I Ching reads the structure as a route whose direct continuation is both blocked and hazardous. Wisdom lies in changing orientation, finding help, or returning to a position from which another path can be chosen.",
    reflectionQuestions: [
      "What is this obstruction teaching about the route itself rather than merely about your willingness to persist?",
      "Who has information, leverage, or experience that could reveal an alternative path you cannot see from the blocked position?",
      "What part of the original purpose can be preserved even if the direct route has to be abandoned?",
    ],
    watchFor: [
      "The same barrier producing less progress with each additional push, showing that persistence is no longer informative.",
      "A useful ally or perspective changing the map rather than simply encouraging you to try the blocked route harder.",
      "A revised path restoring movement while preserving the underlying purpose that made the original route worth attempting.",
    ],
    transitionTheme: "blocked movement becoming redirection when the obstacle is treated as information",
    stabilityTheme: "adaptability that preserves purpose without worshipping one route",
    lowerTrigram: "gen",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Going meets obstruction; returning earns perspective",
        "The first line sees the block early enough that continuing outward would add difficulty without adding useful information. Returning is not defeat. It restores a position from which the terrain can be reviewed and the next attempt can be based on a better map.",
        "Change here converts frustrated advance into strategic reconsideration. The emerging pattern gains options because the person stops spending capacity on a route already showing that it cannot currently support movement.",
        "Do not retreat from every first resistance. The obstacle should be substantial enough to change the economics or safety of the route. Ordinary friction still belongs to ordinary persistence.",
        "What evidence shows that returning to reassess now would create more options than another immediate attempt to push through the same block?",
        "Line 1 treats early obstruction as route information and returns for perspective before wasted effort reduces the available options.",
      ),
      authoredLine(
        "A difficult mission can require repeated obstruction",
        "The second line recognizes that some blockage cannot be avoided because the responsibility itself is legitimate. A person serving a larger duty may have to encounter difficulty repeatedly without interpreting every obstacle as a reason to abandon the mission. The key is that the hardship belongs to the task, not to private stubbornness.",
        "As this line changes, endurance becomes service rather than self-display. The emerging pattern gains dignity because persistence is anchored in responsibility to something larger than personal success.",
        "Duty can be invoked to justify poor planning or unnecessary sacrifice. Repeated obstruction still deserves learning. Service does not remove the obligation to improve the route wherever possible.",
        "Which part of this difficulty is genuinely inseparable from the responsibility you accepted, and which part could still be redesigned?",
        "Line 2 accepts repeated obstruction when it belongs to a legitimate duty while still asking the route to learn from every encounter.",
      ),
      authoredLine(
        "Turning back reconnects you with those who depend on you",
        "The third line finds that outward movement meets too much obstruction while return restores contact with people, resources, or responsibilities at home. Continuing forward alone may deprive the inner system of support it actually needs. Reorientation can strengthen both the traveler and those waiting behind.",
        "Change here transforms frustrated individual advance into renewed connection. The emerging pattern gains support because the person returns to a base capable of sharing information, responsibility, and emotional load.",
        "Do not use dependence at home as a permanent excuse never to leave. The return is useful if it restores capacity or changes the plan. If nothing is learned, the same obstruction will simply wait for the next attempt.",
        "What support or responsibility becomes visible only when you turn back from the blocked route and reconnect with the people behind you?",
        "Line 3 redirects blocked individual movement toward the base that can restore connection, support, and a better plan for whatever comes next.",
      ),
      authoredLine(
        "Returning creates connection; going alone deepens the block",
        "The fourth line emphasizes alliance. The outer field is too difficult for solitary movement, but returning or pausing can create the relationships needed for another attempt. The obstacle is partly a coordination problem: progress requires people or resources that cannot be assembled while you are already exposed on the blocked path.",
        "When this line changes, obstruction becomes a reason to gather support. The emerging pattern can reopen movement because the next advance is no longer being asked to carry every dependency alone.",
        "More supporters do not automatically make a bad route good. Alliance should change capability, information, or leverage in a concrete way. A crowd of encouragement without structural help can deepen the same mistake.",
        "What specific ally or resource would change the route materially rather than simply make you feel less alone while attempting it?",
        "Line 4 converts obstruction into coordinated support, gathering the specific relationships or resources that can actually change the next attempt.",
      ),
      authoredLine(
        "Great obstruction attracts real companions",
        "The fifth line stands at a serious difficulty in a central position, but the weight of the problem draws capable support. People recognize that the obstacle matters and that coordinated response is justified. Leadership consists in receiving that help and organizing it around the problem rather than around personal heroism.",
        "Change here turns a major obstacle into a focal point for collective capability. The emerging pattern may succeed not because the obstruction became small but because enough trustworthy people can now carry different parts of it together.",
        "A crisis can attract opportunists as well as allies. Do not confuse attention with useful support. Define roles and standards so the gathered help increases capacity instead of adding coordination burden.",
        "Who is showing up because the obstruction itself is important, and how can their specific capabilities be organized around the real problem?",
        "Line 5 lets a major obstruction become a center for capable alliance, replacing heroic isolation with organized collective response.",
      ),
      authoredLine(
        "Returning from the far route brings a larger view",
        "At the top line, the person has gone far enough into obstruction to gain perspective that the lower positions did not have. Continuing outward offers little, while returning can bring the hard-earned knowledge back into the larger system. The return may carry wisdom, warning, or a new route rather than simply retreat.",
        "Change here completes the obstructed journey by converting experience into guidance. The emerging direction becomes more valuable because the person stops measuring success only by whether the original route was completed and begins using what the blockage taught.",
        "Do not romanticize failure as wisdom automatically. Experience becomes valuable only when it is analyzed clearly and communicated in a form others can use. Otherwise the return simply carries exhaustion home.",
        "What have you learned far inside this obstruction that would be more valuable if brought back and used to change the wider plan?",
        "Line 6 completes obstruction by returning with perspective, turning a blocked route into guidance that can improve the larger system’s next direction.",
      ),
    ],
  },
  {
    number: 40,
    coreTheme: "Release",
    coreMeaning: "Release describes the loosening that becomes possible after pressure, danger, or binding obligation has begun to dissolve. Jie asks what can now be let go, what still requires completion, and how to prevent freedom from recreating the old bind in a new form. Relief often creates urgency to move quickly, but the cleanest release may be simple: return to ordinary duties, settle the remaining issue, remove an unnecessary burden, and stop feeding the conflict. Some constraints require direct correction before they can be released; others disappear once nobody keeps them alive. The reading favors finishing rather than celebrating. Genuine release increases movement and reduces vigilance because the underlying tension has changed. If the person continues defining themselves through the former struggle, the pressure may be gone externally while remaining active inside conduct.",
    strength: "the ability to discharge tension and simplify after pressure begins to lift",
    challenge: "continuing the fight after it is over or releasing obligations that still need completion",
    orientation: "finish what remains necessary, let go of the rest, and move without recreating the old bind",
    structureInterpretation: "Water below contains the old danger while Thunder above moves outward from it. Quick I Ching reads the structure as motion after a constraining passage. Release becomes possible because energy that was tied up in hazard can finally move, but the transition is cleanest when remaining obligations are resolved rather than dragged into the new phase.",
    reflectionQuestions: [
      "What pressure has actually changed enough that continued defensive behavior is now unnecessary?",
      "Which obligation still needs a clean ending before you can honestly call the situation released?",
      "What habit from the constrained phase would recreate the old bind if carried unchanged into the freer conditions?",
    ],
    watchFor: [
      "Attention and energy becoming available for ordinary life because the former threat no longer requires constant monitoring.",
      "A person continuing to rehearse conflict, emergency routines, or defensive identity after the external pressure has materially changed.",
      "One remaining task or conversation whose completion would allow the release to become structurally real rather than emotional only.",
    ],
    transitionTheme: "constraint becoming renewed movement once necessary tension is discharged",
    stabilityTheme: "freedom protected by not recreating the conditions that produced the old bind",
    lowerTrigram: "kan",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Nothing more needs to be added",
        "The first line finds a release simple enough that restraint after the fact is the right response. The pressure has eased and no additional campaign, explanation, or symbolic closure is required. Allow normal life to resume instead of manufacturing another task around the ending.",
        "Change here turns release into quiet stabilization. The emerging pattern gains health because the system can experience ordinary conditions again rather than being kept in an emergency narrative for emotional completeness.",
        "Do not use simplicity to skip a remaining duty that is merely inconvenient. ‘Nothing more’ is true only when the essential obligation is already complete. Verify before relaxing.",
        "What are you tempted to add to this ending even though the situation may already be sufficiently resolved?",
        "Line 1 protects release by refusing unnecessary after-action drama when the essential constraint has already been removed.",
      ),
      authoredLine(
        "Remove the small corruptions that keep freedom dirty",
        "The second line shows that release may require clearing out lingering distortions—small deceptions, opportunistic habits, or relationships that benefited from the constrained period. These are not the main danger anymore, but leaving them in place would contaminate the freer system.",
        "As this line changes, release becomes cleaner and more trustworthy. The emerging pattern gains stability because hidden incentives that could recreate the old pressure are removed while conditions are still favorable for correction.",
        "Do not turn cleanup into a purge. The target should be specific behaviors or mechanisms, not everyone who happened to operate during the difficult period. Proportion remains essential after victory.",
        "Which small opportunistic pattern could recreate the old bind if it is allowed to survive into the newly released situation?",
        "Line 2 completes release by removing lingering corruptions that would otherwise carry the logic of the old constraint into the freer phase.",
      ),
      authoredLine(
        "Displaying wealth while carrying a burden invites trouble",
        "The third line warns against moving into release with a mismatch between appearance and actual position. A person may display freedom, status, or resources while still carrying obligations that make the display unsafe or provocative. The contradiction attracts scrutiny and can generate new trouble.",
        "Change here brings outward posture back into alignment with real capacity. The emerging pattern becomes safer when the person reduces display, settles the carried burden, or stops acting as if release has produced more freedom than it actually has.",
        "Do not interpret the warning as a reason to hide legitimate success forever. The issue is incongruence. Once obligations and capacity match the outward posture, visibility becomes less risky.",
        "Where are you presenting yourself as freer, richer, or less constrained than your remaining obligations actually allow?",
        "Line 3 protects release from new trouble by aligning outward display with the burdens and limits that still remain in reality.",
      ),
      authoredLine(
        "Release the binding toe so trustworthy company can approach",
        "The fourth line asks you to let go of a small but persistent attachment that restricts movement and affects whom you can trust or welcome. A habit, alliance, or lingering dependency may be physically minor but relationally important because it signals that the old bind is not truly finished.",
        "When this line changes, release becomes social as well as personal. The emerging pattern opens room for more trustworthy relationships because the person is no longer carrying an attachment that creates divided loyalty or hidden constraint.",
        "Do not cut a relationship merely to prove freedom. Identify the actual binding function. Some ties can be renegotiated rather than abandoned if the constraint can be removed without destroying the relationship.",
        "What small attachment is still limiting your movement or making trustworthy people unsure whether you are actually free to engage?",
        "Line 4 releases a lingering attachment whose small practical hold has been creating a larger relational constraint on future movement.",
      ),
      authoredLine(
        "The centered person proves release by actually letting go",
        "The fifth line places release inside personal responsibility. Nobody else can make the final letting-go credible. The person in the central role must stop benefiting from, monitoring, or emotionally reenacting the old bind. Others trust the release when conduct shows that the former constraint no longer organizes the center.",
        "Change here turns declared freedom into observable behavior. The emerging pattern becomes trustworthy because the person’s choices no longer require the old enemy, emergency, or obligation to remain psychologically present.",
        "Performing detachment can be another form of attachment. Do not repeatedly announce that you have moved on while continuing to check, provoke, or define yourself against the past. Quiet behavioral change is stronger evidence.",
        "What behavior would show, without another declaration, that the former bind no longer organizes your decisions?",
        "Line 5 makes release credible through central conduct that no longer depends on keeping the old constraint active as an identity or reference point.",
      ),
      authoredLine(
        "Remove the last elevated source of threat",
        "At the top line, one remaining threat or obstruction still occupies a powerful position after the broader release. A precise final action may be needed to remove it. This is not a return to general conflict; it is a targeted completion that allows the rest of the system to relax without leaving a dangerous exception overhead.",
        "Change here closes the release cycle decisively. The emerging pattern gains full freedom because the last significant source of threat is addressed rather than tolerated out of fatigue after the larger struggle has already ended.",
        "A desire for complete purity can invent new ‘last threats’ forever. The target must be concrete, consequential, and genuinely capable of recreating the old constraint. Otherwise the final action becomes another excuse to continue fighting.",
        "What specific remaining threat still has enough leverage to recreate the old constraint, and what proportionate final action would remove that risk?",
        "Line 6 completes release through a precise final correction of the remaining high-leverage threat, then ends the conflict rather than extending it.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
