import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 37,
    coreTheme: "The family",
    legacySummary: "Stable relationships depend on roles, boundaries, and example. Improve the immediate system of conduct before trying to correct the wider environment.",
    strength: "order created through consistent roles, boundaries, and example",
    challenge: "hypocrisy, unclear expectations, or trying to control others without modeling the standard",
    orientation: "begin with conduct in the immediate system and make expectations consistent",
    transitionTheme: "disorder becoming trust when daily roles and examples align",
    stabilityTheme: "relational order maintained by repeated conduct rather than occasional correction",
    lowerTrigram: "li",
    upperTrigram: "xun",
    lineEmphases: [
      "set the first household or team expectation through your own conduct",
      "make roles and boundaries dependable in the ordinary center of relationship",
      "correct inconsistency when pressure exposes a gap between stated standards and lived example",
      "carry internal order into wider relationships without trying to manage everyone by family rules",
      "use central responsibility to make expectations fair, stable, and visible",
      "release rigid roles when they survive only because nobody has revisited whether they still serve",
    ],
  },
  {
    number: 38,
    coreTheme: "Opposition",
    legacySummary: "Differences are real and should not be blurred. Small areas of cooperation may still be possible when each side understands where alignment ends.",
    strength: "clarity about difference without requiring total separation",
    challenge: "forcing false unity, escalating every difference, or treating disagreement as betrayal",
    orientation: "name the difference, protect distinct positions, and cooperate only where real common ground exists",
    transitionTheme: "friction becoming workable coexistence through precise boundaries",
    stabilityTheme: "respectful distinction that permits limited cooperation without pretending full agreement",
    lowerTrigram: "dui",
    upperTrigram: "li",
    lineEmphases: [
      "name the first real difference without treating it as a total rupture",
      "preserve distinct positions while finding a small area where cooperation remains honest",
      "avoid turning pressure around one disagreement into opposition on every issue",
      "bring difference into the wider field with precise boundaries and no false appearance of unity",
      "use a central role to protect fair coexistence rather than force alignment",
      "stop feeding opposition when the distinction has been made and further contrast adds no value",
    ],
  },
  {
    number: 39,
    coreTheme: "Obstruction",
    legacySummary: "The direct route is blocked. Reconsider direction, seek assistance, and use the obstacle as information about what the current approach cannot solve.",
    strength: "the ability to learn from blockage and find support or another route",
    challenge: "repeatedly attacking the same barrier, isolation, or reading obstruction only as bad luck",
    orientation: "pause the direct push, reassess the route, and involve the support the obstacle reveals you need",
    transitionTheme: "blocked movement becoming redirection, assistance, or a more viable path",
    stabilityTheme: "adaptability that treats resistance as information rather than insult",
    lowerTrigram: "gen",
    upperTrigram: "kan",
    lineEmphases: [
      "treat the first blockage as information about the route, not as a verdict on the goal",
      "seek practical support before isolation becomes part of the obstruction",
      "change direction when repeated pressure proves the direct path is not workable",
      "carry the revised route outward and test it against the real terrain",
      "use central judgment to coordinate help and decide which obstacles are worth engaging",
      "leave the obstructed frame behind when a different path has clearly become viable",
    ],
  },
  {
    number: 40,
    coreTheme: "Release",
    legacySummary: "Tension can now be loosened. Resolve what is necessary, forgive what no longer needs carrying, and move promptly once the obstruction has actually cleared.",
    strength: "the ability to discharge accumulated tension and simplify after resolution",
    challenge: "continuing the fight after the cause has passed or releasing obligations that still matter",
    orientation: "finish what must be finished, let unnecessary tension go, and move once release is real",
    transitionTheme: "constraint becoming renewed movement after the source of pressure is removed",
    stabilityTheme: "lightness preserved by not recreating the conditions that produced the bind",
    lowerTrigram: "kan",
    upperTrigram: "zhen",
    lineEmphases: [
      "loosen the first unnecessary tension once the actual cause has been addressed",
      "make release practical by closing small obligations that no longer need carrying",
      "avoid declaring freedom while unresolved pressure is still active underneath",
      "bring renewed movement into the wider field without recreating the old conflict",
      "use a central opening to simplify responsibilities and restore normal circulation",
      "stop defining the situation by what was released after the release has become real",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
