import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 41,
    coreTheme: "Decrease",
    coreMeaning: "Decrease describes purposeful reduction: removing something so the whole can regain balance, clarity, or capacity. Sun is not austerity for its own sake. The central question is what should become smaller and what must be protected from the cut. A useful reduction may simplify commitments, redirect resources, lower consumption, or surrender an advantage that is weakening the system. The lines distinguish different kinds of decrease—swift help, preserving one’s own center, reducing a group to a workable relationship, correcting a defect, receiving support, and finally recognizing when the period of cutting has ended. The reading favors explicit purpose and review. Sacrifice becomes harmful when it is vague, performative, or repeatedly taken from the same essential layer. Reduce the excess, not the life of the system; once balance returns, continued cutting is no longer discipline.",
    strength: "selective reduction that frees capacity and restores proportion",
    challenge: "cutting what is essential, performative sacrifice, or reducing without a clear purpose",
    orientation: "remove excess deliberately while protecting the functions that must remain strong",
    structureInterpretation: "Lake below opens and can be diminished while Mountain above sets a firm upper boundary. Quick I Ching reads the structure as reduction that serves containment and proportion. What is given up below should strengthen the whole rather than simply concentrate benefit at the top.",
    reflectionQuestions: [
      "What would become healthier if it were deliberately smaller, simpler, or less demanding?",
      "Which essential function is at risk of being cut because it is easier to reduce than the real source of excess?",
      "What evidence would tell you that balance has returned and the reduction phase should stop?",
    ],
    watchFor: [
      "A reduction freeing real time, money, attention, or structural capacity instead of merely producing a sense of discipline.",
      "Cuts repeatedly landing on the same essential layer while prestige, complexity, or low-value demand remains untouched.",
      "The system beginning to function better at a smaller scale, indicating that continued reduction may no longer be necessary.",
    ],
    transitionTheme: "overload becoming clearer proportion through deliberate reduction",
    stabilityTheme: "restraint guided by priorities rather than by an identity built around sacrifice",
    lowerTrigram: "dui",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Reduce your own business quickly to help where it matters",
        "The first line shows a person able to set aside some private activity in order to support a more important need. The reduction should be prompt and proportionate: help where the value is clear, then return to your own responsibilities. Sacrifice works because it is targeted rather than open-ended.",
        "Change here converts private capacity into timely support. The emerging pattern improves when a small reduction in one place prevents a larger problem elsewhere, without making the helper permanently responsible for the whole burden.",
        "Do not let a useful emergency contribution turn into an indefinite transfer of responsibility. Clarify how much is needed and when your own work must resume.",
        "What can you temporarily reduce in your own activity to help a more important need without abandoning the responsibilities that still belong to you?",
        "Line 1 uses a quick, limited self-reduction to support an important need while keeping the sacrifice bounded and reversible.",
      ),
      authoredLine(
        "Do not injure the center in the name of giving",
        "The second line warns that decrease should not weaken the very capacity from which help comes. Generosity that damages core health, solvency, dignity, or responsibility eventually helps no one. Preserve the center and contribute from what can actually be spared.",
        "As this line changes, reduction becomes sustainable because it respects the provider’s limits. The emerging pattern may even create increase elsewhere precisely because the source remains strong enough to continue contributing over time.",
        "Self-protection can become an excuse for stinginess if every resource is declared essential. Distinguish a genuine core requirement from comfort, status, or unused reserve.",
        "What must remain intact so this reduction or contribution can be sustained without weakening the source that makes it possible?",
        "Line 2 protects the giver’s core capacity, making reduction sustainable enough to create real benefit rather than hidden self-damage.",
      ),
      authoredLine(
        "Three become two when excess relationship is removed",
        "The third line shows that reducing one element from an overcomplicated relationship can create a clearer pair or partnership. Too many competing loyalties, intermediaries, or voices may be preventing direct trust. Simplification is relational: fewer parties can sometimes produce more genuine connection.",
        "Change here turns diffuse association into a more workable bond. The emerging pattern becomes clearer because responsibility and communication are no longer divided among too many overlapping connections.",
        "Do not reduce people merely because coordination is inconvenient. The issue is structural excess, not preference for a smaller circle. Ensure that the removed role or relationship truly duplicates, triangulates, or destabilizes what should be direct.",
        "Which extra relationship, intermediary, or overlapping role is making a simpler and more accountable connection unnecessarily difficult?",
        "Line 3 simplifies an overcomplicated relational structure so direct responsibility and trust can become clearer between the remaining parties.",
      ),
      authoredLine(
        "Decrease the defect and others can approach",
        "The fourth line focuses reduction on a personal or structural flaw that makes cooperation harder. Removing an irritating habit, unnecessary barrier, or recurring defect can quickly improve how others experience the relationship. The best cut is the one that removes friction rather than value.",
        "When this line changes, decrease produces renewed connection. The emerging pattern benefits because energy previously spent compensating for the defect becomes available for actual work or relationship.",
        "Do not treat every criticism as proof that you must make yourself smaller. The defect should be specific and observable. Reduction of healthy difference would weaken the system instead of improving it.",
        "What recurring defect or unnecessary friction could you reduce so other people no longer have to organize around compensating for it?",
        "Line 4 targets decrease at a real defect, improving connection by removing friction rather than reducing healthy capacity or difference.",
      ),
      authoredLine(
        "Great support arrives without needing to be chased",
        "The fifth line shows decrease producing an unexpected increase from outside. By simplifying, giving up excess, or correcting imbalance, the system becomes capable of receiving support that previously had no place to land. The gain may feel larger than the sacrifice that made room for it.",
        "Change here turns disciplined reduction into receptivity. The emerging pattern demonstrates that not every resource must be acquired through pursuit; sometimes clearing the structure allows help, trust, or opportunity to enter naturally.",
        "Do not turn one favorable arrival into a superstition that every sacrifice will be rewarded. The value of the reduction must remain sound even if no external gain appears.",
        "What space has this reduction created that can now receive support or opportunity which the previous crowded structure could not hold?",
        "Line 5 shows a well-chosen decrease creating room for substantial support, while keeping the reduction justified independently of any promised reward.",
      ),
      authoredLine(
        "Stop decreasing when increase can serve the whole",
        "At the top line, the reduction phase reaches its limit. Further cutting would no longer restore balance; the better move is to use what remains to create value and allow growth. A person who has learned restraint can now increase without returning automatically to the old excess.",
        "Change here closes decrease and opens a generative phase. The emerging pattern converts lessons from reduction into better allocation, rebuilding, or contribution that strengthens more than one part of the system.",
        "Austerity can become identity. Do not keep cutting because it feels morally safer than investing or expanding. Once the structure is healthy, refusal to increase can become another imbalance.",
        "What evidence shows that reduction has completed its purpose and that the next responsible move is to build, invest, or contribute again?",
        "Line 6 ends decrease when balance is restored, carrying restraint forward as discipline for a new phase of useful increase.",
      ),
    ],
  },
  {
    number: 42,
    coreTheme: "Increase",
    coreMeaning: "Increase describes added resources, attention, trust, or opportunity that can become generative when they strengthen capacity rather than merely enlarge volume. Yi asks where an addition will multiply usefulness and where it might simply feed an already weak or distorted structure. Growth is most durable when benefit circulates, infrastructure keeps pace, and those receiving support become more capable rather than more dependent. The reading favors timely investment and visible generosity, but it also warns that increase must remain coherent. More customers without systems, more funding without governance, or more authority without accountability can magnify weakness. The highest line shows what happens when accumulation becomes one-sided: support disappears because the person has stopped contributing to the field that made increase possible. Add where the whole can carry it and where the addition improves the conditions for future value.",
    strength: "generative growth that turns added resources into wider capacity",
    challenge: "unequal accumulation, growth without infrastructure, or adding to a system whose weakness remains uncorrected",
    orientation: "direct additional resources toward capabilities and relationships that can multiply their value",
    structureInterpretation: "Thunder below activates movement while Wind above spreads and penetrates gradually. Quick I Ching reads the structure as increase that travels: added energy should propagate through the system rather than remain concentrated. Growth becomes useful when movement and distribution reinforce one another.",
    reflectionQuestions: [
      "Where would one added unit of time, money, authority, or attention create more than one unit of lasting capability?",
      "Which part of the system is already too weak to absorb further growth without first improving infrastructure?",
      "Who should become more capable because of this increase rather than simply receive more from the same source?",
    ],
    watchFor: [
      "A new resource reducing future dependence because it improves skill, infrastructure, or self-sustaining capacity.",
      "Volume increasing faster than governance, maintenance, or delivery quality can support.",
      "Benefit circulating back into the wider system instead of accumulating around one participant who contributed less and less over time.",
    ],
    transitionTheme: "added resources becoming durable increase when foundations and distribution improve with growth",
    stabilityTheme: "growth that strengthens the system capable of carrying the next increment",
    lowerTrigram: "zhen",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Use the first increase for a substantial task",
        "The first line receives enough added capacity to do something meaningful rather than merely become comfortable. Early increase is best used where the result can justify the resource and establish a productive direction. A significant task can turn surplus into evidence of what growth is for.",
        "Change here converts new capacity into visible contribution. The emerging pattern gains momentum because the increase begins with an accomplishment that improves confidence and clarifies how future resources should be used.",
        "Do not choose a large task simply to make the increase look impressive. The undertaking should fit the added capacity and produce durable value, not expose the system to a risk larger than the new resource can absorb.",
        "What meaningful task has become possible because capacity genuinely increased, and why is it a better use than simply expanding comfort or display?",
        "Line 1 puts the first increase to work in a substantial but proportionate task that demonstrates what the added capacity can responsibly enable.",
      ),
      authoredLine(
        "Support arrives when the center can receive it",
        "The second line shows increase reinforced by substantial outside support. The recipient is able to use the gain because the underlying direction is already trustworthy. Additional resources do not need to rescue a broken center; they amplify something that can carry them.",
        "As this line changes, external support becomes part of a larger growth cycle. The emerging pattern benefits when the recipient turns the increase into repeatable capability and remains accountable to the standards that made support reasonable.",
        "Large support can distort incentives or create a sense that favorable conditions are guaranteed. Keep the original discipline visible and avoid scaling obligations faster than the new resource has proven sustainable.",
        "What would make this outside support increase your own capacity rather than simply make you accustomed to having a larger resource available?",
        "Line 2 receives substantial support into a sound center and converts the gain into repeatable capacity rather than dependence on continued abundance.",
      ),
      authoredLine(
        "Even misfortune can become an increase when used well",
        "The third line shows a difficult event producing knowledge, solidarity, authority, or capability that would not have emerged under easier conditions. The increase is not the suffering itself. It comes from using the event honestly enough that the system learns and becomes better prepared afterward.",
        "Change here converts adversity into institutional or personal capacity. The emerging pattern becomes stronger when lessons are documented, resources are redirected, and the painful event changes future practice instead of becoming only a story of survival.",
        "Do not romanticize harm or imply that suffering was necessary for growth. The event may still be regrettable. The task is simply to refuse waste by extracting usable learning from what already happened.",
        "What capability or knowledge can be built from this difficult event without pretending that the harm itself was beneficial or required?",
        "Line 3 turns adversity into increase only through honest learning and changed practice, never by treating the original harm as inherently good.",
      ),
      authoredLine(
        "Move the center so increase can reach the right place",
        "The fourth line recognizes that growth may require relocating authority, resources, or the operational center. An arrangement that was adequate at smaller scale may now prevent value from reaching where it is needed. A trusted intermediary can help shift the system without losing continuity.",
        "When this line changes, increase becomes structural redesign. The emerging pattern distributes capacity more effectively because the center is placed closer to the new reality rather than forcing all growth through an old location or hierarchy.",
        "Reorganization can become fashionable churn. Move the center only when access, coordination, or distribution materially improves. A new chart with the same bottlenecks is not an increase in capability.",
        "What authority or resource center should move because growth has changed where decisions and support need to be closest to the work?",
        "Line 4 turns increase into organizational adaptation by moving the center where added capacity can circulate more effectively.",
      ),
      authoredLine(
        "Beneficent increase does not need constant calculation",
        "The fifth line shows a central person or system able to increase others sincerely because the act is aligned with the larger purpose. Generosity and authority work together without requiring a transactional ledger for every benefit. Trust grows because the increase is consistent with a known standard.",
        "Change here turns central abundance into a culture of mutual benefit. The emerging pattern becomes more resilient as others gain capability and can eventually contribute back without being bound by hidden debt.",
        "Unconditional tone can conceal unspoken expectations. If support carries obligations, name them. Genuine generosity is clearer when recipients do not have to guess what loyalty or repayment will later be demanded.",
        "How can you use central capacity to increase others in a way that is generous, transparent, and free of hidden relational debt?",
        "Line 5 makes increase trustworthy through sincere central generosity whose terms are clear enough that benefit does not become hidden obligation.",
      ),
      authoredLine(
        "Accumulation without giving back loses support",
        "At the top line, increase has become one-sided. The person or part of the system wants continued gain but no longer contributes enough to the relationships and structures that make gain possible. Resentment and instability follow because circulation has stopped.",
        "Change here ends unsustainable accumulation. The emerging direction requires redistribution, contribution, or acceptance that support will withdraw. Increase can resume only after reciprocity becomes credible again.",
        "Do not answer criticism by making a symbolic gift while preserving the extraction model underneath. The problem is structural imbalance in circulation, not public perception alone.",
        "Where has receiving become detached from contribution, and what concrete return of value would restore reciprocity rather than merely improve appearances?",
        "Line 6 exposes increase that has stopped circulating and requires genuine reciprocity before continued support can become stable again.",
      ),
    ],
  },
  {
    number: 43,
    coreTheme: "Breakthrough",
    coreMeaning: "Breakthrough describes a point when a harmful condition can no longer remain unspoken or indefinitely tolerated. Guai favors clear declaration, preparation, and principled support rather than sudden attack. The issue should be made explicit enough that people understand what must change, why it matters, and what consequences follow if the condition continues. Because the hexagram contains strong force pressing against a final resistant line, aggression is a constant risk: the majority can become intoxicated by its own certainty and turn necessary decision into humiliation or purge. The reading therefore distinguishes decisiveness from vindictiveness. Gather facts, state the matter publicly enough to prevent hidden manipulation, and act consistently after the declaration. Once the decision has been carried through, release the breakthrough posture. A system cannot remain permanently organized around removing an enemy without creating another form of imbalance.",
    strength: "clear declaration backed by resolve and principled support",
    challenge: "aggression, public accusation without preparation, or making a declaration larger than the evidence supports",
    orientation: "state what must change, gather legitimate support, and act firmly without vindictiveness",
    structureInterpretation: "Heaven below concentrates five strong yang lines while Lake above contains one yielding line at the top. Quick I Ching reads the structure as accumulated force reaching the point of declaration against a remaining obstruction. The strength must be governed because the imbalance makes overreaction easy.",
    reflectionQuestions: [
      "What condition has become clear enough that continuing not to name it now creates more harm than declaring it?",
      "What evidence and legitimate support should exist before a decisive public step is taken?",
      "How will you know that the breakthrough is complete so the system can stop organizing itself around opposition?",
    ],
    watchFor: [
      "A previously hidden or ambiguous problem becoming specific enough that people can evaluate the claim on shared facts.",
      "The coalition seeking change becoming more aggressive as its numerical or moral confidence increases.",
      "A decision being implemented consistently after declaration rather than remaining a dramatic statement with no operational follow-through.",
    ],
    transitionTheme: "hidden tension becoming an explicit and actionable decision",
    stabilityTheme: "resolve tied to evidence, transparent process, and an ability to stop after the issue is settled",
    lowerTrigram: "qian",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Strength in the advancing toes is premature",
        "The first line wants to move into breakthrough before preparation is complete. The cause may be justified, but the first surge of confidence is not enough to carry confrontation safely. Acting and then failing would weaken the very issue that needs correction.",
        "Change here converts impulsive resolve into preparation. The emerging pattern becomes stronger as evidence, support, and consequence are clarified before the decisive step is exposed to resistance.",
        "Do not mistake delay for cowardice when the action still lacks the conditions needed for success. But preparation should have an endpoint; endless readiness can become another form of avoidance.",
        "What must be true before this declaration or decisive move has enough support that failure will not simply strengthen the obstruction?",
        "Line 1 restrains premature breakthrough until preparation gives the first decisive step enough strength to survive resistance.",
      ),
      authoredLine(
        "Alertness at night prevents surprise",
        "The second line combines resolve with vigilance. Once a breakthrough process begins, resistance may appear at inconvenient or unexpected times. Preparation reduces fear: clear procedures, documented facts, contingency plans, and communication channels make sudden reaction less capable of derailing the course.",
        "As this line changes, alertness becomes operational readiness. The emerging pattern can stay calm under opposition because surprise no longer forces improvisation. Confidence grows from knowing how the system will respond if pressure increases.",
        "Vigilance can become paranoia if every ambiguous signal is treated as attack. Prepare for specific credible risks and continue to distinguish evidence from anticipation.",
        "What realistic counteraction should be prepared for now so that its arrival would not force a frightened or improvised response?",
        "Line 2 strengthens breakthrough through calm preparedness, making resistance less dangerous because the response has been considered in advance.",
      ),
      authoredLine(
        "Breakthrough written on the face creates isolation",
        "The third line warns against letting resolve become a public persona before the process is ready. Visible anger, contempt, or self-righteousness can alienate potential allies and make the issue look personal. Sometimes a necessary course must be carried quietly until evidence and timing support open declaration.",
        "Change here separates principle from emotional display. The emerging pattern gains credibility because the person can continue necessary contact without allowing facial or rhetorical hostility to announce a battle before the formal decision exists.",
        "Do not use strategic composure to hide a conflict of interest or deceive partners. The point is to avoid premature hostility, not to manipulate others about the direction you genuinely intend to take.",
        "What part of your anger or certainty is currently visible in a way that could make a principled issue look like a personal feud?",
        "Line 3 protects the credibility of breakthrough by keeping emotional hostility from becoming the public face of a still-developing decision.",
      ),
      authoredLine(
        "A wounded position needs guidance more than pushing",
        "The fourth line describes someone whose current position makes decisive movement awkward or painful. Pride may encourage continued pushing even though leverage is poor. Accepting guidance, changing the approach, or yielding tactical control can restore movement more effectively than insisting on leading from a compromised position.",
        "When this line changes, breakthrough becomes more collaborative and less ego-bound. The emerging pattern can use another person’s route, expertise, or timing without surrendering the underlying principle.",
        "Following guidance does not mean abandoning judgment. Verify that the proposed route serves the same purpose. Desperation can make any confident adviser look attractive.",
        "Where is your position too compromised to lead the breakthrough effectively, and whose guidance could improve the route without changing the principle?",
        "Line 4 loosens pride around a compromised position so capable guidance can restore movement toward the necessary decision.",
      ),
      authoredLine(
        "Cut through persistent weeds with a steady center",
        "The fifth line reaches a recurring obstruction that keeps returning if addressed only superficially. Decisive removal is appropriate, but the person must remain centered enough that the correction does not expand into indiscriminate hostility. Persistence is needed because the problem has roots.",
        "Change here converts breakthrough into completion of the difficult central task. The emerging pattern gains stability when the obstruction is removed at its source and the surrounding system is left capable of returning to ordinary operation.",
        "Root removal can become justification for treating every connected person or symptom as part of the enemy. Keep the target specific and verify that each action contributes to the actual source of recurrence.",
        "What keeps regenerating this problem after partial fixes, and how can you address that source without widening the campaign beyond it?",
        "Line 5 completes the central work of breakthrough by removing a recurring obstruction at its source while keeping correction tightly bounded.",
      ),
      authoredLine(
        "The final resistant condition cannot call for help forever",
        "At the top line, the remaining obstruction has little structural support but may still appeal, warn, or resist. The breakthrough is near completion. The task is to carry the decision through without allowing last-minute noise to reopen an issue that has already been legitimately settled.",
        "Change here ends the breakthrough cycle. The emerging pattern becomes healthy only if the coalition disbands its battle posture and the ordinary rules of the system return after the final obstruction is addressed.",
        "Do not silence a final objection merely because it comes from the losing side; a last fact can still matter. Confirm that the process is legitimate, then finish. After completion, continued aggression becomes its own problem.",
        "What final objection deserves one last factual check before the decision is completed and the breakthrough posture is deliberately ended?",
        "Line 6 completes a legitimate breakthrough after a final factual check, then releases the system from the identity of permanent opposition.",
      ),
    ],
  },
  {
    number: 44,
    coreTheme: "Coming to meet",
    coreMeaning: "Coming to meet describes the sudden appearance of an influence that is small in formal position but potentially large in effect. Gou asks for early recognition and boundary-setting because new forces can gain leverage faster than their initial size suggests. The influence might be a person, desire, technology, idea, opportunity, or dependency. The reading does not declare the newcomer evil; it asks what terms should govern contact before fascination or convenience normalizes access. Some lines favor containing the influence, some warn against aggressive rejection, and later positions show the costs of isolation or unexamined attraction. Mature response neither demonizes nor romanticizes what arrives. It places the influence accurately inside the larger system, makes participation conditional where necessary, and lets fascination end once the real function and limit are understood.",
    strength: "early recognition of a new influence before it gains hidden leverage",
    challenge: "underestimating a small force, becoming fascinated by it, or granting access before terms are clear",
    orientation: "assess the newcomer’s leverage early and define the terms under which it may participate",
    structureInterpretation: "Wind below introduces one yielding line beneath five strong yang lines of Heaven. Quick I Ching reads the structure as a small influence entering a powerful field from below. Because leverage can grow before formal power looks large, early terms and accurate placement matter more than later attempts at dramatic suppression.",
    reflectionQuestions: [
      "What new influence looks small now but could become structurally important if access expands without explicit terms?",
      "Which part of your attraction or resistance is based on the newcomer’s actual effects, and which part comes from novelty itself?",
      "What boundary would allow useful contact while preventing the relationship from becoming difficult to reverse?",
    ],
    watchFor: [
      "A new participant or dependency becoming more central before anyone has explicitly decided what authority or access it should have.",
      "Strong fascination or rejection making it harder to evaluate the influence according to ordinary evidence and standards.",
      "Clear early terms allowing the new influence to remain useful without quietly reorganizing the whole system around itself.",
    ],
    transitionTheme: "unexpected influence becoming bounded participation rather than hidden control",
    stabilityTheme: "early discernment that keeps fascination and fear from deciding the terms of contact",
    lowerTrigram: "xun",
    upperTrigram: "qian",
    lines: [
      authoredLine(
        "Apply the brake at the first point of entry",
        "The first line sees the new influence at the moment when a small restraint can still govern it. A clear condition, access rule, spending limit, trial period, or scope boundary may be enough. Early containment is less dramatic than later expulsion and provides better information about how the newcomer behaves under limits.",
        "Change here turns surprise into a controlled experiment. The emerging pattern gains safety because participation is reversible and the system can observe whether the influence respects terms before expanding access.",
        "Do not make the brake so absolute that no useful learning can occur. The purpose is governance, not panic. A boundary should permit enough contact to evaluate the influence honestly.",
        "What simple early condition would keep this new influence reversible while you learn whether it deserves wider access?",
        "Line 1 governs the newcomer at the first point of entry with a clear, reversible boundary before small influence becomes hidden leverage.",
      ),
      authoredLine(
        "Keep the fish in the container",
        "The second line finds the influence already present and potentially useful if contained within the proper domain. There is no need to display it publicly or extend it to every relationship. A bounded resource can serve well precisely because its scope is understood.",
        "As this line changes, containment becomes selective use. The emerging pattern gains practical benefit without requiring the whole system to reorganize around the newcomer. Local fit is treated as local evidence, not universal approval.",
        "Hidden containment can become secrecy that deprives affected people of necessary information. Keep scope limited, but disclose enough that those carrying the risk understand what is inside the container.",
        "Where is this new influence useful within a limited scope, and who still needs to know about it even if wider adoption is not appropriate?",
        "Line 2 keeps the newcomer inside a useful container, gaining local benefit without treating bounded success as a reason for unrestricted expansion.",
      ),
      authoredLine(
        "The urge to meet causes painful friction",
        "The third line feels drawn toward the new influence but lacks an easy or dignified route of contact. Pushing the relationship can create strain without producing real connection. The discomfort is useful because it slows the impulse and exposes whether the attraction is strong enough to survive limits.",
        "Change here turns frustrated pursuit into more deliberate judgment. The emerging pattern becomes clearer if the person stops forcing contact and watches whether a legitimate path develops through ordinary conditions.",
        "Do not interpret difficulty of access as proof that the object is especially valuable. Scarcity can intensify fascination. Evaluate the influence by what it actually contributes, not by how hard it is to reach.",
        "What are you valuing more because access is difficult, and what evidence would show whether the attraction survives once scarcity is removed from the picture?",
        "Line 3 lets painful friction slow fascination long enough to test whether the new influence deserves pursuit apart from the difficulty of access.",
      ),
      authoredLine(
        "An empty container shows lost connection",
        "The fourth line discovers that the influence or resource once expected to be available is absent. A relationship may have been neglected, a channel closed, or an opportunity lost because the system assumed access without maintaining the connection. Aggressive recovery is unlikely to help.",
        "When this line changes, absence becomes information about maintenance and relationship. The emerging pattern may require rebuilding trust, accepting loss, or designing a less dependent system rather than simply demanding the resource return.",
        "Do not blame the missing influence automatically. Ask what conditions made the connection unsustainable. A system that repeatedly loses access may be contributing to the pattern through entitlement or neglect.",
        "What relationship or resource has become unavailable, and what does its absence reveal about how the connection was maintained or taken for granted?",
        "Line 4 treats an empty container as evidence about neglected connection, redirecting attention from angry recovery toward maintenance, redesign, or acceptance of loss.",
      ),
      authoredLine(
        "Contain the ripe possibility without forcing it into view",
        "The fifth line holds a valuable development inside a protective covering. Something new may be maturing quietly and does not yet need public exposure or aggressive promotion. The central role is to create conditions in which the potential can ripen without being harvested early for status or reassurance.",
        "Change here turns disciplined containment into timely emergence. The emerging pattern becomes favorable when the development reaches enough maturity that appearance follows readiness instead of replacing it.",
        "Protection can become possessiveness or secrecy for its own sake. Define what maturity means. If the possibility is never tested outside the container, nobody can know whether it truly ripened.",
        "What promising new development needs protection from premature visibility, and what concrete sign would tell you it is ready to emerge?",
        "Line 5 protects a valuable newcomer while it matures, allowing visibility to follow readiness rather than using exposure to manufacture confidence.",
      ),
      authoredLine(
        "Meeting with horns produces isolation",
        "At the top line, the response to the newcomer has become hard, defensive, or combative. Strong boundaries may be justified, but if the entire relationship is organized around attack, the person can become isolated from useful information as well as from the unwanted influence. The task is to end fascination and hostility together.",
        "Change here releases the meeting as an active struggle. The emerging direction places the influence in its final scope—excluded, limited, or accepted—without continuing to define the whole system around resistance to it.",
        "Do not soften a necessary boundary merely to appear open-minded. The correction is not greater access; it is proportionate final placement without emotional overinvestment in the conflict.",
        "What final boundary would let you stop fighting with this influence and simply place it where it belongs in the larger system?",
        "Line 6 ends the encounter by replacing defensive preoccupation with a final proportionate placement of the influence inside or outside the system.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
