import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 41,
    coreTheme: "Decrease",
    legacySummary: "Deliberate reduction can restore balance. Let go of what is excessive so attention and resources can return to what is essential.",
    strength: "selective reduction that restores proportion and focus",
    challenge: "cutting what is essential, making sacrifice performative, or reducing without a purpose",
    orientation: "remove excess deliberately so the remaining structure can work better",
    transitionTheme: "overload becoming clarity when less is chosen in service of what matters most",
    stabilityTheme: "restraint that keeps resources aligned with genuine priorities",
    lowerTrigram: "dui",
    upperTrigram: "gen",
    lineEmphases: [
      "remove the first excess where reduction creates immediate clarity",
      "make decrease purposeful by protecting what is essential while trimming what is not",
      "pause when pressure for sacrifice starts cutting into the structure that needs protection",
      "carry a leaner approach into the wider field and test whether it actually improves function",
      "use central judgment to decide what reduction serves the whole rather than one narrow interest",
      "end the reducing phase when further cuts would destroy the balance they were meant to restore",
    ],
  },
  {
    number: 42,
    coreTheme: "Increase",
    legacySummary: "Growth is available when benefits circulate rather than accumulate narrowly. Invest where added energy strengthens the whole situation.",
    strength: "generative growth that distributes benefit and expands capacity",
    challenge: "unequal accumulation, growth without infrastructure, or adding more to a weak system",
    orientation: "direct added resources toward places where they increase shared capacity",
    transitionTheme: "available growth becoming durable increase when benefits circulate and foundations expand",
    stabilityTheme: "expansion that remains healthy because gains reinforce the whole",
    lowerTrigram: "zhen",
    upperTrigram: "xun",
    lineEmphases: [
      "direct the first extra resource toward a place where it can genuinely multiply usefulness",
      "make growth repeatable by strengthening capacity rather than simply adding volume",
      "slow expansion when pressure reveals that infrastructure is not keeping pace",
      "carry added benefit outward so increase does not remain concentrated in one part",
      "use a central position to distribute growth where it improves the whole system",
      "stop adding when increase has reached the point where more would weaken coherence",
    ],
  },
  {
    number: 43,
    coreTheme: "Breakthrough",
    legacySummary: "A problem needs to be named openly and addressed firmly. Clarity should precede action, and determination should not become aggression.",
    strength: "clear declaration joined to disciplined resolve",
    challenge: "aggression, public accusation without preparation, or declaring more than you can carry through",
    orientation: "state the issue plainly, gather support for the principle, and act without vindictiveness",
    transitionTheme: "hidden tension becoming explicit decision and cleaner boundaries",
    stabilityTheme: "resolve maintained by transparency, proportion, and follow-through",
    lowerTrigram: "qian",
    upperTrigram: "dui",
    lineEmphases: [
      "name the first unacceptable condition plainly before building momentum against it",
      "make resolve credible through facts, preparation, and conduct that can be defended",
      "keep determination from becoming aggression when resistance intensifies",
      "bring the declaration into the wider field with transparent reasons and proportionate action",
      "use central authority to follow through without humiliating those on the losing side",
      "release the breakthrough posture once the decision is made and a new order must be built",
    ],
  },
  {
    number: 44,
    coreTheme: "Coming to meet",
    legacySummary: "A small but potent influence is entering the situation. Recognize its character early and set boundaries before attraction or convenience gives it disproportionate power.",
    strength: "early recognition of a new influence before it becomes entrenched",
    challenge: "underestimating a small force, fascination, or granting access before understanding its effects",
    orientation: "notice what is entering, assess its leverage, and establish terms early",
    transitionTheme: "a new influence becoming either bounded participation or disproportionate control depending on early choices",
    stabilityTheme: "clear entry conditions that prevent novelty from quietly becoming dominance",
    lowerTrigram: "xun",
    upperTrigram: "qian",
    lineEmphases: [
      "notice the first small influence before convenience or attraction normalizes it",
      "set practical terms early enough that contact does not quietly become dependency",
      "reassess access when pressure reveals that a minor influence carries disproportionate leverage",
      "bring the new influence into the wider field only with boundaries others can understand",
      "use central judgment to decide what may participate without allowing it to dominate",
      "end fascination or resistance once the influence has been accurately placed and contained",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
