import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 45,
    coreTheme: "Gathering",
    legacySummary: "People or resources can collect around a center. Shared purpose, preparation, and trustworthy leadership determine whether gathering becomes coherence or crowding.",
    strength: "the ability to concentrate people and resources around a shared center",
    challenge: "crowding, symbolic unity without purpose, or gathering without reliable leadership",
    orientation: "make the center and purpose explicit before asking more people or resources to converge",
    transitionTheme: "dispersed elements becoming coordinated when the center can hold them",
    stabilityTheme: "cohesion maintained by clear purpose, rituals of trust, and accountable leadership",
    lowerTrigram: "kun",
    upperTrigram: "dui",
    lineEmphases: [
      "define the first real center before asking people or resources to gather around it",
      "make gathering coherent through ordinary practices of trust and shared purpose",
      "address crowding or competing agendas before pressure fragments the group",
      "open the gathering to the wider field while keeping purpose and responsibilities intelligible",
      "use central leadership to coordinate resources without making the center dependent on one personality",
      "let the gathering disperse or reorganize when the reason for assembling has been fulfilled",
    ],
  },
  {
    number: 46,
    coreTheme: "Pushing upward",
    legacySummary: "Steady ascent is possible through modest, cumulative effort. Seek support, do the next workable thing, and let progress build from a sound base.",
    strength: "patient upward development through accumulated small gains",
    challenge: "forcing rapid ascent, skipping support, or judging gradual progress as insignificant",
    orientation: "keep climbing through concrete steps and use available support without embarrassment",
    transitionTheme: "small gains becoming meaningful ascent through continuity and grounded effort",
    stabilityTheme: "progress sustained by humility, support, and attention to the next reachable level",
    lowerTrigram: "xun",
    upperTrigram: "kun",
    lineEmphases: [
      "take the first upward step that can be supported by the ground already gained",
      "make ascent cumulative through modest effort and useful assistance",
      "avoid forcing the next level when pressure reveals missing support underneath",
      "carry the developing work into a wider field without pretending it is further advanced than it is",
      "use a central opening to keep progress steady, supported, and connected to real capability",
      "stop climbing for its own sake when the ascent has reached the level the purpose required",
    ],
  },
  {
    number: 47,
    coreTheme: "Constraint",
    legacySummary: "External room is limited, so inner steadiness matters. Distinguish what cannot currently be changed from the commitments you can still uphold.",
    strength: "inner coherence when outer options are restricted",
    challenge: "despair, performative struggle, or wasting scarce energy on what cannot move",
    orientation: "identify the real constraint, conserve energy, and keep faith with the commitments still under your control",
    transitionTheme: "restriction becoming a test of what remains reliable when options narrow",
    stabilityTheme: "integrity preserved even when external validation or room to act is limited",
    lowerTrigram: "kan",
    upperTrigram: "dui",
    lineEmphases: [
      "name the first real constraint so energy is not wasted fighting an imaginary one",
      "protect an inner commitment that remains possible despite limited external room",
      "avoid despair or performative struggle when pressure narrows the available options",
      "carry integrity into the wider field without promising control you do not possess",
      "use a central role to allocate scarce attention and resources toward what still matters",
      "leave the identity of being constrained when the restriction has changed or been exhausted",
    ],
  },
  {
    number: 48,
    coreTheme: "The well",
    legacySummary: "A durable source of nourishment may already exist, but access and maintenance matter. Improve the shared resource and the means by which people draw from it.",
    strength: "attention to common resources and the infrastructure that makes them usable",
    challenge: "neglecting maintenance, guarding access unfairly, or possessing a resource nobody can effectively use",
    orientation: "improve both the shared source and the practical means of reaching it",
    transitionTheme: "latent value becoming dependable support when access and maintenance are repaired",
    stabilityTheme: "common resources kept useful through stewardship and reliable access",
    lowerTrigram: "xun",
    upperTrigram: "kan",
    lineEmphases: [
      "inspect the first point of access to the shared resource before assuming the source itself is weak",
      "make maintenance and access reliable in ordinary use, not only during crisis",
      "repair neglected infrastructure when pressure exposes a gap between available value and usable value",
      "bring the resource into wider reach without damaging the source or making access arbitrary",
      "use central stewardship to keep the common source maintained, trusted, and fairly usable",
      "renew the vessel or access method when tradition has become an obstacle to the resource it once served",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
