import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 45,
    coreTheme: "Gathering",
    coreMeaning: "Gathering describes people, resources, and attention concentrating around a center. Cui asks whether that center is clear enough to justify the concentration. Crowds create energy but also ambiguity: people can arrive for different reasons, assume different obligations, and mistake emotional unity for actual coordination. The reading favors visible purpose, trustworthy leadership, and practical rituals or structures that help a group know what it belongs to. Early gathering may include confusion or tears; a strong center can turn emotion into organized participation. The later lines remind you that gathering has a life cycle. If the purpose is fulfilled or the center loses legitimacy, the group should be able to disperse or reorganize without treating separation as betrayal. Cohesion is healthiest when it can explain both why people come together and when the gathering no longer needs to remain concentrated.",
    strength: "the ability to concentrate people and resources around a meaningful center",
    challenge: "crowding, symbolic unity without coordination, or gathering without trustworthy leadership",
    orientation: "make the center and purpose explicit, then organize participation around them",
    structureInterpretation: "Earth below provides a receptive field while Lake above creates openness and collective exchange. Quick I Ching reads the structure as many elements gathering into a shared basin. Concentration becomes useful when the center can hold different contributions without turning the crowd into undifferentiated mass.",
    reflectionQuestions: [
      "What exactly are people gathering around, and would the purpose still be clear to someone outside the inner circle?",
      "Which responsibility, ritual, or decision process would turn emotional unity into actual coordination?",
      "What condition would tell you that this gathering has served its purpose and should disperse, reorganize, or decentralize?",
    ],
    watchFor: [
      "A crowd becoming a coordinated group because roles, purpose, and decision rights become more visible.",
      "Strong emotion or symbolic belonging masking the fact that participants are pursuing incompatible aims.",
      "A central person or institution becoming so indispensable that the gathering cannot imagine functioning without it.",
    ],
    transitionTheme: "scattered people and resources becoming coordinated around a trustworthy center",
    stabilityTheme: "cohesion maintained by explicit purpose, credible leadership, and accountable participation",
    lowerTrigram: "kun",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Confused gathering needs a clear signal",
        "The first line shows people drawn together without enough certainty about whom or what to follow. Emotion can swing quickly between confidence and distress because the center has not yet become unmistakable. One clear call, commitment, or organizing act can reduce the noise if it genuinely represents the purpose.",
        "Change here turns scattered attraction into recognizable gathering. The emerging pattern improves when participants can identify the center and know what joining actually asks of them rather than relying on mood or crowd behavior.",
        "Do not manufacture unity through a dramatic signal that lacks real authority. A loud call can gather people temporarily while making later disillusionment worse. The center needs legitimacy, not just visibility.",
        "What clear signal or commitment would let people know what this gathering is actually for and whether they truly intend to join it?",
        "Line 1 converts emotional, uncertain gathering into recognizable participation by making the center and commitment clear enough to choose.",
      ),
      authoredLine(
        "Being drawn into the gathering can be right",
        "The second line allows responsive participation when a trustworthy pull is already present. You do not need to control the whole gathering or possess elaborate credentials before joining. A modest, sincere contribution can be enough if the center is sound and the relationship is real.",
        "As this line changes, attraction becomes practical membership. The emerging pattern gains strength because participation begins with an appropriate offering rather than with a demand for status or full control.",
        "Being invited or attracted does not remove the need for discernment. Verify the purpose and terms before allowing social momentum to make the decision for you. A strong pull is evidence of connection, not proof of goodness.",
        "What modest contribution would let you test this gathering through participation without pretending you already understand or control the whole?",
        "Line 2 joins a trustworthy gathering through a sincere, proportionate contribution rather than waiting for perfect certainty or demanding central status.",
      ),
      authoredLine(
        "Gathering without belonging produces sighs",
        "The third line describes being near a group but not truly integrated into it. People are present, yet the needed connection or recognition is missing. The useful response may be to approach a more fitting ally or role rather than trying to force acceptance from the whole crowd.",
        "Change here turns diffuse loneliness into a specific connection. The emerging pattern becomes more workable when one credible relationship gives the person a real point of participation inside or adjacent to the larger gathering.",
        "Do not assume exclusion proves the group is wrong or that you are unworthy. Fit can be local and role-specific. Equally, do not keep chasing belonging where the terms repeatedly show that no real place exists.",
        "Which specific person, role, or subgroup offers a genuine point of connection instead of leaving you to seek approval from the whole crowd?",
        "Line 3 addresses alienation inside a gathering by finding one real point of connection rather than forcing belonging at the level of the entire group.",
      ),
      authoredLine(
        "A strong organizer can create broad good fortune",
        "The fourth line places substantial coordinating power inside the gathering. Someone can connect people, allocate resources, and make collective action possible. This is favorable when the organizer serves the purpose rather than using the crowd as proof of personal importance.",
        "When this line changes, gathering becomes operational capacity. The emerging pattern gains momentum because leadership converts presence into roles, sequence, and shared action instead of leaving energy unstructured.",
        "Organizational success can make the coordinator indispensable. Build processes and other leaders so the group’s coherence does not depend entirely on one person’s continual presence.",
        "How can central coordination turn this crowd into useful collective action while making the group less, not more, dependent on the organizer?",
        "Line 4 converts gathering into coordinated capability through strong organization that serves the shared purpose rather than personal centrality.",
      ),
      authoredLine(
        "Central position does not automatically create trust",
        "The fifth line occupies the recognized center of the gathering, yet some participants may still lack confidence. Position alone cannot solve that problem. Consistent conduct, transparent decisions, and visible service to the shared purpose must demonstrate why the center deserves continued alignment.",
        "Change here turns formal centrality into earned legitimacy. The emerging pattern becomes more durable as trust moves from office or title toward repeated evidence that the center uses authority fairly and responsibly.",
        "Do not respond to doubt by demanding stronger displays of loyalty. Coerced reassurance hides the information leadership needs most. Let skepticism remain audible enough that the center can learn what credibility is missing.",
        "What repeated conduct would make this center trustworthy even to people who do not already feel personal loyalty toward it?",
        "Line 5 makes the center of a gathering earn trust through consistent stewardship instead of relying on position to manufacture confidence.",
      ),
      authoredLine(
        "Tears at the edge of the gathering reveal the end of concentration",
        "At the top line, attachment to the gathering can become painful because the period of concentration is ending or because belonging remains unavailable. Grief is not necessarily a sign that the group should be forced to stay together. It may simply acknowledge that the connection mattered and is changing form.",
        "Change here releases the need to maintain gathering at all costs. The emerging direction can preserve relationship, memory, or purpose in a looser structure once concentration no longer serves the whole.",
        "Do not use emotion to pressure people into remaining. A meaningful gathering can end without being invalidated. Conversely, do not rush past grief so quickly that lessons and commitments are abandoned carelessly.",
        "What should be honored or carried forward even if this gathering now needs to disperse or change its form?",
        "Line 6 lets a gathering end or loosen without denying its value, preserving what matters while releasing concentration that has completed its purpose.",
      ),
    ],
  },
  {
    number: 46,
    coreTheme: "Pushing upward",
    coreMeaning: "Pushing upward describes gradual ascent earned through steady development and receptive support. Sheng is not a leap. Its strength lies in accumulating capability, relationships, and trust until higher responsibility becomes a natural extension of what has already been demonstrated. The reading favors modest beginnings, willingness to seek support, and respect for sequence. Pressure can tempt someone to claim a level before the supporting stage is ready; the result is an unstable ascent that requires constant performance to maintain. Genuine upward movement often looks unremarkable while it is happening because each step is small enough to be integrated. At the highest point, climbing itself must stop being the purpose. The question becomes what the elevated position is for and whether further ascent still serves the underlying work. A good rise increases usefulness rather than merely altitude.",
    strength: "cumulative advancement built through repeated work and support",
    challenge: "forcing ascent, skipping foundational stages, or dismissing gradual progress as too small",
    orientation: "build upward through supported steps and let each stage prove itself before taking the next",
    structureInterpretation: "Wind below penetrates gradually like roots while Earth above provides a receptive field through which growth can rise. Quick I Ching reads the structure as ascent from below: development gains height because roots, support, and repeated effort continue to work rather than because one dramatic push overcomes the whole distance.",
    reflectionQuestions: [
      "What stage of advancement has already been earned through evidence rather than merely desired?",
      "Which support, skill, or relationship must mature before the next level can be carried without performance or strain?",
      "At what point would continuing to climb stop serving the purpose that made advancement valuable in the first place?",
    ],
    watchFor: [
      "A small but repeatable capability opening access to a higher level of responsibility without requiring a dramatic leap.",
      "Status or urgency pressuring the person to skip a stage whose missing support later becomes a hidden weakness.",
      "Advancement beginning to create more useful contribution rather than simply more distance from the work that built credibility.",
    ],
    transitionTheme: "small gains becoming real ascent when each stage strengthens the next",
    stabilityTheme: "humble upward movement supported by roots, relationships, and repeated capability",
    lowerTrigram: "xun",
    upperTrigram: "kun",
    lines: [
      authoredLine(
        "Confident rise begins from below",
        "The first line starts upward movement where roots and support are still close. Confidence is appropriate because the direction has contact with real ground. The first advance should demonstrate that growth can occur without disconnecting from the practices and relationships that nourish it.",
        "Change here turns latent development into visible ascent. The emerging pattern gains credibility because the first step remains supported and modest enough to integrate rather than forcing the system to pretend it is already higher than it is.",
        "Do not despise the low starting point or rush to erase it. Early contact with the ground supplies feedback that becomes harder to obtain later. Preserve the source of practical learning while moving upward.",
        "What first upward step is already supported strongly enough that taking it would confirm, rather than speculate about, your readiness?",
        "Line 1 begins ascent with a grounded, confident step whose modest scale keeps the source of support and learning intact.",
      ),
      authoredLine(
        "Sincere effort can substitute for elaborate display",
        "The second line shows that genuine contribution does not need expensive ceremony or perfect presentation to justify advancement. A modest offering, if sincere and fit for purpose, can earn trust because substance is visible. This is useful when someone delays progress because they think they lack the symbols associated with the next level.",
        "As this line changes, upward movement becomes less dependent on status signaling. The emerging pattern rewards credible work and relationship, allowing limited resources to become sufficient when intention and execution are sound.",
        "Sincerity does not excuse poor preparation. A modest offering still needs to meet the real requirement. The warning is against unnecessary display, not against competence.",
        "What simple but substantive contribution could demonstrate readiness more clearly than another attempt to look fully established?",
        "Line 2 allows sincere, sufficient substance to support ascent without waiting for the elaborate signals usually associated with higher status.",
      ),
      authoredLine(
        "Rise through an empty city",
        "The third line encounters little resistance. A route may open quickly because the field is underoccupied, the need is obvious, or previous barriers have disappeared. This can create rapid progress, but the ease also means there may be fewer structures available to support what comes next.",
        "Change here accelerates ascent while increasing the need for self-organization. The emerging pattern can use the open route, but must build its own routines and standards rather than assuming the absence of obstacles means the next level is already mature.",
        "Easy advancement can hide missing feedback. If nobody resists or competes, weak assumptions may survive longer. Create deliberate review where the environment does not naturally provide it.",
        "What support or standard should you build yourself because this unusually open path is letting you rise faster than the surrounding structure can train you?",
        "Line 3 uses an open route for advancement while compensating for the lack of resistance by creating its own standards and feedback.",
      ),
      authoredLine(
        "Recognition at the sacred mountain",
        "The fourth line reaches a stage where advancement is acknowledged by a larger institution, tradition, or authority. The recognition matters because it connects individual development to a wider order. The person is not merely higher; the new position has been received into a structure that gives it meaning and responsibility.",
        "When this line changes, ascent becomes legitimate placement. The emerging pattern gains durability because advancement is no longer private self-assertion but part of an acknowledged system of roles and obligations.",
        "Institutional recognition can become status intoxication. Keep contact with the work that justified the ascent and examine whether the institution’s standards remain worthy rather than treating recognition itself as proof.",
        "What larger standard or institution should this next level of advancement become accountable to, not merely recognized by?",
        "Line 4 turns upward movement into legitimate placement by connecting advancement to a larger structure of meaning and responsibility.",
      ),
      authoredLine(
        "Ascend step by step",
        "The fifth line states the core method of Sheng plainly: the strongest central ascent proceeds by sequence. Each level should be stable enough that the next does not need to compensate for an unresolved weakness below. This is disciplined progress, not timid progress.",
        "Change here turns gradual advancement into durable authority. The emerging pattern can carry more because each new responsibility rests on a stage already practiced and integrated.",
        "Stepwise progress can become bureaucratic delay if every stage is treated as sacred regardless of evidence. Sequence should protect capability, not preserve unnecessary gates. Skip only what has truly become redundant.",
        "Which next step is small enough to integrate fully but substantial enough to prove readiness for the level after it?",
        "Line 5 makes ascent durable through a sequence in which every level is practiced enough to support the responsibility built above it.",
      ),
      authoredLine(
        "Blind upward movement must become inward persistence",
        "At the top line, climbing can continue after the purpose of ascent has become unclear. The person may be moving upward because upward movement itself has become identity. When the higher destination is no longer visible, persistence should turn toward internal standards rather than another increase in altitude.",
        "Change here releases advancement from the compulsion to climb. The emerging direction may consolidate, serve, deepen mastery, or redirect effort toward work whose value does not depend on occupying a higher position.",
        "Do not mistake plateau for failure simply because the culture rewards constant advancement. But also do not use reflection to avoid a genuinely open next step. The question is whether height still serves the purpose.",
        "If no further title, scale, or rank were available, what part of the work would still deserve persistent development?",
        "Line 6 ends blind ascent by redirecting persistence toward purpose and mastery rather than treating continued height as the only form of progress.",
      ),
    ],
  },
  {
    number: 47,
    coreTheme: "Constraint",
    coreMeaning: "Constraint describes a period when options, resources, or influence are genuinely limited. Kun asks for inner coherence when outer freedom is small. The danger is not only scarcity itself but the stories scarcity produces: despair, frantic promises, performative struggle, or wasting the remaining capacity trying to appear unconstrained. The reading favors accurate inventory and credible commitments. Some words carry little weight in a constrained environment; conduct matters more. Support may be limited, but a trustworthy center can still preserve dignity and allocate scarce resources according to priority. Constraint is not necessarily permanent. When conditions change, the person must be willing to leave the identity of being trapped rather than recreating the old limitation psychologically. Until then, conserve what still works, keep promises small enough to honor, and refuse to let pressure determine every standard.",
    strength: "inner coherence and responsible allocation when external options are limited",
    challenge: "despair, performative struggle, or wasting scarce capacity on appearances",
    orientation: "name the real constraint, conserve what works, and make only commitments that can be carried",
    structureInterpretation: "Water below places danger and scarcity inside while Lake above opens outward but is deprived of an easy source. Quick I Ching reads the structure as a system whose expression exceeds its available supply. Integrity depends on accepting the limit and governing the remaining capacity rather than pretending abundance still exists.",
    reflectionQuestions: [
      "What resource or option is genuinely constrained, and which part of your suffering comes from resisting that fact rather than from the limit itself?",
      "What promise can still be kept reliably even under these conditions, and what commitment should not be made right now?",
      "Which capability or relationship must be protected because it will matter most when the constraint eventually loosens?",
    ],
    watchFor: [
      "Scarce resources becoming easier to manage after priorities are made explicit and symbolic commitments are reduced.",
      "People making larger promises to compensate emotionally for having less ability to deliver.",
      "External conditions improving while old habits of scarcity continue to restrict choices that are actually available again.",
    ],
    transitionTheme: "restriction testing which commitments and capacities remain genuinely reliable",
    stabilityTheme: "integrity preserved by accepting real limits without making them the whole identity",
    lowerTrigram: "kan",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Sitting under a barren tree deepens the constraint",
        "The first line shows a person remaining in an unproductive place after the constraint is already evident. Isolation, shame, or numbness can keep attention fixed on what cannot nourish. The first improvement may simply be to move toward a position where information, support, or basic function is still available.",
        "Change here turns passive confinement into a search for a more viable footing. The emerging pattern gains options because the person stops treating the current barren position as the only place from which the problem can be faced.",
        "Do not confuse relocation with escape from responsibility. The move is useful if it improves access to real capacity. Simply changing scenery without changing the pattern may preserve the same constraint elsewhere.",
        "What barren position are you remaining in mainly because constraint has made movement feel pointless, and where would a more viable footing exist?",
        "Line 1 begins release from constraint by leaving an unproductive position and recovering access to information, support, or basic function.",
      ),
      authoredLine(
        "Provision exists, but formal help arrives slowly",
        "The second line has enough for basic survival yet still lacks the larger support or recognition needed to solve the constraint. Relief may come through an authority, institution, or relationship, but timing cannot be forced. Maintain ordinary obligations and be ready to receive help without treating delay as abandonment.",
        "As this line changes, scarcity becomes a relationship with incoming support. The emerging pattern can use assistance well because the center has remained orderly instead of making desperate commitments while waiting.",
        "Comfort at the basic level can hide a deeper unresolved limit, while impatience can make promised help seem more certain than it is. Keep both the sufficiency and the remaining constraint visible.",
        "What can you maintain responsibly with what you have now while waiting for larger support that is not yet under your control?",
        "Line 2 preserves ordinary order inside constraint so delayed outside support can be received without having to rescue additional damage created by impatience.",
      ),
      authoredLine(
        "Pressed by stone and leaning on thorns",
        "The third line experiences constraint from both the hard obstacle ahead and the poor support chosen for relief. Pushing one direction hurts; resting in the wrong place also hurts. This is a signal that the current map is not producing a viable choice and needs external perspective.",
        "Change here breaks the false binary between two painful options. The emerging pattern may come from asking for help, revisiting assumptions, or accepting that a familiar support is itself part of the constraint.",
        "Desperation makes weak supports look better than they are. Do not lean harder on a relationship, habit, or resource that repeatedly adds harm simply because the main obstacle is also severe.",
        "Which supposed source of support is actually adding pain to the constraint, and what third option becomes visible if you stop relying on it?",
        "Line 3 exposes a false choice between obstruction and harmful support, opening the search for a genuinely different source of relief.",
      ),
      authoredLine(
        "Help comes slowly because status and apparatus obstruct it",
        "The fourth line wants to respond to constraint but is delayed by its own position, procedure, or heavy apparatus. Formal resources can paradoxically make movement slower. The problem is not lack of goodwill but friction between responsibility and the mechanisms available to carry it.",
        "When this line changes, support becomes more direct. The emerging pattern improves as unnecessary layers are removed and the person in the outer role finds a simpler route to the actual need.",
        "Do not use bureaucracy as a moral excuse for delay. If the current process repeatedly prevents necessary support, part of the responsibility is to redesign the process rather than merely apologize for it.",
        "What formal layer is making helpful action slower than the situation can afford, and which step could be removed without losing accountability?",
        "Line 4 turns constrained support into more direct action by reducing the procedural weight that has been delaying an otherwise genuine response.",
      ),
      authoredLine(
        "Cut by authority, yet a center for trust remains",
        "The fifth line sits in central responsibility while feeling constraint from above, below, or both. Resources and freedom may be restricted, but credibility can still be maintained through fair allocation and honest communication. A ritual, standard, or shared practice can preserve coherence until the pressure changes.",
        "Change here turns central suffering into institutional trust. The emerging pattern becomes more resilient because people know what standard will govern scarce decisions even when nobody can offer abundance.",
        "Authority under pressure can become punitive simply to feel effective. Do not make scarcity a reason to humiliate or silence. Transparent limits often preserve more order than performative toughness.",
        "What fair standard should govern scarce decisions here so people can trust the center even when it cannot give everyone what they want?",
        "Line 5 preserves trust under severe constraint by making central allocation transparent, fair, and connected to a shared standard.",
      ),
      authoredLine(
        "Entangled by vines, the final constraint is partly self-maintained",
        "At the top line, some external restriction remains, but habits of fear, resentment, or repeated avoidance may now be helping the bind persist. Movement feels risky because the person has learned the constraint so thoroughly that every available opening is interpreted through the old danger.",
        "Change here distinguishes the remaining real limit from the internal pattern that no longer needs to continue. The emerging direction becomes possible through a small committed move that tests the new conditions instead of assuming the old constraint still governs everything.",
        "Do not blame yourself for a constraint that was genuinely imposed. Internal habits are secondary adaptations, not proof that the original pressure was imaginary. Work only on the part that is now within your control.",
        "Which part of the current bind is still externally real, and which part survives mainly because you are continuing a protective habit that the new conditions no longer require?",
        "Line 6 begins leaving constraint by separating the remaining real limits from protective habits that have outlived the conditions that created them.",
      ),
    ],
  },
  {
    number: 48,
    coreTheme: "The well",
    coreMeaning: "The well describes a shared resource whose value depends on access, maintenance, and trustworthy stewardship. Jing asks you to look beneath changing surface arrangements to the infrastructure that repeatedly supports people: knowledge, water, public systems, institutional memory, community trust, or other common capacities. A good source can remain unused because the access mechanism is broken; a poor source can be mistaken for adequacy because everyone has adapted to low expectations. The reading therefore separates source quality from delivery quality. Clean the well, repair the rope and vessel, distribute access fairly, and keep the source protected enough to remain viable. Tradition is useful only if it still gets water to people. At the highest point the well is open and dependable, but even then stewardship remains necessary so shared benefit does not become careless depletion.",
    strength: "the ability to maintain and distribute a common source of value",
    challenge: "neglected maintenance, unfair access, or having a good resource that cannot actually be used",
    orientation: "inspect both the source and the access system, then repair what prevents reliable shared use",
    structureInterpretation: "Wind below penetrates downward while Water above represents the source being drawn upward. Quick I Ching reads the structure as infrastructure connecting depth to use. The value of the well depends not only on what exists below but on whether the system can repeatedly reach, lift, and share it.",
    reflectionQuestions: [
      "Is the main problem the quality of the shared resource, or the mechanism by which people gain access to it?",
      "What maintenance task has been deferred because the source continued functioning just well enough to hide the accumulating risk?",
      "Who lacks fair access to a resource that is already strong enough to serve them if the delivery system were repaired?",
    ],
    watchFor: [
      "A valuable resource remaining underused because access, distribution, or maintenance creates more friction than the source itself.",
      "People compensating for degraded infrastructure until poor service becomes normalized as the expected standard.",
      "A repaired access mechanism making old shared capacity newly useful without requiring the source itself to be reinvented.",
    ],
    transitionTheme: "latent common value becoming reliable support when access and maintenance are restored",
    stabilityTheme: "shared stewardship that keeps both source quality and distribution trustworthy",
    lowerTrigram: "xun",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Muddy water is not yet fit to use",
        "The first line looks directly at source quality. If the well itself is contaminated, neglected, or exhausted, improving access will only distribute the problem faster. The first task is cleanup, restoration, or honest recognition that the current source cannot yet support normal use.",
        "Change here turns a degraded source toward rehabilitation. The emerging pattern begins beneath the surface: remove contamination, restore basic quality, and establish evidence that the source is becoming usable before inviting wider demand.",
        "Do not spend resources polishing the access point while the underlying source remains poor. Presentation can hide degradation for a time but increases eventual harm by encouraging trust in an unready resource.",
        "What evidence about the underlying source must improve before it is responsible to increase access or encourage wider use?",
        "Line 1 puts source quality before distribution, restoring the well itself before making an impaired resource easier for more people to reach.",
      ),
      authoredLine(
        "A leaking vessel wastes good water",
        "The second line finds value in the source but a weak method of drawing or holding it. Knowledge, money, trust, or capability may exist, yet the delivery mechanism loses much of it before it reaches the user. Repairing the container can create more effective capacity than increasing the source.",
        "As this line changes, the system becomes better at converting latent value into usable provision. The emerging pattern gains efficiency because fewer resources are lost through broken handoffs, poor tools, or weak retention.",
        "Do not blame users for failing to benefit from a resource that arrives inconsistently or damaged. If the vessel leaks, demand-side discipline will not solve the delivery failure.",
        "Where is a good resource being lost through a broken handoff, tool, process, or container before it reaches the people who need it?",
        "Line 2 repairs the delivery vessel so existing value can actually reach users instead of being lost between source and use.",
      ),
      authoredLine(
        "Clean water unused is a failure of recognition or access",
        "The third line shows a good source that people are not using. The problem may be awareness, trust, authority, location, or an access rule that makes the resource effectively invisible. This is frustrating because the capacity already exists; the task is to connect recognition with use.",
        "Change here turns hidden quality into available support. The emerging pattern benefits when credible people can see, verify, and authorize use of what has already been restored rather than commissioning an unnecessary replacement.",
        "Do not assume unused capacity proves users are irrational. Access barriers can be subtle. Study why people are not drawing from the source before spending more effort advertising its quality.",
        "What prevents people from using this already-good resource: lack of trust, awareness, permission, convenience, or a problem in the access path?",
        "Line 3 converts an unused good source into shared value by removing the recognition or access barrier that has kept people from drawing from it.",
      ),
      authoredLine(
        "Repair the well wall before demanding more output",
        "The fourth line focuses on maintenance of the surrounding structure. Even a good source and functional vessel will fail if the infrastructure itself is crumbling. A period of reduced output may be justified so walls, platforms, security, records, or governance can be rebuilt properly.",
        "When this line changes, maintenance creates future reliability. The emerging pattern can support more use because the structure around the source is no longer depending on deferred repair and luck.",
        "Maintenance windows can become excuses for endless closure if scope and completion are vague. Define what must be repaired and how readiness for reopening will be tested.",
        "What infrastructure around this shared resource needs a real maintenance period before another increase in demand is responsible?",
        "Line 4 accepts temporary reduction in use so the well’s surrounding structure can be repaired before deferred maintenance becomes failure.",
      ),
      authoredLine(
        "A clear cold well can be trusted",
        "The fifth line shows the source, access, and quality aligned well enough for ordinary use. The emphasis is dependable provision rather than dramatic abundance. People can draw from the resource because standards are clear and the result consistently meets the need.",
        "Change here turns infrastructure into public trust. The emerging pattern becomes part of normal life because reliability no longer requires special intervention. The resource earns confidence through repeatable service.",
        "Success can reduce maintenance attention precisely when the system appears easiest. Keep monitoring quality and capacity. A trustworthy well remains trustworthy because stewardship continues after crisis disappears.",
        "What routine measure would show that this shared resource remains consistently fit for use instead of relying on reputation from its last successful period?",
        "Line 5 establishes trust in the well through repeatable quality and ordinary access while keeping maintenance active after reliability is restored.",
      ),
      authoredLine(
        "An open well should remain accessible and protected",
        "At the top line, the shared resource is fully usable and does not need to be hidden or unnecessarily restricted. Broad access can create real common benefit when the source is strong enough and governance protects it from depletion. Openness becomes the culmination of good stewardship.",
        "Change here turns a maintained resource into a durable commons. The emerging pattern spreads value widely because the system trusts its source, access mechanism, and users enough to reduce needless barriers.",
        "Open access without stewardship can exhaust even a strong source. Keep monitoring total load, abuse, and renewal. The goal is generous availability, not a fiction that common resources have no limits.",
        "How can access become more open while preserving the monitoring, contribution, and renewal needed to keep the shared source viable?",
        "Line 6 completes the well by making dependable value broadly accessible while retaining the stewardship that prevents openness from becoming depletion.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
