import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 49,
    coreTheme: "Revolution",
    coreMeaning: "Revolution describes a change of form that becomes legitimate only after the old arrangement has exhausted its ability to carry the situation. Ge is not a license for rebellion whenever frustration rises. It asks for timing, evidence, public trust, and a coherent replacement. Before the moment is ripe, restraint protects credibility. Once the need is established, transformation should be visible enough that people understand what is ending and what new standard will govern afterward. A change that only removes the old system without creating a trustworthy new one prolongs instability. The later lines emphasize stabilization: mature transformation eventually stops calling itself revolutionary and becomes ordinary order. The reading therefore favors preparation before rupture, decisive implementation at the right time, and disciplined transition afterward so the new form does not depend on permanent opposition to the old.",
    strength: "the ability to transform an exhausted form when timing and legitimacy are sufficient",
    challenge: "premature rebellion, cosmetic change, or replacing the old without a credible new structure",
    orientation: "build the case, wait for the right moment, and make the new form coherent enough to earn trust",
    structureInterpretation: "Fire below creates clarity and pressure while Lake above opens the social field to exchange and response. Quick I Ching reads the structure as change becoming public: insight about what no longer works must meet collective trust and timing before transformation can become legitimate rather than merely disruptive.",
    reflectionQuestions: [
      "What evidence shows that the existing form is exhausted rather than simply uncomfortable or temporarily underperforming?",
      "What new rule, structure, or responsibility will exist the day after the old arrangement is changed?",
      "How will the transformation stop being a permanent campaign and become ordinary trustworthy operation?",
    ],
    watchFor: [
      "Dissatisfaction becoming a shared, evidence-based case for change rather than a coalition held together mainly by anger.",
      "A dramatic rebrand or leadership change occurring while the incentives and routines that produced the old problem remain intact.",
      "The new structure becoming boringly reliable enough that people no longer need revolutionary language to believe it will hold.",
    ],
    transitionTheme: "an exhausted form giving way to a legitimate new structure at the right time",
    stabilityTheme: "post-change order made credible through consistent new rules rather than continuing opposition",
    lowerTrigram: "li",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Bind the first revolutionary impulse",
        "The first line sees the need for change before the moment for open transformation has arrived. Strong feeling should be bound to preparation: gather facts, understand dependencies, and protect credibility. Acting too early can let the old system portray legitimate reform as reckless disruption.",
        "Change here turns dissatisfaction into disciplined readiness. The emerging pattern becomes stronger because the reformer learns what must replace the old form before asking others to endure the rupture of change.",
        "Restraint can become fear if preparation has no decision point. Define what evidence or support would make the timing ripe so caution does not simply preserve the status quo indefinitely.",
        "What must be prepared before open change begins so the first decisive act cannot be dismissed as an impulsive revolt?",
        "Line 1 restrains the first revolutionary impulse long enough to build the evidence, replacement, and timing that later change will need.",
      ),
      authoredLine(
        "Change becomes timely when the day is clear",
        "The second line reaches a moment when transformation can be announced and acted upon because the case is sufficiently mature. The person should still prepare the immediate transition, but hesitation now has a different risk: leaving an exhausted form in place after the conditions for responsible change have arrived.",
        "As this line changes, preparation becomes implementation. The emerging pattern gains legitimacy because action occurs at a recognizable moment and follows a reason that others can understand, not merely the reformer’s private impatience.",
        "A favorable moment does not excuse vague execution. Make responsibilities, sequencing, and consequences visible before asking people to cross into the new arrangement.",
        "What has become clear enough that delaying change now would protect the old form more than it would protect the people affected by transition?",
        "Line 2 recognizes the ripe moment for transformation and converts a prepared case into visible, responsible implementation.",
      ),
      authoredLine(
        "Repeated argument must become settled conviction",
        "The third line warns against either rushing change after one complaint or debating forever after the evidence is already clear. A transformation should survive repeated examination. When the same conclusion returns after serious discussion, conviction becomes more trustworthy than enthusiasm.",
        "Change here turns contested reform into a decision supported by tested reasoning. The emerging pattern can move because objections have been heard enough that continued repetition would no longer improve the judgment.",
        "Do not count repetitions as proof if every discussion occurred inside the same faction. The case needs genuine challenge, not ritual confirmation. Once tested, however, endless reopening can become sabotage by delay.",
        "Which serious objection still needs examination, and which argument has already been tested enough that continuing to relitigate it no longer improves the decision?",
        "Line 3 makes revolutionary conviction credible by surviving genuine repeated scrutiny and then refusing endless debate once the case is settled.",
      ),
      authoredLine(
        "Trust permits the mandate to change",
        "The fourth line shows transformation gaining legitimacy because the person or group leading it is trusted. This trust should come from conduct and clarity, not simply from occupying power. When people believe the motive and method are sound, a major change can occur without every detail being interpreted as hidden self-interest.",
        "When this line changes, legitimacy becomes operational freedom. The emerging pattern can redesign the structure more deeply because trust lowers the defensive friction that usually surrounds large transitions.",
        "Trust is not a blank check. Keep decision-making transparent and preserve mechanisms for correction. A leader who spends accumulated credibility carelessly can lose the mandate faster than it was built.",
        "What conduct has earned enough trust to support this change, and what transparency will keep that trust from becoming unquestioned permission?",
        "Line 4 gives transformation a credible mandate through earned trust while preserving the accountability needed after the change begins.",
      ),
      authoredLine(
        "The new pattern becomes visible before divination is needed",
        "The fifth line represents transformation at its strongest: the new form is coherent enough that people can see its direction in conduct, design, and leadership. Confidence no longer depends on constant reassurance. The change itself demonstrates a recognizable pattern capable of organizing the next phase.",
        "Change here turns revolution into established leadership. The emerging structure gains authority because the new rules are visible and internally consistent rather than merely defined by what they replaced.",
        "A powerful new pattern can create its own cult of certainty. Do not treat early coherence as proof that every new decision is correct. The new system still needs feedback, succession, and willingness to repair its own defects.",
        "What feature of the new structure makes its governing principle visible without needing another campaign to explain why the old one was wrong?",
        "Line 5 shows mature transformation becoming self-evident through coherent new conduct and structure rather than through continued revolutionary rhetoric.",
      ),
      authoredLine(
        "After revolution, change the face and return to order",
        "At the top line, the major transformation is complete enough that further revolutionary intensity would be harmful. People now need stable expectations and ordinary conduct. Some participants may only change outwardly at first; that can still be part of transition if the new rules are consistently applied.",
        "Change here closes the revolutionary phase. The emerging pattern becomes durable as new behavior is normalized and the system stops measuring loyalty by enthusiasm for change. Maintenance replaces mobilization.",
        "Do not launch another revolution simply because every person has not been inwardly converted. Judge the new structure by conduct and results. Permanent ideological mobilization can destabilize a reform that has already succeeded institutionally.",
        "What should now become ordinary routine so this successful transformation no longer depends on people feeling revolutionary every day?",
        "Line 6 ends the revolutionary posture and stabilizes the new order through ordinary conduct, consistent rules, and reduced ideological pressure.",
      ),
    ],
  },
  {
    number: 50,
    coreTheme: "The vessel",
    coreMeaning: "The vessel describes transformation through a container capable of combining ingredients into something more useful than their separate parts. Ding asks about institutions, processes, culture, and roles that hold material long enough for maturation to occur. Better ingredients cannot rescue a cracked vessel; a beautiful vessel cannot produce value if what enters it is poor. The reading therefore favors improving both input and container while protecting the conditions that let transformation happen. The six lines move from emptying the old contents and correcting the vessel, through reliable nourishment and blocked access, toward strong handles and finally a refined form that can be trusted. At its best, the vessel becomes almost infrastructural: people can rely on the process to transform raw material into capability, knowledge, culture, or nourishment without constant heroic intervention.",
    strength: "the ability to transform raw inputs through a sound container and process",
    challenge: "focusing on ingredients while ignoring the vessel, or preserving a container that no longer transforms well",
    orientation: "strengthen the process and container so good inputs can mature into something more useful",
    structureInterpretation: "Wind below penetrates and feeds Fire above, creating the image of fuel sustaining a cooking vessel. Quick I Ching reads the structure as transformation produced by a relationship between input, container, heat, and time. Value comes from process, not from raw material alone.",
    reflectionQuestions: [
      "What process or institution is supposed to transform inputs here, and where is its container currently weak or distorted?",
      "Which ingredient needs improvement, and which problem would remain even with better ingredients because the vessel itself is flawed?",
      "What conditions of time, heat, sequence, or culture must be protected for the transformation to mature instead of being rushed?",
    ],
    watchFor: [
      "Better inputs failing to improve outcomes because the surrounding process continues to leak, distort, or undercook them.",
      "A repaired container making ordinary materials surprisingly productive because the transformation process finally works consistently.",
      "The process becoming dependable enough that value no longer depends on one exceptional person manually correcting every batch.",
    ],
    transitionTheme: "raw material becoming nourishment or capability through a trustworthy container",
    stabilityTheme: "a vessel and process maintained well enough to transform repeatedly without heroic repair",
    lowerTrigram: "xun",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Turn the vessel over and empty what should not remain",
        "The first line begins transformation by clearing the container. Old residue, inherited assumptions, stale inventory, or previous mistakes can contaminate new work if they are preserved merely because they already occupy the vessel. Cleaning may look disorderly but serves the next use.",
        "Change here converts inherited contents into a fresh starting condition. The emerging pattern gains integrity because the new process does not have to cook around remnants that should have been removed before better ingredients arrived.",
        "Do not discard history indiscriminately. Some residue is actually seasoning—knowledge embedded in prior use. Remove what contaminates; document what still carries value before clearing the vessel.",
        "What inherited content needs to be emptied before this process can honestly claim to transform new material on fresh terms?",
        "Line 1 prepares the vessel for renewal by removing contaminating remnants while preserving whatever experience still deserves to inform the next use.",
      ),
      authoredLine(
        "A full vessel need not answer envy",
        "The second line has real substance inside the container. Others may question, envy, or attempt to interfere, but the strongest answer is continued quality. When the process is producing something valuable, attention should remain on protecting and completing the transformation rather than on managing every outside reaction.",
        "As this line changes, internal substance becomes more secure. The emerging pattern gains confidence from the contents themselves: results make the vessel harder to dismiss and reduce dependence on reputation management.",
        "Confidence can become secrecy or arrogance. Protect the process from interference, but keep enough transparency that quality can be verified. A full vessel should not need to hide what it produces.",
        "What real substance is already developing here that deserves protection from distraction more than it needs another response to outside judgment?",
        "Line 2 keeps attention on the valuable contents already maturing inside the vessel, allowing substance rather than reaction to defend the process.",
      ),
      authoredLine(
        "A good vessel is useless when the handles cannot be used",
        "The third line shows a process with value that people cannot access, operate, or recognize. The vessel may be sound but its interface is wrong: authority, usability, communication, distribution, or timing prevents the transformed value from reaching those who need it.",
        "Change here turns internal quality into usable output by repairing access. The emerging pattern improves when handles, channels, or recognition are restored so the vessel can finally be moved and served from.",
        "Do not rebuild the entire transformation process when the real problem is interface. Conversely, do not polish access if the contents are still unready. Diagnose which layer is actually failing.",
        "Where is a sound process producing value that remains unusable because people cannot access, operate, or recognize it properly?",
        "Line 3 repairs the handle between transformation and use so good contents can finally be carried into the wider system.",
      ),
      authoredLine(
        "A broken leg spills the responsibility",
        "The fourth line depicts structural failure under load. A support that should carry the vessel breaks, spilling what has been prepared and creating visible consequences. This is a governance failure: the system accepted more weight than its support could bear or ignored warning signs in a critical component.",
        "When this line changes, failure becomes a demand for structural repair. The emerging pattern must rebuild support before restarting the transformation, not simply replace the lost contents and hope the old base holds next time.",
        "Do not scapegoat the last person near the failure if the load, maintenance, or design made breakdown predictable. Responsibility should follow the structure that permitted the weak support to carry critical weight.",
        "What critical support failed here, and what system decision allowed it to carry more responsibility than it could safely bear?",
        "Line 4 treats a spilled vessel as structural evidence, repairing the failed support and governance rather than merely replacing what was lost.",
      ),
      authoredLine(
        "Strong handles make a valuable vessel governable",
        "The fifth line gives the vessel reliable handles and a balanced center. The transformation is valuable, and the institution or process can now be moved, governed, and handed responsibly. Leadership makes the contents accessible without disturbing the conditions that produced them.",
        "Change here turns a successful process into durable stewardship. The emerging pattern can scale or transfer because authority is attached to a usable interface rather than locked inside informal knowledge.",
        "Strong governance can become overmanagement if every movement requires central permission. Handles exist to make the vessel usable, not to ensure only one person can touch it. Build clear delegation around the stable process.",
        "What governance, interface, or handoff would let this successful process be carried reliably by more than the people who originally built it?",
        "Line 5 makes a valuable vessel governable and transferable through strong handles, clear stewardship, and practical access to the process.",
      ),
      authoredLine(
        "The refined vessel becomes both strong and graceful",
        "At the top line, the vessel has reached a high level of refinement: strength, usefulness, and form support one another. The process no longer needs crude reinforcement because its design itself carries integrity. This is transformation that has become culture or institution rather than a temporary project.",
        "Change here completes the vessel by making its quality self-reinforcing. The emerging direction can focus on continuity, renewal, and teaching others how to maintain the process rather than on repeated redesign.",
        "Refinement can become reverence for the vessel itself. No institution is beyond review. Preserve the principles that make transformation work while remaining willing to change the form if future conditions require it.",
        "What principle makes this mature process trustworthy enough to preserve, and what part of the vessel should still remain open to future redesign?",
        "Line 6 completes the vessel as a mature institution whose strength and grace support repeated transformation without making its present form sacred forever.",
      ),
    ],
  },
  {
    number: 51,
    coreTheme: "Shock",
    coreMeaning: "Shock describes disruption that abruptly restores attention. Zhen can arrive as bad news, surprise, crisis, sudden opportunity, or any event that makes routine assumptions impossible to continue unconsciously. The first task is physiological and practical: regain orientation, protect essentials, and avoid letting one disturbance cascade into several. A good response does not deny fear; it uses the signal to inspect what the shock exposed about preparedness, dependency, or neglected responsibility. Repeated shocks can train resilience if each produces a better procedure rather than simply more anxiety. The reading also warns against living inside the echo after the event has passed. At the highest position, fear can spread socially before the danger arrives personally. Learn from the disruption, repair the revealed weakness, and then let the nervous system return to ordinary life.",
    strength: "the ability to recover attention and restore order after sudden disruption",
    challenge: "panic, denial, or allowing one shock to cascade into avoidable secondary failures",
    orientation: "stabilize first, learn what the shock exposed, and restore ordinary responsibilities",
    structureInterpretation: "Thunder below and Thunder above repeat the trigram of sudden arousal and movement. Quick I Ching reads the doubled structure as disruption arriving more than once or reverberating through several layers. Resilience depends on returning to order between shocks rather than making alarm the permanent operating mode.",
    reflectionQuestions: [
      "What essential function needs stabilization before you attempt to interpret the meaning of the shock?",
      "Which hidden dependency or weak preparation did the disruption expose that ordinary conditions had allowed you to ignore?",
      "What would show that the event has been integrated enough that continued alarm is no longer helping you prepare?",
    ],
    watchFor: [
      "A sudden event producing clearer priorities and a more reliable emergency practice after the initial reaction settles.",
      "Secondary mistakes multiplying because decisions are being made to reduce panic rather than to address the actual disruption.",
      "The external situation returning to normal while internal vigilance remains elevated and continues to distort ordinary choices.",
    ],
    transitionTheme: "disruption becoming usable information after orientation and order are restored",
    stabilityTheme: "preparedness that allows shock to sharpen attention without becoming permanent alarm",
    lowerTrigram: "zhen",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Shock first frightens, then restores laughter",
        "The first line captures a healthy shock cycle. Fear arrives quickly because something important changed, but once the situation is assessed and essentials remain intact, relief becomes possible. The ability to move from alarm back toward ordinary emotion shows that the nervous system is not trapped by the event.",
        "Change here turns raw arousal into adaptive learning. The emerging pattern becomes more resilient because shock gains a beginning and an end: attention rises, action occurs, and the body is allowed to stand down.",
        "Do not force cheerfulness before the situation is actually safe. Premature reassurance can suppress information. But once the danger has passed, continuing to cultivate fear is no longer vigilance.",
        "What fact would allow you to distinguish ‘the shock is still active’ from ‘the shock happened and I can begin returning to ordinary function’?",
        "Line 1 models a complete shock response: alarm sharpens attention, assessment restores proportion, and relief is allowed when safety becomes real.",
      ),
      authoredLine(
        "Shock causes temporary loss; do not chase immediately",
        "The second line shows disruption scattering resources or creating a sense that something important has been lost. Chasing everything at once may deepen exposure. Some losses can return or be recovered later if the person first reaches a safer position and lets the event settle.",
        "As this line changes, the response prioritizes safety over immediate recovery. The emerging pattern protects the capacity needed to reclaim what matters once the shock stops moving the ground beneath every decision.",
        "Do not abandon an asset whose recovery window is genuinely brief. The principle is to distinguish urgent retrieval from panic-driven pursuit. Protect life and core function before secondary possessions or status.",
        "What feels lost right now, and which part can safely wait until your position is stable enough to pursue it without creating more risk?",
        "Line 2 puts stabilization before frantic recovery, preserving the capacity to reclaim losses after the shock has stopped dictating every move.",
      ),
      authoredLine(
        "Shock should move you into corrective action",
        "The third line experiences repeated trembling but still has agency. The useful question is what the disruption is asking you to change. If shock merely produces fear without altered conduct, its information is wasted. A concrete correction can convert nervous energy into preparedness.",
        "Change here turns arousal into movement. The emerging pattern becomes safer because a revealed weakness receives a practical response—backup, training, boundary, communication, or another measure connected to the actual failure.",
        "Activity can be a way to avoid feeling uncertainty. Do not launch unrelated improvements simply to regain a sense of control. Correct what the shock genuinely exposed.",
        "What specific weakness did this disruption reveal that you can correct now instead of carrying the same vulnerability into the next shock?",
        "Line 3 converts trembling into targeted corrective action so the shock changes preparedness rather than merely increasing anxiety.",
      ),
      authoredLine(
        "Shock stuck in mud loses its teaching value",
        "The fourth line shows arousal becoming bogged down. The person may be frozen, replaying the event, or responding so diffusely that energy cannot reach a useful action. The danger is not the original shock alone but getting trapped in an unproductive reaction state.",
        "When this line changes, shock can regain direction by simplifying the next step. The emerging pattern may require outside support, rest, or one concrete action that restores movement without demanding complete emotional resolution first.",
        "Do not shame a slow recovery. Trauma, exhaustion, and real loss can take time. The issue is whether the current response creates any path toward function or simply repeats the same activation without new information.",
        "What single action or support would help this shock response move again instead of remaining stuck in replay, paralysis, or diffuse alarm?",
        "Line 4 recognizes when shock has become stuck and restores movement through a small practical step rather than demanding instant emotional recovery.",
      ),
      authoredLine(
        "Repeated shocks need not destroy the center",
        "The fifth line faces disruption more than once but retains the central responsibilities. Not every shock can be prevented, yet the system can become good at protecting essentials. Repeated exposure is useful only if each event improves prioritization and reduces avoidable loss.",
        "Change here turns resilience into institutional practice. The emerging pattern becomes less dependent on one person’s composure because continuity plans, roles, and safeguards protect what must not be lost.",
        "Surviving repeated shocks can create false confidence and normalize unacceptable risk. Resilience should not be used to excuse a preventable hazard that could be removed at its source.",
        "Which essential function has survived repeated disruption, and what should now be formalized so that continuity does not depend on luck or heroics?",
        "Line 5 builds resilience around the center, preserving essential responsibilities through repeated shocks while still addressing preventable causes.",
      ),
      authoredLine(
        "Fear spreads before the shock reaches you",
        "At the top line, alarm may be traveling socially or through anticipation before the event directly reaches your own position. Other people’s reaction is real information, but it can amplify fear beyond the evidence available to you. Prepare responsibly without allowing contagious panic to set the scale of response.",
        "Change here separates observed risk from transmitted fear. The emerging direction becomes more proportionate as the person prepares for credible exposure while refusing unnecessary behavior driven mainly by what others are imagining or broadcasting.",
        "Do not dismiss warnings simply because they come from others. Verify distance, probability, and consequence. Social transmission can carry both valuable early warning and exaggerated alarm.",
        "What part of your current fear comes from direct evidence, and what part is being amplified by watching other people react to a danger that has not reached you?",
        "Line 6 keeps early warning useful by separating contagious alarm from direct evidence and scaling preparation to the risk that actually approaches.",
      ),
    ],
  },
  {
    number: 52,
    coreTheme: "Keeping still",
    coreMeaning: "Keeping still describes the ability to stop at the point where movement no longer adds value. Gen is active restraint: attention returns to the body, the boundary, and the present task instead of being carried automatically by momentum. Different lines show how hard stopping can be at different levels—feet can halt early, calves may be pulled by what they follow, the waist can seize under forced stillness, speech may need quieting, and finally the whole person can rest in a generous form of stillness. The reading does not praise rigidity. A stop should make later action clearer, not suppress necessary movement indefinitely. Good stillness reduces noise, prevents escalation, and lets sensation or evidence catch up with intention. Once the pause has done its work, movement can resume without violating the boundary that made clarity possible.",
    strength: "the ability to stop, hold a boundary, and recover attention",
    challenge: "rigidity, suppression, or continuing motion simply because stopping feels uncomfortable",
    orientation: "stop where further movement is not useful and let attention settle before choosing the next action",
    structureInterpretation: "Mountain below and Mountain above double the trigram of stopping, boundary, and stillness. Quick I Ching reads the structure as repeated containment: the task is not to eliminate movement forever but to recognize the exact place where movement should end so the next action is not driven by residual momentum.",
    reflectionQuestions: [
      "What movement—physical, verbal, emotional, or strategic—has continued past the point where it still provides useful information?",
      "What boundary would allow your attention to settle instead of requiring constant response to the same stimulus?",
      "What evidence would tell you that the pause has completed its purpose and movement can responsibly resume?",
    ],
    watchFor: [
      "A conflict or decision becoming clearer after one unnecessary channel of movement or speech is deliberately stopped.",
      "Stillness becoming rigid enough that new information is rejected simply because it would require movement again.",
      "Attention returning to ordinary bodily or practical signals once momentum and repeated reaction begin to quiet.",
    ],
    transitionTheme: "compulsive movement becoming clearer action after an appropriate stop",
    stabilityTheme: "boundaries and pauses that remain responsive rather than rigid",
    lowerTrigram: "gen",
    upperTrigram: "gen",
    lines: [
      authoredLine(
        "Stop the toes before momentum begins",
        "The first line stops movement at its earliest point. This is the cheapest and cleanest boundary because little momentum has accumulated. A first impulse can be noticed without being followed, allowing the person to decide whether the direction deserves any movement at all.",
        "Change here turns automatic initiation into conscious choice. The emerging pattern gains freedom because the person learns that an impulse does not have to become a sequence before it can be evaluated.",
        "Early stopping can become timidity if every unfamiliar movement is blocked. Use the pause to assess, not to create a permanent prohibition. If the direction is sound, later movement should still be possible.",
        "What first impulse could you pause before it becomes momentum, simply to find out whether you actually want the sequence that normally follows it?",
        "Line 1 places stillness at the first impulse, creating choice before momentum makes continuation feel automatic.",
      ),
      authoredLine(
        "The calves stop, but the heart follows what moves ahead",
        "The second line shows physical or practical restraint without full inner agreement. You may have stopped, yet attention remains attached to another person or process that keeps moving. The result can be frustration because the boundary exists externally while desire still follows the old momentum.",
        "As this line changes, stillness becomes more integrated. The emerging pattern asks the person to understand what remains emotionally attached rather than expecting an external stop to produce immediate internal peace.",
        "Do not interpret lingering desire as proof that the boundary is wrong. Adjustment often takes longer than the decision. But if the heart remains persistently opposed after careful review, the stop may need re-examination.",
        "What have you stopped doing while still mentally following it, and what would help the inner attachment catch up with the practical boundary?",
        "Line 2 distinguishes external stopping from inner attachment, allowing stillness to deepen without treating lingering desire as immediate failure.",
      ),
      authoredLine(
        "Forced stillness at the waist creates internal strain",
        "The third line restrains movement too rigidly at the center, creating tension rather than calm. Suppressed energy can become painful when the boundary does not allow breathing room, expression, or legitimate adjustment. Stillness imposed through force may preserve appearances while increasing internal pressure.",
        "Change here turns rigid immobilization into a more workable boundary. The emerging pattern allows enough movement inside the stop—breathing, speaking, repositioning, or processing—that the restraint can remain without becoming harmful.",
        "Do not use the language of ‘release’ to abandon a necessary boundary. The correction is flexibility within the stop, not automatic removal of the limit that protects the situation.",
        "Where is your current form of restraint creating unnecessary internal strain, and what small movement could make the boundary sustainable without dissolving it?",
        "Line 3 corrects forced stillness by allowing enough internal movement that the necessary boundary can be held without creating damaging strain.",
      ),
      authoredLine(
        "Still the trunk and let the whole posture settle",
        "The fourth line brings stillness into the central posture rather than fighting individual impulses one by one. When the core position settles, peripheral movements often quiet naturally. This can mean clarifying the main decision, changing the environment, or adopting a bodily posture that reduces repeated reaction.",
        "When this line changes, stillness becomes systemic rather than tactical. The emerging pattern gains coherence because the person is no longer micromanaging every symptom of agitation; the central orientation itself has changed.",
        "A strong central posture can become inflexible if it stops receiving feedback from the edges. Stay settled, but notice when a peripheral signal indicates that the main position genuinely needs revision.",
        "What central decision or posture, if settled clearly, would make several smaller reactive movements unnecessary?",
        "Line 4 establishes stillness at the center so peripheral reactions can quiet without needing to be controlled individually.",
      ),
      authoredLine(
        "Still the jaws and order speech",
        "The fifth line focuses on verbal movement. Words can prolong conflict, anxiety, or confusion long after practical action has stopped. A pause in speaking creates space to choose sequence and proportion: what truly needs to be said, what can wait, and what is only discharge of emotion.",
        "Change here turns silence into more ordered communication. The emerging pattern does not eliminate speech; it makes words more deliberate because they are no longer being produced at the speed of the first reaction.",
        "Silence can become punishment, avoidance, or concealment. If another person needs information to act safely or fairly, withholding it is not stillness. Pause only long enough to improve the quality of necessary speech.",
        "Which sentence should not be spoken in its current emotional form, and what essential message would remain after the reaction settles?",
        "Line 5 uses a pause in speech to restore order, allowing necessary communication to emerge after reactive words have lost their urgency.",
      ),
      authoredLine(
        "Generous stillness at the end",
        "At the top line, stillness becomes spacious rather than defensive. The person is no longer stopping merely to avoid danger or control an impulse; rest itself has become a stable capacity. This kind of stillness can hold other people’s movement without needing to join or suppress it.",
        "Change here completes the stopping cycle and makes later movement freer. The emerging direction can act from a quieter center because pause is no longer experienced as deprivation or failure.",
        "Deep stillness can become withdrawal from life if it is idealized. The value of the mountain is that it knows when to stop; it does not mean nothing should ever cross the landscape. Re-enter movement when purpose returns.",
        "What becomes available when you stop treating stillness as an emergency measure and allow it to be a normal capacity you can leave when action is again useful?",
        "Line 6 completes Keeping Still as a generous capacity for rest, creating a quiet center from which later movement can resume without compulsion.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
