import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 49,
    coreTheme: "Revolution",
    legacySummary: "Real change may require replacing an exhausted form, but legitimacy and timing are essential. Transform only when the case for change is mature and understood.",
    strength: "capacity for decisive transformation when an old form no longer serves",
    challenge: "premature rebellion, cosmetic change, or radical action without legitimacy",
    orientation: "build the case, choose the timing, and change the form only when the need is mature",
    transitionTheme: "an exhausted order becoming a new one through legitimate, timely transformation",
    stabilityTheme: "renewal stabilized by making the new structure credible after the break",
    lowerTrigram: "li",
    upperTrigram: "dui",
    lineEmphases: [
      "establish the first credible reason that the old form can no longer be repaired",
      "build trust for change through evidence, timing, and preparation before the break",
      "do not confuse frustration under pressure with sufficient legitimacy for transformation",
      "carry the case for change into the wider field and listen for consequences you have not considered",
      "use central authority to make the transition coherent rather than merely dramatic",
      "stabilize the new order instead of remaining addicted to the identity of revolution",
    ],
  },
  {
    number: 50,
    coreTheme: "The vessel",
    legacySummary: "Raw material can be transformed into something of lasting value. Focus on the container, process, and culture that make refinement possible.",
    strength: "the capacity to transform inputs through a sound container and process",
    challenge: "focusing on ingredients while neglecting the vessel, culture, or process that gives them form",
    orientation: "strengthen the container and process that turn raw potential into durable value",
    transitionTheme: "potential becoming culture, nourishment, or capability through sustained refinement",
    stabilityTheme: "quality preserved by caring for the structures that make transformation repeatable",
    lowerTrigram: "xun",
    upperTrigram: "li",
    lineEmphases: [
      "improve the first container or process before asking better material to produce better results",
      "make refinement repeatable through dependable routines, standards, and culture",
      "repair the vessel when pressure reveals that good inputs are being spoiled by the process",
      "bring the transforming process into wider use without lowering the standard that gives it value",
      "use a central role to protect the conditions in which people or material can mature",
      "renew the container when a once-useful process has become too rigid for the value it should create",
    ],
  },
  {
    number: 51,
    coreTheme: "Shock",
    legacySummary: "A sudden disturbance demands presence rather than panic. Recover orientation quickly, learn what the shock reveals, and keep essential responsibilities intact.",
    strength: "rapid recovery of attention after disruption",
    challenge: "panic, denial, or letting the surprise disorganize responsibilities beyond what the event requires",
    orientation: "stabilize first, observe what the shock exposed, and restore essential duties",
    transitionTheme: "disruption becoming information and renewed alertness rather than prolonged chaos",
    stabilityTheme: "preparedness that allows surprise without loss of basic orientation",
    lowerTrigram: "zhen",
    upperTrigram: "zhen",
    lineEmphases: [
      "recover basic orientation after the first shock before drawing conclusions",
      "turn alertness into a steady practice rather than staying trapped in alarm",
      "avoid panic or denial when repeated disturbance tests your ability to stay present",
      "carry restored composure into the wider field so others are not forced to absorb your disorganization",
      "use a central role to keep essential responsibilities intact while learning from disruption",
      "let the shock end when its lesson is understood instead of repeatedly reliving the disturbance",
    ],
  },
  {
    number: 52,
    coreTheme: "Keeping still",
    legacySummary: "Stopping is appropriate when further motion would only add noise. Let attention settle, respect boundaries, and act again when stillness has clarified the next move.",
    strength: "the ability to stop movement and let attention become precise",
    challenge: "rigidity, suppression, or continuing to move because stopping feels unproductive",
    orientation: "stop where motion is no longer useful and let stillness restore discrimination",
    transitionTheme: "restless motion becoming clearer action after a genuine pause",
    stabilityTheme: "boundaries and pauses that prevent activity from outrunning judgment",
    lowerTrigram: "gen",
    upperTrigram: "gen",
    lineEmphases: [
      "stop the first unnecessary motion and notice what becomes visible in stillness",
      "make a boundary steady enough that attention can settle inside it",
      "avoid turning restraint into rigid suppression when pressure builds behind the stop",
      "carry a clarified boundary into the wider field without demanding that everyone become equally still",
      "use a central pause to distinguish what truly requires action from what can remain at rest",
      "move again when stillness has completed its work instead of making stopping into an identity",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
