import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 53,
    coreTheme: "Gradual development",
    legacySummary: "Progress is real but sequential. Build each stage so the next has something stable to rest on; rushing would weaken the development.",
    strength: "sequenced growth that builds trust and stability over time",
    challenge: "skipping stages, impatience, or comparing mature outcomes with an early phase",
    orientation: "respect the order of development and make each stage strong enough to support the next",
    transitionTheme: "small established steps becoming durable advancement through proper sequence",
    stabilityTheme: "growth sustained by pacing, continuity, and realistic milestones",
    lowerTrigram: "gen",
    upperTrigram: "xun",
    lineEmphases: [
      "establish the first stage fully enough that later growth has something to rest on",
      "make gradual progress visible through repeatable milestones and trustworthy pacing",
      "resist skipping a stage when pressure makes the current pace feel inadequate",
      "carry the development into a wider context only when the prior stage can support it",
      "use a central role to protect sequence, continuity, and realistic expectations",
      "recognize maturity without endlessly extending a development process that has already arrived",
    ],
  },
  {
    number: 54,
    coreTheme: "Unequal position",
    legacySummary: "You may be entering a situation without full authority or control. Understand the terms, protect dignity, and avoid assuming influence you do not yet possess.",
    strength: "clear awareness of position, terms, and actual influence",
    challenge: "overreaching, accepting degrading terms, or confusing proximity with authority",
    orientation: "understand the role you truly occupy and act within it without surrendering dignity",
    transitionTheme: "limited position becoming either clearer participation or a reason to renegotiate terms",
    stabilityTheme: "self-respect maintained by distinguishing desire from actual standing",
    lowerTrigram: "dui",
    upperTrigram: "zhen",
    lineEmphases: [
      "understand the first terms of participation before emotional investment outruns actual standing",
      "act with dignity inside a limited role without pretending it carries more authority",
      "renegotiate or step back when pressure exposes a mismatch between expectations and position",
      "enter the wider relationship with the terms visible rather than relying on implication",
      "use whatever influence is real without borrowing status you do not possess",
      "leave an unequal arrangement when its limits have become incompatible with self-respect or purpose",
    ],
  },
  {
    number: 55,
    coreTheme: "Abundance",
    legacySummary: "Conditions are full and highly visible. Use the peak actively and responsibly, knowing that fullness is a phase rather than a permanent state.",
    strength: "capacity to use a period of fullness, visibility, and rich activity",
    challenge: "overload, triumphalism, or acting as though peak conditions will last",
    orientation: "use the fullness now, distribute attention wisely, and prepare for the cycle to change",
    transitionTheme: "a peak becoming useful harvest when intensity is organized rather than merely enjoyed",
    stabilityTheme: "perspective that treats abundance as a phase requiring stewardship",
    lowerTrigram: "li",
    upperTrigram: "zhen",
    lineEmphases: [
      "use the first sign of fullness to organize attention rather than simply celebrate abundance",
      "make peak conditions productive through clear priorities and distribution of effort",
      "avoid overload when pressure comes from having too much happening at once",
      "bring abundance into the wider field while remembering that visibility also attracts demands",
      "use a central peak to harvest value, share benefit, and prepare for changing conditions",
      "release the peak posture when fullness naturally declines instead of treating decline as failure",
    ],
  },
  {
    number: 56,
    coreTheme: "The traveler",
    legacySummary: "You are operating without deep roots in the present setting. Keep aims modest, observe local conditions, and rely on good conduct more than entitlement.",
    strength: "adaptability and good conduct in unfamiliar or temporary settings",
    challenge: "carelessness, entitlement, or trying to build permanent claims where you lack roots",
    orientation: "keep objectives modest, read local conditions, and protect trust through conduct",
    transitionTheme: "temporary presence becoming useful passage when expectations match the setting",
    stabilityTheme: "mobility supported by restraint, awareness, and a light footprint",
    lowerTrigram: "gen",
    upperTrigram: "li",
    lineEmphases: [
      "learn the first local condition before acting as though the setting belongs to you",
      "make a temporary position workable through modest aims and dependable conduct",
      "avoid entitlement or careless exposure when pressure reminds you that roots are shallow",
      "enter the wider setting lightly, reading customs and consequences before making claims",
      "use a visible role to earn trust through behavior rather than assumed status",
      "leave cleanly when the passage is complete instead of trying to turn every stop into a permanent home",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
