import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 53,
    coreTheme: "Gradual development",
    coreMeaning: "Gradual development describes growth that gains durability by respecting sequence. Jian is the movement of something becoming established stage by stage rather than through a single decisive leap. The reading favors milestones that can actually support what follows: first a foothold, then a place in ordinary life, then wider responsibility, and eventually a mature position that can influence beyond itself. Impatience is the main distortion. Skipping a stage can create visible progress while leaving the missing support hidden until the next pressure arrives. Gradual development is not an excuse for slowness when readiness is already present; each stage should move once it has done its work. The measure is integration. A step is complete when the new capacity, relationship, or role has become stable enough that the next one does not have to compensate for it.",
    strength: "sequenced growth that lets each stage support the next",
    challenge: "impatience, skipped stages, or judging early development by mature standards",
    orientation: "respect the order of development and let each stage become stable before advancing",
    structureInterpretation: "Mountain below establishes a firm foothold while Wind above penetrates and develops gradually. Quick I Ching reads the structure as growth rooted in stability and extended through persistent influence. The path advances because each stage becomes inhabitable, not because distance is covered quickly.",
    reflectionQuestions: [
      "Which stage of development is genuinely complete enough that the next responsibility will not have to repair it?",
      "Where are you comparing an early-stage result with a mature standard in a way that obscures real progress?",
      "What milestone would prove integration rather than simply produce the appearance of advancement?",
    ],
    watchFor: [
      "A new capability becoming ordinary and repeatable before the next layer of responsibility is added.",
      "Pressure for visible progress causing a stage to be skipped even though its missing support still matters structurally.",
      "A point where waiting no longer improves readiness and advancement becomes the more disciplined choice.",
    ],
    transitionTheme: "small stable stages accumulating into mature development",
    stabilityTheme: "patient sequencing that keeps advancement integrated rather than performative",
    lowerTrigram: "gen",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "The wild goose reaches the shore",
        "The first line establishes a first foothold at the edge of a larger journey. The position is exposed and not yet prestigious, so criticism or uncertainty may accompany the beginning. What matters is whether the landing is safe enough for the next stage to be built from it.",
        "Change here turns arrival into initial settlement. The emerging pattern gains credibility as the first foothold proves it can be occupied without constant rescue or improvisation.",
        "Do not rush inland merely to escape the vulnerability of being a beginner. Early exposure is part of learning the terrain. Protect the foothold before asking it to carry mature expectations.",
        "What would make this first foothold stable enough that criticism or uncertainty no longer forces you to abandon the development prematurely?",
        "Line 1 gives gradual development a real first landing, protecting the vulnerable beginning until it can support the next stage.",
      ),
      authoredLine(
        "The goose reaches the rock and can be nourished",
        "The second line finds a more secure place where development can receive nourishment and companionship. Progress is no longer only survival; the new position can support ordinary functioning. This is a stage to consolidate trust, resources, and routine rather than immediately chase the next elevation.",
        "As this line changes, a secure stage becomes a platform for continued growth. The emerging pattern gains endurance because nourishment and social support are now part of the development rather than temporary aids around it.",
        "Comfort can make a good intermediate stage feel like a final destination. Enjoy stability without forgetting the larger developmental arc. Move when the stage has become truly integrated.",
        "What resource, relationship, or routine can be strengthened here so this secure stage becomes a genuine platform rather than a temporary rest?",
        "Line 2 consolidates a nourished and secure stage so gradual development gains enough ordinary stability to continue without strain.",
      ),
      authoredLine(
        "The goose reaches dry land, but separation creates risk",
        "The third line moves farther from the protected beginning and exposes the cost of advancement that outruns relationship or support. One part may push ahead while another is left without protection. Development becomes fragile when ambition separates the advancing element from the system that must still carry life behind it.",
        "Change here turns premature advance into a review of support and responsibility. The emerging pattern becomes safer when the outward move is coordinated with what remains dependent on it.",
        "Do not interpret the warning as a command never to leave familiar support. The issue is uncoordinated separation. Advancement is sound when responsibilities and protection travel in an appropriate form.",
        "What or who would be left structurally exposed if you advanced to the next stage before the supporting relationship was ready?",
        "Line 3 warns that gradual advancement fails when outward movement separates from responsibilities that still require coordinated support.",
      ),
      authoredLine(
        "The goose finds a branch that can hold it",
        "The fourth line reaches an unfamiliar outer environment and must find a workable perch. The fit may not be perfect, but a suitable position can provide enough support to continue learning the wider field. Adaptation matters more than demanding that the new stage resemble the previous one.",
        "When this line changes, development gains an outer foothold. The emerging pattern becomes more flexible because the person learns how to occupy a new environment without requiring complete control over it.",
        "A temporary perch should not be mistaken for permanent security. Keep testing load, fit, and relationship. If the support cannot carry the role over time, adaptation needs to continue.",
        "What workable but imperfect position could support you in the new environment while you learn what a more durable fit requires?",
        "Line 4 finds a usable outer perch, allowing development to continue through adaptation before permanent fit is fully known.",
      ),
      authoredLine(
        "The goose reaches the high ground after a long delay",
        "The fifth line shows mature development slowed by a period in which expected results do not arrive. The delay can test trust in the sequence, but a sound developmental process may still be working beneath the visible absence. The line favors constancy when the structure remains healthy even though the anticipated outcome is late.",
        "Change here turns long gestation into mature arrival. The emerging pattern demonstrates that some outcomes require the full sequence and cannot be forced by increasing pressure late in the process.",
        "Do not use patience to protect a dead process. Verify that the underlying relationship, capacity, or trajectory still shows life. Waiting is justified by evidence of maturation, not by sunk cost alone.",
        "What evidence shows that this delayed result is still maturing rather than simply failing to appear?",
        "Line 5 sustains a mature developmental sequence through delay when the underlying evidence still supports eventual completion.",
      ),
      authoredLine(
        "The goose reaches the heights and leaves a pattern others can use",
        "At the top line, gradual development has matured enough that its form becomes exemplary. The value is no longer only personal advancement; the path, standards, or conduct can guide others because the sequence has been lived and tested. Maturity becomes a pattern rather than a private achievement.",
        "Change here completes development by converting experience into transferable form. The emerging direction may involve teaching, succession, documentation, or an example that survives beyond the original participant.",
        "Do not turn mature experience into a rigid formula for everyone else. The pattern should transmit principles and sequence while leaving room for different circumstances.",
        "What part of your completed development could become a useful pattern for others without requiring them to reproduce every detail of your path?",
        "Line 6 completes gradual development by turning a mature path into transferable guidance rather than keeping achievement private.",
      ),
    ],
  },
  {
    number: 54,
    coreTheme: "Unequal position",
    coreMeaning: "Unequal position describes participation in a relationship or structure where influence, status, or timing is not equal. Gui Mei does not assume inequality automatically makes the relationship invalid. It asks whether the terms are known, dignity is preserved, and the limited role can be carried without pretending it is something else. Trouble begins when proximity is confused with authority, emotional investment creates claims the structure never granted, or a secondary position is used to maneuver for central control. The reading favors realism about role and timing. Some limited positions can be honorable and useful; others become degrading because the arrangement never offers a path compatible with self-respect. The highest lines expose empty form—ritual without substance, promise without fulfillment. Participation should be judged by real terms, not by appearances that imply more reciprocity or power than actually exists.",
    strength: "realistic understanding of role, terms, and limited influence",
    challenge: "overreach, degrading compromise, or treating proximity as if it granted authority",
    orientation: "understand the true position, preserve dignity, and renegotiate or leave when the terms become incompatible",
    structureInterpretation: "Lake below opens through attraction while Thunder above moves abruptly, creating a relationship with strong responsiveness but unstable hierarchy. Quick I Ching reads the structure as participation under asymmetrical terms. Clarity about position protects both dignity and function when equal standing is not available.",
    reflectionQuestions: [
      "What authority or reciprocity does this relationship actually grant, apart from what closeness or symbolism seems to imply?",
      "Which limitation can be accepted with dignity, and which one would require you to deny a legitimate need or responsibility?",
      "What evidence would show that the current unequal arrangement has a credible path toward better terms rather than only promises?",
    ],
    watchFor: [
      "A limited role functioning well because terms are explicit and no one has to pretend the position is more central than it is.",
      "Emotional closeness being used to request obligations, influence, or sacrifice that the formal relationship does not reciprocate.",
      "Ceremony, titles, or promises becoming increasingly elaborate while the actual substance of support or authority remains empty.",
    ],
    transitionTheme: "limited participation becoming clearer through honest recognition of terms and leverage",
    stabilityTheme: "self-respect maintained by neither inflating nor denying the actual position",
    lowerTrigram: "dui",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "A secondary position can still walk usefully",
        "The first line accepts a subordinate or limited role without treating it as worthless. Even with reduced formal standing, a person can contribute meaningfully if the role is real and the terms do not require humiliation. Function matters more than appearance at this stage.",
        "Change here turns disappointment about status into practical participation. The emerging pattern can gain value from what the limited position genuinely allows instead of spending energy pretending equality already exists.",
        "Do not romanticize a compromised role merely because some contribution is possible. Track whether the limitation remains proportionate and whether the arrangement respects basic dignity.",
        "What useful contribution is genuinely available from this limited position, and what minimum condition keeps the role from becoming degrading?",
        "Line 1 finds workable dignity inside a secondary position by using its real scope without pretending the hierarchy is equal.",
      ),
      authoredLine(
        "Partial sight can still preserve inward constancy",
        "The second line has limited access or visibility but can maintain a stable inner standard. You may not see the whole system or possess full influence, yet reliable conduct remains possible within the part you do understand. This protects the person from compensating for limited power through manipulation.",
        "As this line changes, constrained perspective becomes disciplined participation. The emerging pattern gains trust because the person does not claim knowledge or authority beyond the actual field of view.",
        "Do not use loyalty to justify staying permanently half-informed where informed consent or responsible action requires more visibility. Limited sight is acceptable only where the role can safely function with it.",
        "What can you carry faithfully with the information you truly have, and what decision should wait until your field of view becomes wider?",
        "Line 2 preserves integrity under limited visibility by keeping conduct reliable while refusing to claim authority beyond what is actually known.",
      ),
      authoredLine(
        "Waiting for a higher role can become degrading",
        "The third line shows someone hoping to enter a better position but accepting terms that diminish dignity in the meantime. The desire for future elevation can make a person tolerate ambiguity, dependency, or treatment that would otherwise be unacceptable. The line asks whether the promise of improvement is real enough to justify the current cost.",
        "Change here turns passive waiting into negotiation or exit. The emerging pattern becomes healthier when the person asks for concrete terms instead of continuing to live inside an implied future that never becomes binding.",
        "Impatience can also make a temporary apprenticeship or limited phase look degrading when it is actually developmental. Examine whether capability and terms are changing over time before judging the position.",
        "What concrete evidence shows that this limited role is progressing toward better terms rather than using future possibility to justify indefinite compromise?",
        "Line 3 challenges degrading delay by asking an unequal position to prove its path toward better terms or face renegotiation and exit.",
      ),
      authoredLine(
        "A delayed match can be better than the wrong match",
        "The fourth line accepts delay rather than entering an unsuitable arrangement simply to meet an expected timetable. The value lies in preserving fit and dignity. Social pressure may make waiting feel like failure, but a later relationship or role can be more sound if the present options require unacceptable compromise.",
        "When this line changes, delay becomes selective readiness. The emerging pattern remains open to a better fit because the person has not spent the waiting period binding themselves to an arrangement chosen mainly to escape uncertainty.",
        "Standards can become perfectionism if every real option is rejected for not matching an ideal. Distinguish essential fit from preferences that could mature through relationship.",
        "Which term is important enough that waiting for a better fit is wiser than accepting an immediate arrangement that violates it?",
        "Line 4 treats delay as protection of fit when the available unequal terms are not worthy of commitment merely to satisfy timing pressure.",
      ),
      authoredLine(
        "A central person can wear modest form without losing dignity",
        "The fifth line shows that visible status does not need elaborate display. A person with real central worth may accept simpler outward form than someone in a secondary role, because dignity comes from substance rather than decoration. This reduces competition around appearances and clarifies where actual influence lies.",
        "Change here separates legitimate position from status theater. The emerging pattern becomes more stable because authority can be recognized through conduct and responsibility rather than through constant symbolic distinction.",
        "Modest form should not be used to hide unequal expectations or avoid formal recognition where it matters legally or practically. Simplicity is sound only when substance remains secure.",
        "What status signal could be simplified because your real responsibility and value no longer depend on outward proof of rank?",
        "Line 5 lets substantive central worth remain dignified in modest form, reducing status competition without surrendering the real responsibility of the position.",
      ),
      authoredLine(
        "Empty ritual reveals an unequal relationship without substance",
        "At the top line, the forms of commitment remain but the substance is missing. A basket is presented without real contents; a sacrifice is performed without what would make it effective. Titles, ceremonies, promises, or relationship labels cannot compensate for absent reciprocity or practical support.",
        "Change here strips away symbolic cover. The emerging direction requires either filling the form with real substance or admitting that the relationship cannot continue under its current claims.",
        "Do not dismiss every ritual as empty. Form can carry meaning when the underlying obligations are real. The warning applies when symbolism is doing the work that substance should be doing.",
        "Which promise, title, or ritual in this relationship currently implies a substance that the actual behavior no longer provides?",
        "Line 6 exposes empty form in an unequal relationship and requires either real substance behind the commitment or an honest end to the claim.",
      ),
    ],
  },
  {
    number: 55,
    coreTheme: "Abundance",
    coreMeaning: "Abundance describes a period of fullness, visibility, and concentrated activity. Feng can bring resources, recognition, responsibility, and information all at once. The opportunity is real, but fullness increases complexity: more signals compete for attention, more people depend on decisions, and the peak itself can hide the approaching shift in the cycle. The reading favors strong prioritization and distribution. Use abundance while it is present; do not spend the entire period trying to preserve the emotional feeling of being at a peak. Some lines show brightness obscured even in a full phase, reminding you that scale can produce shadow and incomplete information. Mature abundance harvests, shares, builds resilience, and prepares for decline without treating decline as failure. The task is stewardship of a season, not possession of permanent noon.",
    strength: "the capacity to act effectively during a period of fullness and high visibility",
    challenge: "overload, triumphalism, or assuming peak conditions are permanent",
    orientation: "use the full period well, distribute attention and resources, and prepare for the cycle to change",
    structureInterpretation: "Fire below provides brightness while Thunder above releases movement and activity. Quick I Ching reads the structure as illumination at high intensity combined with strong action. Fullness creates opportunity and overload simultaneously, so priority and timing become essential.",
    reflectionQuestions: [
      "Which part of this abundance deserves immediate use because the favorable window will not remain equally open forever?",
      "What important information is becoming harder to see precisely because scale and activity are now so high?",
      "What should be harvested, shared, or reinforced now so value remains after the peak conditions change?",
    ],
    watchFor: [
      "High visibility creating useful opportunities while simultaneously increasing coordination load and expectation.",
      "The system treating every new demand as urgent because abundance has weakened prioritization.",
      "A peak beginning to shift while reserves, relationships, and infrastructure built during fullness continue to carry value.",
    ],
    transitionTheme: "peak fullness becoming durable harvest when abundance is prioritized and shared",
    stabilityTheme: "stewardship that uses the bright phase fully without demanding that it remain permanent",
    lowerTrigram: "li",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "Meet an equal partner during abundance",
        "The first line finds another capable force during a full period. Cooperation among equals can multiply what the season makes possible, especially when neither side wastes time proving superiority. A limited period of intense collaboration can be appropriate without requiring permanent merger.",
        "Change here turns individual abundance into shared capacity. The emerging pattern gains reach because strong participants coordinate around a concrete window instead of competing for ownership of the bright moment.",
        "Equal strength can still create rivalry if purpose is vague. Define what the partnership is for and when it ends. A peak-time alliance should not accumulate unnecessary obligations beyond the task.",
        "What capable equal could help use this favorable window better, and what clear task would keep cooperation from becoming competition?",
        "Line 1 uses abundance through a focused alliance of equals, multiplying opportunity without turning temporary cooperation into a status contest.",
      ),
      authoredLine(
        "Fullness can cast a thick curtain over the sun",
        "The second line shows abundance obscuring clarity. Scale, noise, intermediaries, or political complexity may block direct sight even while the period is outwardly bright. The response is not panic but sincere effort to restore trustworthy information channels.",
        "As this line changes, fullness becomes more governable because obscured facts can reach the center again. The emerging pattern gains confidence from better visibility rather than from the emotional assumption that a prosperous phase must be healthy.",
        "Do not interpret every shadow as conspiracy. Large systems naturally create information loss. Repair the channel before assigning motive to the obstruction.",
        "Which important fact is hardest to see now because abundance has created too much scale, noise, or mediation around it?",
        "Line 2 restores clarity inside abundance by reopening trustworthy information channels when scale has begun to obscure the center’s view.",
      ),
      authoredLine(
        "The shadow becomes so deep that the working arm is injured",
        "The third line shows obscurity within abundance becoming operationally harmful. A critical capability may be damaged or unable to act because the system cannot see or coordinate well enough. The issue has moved beyond imperfect information into reduced function.",
        "Change here turns hidden overload into a demand for immediate operational repair. The emerging pattern should reduce load, restore visibility, or redistribute work before the damaged capability is asked to carry more.",
        "Do not keep celebrating aggregate abundance while a core operator or process is failing. Top-line success can mask local injury until recovery becomes expensive.",
        "What critical capability is being injured by the very scale or complexity that makes the overall situation look abundant?",
        "Line 3 treats functional injury inside a full system as a priority, reducing overload or obscurity before abundance consumes a core capability.",
      ),
      authoredLine(
        "Meet a capable counterpart after seeing through the darkness",
        "The fourth line regains enough perspective to recognize a person or resource capable of sharing the burden. Fullness no longer has to be managed alone. The important shift is from dazzled centrality toward distributed competence.",
        "When this line changes, abundance becomes more resilient because capable counterparts receive real responsibility. The emerging pattern spreads judgment and reduces the risk that one overloaded center becomes the bottleneck for a bright period.",
        "Delegation can fail if the central person gives tasks but withholds authority or information. A capable counterpart needs enough room to make decisions, not merely more work.",
        "Who has demonstrated enough capability to carry a meaningful share of this abundant period with real authority rather than just added workload?",
        "Line 4 finds a capable counterpart and distributes real responsibility so abundance no longer depends on one dazzled or overloaded center.",
      ),
      authoredLine(
        "Talented people arrive and bring blessing",
        "The fifth line uses the peak well by attracting capable people and allowing their contribution to become visible. Abundance becomes generative when talent is welcomed rather than treated as a threat to existing status. Recognition circulates and the center benefits from not needing to be the brightest object in the field.",
        "Change here turns fullness into an ecosystem of capability. The emerging pattern can outlast the peak because more people gain experience, trust, and responsibility during the favorable phase.",
        "Recruiting talent without changing access or authority can become decorative inclusion. Make sure capable people can actually influence work rather than merely adorn the abundant period.",
        "Which capable person should receive meaningful access and recognition now so the value of this abundant period becomes more widely distributed?",
        "Line 5 turns abundance into shared capability by welcoming talented contributors and giving them enough real influence to strengthen the wider system.",
      ),
      authoredLine(
        "A house of abundance becomes isolated and empty",
        "At the top line, fullness has turned inward. A person may possess resources or status while withdrawing behind them, leaving the outer relationships empty. Abundance that is not circulated can become a form of isolation because the structure grows impressive while contact with life decreases.",
        "Change here ends the identification of abundance with enclosure. The emerging direction may require opening access, sharing, simplifying, or accepting that the peak has already passed and the closed structure no longer serves a living purpose.",
        "Do not distribute resources merely to avoid feeling guilty about possession. The real issue is whether abundance remains connected to relationship and use. Thoughtless dispersal can waste what isolation had preserved.",
        "Where has abundance made you less connected to the people or purposes that originally gave the resources value?",
        "Line 6 warns that fullness can become empty isolation when resources are enclosed from the relationships and purposes that make them useful.",
      ),
    ],
  },
  {
    number: 56,
    coreTheme: "The traveler",
    coreMeaning: "The traveler describes life in a place, role, or phase where roots are shallow and local conditions matter greatly. Lu asks for modesty, adaptability, and a light footprint. A traveler cannot rely on the same authority or stored trust available at home; reputation is built through immediate conduct. The reading favors learning local rules, keeping possessions and commitments manageable, and avoiding disputes whose cost is amplified by limited support. Temporary success should not be mistaken for permanent belonging. Some stages offer shelter and loyal help; others warn that carelessness can burn the very lodging that made the journey possible. At the end, arrogance and detachment can leave the traveler laughing one moment and grieving the next. Move respectfully through what is temporary, earn trust locally, and leave cleanly when the passage is complete.",
    strength: "adaptability and careful conduct in unfamiliar or temporary conditions",
    challenge: "carelessness, entitlement, or making permanent claims before local trust exists",
    orientation: "stay modest, learn local conditions, and build trust through conduct rather than status",
    structureInterpretation: "Mountain below provides temporary stopping places while Fire above moves and depends on what it encounters. Quick I Ching reads the structure as brightness traveling across distinct stations. The traveler can pause and learn, but should not confuse each lodging with permanent ground.",
    reflectionQuestions: [
      "Which local rule or relationship do you still understand too poorly to behave as if you were fully established here?",
      "What possession, commitment, or conflict would become disproportionately costly because your roots and support are still shallow?",
      "What would a clean departure look like if this temporary phase ended sooner than expected?",
    ],
    watchFor: [
      "Local trust increasing because conduct remains modest, predictable, and attentive to context.",
      "Temporary success creating entitlement to privileges or permanence that the host environment has never actually granted.",
      "A lodging, role, or relationship becoming harder to leave because unnecessary possessions and commitments accumulate around it.",
    ],
    transitionTheme: "temporary presence becoming a useful passage when local trust is earned without overclaiming belonging",
    stabilityTheme: "a light footprint and clear conduct that keep movement possible",
    lowerTrigram: "gen",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "Petty concerns make the traveler vulnerable",
        "The first line shows someone in a weak temporary position becoming preoccupied with small gains, status signals, or trivial disputes. Because support is limited, behavior that might be merely annoying at home can become dangerous on the road. Keep priorities simple and avoid attracting trouble over matters that do not justify the risk.",
        "Change here restores scale. The emerging pattern becomes safer when attention returns to the essentials of the journey—shelter, purpose, information, and conduct—rather than using a temporary environment to chase minor advantage.",
        "Modesty should not mean accepting exploitation. A traveler still has boundaries. The caution is about unnecessary conflict and petty maneuvering, not about surrendering basic safety or dignity.",
        "Which small advantage or dispute is consuming attention far beyond its value because the temporary setting makes every interaction feel consequential?",
        "Line 1 protects the traveler by reducing petty concerns and keeping scarce local leverage focused on the essentials of the passage.",
      ),
      authoredLine(
        "Find lodging, protect possessions, gain trustworthy help",
        "The second line establishes a healthy temporary base. The traveler has shelter, resources are secure, and a reliable helper or relationship makes local life more workable. This is enough stability to rest and conduct the purpose of the journey without pretending the station is permanent.",
        "As this line changes, temporary settlement becomes functional confidence. The emerging pattern can use local help while preserving enough independence that departure remains possible when the journey calls for it.",
        "Comfort can encourage accumulation that makes the temporary base difficult to leave. Keep possessions and commitments scaled to the actual duration and purpose of the stay.",
        "What local relationship or practical arrangement can make this temporary phase secure without turning it into an unnecessary dependency?",
        "Line 2 creates a sound temporary base through shelter, secure resources, and trustworthy local help while keeping the traveler capable of moving on.",
      ),
      authoredLine(
        "Burning the lodging destroys local support",
        "The third line shows carelessness or conflict damaging the very environment that supports the traveler. A temporary position cannot afford contempt for hosts, staff, allies, or local systems. Losing the lodging and the people who made it workable can make the whole journey precarious.",
        "Change here turns a breakdown into a lesson about stewardship of temporary support. The emerging pattern may require apology, relocation, or rebuilding trust while accepting that some local damage cannot be undone quickly.",
        "Do not blame the temporary environment for consequences created by your own disregard. At the same time, if the lodging was genuinely unsafe, leaving is not the same as burning it through misconduct.",
        "What local support are you taking for granted in a way that could make the entire temporary position much harder if that support withdrew?",
        "Line 3 warns that careless treatment of temporary support can destroy both lodging and relationships, turning a manageable journey into avoidable exposure.",
      ),
      authoredLine(
        "A stopping place with possessions but no inner ease",
        "The fourth line has resources and a place to stop, yet does not feel fully at home. This can be an accurate perception rather than ingratitude. The station is functional but not a final fit. Use what it offers without demanding emotional permanence or making a premature decision to settle.",
        "When this line changes, temporary adequacy becomes clearer as a phase. The emerging pattern preserves resources and purpose while allowing the traveler to continue searching for a more fitting position when conditions permit.",
        "Restlessness can devalue a perfectly good temporary base. You do not need to love the station for it to serve its purpose. Distinguish lack of permanence from actual dysfunction.",
        "What is this temporary position good enough to provide even though it does not feel like a place you should build your identity around?",
        "Line 4 accepts a functional but emotionally incomplete station, using its resources without mistaking temporary adequacy for permanent belonging.",
      ),
      authoredLine(
        "A small loss can win recognition",
        "The fifth line shows the traveler making a precise contribution and accepting a limited cost to gain real recognition in the local field. Skill, usefulness, or an appropriate offering can create access that status alone could not. The loss is justified because it earns relationship or position rather than merely displaying wealth.",
        "Change here turns local contribution into credibility. The emerging pattern becomes more secure because the traveler is known for something useful, allowing trust to rest on conduct rather than outsider charm.",
        "Do not buy belonging through repeated sacrifice. A one-time cost is worthwhile only if it creates a reciprocal relationship or durable access. If recognition always requires another payment, the terms may be exploitative.",
        "What limited contribution or cost could legitimately earn local trust because it demonstrates useful capability rather than purchasing approval?",
        "Line 5 gains recognition through a precise, useful contribution whose limited cost creates reciprocal local credibility rather than dependency.",
      ),
      authoredLine(
        "The bird burns its nest and the traveler loses the ox",
        "At the top line, temporary success has turned into careless confidence. The traveler may laugh at first because status or freedom feels high, then discover that the base, resource, or connection needed for continued movement has been lost. Arrogance is costly when roots are shallow.",
        "Change here ends the illusion that mobility means invulnerability. The emerging direction requires humility, recovery of essentials, and recognition that every traveler remains dependent on some form of shelter, resource, and goodwill.",
        "Do not answer loss with self-condemnation so severe that the journey ends unnecessarily. Learn exactly which behavior destroyed support and rebuild from what remains rather than turning one failure into permanent exile.",
        "What success or freedom is making you careless with the shelter, resources, or goodwill that the journey still depends on?",
        "Line 6 warns that a traveler who mistakes temporary freedom for invulnerability can lose the very support that makes continued movement possible.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
