import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 57,
    coreTheme: "Gentle penetration",
    legacySummary: "Persistent, subtle influence can reach places force cannot. Clarify the direction first, then reinforce it through repeated small actions.",
    strength: "steady influence through repetition, clarity, and subtle entry",
    challenge: "drift, indirectness without direction, or repeated pressure that becomes manipulation",
    orientation: "choose the direction clearly and reinforce it through small consistent actions",
    transitionTheme: "weak influence becoming pervasive effect through persistence and coherence",
    stabilityTheme: "subtle progress sustained by repetition without losing explicit purpose",
    lowerTrigram: "xun",
    upperTrigram: "xun",
    lineEmphases: [
      "choose the first direction clearly before beginning subtle or repeated influence",
      "make small influence cumulative through consistency rather than intensity",
      "correct drift when pressure reveals that repetition has continued without a clear aim",
      "carry the subtle approach outward and listen for where it penetrates or meets resistance",
      "use central influence to reinforce direction without making persistence feel coercive",
      "stop repeating the same influence when penetration has become saturation or manipulation",
    ],
  },
  {
    number: 58,
    coreTheme: "Joyous exchange",
    legacySummary: "Open communication and shared pleasure can strengthen connection. Keep exchange sincere so enjoyment does not become flattery or avoidance.",
    strength: "mutual openness, conversation, and the energy created by genuine exchange",
    challenge: "flattery, escapism, or using pleasantness to avoid difficult truths",
    orientation: "keep communication open and enjoyable while allowing honesty to remain present",
    transitionTheme: "separate perspectives becoming connected through sincere exchange",
    stabilityTheme: "joy sustained by truthfulness rather than constant agreement",
    lowerTrigram: "dui",
    upperTrigram: "dui",
    lineEmphases: [
      "open the first exchange with enough sincerity that pleasantness does not replace truth",
      "make mutual enjoyment support honest communication in ordinary interaction",
      "address avoidance when pressure shows that harmony depends on nobody saying what matters",
      "bring openness into the wider field while allowing different responses and emotional tones",
      "use a central voice to keep exchange generous, candid, and non-coercive",
      "let the conversation change form when repeated pleasantness has stopped producing genuine contact",
    ],
  },
  {
    number: 59,
    coreTheme: "Dispersion",
    legacySummary: "Rigid separation can dissolve when attention returns to a larger shared center. Remove barriers that no longer serve and rebuild connection deliberately.",
    strength: "the capacity to dissolve rigid blocks and reconnect separated parts",
    challenge: "dissolving necessary boundaries, scattering effort, or mistaking looseness for unity",
    orientation: "remove barriers that obstruct real connection while preserving the structure still needed",
    transitionTheme: "frozen separation becoming renewed circulation around a meaningful center",
    stabilityTheme: "connection maintained by shared purpose after obsolete barriers are removed",
    lowerTrigram: "kan",
    upperTrigram: "xun",
    lineEmphases: [
      "identify the first barrier that can safely dissolve without removing necessary structure",
      "restore ordinary circulation between parts that have become unnecessarily separated",
      "avoid scattering effort when pressure makes dissolution feel like the answer to every blockage",
      "carry renewed connection into the wider field around a purpose strong enough to hold it",
      "use a central role to dissolve obsolete divisions while protecting meaningful boundaries",
      "stop dispersing once circulation has returned and the system again needs coherent form",
    ],
  },
  {
    number: 60,
    coreTheme: "Limitation",
    legacySummary: "Useful limits create form and prevent waste. Make constraints clear and proportionate; rules that become oppressive undermine the order they were meant to protect.",
    strength: "clear limits that create shape, discipline, and sustainable use",
    challenge: "overregulation, arbitrary restriction, or rejecting every limit as an obstacle",
    orientation: "set boundaries that are explicit, proportionate, and connected to a real purpose",
    transitionTheme: "unbounded activity becoming workable form through sensible constraint",
    stabilityTheme: "limits maintained by legitimacy and periodic adjustment rather than severity",
    lowerTrigram: "dui",
    upperTrigram: "kan",
    lineEmphases: [
      "set the first limit where it prevents waste without choking useful movement",
      "make boundaries understandable and repeatable in ordinary practice",
      "revise a rule when pressure exposes that restriction has become harsher than its purpose",
      "carry limits into the wider field with reasons and consequences others can understand",
      "use central authority to keep constraints proportionate, legitimate, and open to review",
      "release or redesign a limit when maintaining it now costs more order than it creates",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
