import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 57,
    coreTheme: "Gentle penetration",
    coreMeaning: "Gentle penetration describes influence that becomes effective through repeated, small entry rather than one dramatic push. Xun is wind: it reaches spaces force cannot, but only if direction is clear enough that repetition does not become drift. The reading favors consistency, listening, and subtle reinforcement. A message, standard, habit, or relationship can gradually penetrate resistance when each contact is credible and non-coercive. The danger is indirection without purpose—changing direction with every reaction, repeating words after their meaning is exhausted, or calling manipulation ‘gentleness.’ The lines move from uncertainty at the threshold toward disciplined execution, repeated inquiry, useful hunting, central correction, and finally the point where penetration turns into loss of one’s own position. Gentle influence is strongest when it knows what it serves and when to stop.",
    strength: "consistent subtle influence that can enter where direct force would fail",
    challenge: "drift, excessive indirection, or repeating pressure while calling it gentleness",
    orientation: "clarify the direction and use small consistent actions that others remain free to respond to",
    structureInterpretation: "Wind below and Wind above double the trigram of gradual penetration and repeated influence. Quick I Ching reads the structure as change occurring through recurrence: the same direction enters again and again until the field responds. Repetition needs a stable purpose or it becomes dispersion rather than penetration.",
    reflectionQuestions: [
      "What direction needs to remain stable so small repeated actions accumulate instead of canceling one another?",
      "Where would listening and another modest contact produce better information than a stronger demand?",
      "What sign would tell you that continued subtle influence has become manipulation, saturation, or loss of your own position?",
    ],
    watchFor: [
      "A repeated small practice becoming easier for others to recognize and respond to without increased pressure.",
      "The direction of influence shifting so often that consistency is lost even though activity remains high.",
      "Resistance decreasing because the approach becomes more intelligible, credible, and non-coercive over time.",
    ],
    transitionTheme: "small repeated influence becoming meaningful change when direction remains clear",
    stabilityTheme: "gentle persistence that listens, adapts, and stops before subtlety becomes manipulation",
    lowerTrigram: "xun",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Advance and retreat reveal an unclear direction",
        "The first line shows gentle movement becoming indecisive. Repeated advance and retreat may look flexible but actually reveal that the governing direction has not been chosen. Before influence can penetrate, the person needs a clearer standard for when to proceed and when to stop.",
        "Change here turns wavering into disciplined orientation. The emerging pattern gains force because small actions begin to point the same way rather than being canceled by repeated reversals.",
        "Firming the direction does not mean ignoring feedback. The correction is to choose a stable purpose while allowing tactics to adapt. Rigidity would simply replace one distortion with another.",
        "What principle would let you decide whether to advance or retreat without making each move depend on the latest emotional reaction?",
        "Line 1 gives gentle penetration a stable direction so repeated small movements can accumulate instead of dissolving into indecision.",
      ),
      authoredLine(
        "Penetrate beneath the bed to find the hidden cause",
        "The second line investigates what lies underneath the visible situation. Subtle resistance may come from fear, incentive, history, or an unspoken concern that cannot be addressed by repeating the surface message. Careful inquiry, multiple perspectives, or specialist help may be appropriate because the cause is not immediately visible.",
        "As this line changes, influence becomes diagnostic. The emerging pattern improves because the approach begins addressing the hidden condition rather than applying the same gentle pressure to a symptom that cannot respond.",
        "Deep investigation can become suspicion or endless interpretation. Stop digging when evidence is sufficient. Hidden causes should be supported by observable patterns, not by the fascination of believing something secret must exist.",
        "What underlying fear, incentive, or history might explain the resistance better than the surface explanation, and how can you test that possibility directly?",
        "Line 2 deepens gentle influence into careful diagnosis so repeated contact addresses the hidden cause rather than only the visible resistance.",
      ),
      authoredLine(
        "Repeated penetration without decision becomes humiliating",
        "The third line warns against revisiting the same issue so many times that subtlety loses credibility. If every conversation, review, or intervention ends without decision, repetition signals uncertainty rather than patience. At some point the gathered information must change conduct.",
        "Change here converts repeated inquiry into a clearer choice. The emerging pattern regains dignity because penetration has produced enough understanding to support a decision, boundary, or revised method.",
        "Do not decide merely to escape embarrassment. The issue is unnecessary repetition after sufficient evidence, not a deadline independent of information. If something material remains unknown, continue inquiry deliberately.",
        "What have you examined repeatedly enough that another round would add less value than making a decision from what is already known?",
        "Line 3 ends repetitive penetration once enough information exists, turning accumulated understanding into a decision instead of another cycle of inquiry.",
      ),
      authoredLine(
        "A well-directed hunt can yield several gains",
        "The fourth line shows subtle effort becoming practical and productive. Because the direction is now clear, one well-designed action can produce multiple benefits—information, relationship, resource, and progress together. Gentle penetration no longer looks hesitant; it becomes efficient because prior listening improved the aim.",
        "When this line changes, gradual influence turns into tangible result. The emerging pattern demonstrates why earlier restraint and investigation mattered: the action now reaches several useful targets without requiring excessive force.",
        "Success can tempt the person to generalize one good method too widely. Keep checking fit. A precise hunt is valuable because it is tailored to the present field, not because it proves one tactic is universally effective.",
        "What focused action could now produce several useful results because earlier listening has made the target and timing clearer?",
        "Line 4 converts gentle penetration into efficient practical action, using accumulated understanding to reach several useful outcomes with one well-aimed move.",
      ),
      authoredLine(
        "No good beginning, but a strong center can correct the course",
        "The fifth line recognizes a process that may have started poorly yet can still be repaired through central consistency. The person now has enough understanding and authority to make a sequence of deliberate corrections. Preparation before the change and verification afterward are both important.",
        "Change here turns a weak beginning into a credible new direction. The emerging pattern becomes stable through continuity: announce less, adjust clearly, and keep the revised standard long enough that others can experience the difference.",
        "A corrective campaign can become another wave of constant change. Choose the repair carefully and stop redesigning once the new practice is working. Penetration needs repetition of the improved pattern, not endless novelty.",
        "What central correction could redeem a poor beginning, and what should remain unchanged afterward long enough for the repair to become credible?",
        "Line 5 repairs a weak start through deliberate central correction followed by enough consistency for the improved pattern to penetrate and hold.",
      ),
      authoredLine(
        "Penetrating too far beneath the bed loses the means to act",
        "At the top line, subtle investigation and accommodation have gone so far that the person loses their own position, resources, or capacity to act. The search for hidden causes or perfect receptivity has become self-erasing. Influence cannot remain useful when the influencer no longer has a clear center.",
        "Change here ends excessive penetration by restoring boundary and possession. The emerging direction may require stopping inquiry, naming a final position, and recovering the tools or authority that were diluted through endless accommodation.",
        "Do not react by becoming blunt or closed to all nuance. The lesson is to preserve a center within sensitivity, not to abandon sensitivity. Gentle influence still needs something stable from which to operate.",
        "Where has trying to understand or accommodate every layer of the situation begun to cost you the resources or position needed to act at all?",
        "Line 6 stops excessive penetration when sensitivity has become self-erasure, restoring the clear center and resources from which gentle influence can remain real.",
      ),
    ],
  },
  {
    number: 58,
    coreTheme: "Joyous exchange",
    coreMeaning: "Joyous exchange describes openness that creates energy through conversation, relationship, shared pleasure, and mutual recognition. Dui is not simple happiness. Its quality depends on whether joy makes truth easier to speak or harder. Pleasant interaction can lower defenses and strengthen cooperation, but it can also become flattery, distraction, or a silent agreement not to disturb the mood. The reading favors candid enjoyment: let connection make difficult truth more possible, not less. Different lines distinguish sincere joy, trustworthy inner satisfaction, dependence on external approval, negotiated pleasure, attraction to corrosive influence, and finally the danger of drawing others through charm alone. Sustainable joy renews itself through real contact and shared value. It does not require constant stimulation or the suppression of uncomfortable evidence.",
    strength: "open exchange that can renew connection and make communication easier",
    challenge: "flattery, escapism, or preserving a pleasant mood by avoiding necessary truths",
    orientation: "enjoy connection while keeping speech honest enough that pleasure remains trustworthy",
    structureInterpretation: "Lake below and Lake above double the trigram of openness, speech, and pleasure. Quick I Ching reads the doubled structure as exchange reinforcing itself through response. Joy becomes durable when the openness remains truthful; otherwise reciprocal pleasure can amplify distortion just as easily as trust.",
    reflectionQuestions: [
      "What truth becomes easier to say because the relationship currently contains enough warmth and openness to receive it?",
      "Where are you protecting a pleasant atmosphere at the cost of information that the relationship actually needs?",
      "What form of joy leaves both parties more capable afterward rather than more dependent on another dose of reassurance or stimulation?",
    ],
    watchFor: [
      "Conversation becoming more candid because people feel secure enough to disagree without losing the relationship.",
      "Praise, humor, or pleasant ritual repeatedly appearing at the exact point where a difficult issue should be addressed.",
      "Shared enjoyment producing stronger cooperation and energy even after the immediate pleasurable moment has passed.",
    ],
    transitionTheme: "separate positions becoming connected through open and truthful exchange",
    stabilityTheme: "joy renewed by sincerity rather than maintained through avoidance or performance",
    lowerTrigram: "dui",
    upperTrigram: "dui",
    lines: [
      authoredLine(
        "Simple harmonious joy needs no performance",
        "The first line begins with pleasure that is uncomplicated by strategic display. People can enjoy the exchange because neither side needs the moment to prove status, secure a promise, or create debt. This simplicity is a useful baseline for judging later forms of joy.",
        "Change here lets genuine pleasure become trust. The emerging pattern gains stability because repeated positive contact does not carry hidden terms that need to be decoded afterward.",
        "Do not mistake shallowness for simplicity. A light interaction can be sincere, but if serious responsibilities exist, harmony eventually has to include them. Pleasure should not become the only permitted register.",
        "What part of this connection is enjoyable precisely because neither side is trying to turn the pleasant moment into leverage?",
        "Line 1 establishes joyous exchange through uncomplicated harmony, creating trust because pleasure is not being used to secure hidden advantage.",
      ),
      authoredLine(
        "Sincere joy creates confidence from within",
        "The second line describes satisfaction grounded enough that it does not depend entirely on external reaction. A person can enjoy connection while remaining internally steady. This makes speech more trustworthy because approval is welcome but not required for the relationship to feel valuable.",
        "As this line changes, joy becomes a stable relational resource. The emerging pattern can tolerate disagreement or temporary distance without treating either as proof that the connection has disappeared.",
        "Inner confidence can become self-satisfaction that stops listening. Sincerity still requires response to the other person’s experience. A stable center should increase openness, not remove the need for mutuality.",
        "What makes this relationship satisfying even when you are not receiving immediate praise, reassurance, or visible enthusiasm from the other side?",
        "Line 2 grounds joy in sincere inner confidence so connection can remain open without becoming dependent on constant external approval.",
      ),
      authoredLine(
        "Joy that comes only from outside is unstable",
        "The third line warns about relying on external stimulation, attention, or approval to produce a sense of aliveness. The person keeps looking outward for the next pleasurable response. This can make relationships instrumental because other people become suppliers of mood rather than partners in exchange.",
        "Change here redirects joy toward a more balanced source. The emerging pattern becomes healthier when external pleasure complements rather than substitutes for inward stability, meaningful activity, and reciprocal contribution.",
        "Do not use self-sufficiency as an excuse to deny normal human need for connection. The issue is monopoly: joy becomes fragile when one external source is expected to regulate the entire emotional system.",
        "What external source of pleasure or approval has become responsible for more of your emotional stability than any relationship can sustainably carry?",
        "Line 3 reduces dependence on externally supplied joy so relationship can return to reciprocal exchange instead of functioning as emotional regulation on demand.",
      ),
      authoredLine(
        "Negotiated joy cannot settle until terms are clear",
        "The fourth line experiences pleasure mixed with calculation. Competing attractions, loyalties, or terms make it difficult to relax into the exchange. The discomfort is useful because it signals that a choice or boundary remains unresolved. Once the harmful option is separated from the healthy one, joy can become simpler.",
        "When this line changes, ambivalence becomes clearer preference. The emerging pattern gains ease because the relationship no longer has to carry incompatible conditions at the same time.",
        "Do not eliminate complexity simply to feel comfortable. Some tensions are legitimate and deserve ongoing negotiation. The cut should target what is actually corrosive, not every condition that prevents effortless pleasure.",
        "What unresolved term or competing attraction is preventing this exchange from becoming genuinely relaxed and trustworthy?",
        "Line 4 treats unsettled joy as evidence that terms need clarification, allowing pleasure to become simpler once the corrosive condition is removed.",
      ),
      authoredLine(
        "Trusting what is corrosive makes joy dangerous",
        "The fifth line warns that openness can be exploited. A charming person, habit, or influence may offer pleasure while quietly weakening judgment or integrity. The central challenge is to remain capable of discriminating inside attraction rather than assuming what feels enjoyable is therefore safe.",
        "Change here restores a boundary within openness. The emerging pattern can preserve joy that is healthy while withdrawing trust from the element that repeatedly produces harm beneath the pleasant surface.",
        "Suspicion can also destroy good connection. Use evidence of corrosive effect, not fear of pleasure itself. A boundary is most credible when it responds to a repeated pattern rather than to moral anxiety about enjoyment.",
        "What pleasurable influence repeatedly leaves your judgment, commitments, or relationships weaker after the enjoyment has passed?",
        "Line 5 protects joyous openness from corrosive influence by judging pleasure according to its repeated effects rather than its immediate appeal.",
      ),
      authoredLine(
        "Drawing others through charm reaches its limit",
        "At the top line, joy becomes something actively used to attract or pull people. Charisma, entertainment, praise, or social ease can gather attention, but influence built mainly on pleasantness becomes unstable once a harder truth, cost, or disagreement appears.",
        "Change here releases charm from the burden of carrying the whole relationship. The emerging direction asks substance, shared work, and honest terms to take over what pleasantness can no longer sustain by itself.",
        "Do not become ashamed of charisma or hospitality. They are valuable doors. The warning is against treating the door as the entire house and then being surprised when people leave once pleasure alone is insufficient.",
        "What relationship or audience are you trying to hold mainly through pleasantness, and what substantive connection would need to exist if the charm stopped working?",
        "Line 6 marks the limit of attraction through pleasure alone and redirects the relationship toward substance strong enough to survive beyond charm.",
      ),
    ],
  },
  {
    number: 59,
    coreTheme: "Dispersion",
    coreMeaning: "Dispersion describes the dissolving of barriers that have become too rigid for healthy circulation. Huan can loosen fear, frozen roles, isolation, stale conflict, and boundaries that once protected but now prevent contact. The reading does not call for indiscriminate dissolution. Some forms are necessary; the task is to distinguish an obsolete barrier from a structure that still carries responsibility. Dispersion often works by reconnecting people to a larger center—shared purpose, ritual, institution, or common need—so hardened local divisions lose some of their power. The lines move from immediate rescue through dissolving self-interest and faction, toward central renewal and finally release from lingering danger. The goal is restored flow, not permanent looseness. Once circulation returns, a suitable form should emerge again so connection has enough structure to remain useful.",
    strength: "the ability to dissolve obsolete barriers and restore circulation",
    challenge: "removing necessary boundaries, scattering resources, or mistaking looseness for unity",
    orientation: "dissolve what is frozen while preserving the structures still needed for responsibility and trust",
    structureInterpretation: "Water below represents separation and danger while Wind above moves across the surface and disperses what has congealed. Quick I Ching reads the structure as circulation returning through penetration and movement. Dispersion is valuable when it reconnects what fear or rigidity had isolated.",
    reflectionQuestions: [
      "Which boundary once protected something useful but now mainly blocks communication, trust, or movement?",
      "What shared center could help people loosen factional identity without requiring their differences to disappear?",
      "What new structure will be needed after the barrier dissolves so restored circulation does not become scattering?",
    ],
    watchFor: [
      "A previously frozen relationship becoming easier to approach after one defensive ritual, rule, or assumption is relaxed.",
      "Resources and attention scattering because every boundary is being treated as an obstacle rather than evaluated by function.",
      "A larger shared purpose making local divisions less absolute and allowing practical contact to resume.",
    ],
    transitionTheme: "frozen separation becoming circulation when obsolete barriers dissolve",
    stabilityTheme: "connection preserved by rebuilding only the forms that still serve trust and responsibility",
    lowerTrigram: "kan",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Use strong help to disperse the first danger",
        "The first line responds quickly before separation or fear hardens. A strong ally, resource, or practical intervention can break the first frozen pattern and restore movement. Speed matters because a small barrier is easier to dissolve before people build identity around it.",
        "Change here turns emerging isolation into renewed contact. The emerging pattern benefits from using available strength for rescue rather than for blame, giving circulation a chance to restart before the problem becomes institutional.",
        "Do not bring overwhelming force to a barrier that only needs a small opening. The helper should disperse danger, not become the new center of control. Scale assistance to the actual freeze.",
        "What strong but proportionate help could reopen contact now before fear or separation becomes a settled pattern?",
        "Line 1 uses timely support to break an early freeze, restoring movement before separation gains enough history to become harder to dissolve.",
      ),
      authoredLine(
        "Disperse toward a reliable support",
        "The second line needs somewhere sound to move as the old pattern loosens. Dispersion without a refuge can feel like collapse. A trusted relationship, practice, or institution can provide enough stability that defensive structures are no longer needed merely to prevent falling apart.",
        "As this line changes, loosening becomes supported transition. The emerging pattern gains courage because people can release an obsolete defense while still knowing what they can lean on during the change.",
        "A support can become a new dependency or faction if it is used as the only safe place. The goal is to restore wider circulation, not simply move from one closed shelter into another.",
        "What reliable support would make it safer to release this old defense without turning the support itself into a new enclosure?",
        "Line 2 gives dispersion a trustworthy support point so obsolete defenses can loosen without making the transition feel like uncontained collapse.",
      ),
      authoredLine(
        "Disperse the self-centered knot",
        "The third line asks the person to release an attachment to personal position, grievance, or advantage that keeps the larger situation frozen. The barrier may be partly maintained by insisting that one’s own perspective remain the center of the repair. Letting go can create room for a solution that serves more than personal vindication.",
        "Change here turns private fixation into wider participation. The emerging pattern gains circulation because the person can rejoin the whole without demanding that every step confirm their original story.",
        "Self-release is not self-erasure. Do not abandon legitimate needs or boundaries merely to restore harmony. The target is the knot of egoic insistence, not the underlying right to safety or fairness.",
        "What personal grievance or need to be vindicated is keeping you from participating in a solution that would still protect the essential boundary?",
        "Line 3 dissolves a self-centered knot so the person can rejoin a wider solution without surrendering legitimate needs or standards.",
      ),
      authoredLine(
        "Disperse the faction to create a larger gathering",
        "The fourth line dissolves a subgroup identity that has become more important than the whole. This can look like loss at first because faction provides belonging, but releasing it may create a larger field of cooperation that was impossible while loyalty remained locally concentrated.",
        "When this line changes, dispersion becomes a new kind of gathering. The emerging pattern connects people across former subgroup lines, allowing purpose and resources to circulate at a larger scale.",
        "Do not erase communities that provide real support merely in the name of unity. A faction becomes a problem when it systematically prevents wider cooperation or treats the whole as an enemy.",
        "Which subgroup identity is now blocking cooperation at a larger level, and what shared purpose could make loosening that boundary worth the loss of local exclusivity?",
        "Line 4 dissolves a restrictive faction so people can gather around a larger purpose without requiring every local bond to disappear.",
      ),
      authoredLine(
        "A central declaration disperses confusion and hoarded resources",
        "The fifth line uses central authority to restore circulation. Clear communication and visible redistribution can dissolve uncertainty about what the system is doing and who the resources are for. The center becomes useful not by holding everything, but by moving information and capacity where they can function.",
        "Change here turns centrality into dispersive stewardship. The emerging pattern gains trust because the leader makes purpose, resources, and decisions circulate instead of allowing ambiguity to accumulate around the center.",
        "Transparency can become indiscriminate disclosure, and redistribution can ignore legitimate reserves. Disperse what is blocking trust and function; keep what must remain protected for continuity or privacy.",
        "What information or resource is currently too concentrated at the center, and how could releasing it restore useful circulation without compromising necessary protection?",
        "Line 5 uses central authority to disperse confusion and excess concentration, restoring circulation through clear communication and responsible redistribution.",
      ),
      authoredLine(
        "Disperse the blood and leave the danger",
        "At the top line, dispersion reaches the source of immediate harm. The correct movement is away from the dangerous condition rather than continued analysis inside it. Separation from violence, toxicity, or acute threat can be the final and healthiest form of dissolving the old connection.",
        "Change here completes dispersion through decisive release from danger. The emerging pattern creates enough distance for ordinary circulation and relationship to be rebuilt elsewhere without the acute threat organizing every decision.",
        "Do not use the language of danger casually to justify abandoning every difficult relationship. The threat should be concrete and consequential. When it is, however, safety takes precedence over preserving connection.",
        "What concrete danger requires real distance now, rather than another attempt to preserve a connection whose current form keeps producing harm?",
        "Line 6 completes dispersion by creating decisive distance from a real danger so the wider system can recover circulation without remaining organized around acute threat.",
      ),
    ],
  },
  {
    number: 60,
    coreTheme: "Limitation",
    coreMeaning: "Limitation describes boundaries that make action sustainable by giving resources, behavior, and expectations a usable form. Jie distinguishes good limits from arbitrary restriction. A sound limit has a purpose people can understand, a cost proportionate to what it protects, and some mechanism for review when conditions change. Too few limits create leakage and overload; too many make the system brittle or invite evasion. The reading moves from staying inside an initial boundary, through knowing when to step out, recognizing the cost of limitlessness, accepting workable rules, centralizing a fair standard, and finally rejecting bitter limitation that cannot be sustained. Discipline is credible when it saves more capacity than it consumes. The strongest boundary is not the harshest one; it is the one people can follow because its reason remains visible and its burden remains proportionate.",
    strength: "clear limits that shape and sustain effort",
    challenge: "overregulation, arbitrary restriction, or rejecting all limits as loss of freedom",
    orientation: "make limits explicit, proportionate, and connected to the purpose they protect",
    structureInterpretation: "Lake below contains a finite body of water while Water above adds risk and flow. Quick I Ching reads the structure as capacity that needs boundaries to remain usable. Limitation prevents leakage and excess, but because water must still move, boundaries also need channels and review.",
    reflectionQuestions: [
      "What resource or behavior currently needs a clearer limit so it remains usable rather than being consumed by excess?",
      "Which rule has become expensive enough that its burden may now exceed the purpose it originally protected?",
      "How can people understand and review this boundary rather than experience it as unexplained control?",
    ],
    watchFor: [
      "A clear limit reducing anxiety because people no longer have to renegotiate the same resource or behavior every time.",
      "Harsh rules producing workarounds, concealment, or brittle compliance instead of the protected outcome they were meant to create.",
      "A boundary becoming easier to respect once its purpose and review condition are explicit.",
    ],
    transitionTheme: "unbounded demand becoming sustainable form through proportionate limits",
    stabilityTheme: "legitimate constraints maintained through clear purpose and regular review",
    lowerTrigram: "dui",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Do not leave the inner gate too early",
        "The first line keeps movement inside a small boundary because the outer conditions are not yet ready. Staying within the immediate sphere can protect resources and prevent unnecessary exposure. The limit is local and temporary, not a statement that movement is always wrong.",
        "Change here turns restraint into readiness. The emerging pattern gains strength because the person uses the contained period to clarify conditions and waits for a real opening rather than testing the boundary merely from impatience.",
        "Do not turn a temporary gate into a permanent comfort zone. Define what evidence would justify stepping out. A limit without a review condition can become avoidance.",
        "What should remain inside the current boundary for now, and what specific change would make it appropriate to step beyond it?",
        "Line 1 uses a temporary local limit to protect readiness while keeping the conditions for eventual movement explicit.",
      ),
      authoredLine(
        "Not leaving the outer gate can become its own mistake",
        "The second line shows the opposite problem: a boundary that was useful has become too restrictive because the opening is now present. Continuing to stay inside wastes opportunity and turns caution into self-imposed confinement. Limits should respond to conditions, not survive them automatically.",
        "As this line changes, disciplined restraint becomes disciplined expansion. The emerging pattern uses the capacity protected by the earlier limit in the moment when outward movement can finally be supported.",
        "Do not step out simply because boredom makes the boundary irritating. Verify that conditions truly changed. The lesson is timely release of the limit, not rejection of restraint itself.",
        "What evidence shows that a previously useful boundary has completed its purpose and is now costing more than it protects?",
        "Line 2 releases a boundary whose time has passed, recognizing that disciplined movement can be as important as disciplined restraint.",
      ),
      authoredLine(
        "A life without limits eventually produces lament",
        "The third line experiences the consequence of insufficient restraint. Resources, time, appetite, or behavior have been allowed to flow without a governing boundary, and regret appears only after the cost becomes visible. The useful response is not shame but design: create a limit connected to the failure that occurred.",
        "Change here converts regret into a practical constraint. The emerging pattern becomes more sustainable because the cost has revealed where freedom actually needed form.",
        "Do not respond to one episode of excess with a sweeping punitive regime. The new limit should target the mechanism that created the loss. Overcorrection often produces a second cycle of failure.",
        "What specific absence of a limit produced this regret, and what narrow boundary would prevent recurrence without controlling unrelated parts of life?",
        "Line 3 turns the cost of limitlessness into a targeted, proportionate rule rather than a shame-driven overcorrection.",
      ),
      authoredLine(
        "Contentment with a workable limit creates ease",
        "The fourth line shows a boundary that fits the situation well enough to be lived without constant resentment. People understand the limit, the burden is tolerable, and the protected purpose remains visible. This is one of the best signs that restraint has become sustainable rather than imposed.",
        "When this line changes, limitation becomes cultural habit. The emerging pattern requires less enforcement because the boundary feels like a normal condition of good functioning rather than an external obstacle.",
        "Comfort with a rule should not eliminate periodic review. Conditions can change slowly. A boundary that once fit can become obsolete while people continue following it from habit.",
        "Which current limit is working well enough that people can live inside it without constant negotiation, and how will you know when it needs review?",
        "Line 4 shows a proportionate limit becoming easy to inhabit, reducing the need for enforcement while keeping future review available.",
      ),
      authoredLine(
        "A fair central limit becomes sweet rather than bitter",
        "The fifth line places limitation in a central governing role. A good standard distributes burden fairly, is explained clearly, and applies consistently enough that people can plan around it. The rule becomes ‘sweet’ because it creates predictability and protects shared capacity rather than merely displaying authority.",
        "Change here turns central restraint into legitimacy. The emerging pattern gains trust because limits are seen to serve the whole and because leaders themselves remain subject to the standard.",
        "Even a fair rule can become self-satisfied if leaders stop hearing edge cases. Preserve a credible exception or review process so consistency does not become indifference to context.",
        "What would make this central limit feel fair even to the people who receive the least immediate benefit from it?",
        "Line 5 gives limitation legitimacy through fair burden, clear purpose, and leadership that remains accountable to the same standard.",
      ),
      authoredLine(
        "Bitter limitation cannot be sustained indefinitely",
        "At the top line, restraint has become so harsh that it damages the system it was meant to protect. People may comply temporarily through fear or lack of options, but the cost creates resentment, evasion, and eventual breakdown. The rule needs redesign or release.",
        "Change here ends punitive excess in limitation. The emerging direction preserves the underlying purpose while finding a boundary people can actually sustain. A less severe rule may produce better real compliance than a perfect rule nobody can live with.",
        "Do not remove every difficult limit merely because it is unpopular. Some necessary boundaries are genuinely costly. The test is whether the burden remains proportionate to the protected value and whether a less damaging design can achieve the same purpose.",
        "Which rule has become so costly that it now undermines its own purpose, and what less bitter limit could protect the same essential value?",
        "Line 6 rejects unsustainable harshness while preserving the need for form, redesigning limitation so the protected purpose can survive real human use.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
