import { authoredLine, buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 61,
    coreTheme: "Inner truth",
    coreMeaning: "Inner truth describes credibility produced when belief, speech, and conduct become congruent enough that trust does not depend on performance. Zhong Fu is not a demand to trust every strong feeling. Sincerity becomes useful only when it can listen, receive evidence, and remain honest about what is not known. The image includes both an open center and firm outer structure: truthfulness needs receptivity inside and boundaries around it. The lines distinguish prepared trust, shared resonance, emotional dependence, separation from the group, influence strong enough to bind others, and finally the emptiness of truth that exists only as lofty words. The reading favors evidence-backed sincerity. A trustworthy person can change their mind without becoming false because the deeper commitment is to reality rather than to appearing consistent.",
    strength: "congruence between inner conviction, speech, and observable conduct",
    challenge: "self-deception, credulity, or demanding trust without earning it",
    orientation: "align what you believe, say, and do while keeping conviction open to evidence",
    structureInterpretation: "Lake below and Wind above form a figure with a yielding open center held inside firm outer lines. Quick I Ching reads the structure as receptivity protected by integrity: inner truth requires openness to what enters while outer conduct remains stable enough that sincerity can become credible to others.",
    reflectionQuestions: [
      "Where do your stated beliefs and repeated behavior currently point in different directions?",
      "What evidence would you be willing to accept if it challenged a conviction that presently feels sincere?",
      "What would make another person able to trust this commitment without relying on your intensity of feeling or persuasive language?",
    ],
    watchFor: [
      "Trust increasing because promises, explanations, and repeated conduct begin to align without extra reassurance.",
      "Strong conviction becoming resistant to evidence, with sincerity used as proof that the belief must be correct.",
      "A difficult conversation becoming more workable because both parties can state uncertainty without treating it as dishonesty.",
    ],
    transitionTheme: "uncertainty becoming trust when inward conviction and outward evidence begin to agree",
    stabilityTheme: "credibility renewed through congruent conduct and continued openness to correction",
    lowerTrigram: "dui",
    upperTrigram: "xun",
    lines: [
      authoredLine(
        "Prepared trust brings steadiness",
        "The first line begins inner truth with preparation rather than instant intimacy. Trust becomes safer when expectations, boundaries, and one’s own motives are understood before major reliance is placed on another person or course. A quiet internal check can prevent sincerity from becoming naive exposure.",
        "Change here turns private readiness into the first credible act of trust. The emerging pattern becomes more stable because openness begins from a center that has considered what it can promise and what evidence it still needs.",
        "Preparation can become suspicion if every relationship is required to eliminate uncertainty before trust begins. The goal is enough clarity for proportionate reliance, not perfect knowledge.",
        "What expectation or boundary should you clarify inside yourself before asking this relationship to carry more trust?",
        "Line 1 prepares the ground for inner truth so trust begins proportionately rather than through either impulsive exposure or defensive suspicion.",
      ),
      authoredLine(
        "A sincere call finds a sincere response",
        "The second line shows resonance that does not need public performance. A genuine signal reaches another responsive person because both sides recognize something real in the exchange. Sharing follows naturally from trust rather than being used to manufacture it.",
        "As this line changes, inner sincerity becomes reciprocal relationship. The emerging pattern gains strength because value, information, or support can circulate without elaborate bargaining; the response itself confirms the quality of the connection.",
        "Resonance can feel so affirming that differences disappear from attention. Do not assume shared feeling means total agreement. Keep the relationship spacious enough for independent judgment.",
        "What quiet response from another person provides better evidence of genuine alignment than a larger public display of agreement would?",
        "Line 2 shows sincere inner truth finding voluntary resonance, creating reciprocal exchange without requiring performance or pressure.",
      ),
      authoredLine(
        "Depending on another person for emotional direction creates instability",
        "The third line places inner state too heavily in another person’s hands. Their closeness or distance determines whether you rejoice, grieve, advance, or retreat. The relationship may be real, but dependence on its moment-to-moment signals weakens the center from which truthful response should arise.",
        "Change here restores emotional authorship. The emerging pattern becomes healthier as the person can remain responsive to the relationship without making every fluctuation in another’s behavior the command for their own state.",
        "Independence does not require emotional numbness. Other people should affect us. The issue is whether response remains proportionate and whether your own values can still guide conduct when the other person is inconsistent.",
        "Which part of your emotional direction is currently being set almost entirely by another person’s latest signal, and what inner standard could restore proportion?",
        "Line 3 separates genuine responsiveness from emotional dependency, returning enough center that inner truth can remain stable across another person’s fluctuations.",
      ),
      authoredLine(
        "A nearly full moon requires leaving the pair behind",
        "The fourth line shows sincerity approaching maturity while an old pairing, faction, or dependency must be left behind. Alignment with a larger standard may require separation from a relationship that once helped define the path. The loss can be clean when it serves a more complete integrity.",
        "When this line changes, inner truth becomes less dependent on one companion or local bond. The emerging pattern gains a wider field because the person can carry the principle beyond the relationship through which it was first learned.",
        "Do not abandon loyalty merely because independence sounds mature. Separation is justified when the old bond genuinely conflicts with the larger standard, not simply because closeness has become ordinary.",
        "What relationship or faction helped you develop this conviction but may now be too narrow to define how the conviction should be lived?",
        "Line 4 matures inner truth by allowing a once-important pairing to loosen when fidelity to the larger standard requires greater independence.",
      ),
      authoredLine(
        "Sincerity strong enough to bind people together",
        "The fifth line places inner truth at the center of influence. Trust can connect people because the leader or relationship repeatedly demonstrates congruence between word and act. The binding force is not coercion but predictability of principle: others know what the center will honor even under pressure.",
        "Change here turns personal sincerity into social cohesion. The emerging pattern can coordinate wider responsibility because trust reduces the need for surveillance and defensive bargaining.",
        "Central credibility can become personal dependence if systems are not built around the principle. Make standards transferable so trust survives the absence or succession of the current person.",
        "What principle behind your credibility should be made explicit enough that people can continue trusting the system even when you are not personally present?",
        "Line 5 makes inner truth socially binding through demonstrated congruence, then asks that the trustworthy principle become larger than the individual who embodies it.",
      ),
      authoredLine(
        "Truth proclaimed from the sky without substance cannot last",
        "At the top line, claims of sincerity rise higher than the conduct that can support them. Lofty language, moral certainty, or repeated declarations of trustworthiness become empty when evidence on the ground is thin. Inner truth cannot be sustained as reputation alone.",
        "Change here brings credibility back down to observable life. The emerging direction requires fewer proclamations and more conduct that can be inspected, repeated, and corrected. What is true should not need volume to remain true.",
        "Do not become cynical about ideals merely because rhetoric can be abused. High principles matter when they shape behavior. The correction is embodiment, not abandonment of aspiration.",
        "Which important claim are you making more strongly than your current conduct can support, and what behavior would make the statement unnecessary to repeat?",
        "Line 6 exposes inner truth that has become lofty rhetoric and returns credibility to the ordinary conduct that can actually sustain a principle.",
      ),
    ],
  },
  {
    number: 62,
    coreTheme: "Small exceeding",
    coreMeaning: "Small exceeding describes a situation where modest extra attention is justified but grand action is not. Xiao Guo favors precision, humility, and adjustment close to the ground. Conditions may be unusual enough that ordinary detail needs to be exceeded slightly—more caution, more preparation, more care in a small task—while large ambitions would stretch the structure beyond what it can support. The bird image in the hexagram emphasizes staying lower rather than flying too high. The reading therefore distinguishes necessary small excess from theatrical overreach. A minor warning can deserve an extra check; a small responsibility can deserve unusually careful execution. The danger comes when local success is interpreted as permission for a major leap. Do the little thing better than usual, keep the scope honest, and stop once the specific condition has been addressed.",
    strength: "precision and careful adjustment at a manageable scale",
    challenge: "grand gestures, overreach, or giving minor details more importance than they deserve",
    orientation: "attend closely to small matters and keep ambition within the scale the structure can carry",
    structureInterpretation: "Mountain below provides a firm low base while Thunder above creates movement that can easily rise beyond it; two strong central lines are surrounded by yielding lines. Quick I Ching reads the structure as a call to remain close to manageable scale. Small departures may be useful, but large elevation is poorly supported.",
    reflectionQuestions: [
      "Which small detail deserves more care than usual because the current conditions make a minor error unusually costly?",
      "What large move are you tempted to justify with evidence that really only supports a modest adjustment?",
      "Where would staying lower, closer, or more practical create better results than seeking a more impressive position?",
    ],
    watchFor: [
      "A modest extra check or preparation preventing a problem disproportionate to the small cost of caution.",
      "Success in a narrow task producing confidence for a much larger move whose support has never been tested.",
      "A small adjustment completing its purpose cleanly without growing into an identity of permanent caution or exceptionalism.",
    ],
    transitionTheme: "small departures from the ordinary becoming useful when they remain proportionate to the need",
    stabilityTheme: "accuracy and humility maintained by keeping scale close to what the structure can actually support",
    lowerTrigram: "gen",
    upperTrigram: "zhen",
    lines: [
      authoredLine(
        "The bird flies upward too soon",
        "The first line warns that an early impulse to rise, expand, or make the situation more significant than it is can create immediate trouble. The foundation supports careful local movement, not an ambitious launch. Keep the first action close to the ground where correction remains easy.",
        "Change here redirects premature elevation into modest scale. The emerging pattern gains safety because attention returns to the small task actually supported rather than the larger identity the person wants the task to prove.",
        "Do not equate low position with lack of ambition forever. The warning concerns present support. Build evidence at the small scale so a later larger move can rest on something real.",
        "What larger move are you trying to make before the small foundation beneath it has demonstrated enough support?",
        "Line 1 keeps the first movement low and manageable, preventing ambition from lifting a small task beyond the support it currently has.",
      ),
      authoredLine(
        "Pass the grandparent and meet the nearer caretaker",
        "The second line favors addressing the responsibility through the appropriate nearer level rather than seeking the highest authority. A modest route can be both respectful and effective. The issue does not need to become larger simply because a more prestigious channel exists.",
        "As this line changes, small exceeding becomes correct procedural fit. The emerging pattern resolves the matter closer to where it can actually be handled, reducing delay and symbolic escalation.",
        "Do not bypass necessary authority when the nearer level lacks competence or mandate. Use the lowest level that can genuinely resolve the issue, not the lowest level merely for the appearance of modesty.",
        "Who is the nearest appropriate person capable of handling this matter without unnecessarily escalating it to a more distant or prestigious authority?",
        "Line 2 keeps the issue at the nearest competent level, using modest procedural scale instead of turning a manageable matter into a grand appeal.",
      ),
      authoredLine(
        "Extra caution is needed against a small danger from behind",
        "The third line shows why a minor matter can deserve unusual vigilance. A threat that looks too small to justify attention may exploit exactly that assumption. A small additional safeguard is appropriate because the downside of neglect is larger than the cost of prevention.",
        "Change here turns ordinary caution into targeted protection. The emerging pattern becomes safer without requiring a broad defensive posture; one specific weak point receives the extra attention it deserves.",
        "Do not generalize one warning into suspicion of everything behind you. The strength of small exceeding is precision. Identify the actual vulnerability and protect it without expanding fear beyond the evidence.",
        "What small, credible vulnerability deserves one extra layer of protection because ignoring it could create a much larger consequence?",
        "Line 3 applies extra caution to one specific small danger, keeping vigilance precise rather than converting it into generalized defensiveness.",
      ),
      authoredLine(
        "Meet the issue without passing beyond it",
        "The fourth line reaches the problem directly and can handle it without excess if the person refuses to overtake or dominate the situation. Contact is enough. Stay responsive to timing and avoid turning a successful intervention into a larger campaign.",
        "When this line changes, small adjustment becomes completed contact. The emerging pattern preserves flexibility because the person solves what is present without adding another layer of ambition or control.",
        "Caution itself can become a reason never to act. The line supports meeting the issue; it simply warns against going beyond what the issue requires. Be precise, not passive.",
        "What would it mean to address this problem fully while refusing to make the intervention broader, longer, or more important than necessary?",
        "Line 4 meets the small issue directly and stops at the point of resolution, preventing a useful intervention from growing into overreach.",
      ),
      authoredLine(
        "Dense clouds do not yet produce rain",
        "The fifth line has gathered conditions that look promising, but the expected result is still not falling. Rather than making a dramatic move, use a precise tool to obtain what is actually reachable. Small exceeding here means targeted action inside an incomplete larger condition.",
        "Change here converts suspended potential into a specific gain. The emerging pattern remains realistic because it takes the available result without pretending the whole atmosphere has already changed.",
        "Do not keep interpreting signs of promise as equivalent to delivery. Clouds are not rain. Judge the larger condition by what actually arrives, even while using local opportunity intelligently.",
        "What small, concrete result can be secured now while you continue to wait for the larger promising condition to become real rather than merely visible?",
        "Line 5 takes a precise obtainable gain from an incomplete situation without confusing signs of promise with the larger result actually arriving.",
      ),
      authoredLine(
        "Flying too high misses the point and meets danger",
        "At the top line, small exceeding has lost its scale. The person goes beyond the issue, the mandate, or the support and turns careful exceptionalism into a large overreach. The very energy that was useful in small matters becomes dangerous when elevated too far.",
        "Change here brings the situation back down toward proportion. The emerging direction requires reducing scope, accepting limits, and returning to the small task that can still be handled responsibly.",
        "Do not answer overreach with total retreat if a modest task remains valid. The correction is scale. Preserve what can be done well and relinquish the unsupported altitude.",
        "Where has a justified small exception expanded into a larger claim or ambition that the original evidence never supported?",
        "Line 6 corrects small exceeding that has flown too high by reducing scope and returning attention to the modest responsibility the structure can still carry.",
      ),
    ],
  },
  {
    number: 63,
    coreTheme: "After completion",
    coreMeaning: "After completion describes the deceptively vulnerable period immediately after success. Ji Ji has all lines in their proper alternation, suggesting order achieved; yet that very order can invite complacency. A completed transition still needs stabilization, maintenance, monitoring, and protection of weak details. The reading asks what could unravel now that attention is relaxing. Early restraint prevents the new order from being disturbed; routine maintenance and clear roles keep small failures from becoming structural. Later lines warn that old threats may return, that strong success can obscure dependency, and that overconfidence at the very end can put the whole person ‘over the head’ in danger. Completion is therefore an operating phase, not a victory photograph. Protect what has been established until the new pattern becomes ordinary enough to survive without extraordinary attention.",
    strength: "the ability to stabilize a transition after the main work appears complete",
    challenge: "complacency, neglected details, or assuming a completed state will maintain itself",
    orientation: "shift from achievement to maintenance and monitor the weak points of the new order",
    structureInterpretation: "Fire below and Water above place every yin and yang line in an alternating position, creating a highly ordered but delicately balanced figure. Quick I Ching reads the structure as completion whose very precision requires care: once order is achieved, small neglected changes can disturb the balance.",
    reflectionQuestions: [
      "Which maintenance task becomes most important now that the visible transition is complete?",
      "What weak point is most likely to be ignored because everyone’s attention has moved from building to celebrating?",
      "What indicator would reveal early that the completed system is drifting before the problem becomes obvious?",
    ],
    watchFor: [
      "A successful transition becoming ordinary because maintenance, ownership, and monitoring are assigned rather than assumed.",
      "Small unresolved defects surviving because the project is socially considered ‘done’ and nobody wants to reopen completion.",
      "Confidence after success reducing safeguards faster than the new order has proved it can safely support.",
    ],
    transitionTheme: "achievement becoming durable order through maintenance after the visible completion",
    stabilityTheme: "attention to small weak points after success rather than reliance on the fact that the transition once worked",
    lowerTrigram: "li",
    upperTrigram: "kan",
    lines: [
      authoredLine(
        "Brake the wheels and wet only the tail",
        "The first line begins after completion with deliberate slowing. The main crossing may be finished, but residual momentum can carry the system too far before the new conditions are understood. A small inconvenience caused by restraint is preferable to disturbing a balance just achieved.",
        "Change here converts success momentum into stabilization. The emerging pattern gains reliability because the person accepts a slower first phase and tests the new order before resuming full speed.",
        "Do not use stabilization as an excuse to keep the system frozen indefinitely. The purpose of braking is to learn the new traction and then operate normally, not to remain permanently cautious after success.",
        "What should deliberately slow down right after this completion so momentum does not outrun understanding of the new conditions?",
        "Line 1 protects a fresh completion by braking residual momentum and accepting a small temporary cost while the new order settles.",
      ),
      authoredLine(
        "A lost veil need not be chased immediately",
        "The second line shows a small protective or status element going missing after completion. The first impulse may be to chase it, but the larger order remains intact. What truly belongs may return through ordinary functioning without making the minor loss the center of attention.",
        "As this line changes, maintenance learns to distinguish essential defects from recoverable details. The emerging pattern stays focused on the whole instead of destabilizing itself through disproportionate pursuit of a small loss.",
        "Do not ignore a minor loss if it actually protects safety, privacy, or legal function. The key is consequence, not size. Verify whether the missing element is decorative, recoverable, or essential.",
        "What small post-completion loss can be allowed to resolve through ordinary process rather than becoming an urgent distraction from the stable whole?",
        "Line 2 keeps post-completion attention proportionate by allowing a minor recoverable loss to resolve without destabilizing the larger order.",
      ),
      authoredLine(
        "Old threats require sustained maintenance, not a quick victory",
        "The third line shows that a completed order may still face familiar external problems. A renewed campaign can succeed, but only through sustained effort and careful use of people. The fact that the main transition is complete does not make long-standing threats easy.",
        "Change here extends maintenance into strategic defense. The emerging pattern preserves the new order by acknowledging that some external risks need ongoing management rather than a single final action.",
        "Do not expend inexperienced people or fragile resources simply to prove the completed system can dominate old threats. Protect the new order first and use capability proportionately.",
        "Which recurring external risk still requires a long maintenance strategy even though the internal transition is now complete?",
        "Line 3 protects completion against persistent external threats through sustained, proportionate management rather than a rushed demonstration of victory.",
      ),
      authoredLine(
        "Keep spare clothing ready for hidden leaks",
        "The fourth line stays alert to deterioration that can appear beneath a seemingly finished structure. Small leaks, vulnerabilities, or maintenance gaps deserve preparation before they become visible crises. Readiness is quiet insurance, not a statement that the completion failed.",
        "When this line changes, the completed system develops resilience. The emerging pattern can absorb small failures without panic because contingency resources and attention remain available after the celebratory phase ends.",
        "Preparedness can become permanent anxiety if every hidden risk receives equal attention. Prioritize plausible failure modes and keep safeguards light enough that normal operation remains normal.",
        "What small hidden failure mode is plausible enough that a simple contingency now would be cheaper than emergency repair later?",
        "Line 4 strengthens completion through quiet contingency planning for plausible leaks without turning maintenance into permanent alarm.",
      ),
      authoredLine(
        "A modest sincere offering can matter more than a grand display",
        "The fifth line warns completed systems not to equate prosperity or ceremony with legitimacy. A smaller but sincere act may align more closely with the values that justified the achievement than an impressive display. Substance still matters after success.",
        "Change here renews the moral center of completion. The emerging pattern stays credible because the system continues to judge itself by fit, sincerity, and real responsibility rather than by the scale of its celebrations.",
        "Do not romanticize smallness automatically. A major responsibility may require major resources. The point is to separate necessary scale from display whose primary function is to advertise success.",
        "What simple act would better express the purpose of this completed work than another large display of having succeeded?",
        "Line 5 keeps completion aligned with substance by preferring sincere fit over impressive ceremony when display would add little real value.",
      ),
      authoredLine(
        "The head goes under after the crossing is already complete",
        "At the top line, overconfidence after success creates new danger. The crossing was made, but continuing too far into the same mode of action puts the person back in deep water. Completion required a change of operating state; failure to stop can undo what was achieved.",
        "Change here ends the completed cycle by forcing recognition that the old crossing behavior is no longer appropriate. The emerging direction needs ordinary maintenance, not continued emergency effort or expansion.",
        "Do not become so afraid of post-success overreach that you refuse all further development. The warning is about continuing the same crossing after it is complete, not about never beginning another well-considered project later.",
        "What behavior was necessary to complete the transition but has become dangerous now that the crossing itself is already finished?",
        "Line 6 warns that completion can be undone by continuing the crossing mode too long, requiring a deliberate shift from achievement into ordinary operation.",
      ),
    ],
  },
  {
    number: 64,
    coreTheme: "Before completion",
    coreMeaning: "Before completion describes the last stage when the pieces are nearly in place but final integration has not yet occurred. Wei Ji is dangerous because near-success feels emotionally like success. The reading favors discrimination, sequencing, and restraint at the finish. Small errors now can invalidate a long process because attention relaxes just before the crossing is secure. Early movement should test traction; later progress should keep roles and risks visible; central leadership must coordinate the final conditions rather than simply demand speed. The highest line allows celebration, but even celebration should not become loss of judgment before completion is actually confirmed. This hexagram treats unfinishedness as temporary and specific, not as an identity. Know exactly what remains incomplete, finish it, verify it, and then permit the system to become completed rather than endlessly refining a task whose real work is done.",
    strength: "precision and discernment during the final incomplete stage",
    challenge: "premature confidence, confusion about what remains unfinished, or rushing the last crossing",
    orientation: "identify the remaining gap precisely and complete it without relaxing standards too early",
    structureInterpretation: "Water below and Fire above place all lines out of the alternating positions seen in After Completion. Quick I Ching reads the structure as components present but not yet integrated into final order. The tension is productive if it keeps attention on sequencing; it becomes dangerous when near-completion is mistaken for completion itself.",
    reflectionQuestions: [
      "What exactly remains unfinished, stated as a concrete condition rather than a vague feeling that the project is ‘almost there’?",
      "Which final-stage error would be disproportionately costly because earlier success has made attention relax?",
      "What verification should occur before celebration, handoff, or the declaration that the work is complete?",
    ],
    watchFor: [
      "The remaining gap becoming small and specific enough that final effort can be focused rather than broadly increased.",
      "People speaking and behaving as if completion has occurred before the last dependency, test, or handoff is actually secure.",
      "The system continuing to refine after objective completion because unfinishedness has become a habit or source of identity.",
    ],
    transitionTheme: "near-completion becoming real completion through final discrimination and integration",
    stabilityTheme: "attention maintained until the last condition is verified rather than relaxed by anticipation",
    lowerTrigram: "kan",
    upperTrigram: "li",
    lines: [
      authoredLine(
        "The fox wets its tail by moving too early",
        "The first line begins the final crossing before traction is secure. Because completion is close, impatience can make a small misstep feel harmless, yet the last stage is exactly where a minor loss of footing can delay everything. Test the first movement and keep the remaining load light.",
        "Change here turns premature motion into a more careful final approach. The emerging pattern gains reliability because the person treats the last crossing as a distinct task rather than as a ceremonial continuation of earlier success.",
        "Do not let one cautious correction become fear of finishing. The lesson is to improve footing, not retreat from the goal. Once the first step is stable, proceed deliberately.",
        "What first step in the final crossing needs a smaller test before the whole project commits its weight to it?",
        "Line 1 protects near-completion by testing the first final-stage movement before impatience commits the whole system to uncertain footing.",
      ),
      authoredLine(
        "Brake the wheels while the final conditions align",
        "The second line has enough momentum to finish but deliberately holds it until timing and sequence are right. Restraint here is active coordination. A brief pause can prevent one part from arriving before the dependency that makes completion safe.",
        "As this line changes, the final stage becomes synchronized. The emerging pattern can move quickly afterward because the pause allowed roles, resources, and conditions to align rather than collide at the finish.",
        "Do not fetishize perfect synchronization. Some final stages can tolerate small variation. Hold only for dependencies that genuinely affect safety or completion, and release the brake once they are ready.",
        "Which dependency needs to align before the final movement can proceed without one part of the system arriving too early?",
        "Line 2 uses a deliberate final-stage pause to synchronize real dependencies before releasing the momentum needed for completion.",
      ),
      authoredLine(
        "Attacking the final gap directly may be dangerous; prepare the crossing",
        "The third line shows incompletion becoming frustrating enough that a direct assault feels attractive. But the gap may still be too risky for brute force. Preparation for the crossing—support, route, equipment, coordination—matters more than intensity of desire to be done.",
        "Change here converts finish-line impatience into a better crossing design. The emerging pattern advances because the remaining obstacle is treated as a technical condition to solve rather than an insult to previous effort.",
        "Preparation should not become another indefinite planning cycle. The remaining gap is real and finite. Once the crossing conditions are met, action should follow.",
        "What final obstacle are you trying to overpower when the real need is a better-supported crossing rather than more force?",
        "Line 3 redirects frustration with the final gap into concrete crossing preparation so near-completion is not endangered by a brute-force finish.",
      ),
      authoredLine(
        "Long effort can finally defeat the lingering disorder",
        "The fourth line enters the sustained work required to remove a stubborn remaining problem. Completion may still demand a substantial period of effort even though most of the system is already in place. The value is endurance tied to a clearly defined final obstacle.",
        "When this line changes, the remaining disorder becomes truly removable. The emerging pattern gains confidence from sustained execution and can finally convert a long incomplete phase into a stable result.",
        "Do not let the length of the final effort expand the definition of the enemy or justify unlimited resources. Keep the campaign tied to the specific unfinished condition and review whether the original objective remains the same.",
        "What specific remaining problem justifies sustained final effort, and what boundary will keep that effort from expanding beyond the actual completion requirement?",
        "Line 4 commits sustained effort to one stubborn final obstacle while keeping the scope precise enough that the finish does not become an endless campaign.",
      ),
      authoredLine(
        "Central integrity makes the unfinished phase trustworthy",
        "The fifth line is not yet complete, but the center is clear and trustworthy enough that people can continue with confidence. Leadership does not need to pretend the work is finished. Honest reporting of what remains, combined with consistent direction, can create more trust than premature declaration.",
        "Change here turns incompletion into credible final coordination. The emerging pattern becomes ready for closure because people know both the progress already made and the exact responsibilities still open.",
        "Optimism can become misinformation if leaders soften the remaining risk to preserve morale. Conversely, constant emphasis on incompletion can hide how much has actually been achieved. Report both accurately.",
        "How can you state the remaining unfinished work plainly while also making the real progress already achieved visible enough to sustain confidence?",
        "Line 5 keeps the center trustworthy before completion by reporting both progress and remaining risk honestly, allowing final coordination without false certainty.",
      ),
      authoredLine(
        "Celebrate the near-finish without drowning judgment",
        "At the top line, confidence and celebration are appropriate because the difficult passage is nearly or effectively complete. The danger is excess at the moment of relief: losing judgment before verification can spill what has been accomplished. Enjoyment should follow the work without erasing the final standard.",
        "Change here closes Before Completion and allows the system to become complete. The emerging direction is to verify, mark the transition, and then stop treating unfinishedness as the defining condition. Completion should be permitted to exist.",
        "Do not keep adding final checks merely because caution has become habitual, but do not let celebration precede the one verification on which completion actually depends. Finish, confirm, then relax.",
        "What final verification deserves to happen before celebration becomes full, and what additional checking after that point would only reflect difficulty accepting that the work is done?",
        "Line 6 completes the unfinished cycle by pairing justified celebration with one last proportionate verification, then allowing the work to be truly finished.",
      ),
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
