import { buildInterpretationCatalog, type HexagramInterpretationProfile } from "../profile";

const profiles: readonly HexagramInterpretationProfile[] = [
  {
    number: 61,
    coreTheme: "Inner truth",
    legacySummary: "Trust grows from inward sincerity matched by outward consistency. Listen carefully, test assumptions, and let credibility emerge from congruent action.",
    strength: "congruence between inward conviction, careful listening, and outward conduct",
    challenge: "self-deception, credulity, or demanding trust without evidence",
    orientation: "align what you believe, say, and do while remaining open to evidence from others",
    transitionTheme: "uncertainty becoming trust when sincerity is matched by observable consistency",
    stabilityTheme: "credibility maintained through congruence rather than persuasion alone",
    lowerTrigram: "dui",
    upperTrigram: "xun",
    lineEmphases: [
      "check the first inward conviction against evidence before asking others to trust it",
      "make sincerity observable through consistent ordinary conduct",
      "notice self-deception or credulity when pressure makes certainty emotionally attractive",
      "carry inner conviction into the wider field while listening seriously to another perspective",
      "use a central role to build trust through congruence rather than persuasive force",
      "release a claimed truth when continued attachment requires ignoring contradictory evidence",
    ],
  },
  {
    number: 62,
    coreTheme: "Small exceeding",
    legacySummary: "The situation favors careful attention to modest matters rather than grand moves. Precision, humility, and manageable steps are safer than overreach.",
    strength: "precision in small matters and the willingness to keep scale modest",
    challenge: "grand gestures, overreach, or overlooking details because they seem minor",
    orientation: "stay close to manageable tasks, details, and proportionate ambitions",
    transitionTheme: "small careful actions becoming sufficient progress without requiring a dramatic move",
    stabilityTheme: "accuracy and humility that keep modest action effective",
    lowerTrigram: "gen",
    upperTrigram: "zhen",
    lineEmphases: [
      "give the first small detail the attention it deserves before attempting a larger move",
      "make modest action precise enough that small gains accumulate safely",
      "avoid overreach when pressure makes a limited task feel too insignificant",
      "carry careful small-scale action into the wider field without inflating its importance",
      "use a central role to protect precision, humility, and manageable scope",
      "stop multiplying minor adjustments when the small task is complete and a different scale is needed",
    ],
  },
  {
    number: 63,
    coreTheme: "After completion",
    legacySummary: "A major transition has been achieved, but completion creates a new maintenance problem. Guard details and prevent success from turning into complacency.",
    strength: "the ability to stabilize a successful transition through maintenance",
    challenge: "complacency, neglect of details, or assuming completion means the system can run unattended",
    orientation: "shift from achieving the transition to protecting its weak points and routines",
    transitionTheme: "completion becoming durable order only through careful maintenance",
    stabilityTheme: "attention to details that prevents a finished crossing from quietly unraveling",
    lowerTrigram: "li",
    upperTrigram: "kan",
    lineEmphases: [
      "protect the first weak detail after completion instead of relaxing immediately",
      "turn a finished transition into reliable routine through ordinary maintenance",
      "respond early when pressure reveals that success has introduced new failure points",
      "carry the completed structure into wider use without assuming it is self-maintaining",
      "use central responsibility to monitor details that could quietly reverse the achievement",
      "renew or redesign maintenance when preserving completion has become complacent repetition",
    ],
  },
  {
    number: 64,
    coreTheme: "Before completion",
    legacySummary: "The crossing is not finished. Keep distinctions clear, avoid premature celebration, and concentrate on the final conditions required for a sound transition.",
    strength: "careful attention during the last incomplete stage of a transition",
    challenge: "premature confidence, confusion near the finish, or rushing because most of the work is done",
    orientation: "stay precise about what remains incomplete and finish the transition without losing discipline",
    transitionTheme: "near-completion becoming actual completion through one more round of careful discrimination",
    stabilityTheme: "patience and clarity maintained until the remaining conditions are genuinely resolved",
    lowerTrigram: "kan",
    upperTrigram: "li",
    lineEmphases: [
      "name the first remaining gap honestly instead of treating near-completion as completion",
      "make the final work precise through careful distinctions and steady follow-through",
      "avoid rushing when pressure comes from being close enough to imagine the finish",
      "carry the incomplete transition into the wider field only with its remaining risks visible",
      "use central judgment to coordinate the last conditions without losing discipline to excitement",
      "complete the crossing by releasing the identity of unfinished work once the remaining conditions are truly met",
    ],
  },
];

export const INTERPRETATIONS = buildInterpretationCatalog(profiles);
